Repository nextcloud/spreed, pull requests merged in 2018-06, with the labels that each got.

#926 Send call notifications to every room participant that is not in the …
  lib/Notification/Hooks.php
  lib/Room.php
Labels: 3. to review, backport-request

#934 Fix appearance of participants menu button
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#936 Mark messages directly as read when waiting for new messages.
  lib/Chat/ChatManager.php
Labels: 3. to review, backport-request, bug, feature: chat

#943 [stable13] Calls are Conversations
  lib/Activity/Provider/Base.php
  lib/Notification/Notifier.php
  tests/php/Activity/Provider/BaseTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, design

#945 [stable13] Mark messages directly as read when waiting for new messages.
  lib/Chat/ChatManager.php
Labels: 3. to review, bug, feature: chat

#946 [stable13] Fix tab header icons not shown
  css/style.scss
Labels: 3. to review, bug, design, feature: frontend

#947 [stable13] Fix appearance of participants menu button
  css/style.scss
Labels: 3. to review, bug, design

#942 [stable13] Send call notifications to every room participant that is not in the call
  lib/Notification/Hooks.php
  lib/Room.php
Labels: 3. to review

#937 Add toggle to show and hide video from other participants
  css/style.scss
  js/webrtc.js
Labels: 3. to review, backport-request, feature: frontend

#941 Fix menu position for rooms and participants
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#940 Fix adding the same participant several times in a row
  js/views/participantview.js
Labels: 3. to review, backport-request, bug, feature: frontend

#949 [stable13] Add toggle to show and hide video from other participants
  css/style.scss
  js/webrtc.js
Labels: 3. to review, feature: frontend

#950 [stable13] Fix local audio and video not disabled when not available
  js/webrtc.js
Labels: 3. to review, bug, feature: frontend

#951 [stable13] Fix add participant shown to normal participants
  js/views/participantview.js
Labels: 3. to review, bug, feature: frontend

#952 [stable13] Fix adding the same participant several times in a row
  js/views/participantview.js
Labels: 3. to review, bug, feature: frontend

#953 [stable13] Fix menu position for rooms and participants
  css/style.scss
Labels: 3. to review, bug, design

#954 Add changelog for 3.2.2
  CHANGELOG.md
Labels: 3. to review, backport-request, enhancement

#955 [stable13] Add changelog for 3.2.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, enhancement

#928 Simplify notification wording
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request

#887 Move loading of chat messages to signaling class.
  js/models/chatmessagecollection.js
  js/signaling.js
Labels: 3. to review, feature: chat, feature: signaling

#890 Support standalone signaling server for chat
  js/signaling.js
  lib/AppInfo/Application.php
  lib/Chat/ChatManager.php
  lib/Controller/ChatController.php
  lib/Signaling/BackendNotifier.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, feature: chat, feature: signaling

#910 More standalone signaling fixes
  js/signaling.js
  lib/AppInfo/Application.php
  lib/Controller/SignalingController.php
Labels: 3. to review, backport-request, bug, feature: signaling

#978 Fix input and grey tones
  css/style.scss
Labels: 3. to review, design, enhancement

#977 Fix wording for 'Leave conversation'
  js/views/roomlistview.js
  tests/acceptance/features/bootstrap/ConversationListContext.php
  tests/acceptance/features/conversation.feature
Labels: design, enhancement, papercut

#981 Participant list whitespace
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#980 Adjust room name and edit flow layout
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#975 Remove guest name input from sidebar as it already is in chat
  js/views/callinfoview.js
Labels: 3. to review, backport-request, design, enhancement

#984 Fix position of local container children in older Firefox versions
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#974 Improve call controls layout to single row
  css/style.scss
  js/views/callinfoview.js
Labels: 3. to review, backport-request, design, enhancement

#990 Name change is in Chat, not right sidebar
  js/app.js
Labels: 3. to review, enhancement

#988 Remove dead code now that the guest name is no longer shown
  js/views/callinfoview.js
Labels: 3. to review

#983 Simplify check for "action" value in room request.
  lib/Controller/SignalingController.php
Labels: 4. to release, backport-request, bug

#398 MCU integration
  js/app.js
  js/signaling.js
  js/simplewebrtc.js
  js/webrtc.js
  lib/Signaling/BackendNotifier.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, enhancement

#992 Set "wd_host" using the simulated "selenium.server" variable
  tests/acceptance/config/behat.yml
Labels: 3. to review

#989 Label button 'Start call' if none is in progress yet, fix #976
  js/views/callinfoview.js
Labels: 3. to review, backport-request, enhancement

#1009 Add supported Browser list to README
  README.md
Labels: 3. to review

#999 Fix participants sorting
  js/models/participantcollection.js
Labels: 3. to review, backport-request, bug, design
