Repository nextcloud/spreed, pull requests merged in 2018-10, with the labels that each got.

#1224 [stable14] Add unit tests for collaborator search
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
Labels: 3. to review, feature: room-shares

#1225 Allow calling "RoomController::formatLastMessage" without a current user.
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug

#1215 Fix interaction with participant menu
  css/style.scss
  js/views/participantlistview.js
Labels: 3. to review, backport-request, design, feature: frontend

#1231 Correctly cast the in_call flag to integer
  lib/Manager.php
Labels: 3. to review, backport-request, bug

#1078 Allow to make guests moderators
  docs/api-v1.md
  js/app.js
  js/views/callinfoview.js
  js/views/participantlistview.js
  lib/AppInfo/Application.php
  lib/Chat/MessageParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Notification/Notifier.php
  lib/Participant.php
  lib/Room.php
  templates/index-public.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement

#1230 Notification levels
  appinfo/info.xml
  appinfo/routes.php
  css/style.scss
  docs/api-v1.md
  js/app.js
  js/views/roomlistview.js
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version4099Date20181001123058.php
  lib/Notification/Notifier.php
  lib/Participant.php
  lib/Room.php
  tests/php/CapabilitiesTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/RoomControllerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request, enhancement, feature: api, feature: chat

#1229 Handle exception on too long chat message gracefully
  docs/api-v1.md
  js/views/chatview.js
  lib/Controller/ChatController.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, bug, feature: api, feature: chat

#1253 Override default CSP for now to allow JavaScript "eval"
  lib/Controller/PageController.php
Labels: 3. to review

#1257 Fix CSP also for guests
  lib/Controller/PageController.php
Labels: 3. to review, bug

#1269 Add quick development setup introduction
  README.md
Labels: 3. to review, enhancement
