Repository nextcloud/spreed, pull requests merged in 2018-04, with the labels that each got.

#766 Increase padding in chat view to leave enough space for side buttons.
  css/style.scss
Labels: 3. to review, backport-request, bug, design, feature: chat

#764 Fix new multi-session signaling endpoints.
  appinfo/routes.php
  lib/Manager.php
Labels: 3. to review, backport-request, bug, feature: signaling

#768 Add acceptance tests
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/ChatAncestorSetter.php
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/bootstrap/ConversationInfoContext.php
  tests/acceptance/features/bootstrap/ConversationListContext.php
  tests/acceptance/features/bootstrap/ParticipantListContext.php
  tests/acceptance/features/bootstrap/TalkAppContext.php
  tests/acceptance/features/conversation.feature
  tests/acceptance/installAndConfigureServer.sh
  tests/acceptance/run.sh
Labels: 3. to review, enhancement

#775 Add acceptance tests for chat
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/chat.feature
Labels: 3. to review, enhancement

#777 Add an icon for participants which are in the call
  css/style.scss
  js/models/participant.js
  js/views/participantlistview.js
Labels: 3. to review, backport-request, enhancement, feature: frontend

#758 Allow to join without camera/mic
  README.md
  css/style.scss
  js/app.js
  js/simplewebrtc.js
  js/webrtc.js
Labels: 3. to review, backport-request, enhancement, feature: webrtc

#779 [stable13] Add a notification when readding the default stun server
  js/admin/stun-server.js
Labels: 3. to review

#781 [stable13] Fixed authenticate script
  css/authenticate.css
Labels: 3. to review, bug

#782 [stable13] Do not cut popover on participant list
  css/style.scss
Labels: 3. to review, bug

#783 [stable13] Remove chat when leaving active room
  js/signaling.js
  js/views/roomlistview.js
Labels: 3. to review, bug

#780 [stable13] Streamline empty content message handling
  js/app.js
  js/views/roomlistview.js
  js/webrtc.js
Labels: 3. to review, bug

#784 [stable13] Multi session support
  appinfo/routes.php
  css/style.scss
  docs/api-v1.md
  js/app.js
  js/connection.js
  js/models/roomcollection.js
  js/signaling.js
  js/views/callinfoview.js
  js/views/roomlistview.js
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/GuestController.php
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Room.php
  lib/TalkSession.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/group.feature
  tests/integration/features/callapi/one-to-one.feature
  tests/integration/features/callapi/password.feature
  tests/integration/features/callapi/public.feature
  tests/integration/features/one-to-one.feature
  tests/integration/features/remove-self.feature
  tests/integration/features/set-password.feature
  tests/php/CapabilitiesTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, enhancement

#785 [stable13] Allow screensharing even when alone
  css/style.scss
  js/app.js
  js/webrtc.js
Labels: 3. to review, enhancement

#787 [stable13] Change keyboard shortcuts
  css/style.scss
  js/app.js
  js/connection.js
  templates/index-public.php
  templates/index.php
Labels: 3. to review, enhancement

#790 [stable13] Set dark style icon to screensharing button when local video is disab…
  css/style.scss
  js/app.js
Labels: 3. to review, bug

#791 [stable13] Increase padding in chat view to leave enough space for side buttons.
  css/style.scss
Labels: 3. to review, enhancement

#792 [stable13] Fix signaling endpoints
  appinfo/routes.php
  lib/Manager.php
Labels: 3. to review, bug

#793 [stable13] Add an icon for participants which are in the call
  css/style.scss
  js/models/participant.js
  js/views/participantlistview.js
Labels: 3. to review, enhancement

#788 [stable13] Correct roomlist sorting
  js/models/roomcollection.js
Labels: 3. to review, bug

#789 [stable13] Unify naming in the UI: rooms are conversations
  js/admin/stun-server.js
  js/app.js
  js/views/callinfoview.js
  js/views/participantview.js
  js/views/roomlistview.js
  templates/index.php
Labels: 3. to review, bug

#587 Always show sidebar toggle, also when sidebar is open
  css/style.scss
  js/views/sidebarview.js
Labels: 3. to review, backport-request, design, enhancement

#797 Add lock icon to password popover.
  js/views/callinfoview.js
Labels: design, enhancement

#794 Backport/758/allow to join without camera and video
  README.md
  css/style.scss
  js/app.js
  js/simplewebrtc.js
  js/webrtc.js
Labels: 3. to review, enhancement

#795 [stable13] Always show sidebar toggle
  css/style.scss
  js/views/sidebarview.js
Labels: 3. to review, bug

#799 Add acceptance tests for chat to Drone
  .drone.yml
Labels: 3. to review, enhancement

#796 [stable13] Show password input field in a popover menu.
  css/patches.scss
  css/style.scss
  js/views/callinfoview.js
  js/views/editabletextlabel.js
Labels: 3. to review, design, enhancement

#767 Add proper chat message offset support
  docs/api-v1.md
  js/models/chatmessagecollection.js
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Controller/ChatController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, bug, enhancement, feature: chat

#804 Remove useless logs
  js/app.js
  js/views/chatview.js
Labels: 3. to review, backport-request, bug

#802 Do not query the last comment info when there is none
  docs/api-v1.md
  js/models/chatmessagecollection.js
  lib/Chat/CommentsManager.php
Labels: 3. to review, bug, feature: chat

#806 Add unread message count to the room list
  docs/api-v1.md
  js/views/roomlistview.js
  lib/Chat/ChatManager.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, enhancement, feature: chat

#807 Make sure the displayname is always a string
  lib/Controller/ChatController.php
Labels: 3. to review, backport-request, bug, feature: chat

#803 [stable13] Proper chat offset
  docs/api-v1.md
  js/models/chatmessagecollection.js
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Controller/ChatController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, enhancement, feature: chat

#805 Format mentions (without avatars) in the message list
  css/comments.scss
  css/style.scss
  docs/api-v1.md
  js/models/chatmessage.js
  js/richobjectstringparser.js
  js/views/chatview.js
  lib/Chat/RichMessageHelper.php
  lib/Controller/ChatController.php
  templates/index-public.php
  templates/index.php
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/chat.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/group.feature
  tests/integration/features/chat/one-to-one.feature
  tests/integration/features/chat/password.feature
  tests/integration/features/chat/public.feature
  tests/integration/features/chat/rich-messages.feature
  tests/php/Chat/RichMessageHelperTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, design, enhancement, feature: chat

#810 [stable13] Format mentions without avatars in the message list
  css/comments.scss
  css/style.scss
  docs/api-v1.md
  js/models/chatmessage.js
  js/richobjectstringparser.js
  js/views/chatview.js
  lib/Chat/RichMessageHelper.php
  lib/Controller/ChatController.php
  templates/index-public.php
  templates/index.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/group.feature
  tests/integration/features/chat/one-to-one.feature
  tests/integration/features/chat/password.feature
  tests/integration/features/chat/public.feature
  tests/integration/features/chat/rich-messages.feature
  tests/php/Chat/RichMessageHelperTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, design, enhancement, feature: chat

#813 Make mentions more prominent
  css/comments.scss
Labels: 3. to review, backport-request, design, enhancement, feature: chat

#812 Autocomplete for mentions
  appinfo/routes.php
  bower.json
  css/autocomplete.scss
  css/comments.scss
  docs/api-v1.md
  js/vendor/At.js/.bower.json
  js/vendor/At.js/CHANGELOG.md
  js/vendor/At.js/CONTRIBUTING.md
  js/vendor/At.js/LICENSE-MIT
  js/vendor/At.js/README.md
  js/vendor/At.js/bower.json
  js/vendor/At.js/component.json
  js/vendor/At.js/dist/css/jquery.atwho.css
  js/vendor/At.js/dist/css/jquery.atwho.min.css
  js/vendor/At.js/dist/js/jquery.atwho.js
  js/vendor/At.js/dist/js/jquery.atwho.min.js
  js/vendor/At.js/examples/cross_document/dataFrame.html
  js/vendor/At.js/examples/cross_document/index.html
  js/vendor/At.js/examples/cross_document/viewFrame.html
  js/vendor/At.js/examples/hashtags.html
  js/vendor/At.js/examples/medium-editor.html
  js/vendor/At.js/examples/style.css
  js/vendor/At.js/examples/tinyMCE.html
  js/vendor/At.js/examples/ueditor.html
  js/vendor/At.js/gulpfile.js
  js/vendor/At.js/index.html
  js/vendor/At.js/package.json
  js/vendor/At.js/specRunner.html
  js/vendor/At.js/src/api.coffee
  js/vendor/At.js/src/app.coffee
  js/vendor/At.js/src/controller.coffee
  js/vendor/At.js/src/default.coffee
  js/vendor/At.js/src/editableController.coffee
  js/vendor/At.js/src/jquery.atwho.css
  js/vendor/At.js/src/model.coffee
  js/vendor/At.js/src/textareaController.coffee
  js/vendor/At.js/src/view.coffee
  js/vendor/At.js/umd.template.js
  js/vendor/Caret.js/.bower.json
  js/vendor/Caret.js/CHANGELOG.md
  js/vendor/Caret.js/Gruntfile.coffee
  js/vendor/Caret.js/LICENSE-MIT
  js/vendor/Caret.js/README.md
  js/vendor/Caret.js/bower.json
  js/vendor/Caret.js/component.json
  js/vendor/Caret.js/dist/jquery.caret.js
  js/vendor/Caret.js/dist/jquery.caret.min.js
  js/vendor/Caret.js/package.json
  js/vendor/Caret.js/src/jquery.caret.coffee
  js/vendor/Caret.js/src/jquery.caret.js
  js/views/chatview.js
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/AutoComplete/Sorter.php
  lib/Chat/CommentsManager.php
  lib/Controller/ChatController.php
  templates/index-public.php
  templates/index.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, design, enhancement, feature: api, feature: chat, help wanted

#815 [stable13] Make mentions more prominent
  css/comments.scss
Labels: 3. to review, design, enhancement, feature: chat

#816 [stable13] Fix pointer cursor not shown on message authors
  css/comments.scss
  js/views/chatview.js
Labels: 3. to review, bug, design, feature: chat

#827 Fix working icon position when sending a message
  css/comments.scss
Labels: 3. to review, backport-request, bug, design, feature: chat

#808 Only group up to 10 messages and only for up to 15 seconds
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat

#830 Fix appearance of author row when showing the date
  css/comments.scss
Labels: 3. to review, backport-request, bug, design, feature: chat

#831 Fix pointer cursor shown for guests and in new message form
  css/comments.scss
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, design, feature: chat
