Repository nextcloud/spreed, pull requests merged in 2018-05, with the labels that each got.

#821 [stable13] Add unread message count to the room list
  docs/api-v1.md
  js/views/roomlistview.js
  lib/Chat/ChatManager.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, enhancement

#822 [stable13] Make sure the displayname is always a string
  lib/Controller/ChatController.php
Labels: 3. to review, bug

#823 [stable13] Chat autocomplete suggestions
  appinfo/routes.php
  bower.json
  css/autocomplete.scss
  css/comments.scss
  docs/api-v1.md
  js/vendor/At.js/.bower.json
  js/vendor/At.js/CHANGELOG.md
  js/vendor/At.js/CONTRIBUTING.md
  js/vendor/At.js/LICENSE-MIT
  js/vendor/At.js/README.md
  js/vendor/At.js/bower.json
  js/vendor/At.js/component.json
  js/vendor/At.js/dist/css/jquery.atwho.css
  js/vendor/At.js/dist/css/jquery.atwho.min.css
  js/vendor/At.js/dist/js/jquery.atwho.js
  js/vendor/At.js/dist/js/jquery.atwho.min.js
  js/vendor/At.js/examples/cross_document/dataFrame.html
  js/vendor/At.js/examples/cross_document/index.html
  js/vendor/At.js/examples/cross_document/viewFrame.html
  js/vendor/At.js/examples/hashtags.html
  js/vendor/At.js/examples/medium-editor.html
  js/vendor/At.js/examples/style.css
  js/vendor/At.js/examples/tinyMCE.html
  js/vendor/At.js/examples/ueditor.html
  js/vendor/At.js/gulpfile.js
  js/vendor/At.js/index.html
  js/vendor/At.js/package.json
  js/vendor/At.js/specRunner.html
  js/vendor/At.js/src/api.coffee
  js/vendor/At.js/src/app.coffee
  js/vendor/At.js/src/controller.coffee
  js/vendor/At.js/src/default.coffee
  js/vendor/At.js/src/editableController.coffee
  js/vendor/At.js/src/jquery.atwho.css
  js/vendor/At.js/src/model.coffee
  js/vendor/At.js/src/textareaController.coffee
  js/vendor/At.js/src/view.coffee
  js/vendor/At.js/umd.template.js
  js/vendor/Caret.js/.bower.json
  js/vendor/Caret.js/CHANGELOG.md
  js/vendor/Caret.js/Gruntfile.coffee
  js/vendor/Caret.js/LICENSE-MIT
  js/vendor/Caret.js/README.md
  js/vendor/Caret.js/bower.json
  js/vendor/Caret.js/component.json
  js/vendor/Caret.js/dist/jquery.caret.js
  js/vendor/Caret.js/dist/jquery.caret.min.js
  js/vendor/Caret.js/package.json
  js/vendor/Caret.js/src/jquery.caret.coffee
  js/vendor/Caret.js/src/jquery.caret.js
  js/views/chatview.js
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/AutoComplete/Sorter.php
  lib/Chat/CommentsManager.php
  lib/Controller/ChatController.php
  templates/index-public.php
  templates/index.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, enhancement, feature: chat

#828 [stable13] Fix working icon position when sending a message
  css/comments.scss
Labels: 3. to review, bug, design, feature: chat

#834 Return the room name on creation
  docs/api-v1.md
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, enhancement, feature: api

#833 Remove support for newest on top chat layout
  css/comments.scss
  js/app.js
  js/views/chatview.js
Labels: 3. to review, backport-request, feature: chat

#836 [stable13] Make the unread count more obvious
  css/style.scss
  js/views/roomlistview.js
Labels: 3. to review, enhancement, feature: chat, feature: frontend

#835 [stable13] Only group up to 10 messages and only for up to 15 seconds
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat

#839 [stable13] Fix pointer cursor shown for guests and in new message form
  css/comments.scss
  js/views/chatview.js
Labels: 3. to review, bug, design, feature: chat

#840 [stable13] Remove support for newest on top chat layout
  css/comments.scss
  js/app.js
  js/views/chatview.js
Labels: 3. to review, feature: chat

#838 Fix scrolling in chat view
  js/app.js
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat

#837 [stable13] Return the room name on creation
  docs/api-v1.md
  lib/Controller/RoomController.php
Labels: 3. to review, enhancement, feature: api

#841 Disable contacts menu for mentions in the public view
  css/comments.scss
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat

#843 [stable13] Fix scrolling in chat view
  js/app.js
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat

#844 [stable13] Disable contacts menu for mentions in the public view
  css/comments.scss
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat

#739 Update changelog with current patches
  CHANGELOG.md
  docs/chat.png
  docs/contacts-menu.png
Labels: 3. to review

#842 [stable13] Update changelog
  CHANGELOG.md
  docs/chat.png
  docs/contacts-menu.png
Labels: 3. to review

#845 Limit unread message counter to "99+"
  css/style.scss
  js/views/roomlistview.js
Labels: 3. to review, backport-request, bug, design, feature: chat, mobile apps

#852 Fix empty guest display name
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat

#861 Don't try to calculate the height of no comment
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat

#854 Join the call only aftrer media access was done
  js/app.js
  js/connection.js
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: webrtc

#856 Do not show "remove from list" option for one2one conversations
  js/views/roomlistview.js
Labels: 3. to review, backport-request, bug, feature: chat, feature: frontend

#864 Various standalone signaling fixes.
  js/app.js
  js/signaling.js
  lib/AppInfo/Application.php
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, backport-request, bug, feature: signaling

#867 Unpromote latest speaker if no users remain in call when removing video.
  js/webrtc.js
Labels: 4. to release, backport-request, bug

#870 Make sure user is in a room before the guest name is set.
  js/app.js
Labels: 3. to review, backport-request, bug

#871 Fix chat view when leaving current room
  js/app.js
  js/connection.js
  js/views/roomlistview.js
  tests/acceptance/features/bootstrap/ConversationListContext.php
  tests/acceptance/features/bootstrap/TalkAppContext.php
  tests/acceptance/features/conversation.feature
Labels: 3. to review, bug, feature: chat, feature: frontend

#869 Notify standalone signaling server about sessions to remove from room.
  lib/AppInfo/Application.php
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, backport-request, feature: signaling

#866 Stop refreshing participant list when a guest is chatting
  lib/Controller/SignalingController.php
  lib/GuestManager.php
Labels: 3. to review, backport-request, bug, feature: chat, feature: signaling

#876 [stable13] Various standalone signaling fixes.
  js/app.js
  js/signaling.js
  lib/AppInfo/Application.php
  lib/Signaling/BackendNotifier.php
Labels: 4. to release, bug, feature: signaling

#877 [stable13] Unpromote latest speaker if no users remain in call when removing video.
  js/webrtc.js
Labels: 4. to release, bug

#878 [stable13] Notify standalone signaling server about sessions to remove from room.
  lib/AppInfo/Application.php
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, feature: signaling

#880 [stable13] Make sure user is in a room before the guest name is set.
  js/app.js
Labels: 3. to review, bug

#873 [stable13] Fix chat view when leaving current room
  js/app.js
  js/connection.js
  js/views/roomlistview.js
Labels: 3. to review, bug, feature: chat, feature: frontend

#883 [stable13] Fix check for guest's display name.
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat

#882 [stable13] Limit unread message counter to "99+"
  css/style.scss
  js/views/roomlistview.js
Labels: 3. to review, enhancement, feature: chat

#884 [stable13] Join the call only aftrer media access was done
  js/app.js
  js/connection.js
  js/webrtc.js
Labels: 3. to review, bug, feature: webrtc

#885 [stable13] Don't try to calculate the height of no comment
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat

#886 [stable13] Stop refreshing participant list when a guest is chatting
  lib/Controller/SignalingController.php
  lib/GuestManager.php
Labels: 3. to review, bug, feature: chat

#881 [stable13] Stop ping and signaling when the room was deleted
  js/signaling.js
Labels: 3. to review, bug, feature: signaling

#888 [stable13] Do not show "remove from list" option for one2one conversations
  js/views/roomlistview.js
Labels: 3. to review, bug, feature: frontend

#889 [stable13] Fix UI when leaving current call
  js/app.js
  js/connection.js
Labels: 3. to review, bug, feature: frontend

#863 Reset audio and video control panel.
  js/app.js
  js/webrtc.js
Labels: 3. to review, backport-request, bug, design

#891 Change deleted room message.
  js/connection.js
  tests/acceptance/features/conversation.feature
Labels: 4. to release, backport-request, design, enhancement

#892 [stable13] Reset audio and video control panel.
  js/app.js
  js/webrtc.js
Labels: 3. to review, bug

#893 Make acceptance test for two users chatting more robust
  tests/acceptance/features/chat.feature
Labels: 3. to review

#896 Fix scrolling on participants list
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#898 [stable13] Make sure to always set the token on joining a room
  js/connection.js
Labels: 4. to release, bug

#900 Add changelog for 3.2.1
  CHANGELOG.md
Labels: 3. to review, backport-request, enhancement

#899 [stable13] Change deleted room message.
  js/connection.js
Labels: 4. to release, design, enhancement

#901 [stable13] Fix scrolling on participants list
  css/style.scss
Labels: 4. to release, bug, design

#913 Add client links to personal settings
  appinfo/info.xml
  lib/Settings/Personal.php
  templates/settings/personal/clients.php
Labels: 3. to review, design, enhancement

#919 Calls are Conversations
  lib/Activity/Provider/Base.php
  lib/Notification/Notifier.php
  tests/php/Activity/Provider/BaseTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request, design
