Repository nextcloud/spreed, pull requests merged in 2018-07, with the labels that each got.

#1018 paste only plaintext into the chat input field
  js/views/chatview.js
Labels: 3. to review, backport-request, bug

#1000 Remove additional non-guideline padding in navigation entries
  css/style.scss
Labels: 3. to review, bug, design

#1030 [stable13] Simplify notification wording
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug

#1031 [stable13] More standalone signaling fixes
  js/signaling.js
  lib/AppInfo/Application.php
  lib/Controller/SignalingController.php
Labels: 3. to review, bug

#1032 [stable13] Participants whitespace
  css/style.scss
Labels: 3. to review, design

#1034 [stable13] Remove guest name input from sidebar
  js/views/callinfoview.js
Labels: 3. to review, design

#1033 [stable13] Adjust room name and edit flow layout
  css/style.scss
Labels: 3. to review, design

#1035 Name not shown for registered users without microphone nor camera
  js/webrtc.js
Labels: 3. to review, bug

#1036 [stable13] Fix position of local container children in older Firefox versions
  css/style.scss
Labels: 3. to review, bug

#1037 [stable13] Improve call controls layout to single row
  css/style.scss
  js/views/callinfoview.js
Labels: 3. to review, design

#1044 Backport all the things
  js/app.js
  js/models/chatmessagecollection.js
  js/signaling.js
  js/simplewebrtc.js
  js/views/roomlistview.js
  js/webrtc.js
  lib/AppInfo/Application.php
  lib/Chat/ChatManager.php
  lib/Controller/ChatController.php
  lib/Signaling/BackendNotifier.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, bug, design, enhancement, feature: chat, feature: frontend, feature: signaling, feature: webrtc

#1028 Use the token instead of the id to identify the room objects
  lib/AppInfo/Application.php
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Notification/Hooks.php
  lib/Notification/Notifier.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/NotifierTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request, enhancement, feature: api, mobile apps

#1045 Remove participant tooltip from room list
  js/views/roomlistview.js
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1053 Add the userId and user status to the disconnect evens
  lib/Room.php
Labels: 3. to review, feature: api

#1048 Allow single quote in date-separater for french translation
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat, feature: frontend

#1062 Only show client links when the firstrunwizard is enabled
  appinfo/info.xml
  lib/AppInfo/Application.php
Labels: 3. to review, bug, regression

#1025 Add support for backend favorites
  appinfo/info.xml
  appinfo/routes.php
  docs/api-v1.md
  js/models/roomcollection.js
  js/views/roomlistview.js
  lib/Capabilities.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version3003Date20180707222130.php
  lib/Participant.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api, mobile apps

#1065 Refresh the room list when favoriting (similar to name and type changes)
  js/views/roomlistview.js
Labels: 3. to review, bug

#1020 Added hook to verify password to allow custom password check
  lib/Controller/PageController.php
  lib/Room.php
  tests/php/PasswordVerificationTest.php
Labels: 2. developing, backport-request, enhancement, feature: api

#1079 PHP7 for OCA\Spreed\Activity
  lib/Activity/Hooks.php
  lib/Activity/Provider/Base.php
  lib/Activity/Provider/Call.php
  lib/Activity/Provider/Invitation.php
  lib/Activity/Setting.php
Labels: 3. to review

#1081 PHP7 for OCA\Spreed\Notifications + PHPUnit 6.5
  .drone.yml
  lib/Notification/Hooks.php
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
  tests/php/bootstrap.php
Labels: 3. to review

#1059 Remove useless ping call and "ping" with the signaling fetch instead
  appinfo/routes.php
  docs/api-v1.md
  js/signaling.js
  lib/Capabilities.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/SignalingController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/group.feature
  tests/integration/features/callapi/one-to-one.feature
  tests/integration/features/callapi/password.feature
  tests/integration/features/callapi/public.feature
  tests/integration/features/rename-room.feature
  tests/php/CapabilitiesTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, enhancement, feature: api, feature: signaling, mobile apps

#924 Add support for last message when fetching a room
  appinfo/info.xml
  docs/api-v1.md
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version3003Date20180718133519.php
  lib/Room.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, backport-request, enhancement, feature: chat

#1047 Move to public autocomplete endpoint
  css/style.scss
  js/app.js
  js/views/participantview.js
Labels: 3. to review, enhancement, feature: frontend

#1067 Start with system chat messages
  css/comments.scss
  docs/api-v1.md
  js/views/callinfoview.js
  js/views/chatview.js
  lib/Activity/Hooks.php
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/RichMessageHelper.php
  lib/Chat/SystemMessage/Listener.php
  lib/Chat/SystemMessage/Parser.php
  lib/Controller/ChatController.php
  lib/Manager.php
  lib/Room.php
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/system-messages.feature
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, enhancement, feature: api, feature: chat, mobile apps

#1084 Fixes #1083
  lib/Controller/PageController.php
  lib/Notification/Hooks.php
Labels: 3. to review

#1085 Adjust UI to layout changes in server
  css/style.scss
  js/app.js
  lib/Controller/PageController.php
  templates/index-public.php
  templates/index.php
  tests/acceptance/features/bootstrap/ConversationInfoContext.php
Labels: 3. to review, bug, design, feature: frontend

#1089 Fix "Participants" text not shown in tab header
  css/style.scss
  js/app.js
Labels: 3. to review, bug, design, regression
