Repository nextcloud/spreed, pull requests merged in 2018-08, with the labels that each got.

#1091 Fix colour and opacity of icons shown over main content
  css/style.scss
  js/app.js
Labels: 3. to review, bug, design, regression

#1093 Adjust UI to further layout changes in server
  css/style.scss
  templates/index-public.php
Labels: 3. to review, bug, design, regression

#1092 Fix size of sidebar trigger and fullscreen icons
  css/style.scss
Labels: 3. to review, bug, design

#1097 Make sure the list of signaling messages is a JSON array
  lib/Controller/SignalingController.php
Labels: 4. to release, backport-request, bug, feature: signaling

#1094 Settings UI enhancements
  css/settings-admin.scss
  js/admin/signaling-server.js
  js/admin/stun-server.js
  js/admin/turn-server.js
  templates/settings/admin/signaling-server.php
Labels: 3. to review, design, papercut

#1087 Don't count system messages to unread
  appinfo/info.xml
  css/style.scss
  docs/api-v1.md
  js/views/roomlistview.js
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Chat/Notifier.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version3003Date20180730080327.php
  lib/Participant.php
  lib/Room.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, bug, feature: api, feature: chat

#1086 Different bubble for mentions
  appinfo/info.xml
  css/style.scss
  docs/api-v1.md
  js/views/roomlistview.js
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version3003Date20180730080327.php
  lib/Participant.php
  lib/Room.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, bug, design, feature: chat, feature: frontend

#1029 Always notify in one2one rooms
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request, enhancement, feature: chat, mobile apps

#1104 Fix the data type of the comment id
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, feature: api, feature: chat

#1112 Fix undefined index latest_comment
  lib/Chat/CommentsManager.php
Labels: 3. to review, bug

#1114 Work around fetching participants before setting the room
  js/app.js
Labels: 3. to review, backport-request, bug, feature: frontend

#1116 [stable13] Work around fetching participants before setting the room
  js/app.js
Labels: 3. to review, bug, feature: frontend

#1119 Set the notification message to the full chat message with mentions
  lib/Chat/Notifier.php
  lib/Notification/Notifier.php
  tests/php/Chat/NotifierTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement

#1121 Increase seconds threshold for grouping messages.
  js/views/chatview.js
Labels: enhancement, feature: chat

#1049 Add support for sending the password for a share by Nextcloud Talk
  appinfo/info.xml
  appinfo/routes.php
  css/publicshareauth.scss
  js/connection.js
  js/publicshareauth.js
  lib/AppInfo/Application.php
  lib/Controller/PageController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version3003Date20180720162342.php
  lib/Notification/Notifier.php
  lib/PublicShareAuth/Listener.php
  lib/PublicShareAuth/TemplateLoader.php
  lib/Room.php
Labels: 3. to review, enhancement

#1122 Fixes for favorite conversations
  css/style.scss
  js/views/roomlistview.js
Labels: 3. to review, bug, feature: frontend

#1123 Add support for video calls when requesting the password for a share
  appinfo/routes.php
  css/publicshareauth.scss
  js/app.js
  js/connection.js
  js/publicshareauth.js
  js/webrtc.js
  lib/Controller/PageController.php
  lib/Room.php
Labels: 2. developing, enhancement

#1118 Ignore user mentions for non-existing users, that basically means you…
  lib/Chat/RichMessageHelper.php
  tests/integration/features/chat/rich-messages.feature
  tests/php/Chat/RichMessageHelperTest.php
Labels: 3. to review, bug, feature: chat

#1124 Fix update of CSS classes during screensharing
  js/webrtc.js
Labels: 4. to release, backport-request, bug, feature: frontend

#1134 Fix "Object of class DateTime could not be converted to int"
  lib/Chat/AutoComplete/Sorter.php
  tests/php/Chat/AutoComplete/SorterTest.php
Labels: 3. to review, bug, feature: chat

#1132 Add unit tests for TalkSession class
  tests/php/TalkSessionTest.php
Labels: 3. to review

#971 Fix missing call-type in groups with no name
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request

#1140 Change <h3> to <h2> in admin-settings
  templates/settings/admin/signaling-server.php
  templates/settings/admin/stun-server.php
  templates/settings/admin/turn-server.php
Labels: 3. to review, design

#1142 Make current-user mentions blue again
  css/comments.scss
Labels: 3. to review, bug, feature: chat

#1141 System message for call started
  docs/api-v1.md
  lib/Chat/SystemMessage/Listener.php
  lib/Chat/SystemMessage/Parser.php
Labels: 4. to release, enhancement, feature: chat

#1147 Update Signaling documentation.
  docs/api-v1.md
Labels: 3. to review, feature: signaling

#1149 Better system messages if you did something
  lib/Chat/SystemMessage/Parser.php
Labels: 3. to review, bug, feature: chat

#1050 Add support for room shares
  js/richobjectstringparser.js
  lib/AppInfo/Application.php
  lib/Chat/SystemMessage/Listener.php
  lib/Chat/SystemMessage/Parser.php
  lib/Share/Helper/DeletedShareAPIController.php
  lib/Share/Helper/ShareAPIController.php
  lib/Share/RoomShareProvider.php
  tests/integration/config/behat.yml
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/sharing/create.feature
  tests/integration/features/sharing/delete.feature
  tests/integration/features/sharing/get.feature
  tests/integration/features/sharing/hooks.feature
  tests/integration/features/sharing/move.feature
  tests/integration/features/sharing/restore.feature
  tests/integration/features/sharing/transfer-ownership.feature
  tests/integration/features/sharing/update.feature
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, enhancement

#914 Change "inCall" state to contain bit flags (#911).
  appinfo/info.xml
  docs/api-v1.md
  js/app.js
  js/connection.js
  js/signaling.js
  js/views/callinfoview.js
  js/views/roomlistview.js
  js/webrtc.js
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Migration/Version3003Date20180722152733.php
  lib/Migration/Version3003Date20180722152849.php
  lib/Participant.php
  lib/Room.php
  lib/Signaling/BackendNotifier.php
  tests/php/CapabilitiesTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, backport-request, enhancement, feature: webrtc

#1151 Add button to share files from Talk UI
  css/comments.scss
  js/views/chatview.js
Labels: 3. to review, enhancement

#1152 Fix "Add" button when chat is shown in sidebar
  css/style.scss
Labels: 3. to review, bug, design

#1154 Fix "call to member function on null"
  lib/Share/RoomShareProvider.php
Labels: 3. to review, bug, feature: room-shares

#1155 Shorten the system messages
  lib/Chat/SystemMessage/Parser.php
Labels: 3. to review, bug, feature: chat

#1159 Fix some a11y issues
  css/comments.scss
  css/style.scss
  js/views/callinfoview.js
Labels: 3. to review, bug, feature: frontend

#1158 Use the search term as conversation name again
  appinfo/info.xml
  css/style.scss
  js/app.js
  js/views/roomlistview.js
Labels: 3. to review, bug, feature: frontend

#1162 Last message and notification for shares
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Chat/SystemMessage/Listener.php
  lib/Chat/SystemMessage/Parser.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Notification/Notifier.php
  tests/php/Chat/NotifierTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement, feature: chat, feature: room-shares

#1169 Fix the system message of call activities
  lib/Activity/Hooks.php
  lib/Manager.php
  lib/Participant.php
Labels: 3. to review, bug, feature: chat
