Repository nextcloud/spreed, pull requests merged in 2018-12, with the labels that each got.

#1323 Add support for Talk sidebar in Files app
  appinfo/routes.php
  css/files.scss
  js/embedded.js
  js/filesplugin.js
  js/views/chatview.js
  js/views/virtuallist.js
  lib/AppInfo/Application.php
  lib/BackgroundJob/RemoveEmptyRooms.php
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/Notifier.php
  lib/Controller/FilesController.php
  lib/Controller/PublicShareAuthController.php
  lib/Files/Listener.php
  lib/Files/TemplateLoader.php
  lib/Files/Util.php
  lib/Manager.php
  lib/Notification/Hooks.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
  tests/php/Chat/NotifierTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement, feature: frontend

#1327 Fix wording and icons for screensharing options
  css/style.scss
  img/share-window.svg
  js/app.js
  js/publicshareauth.js
  templates/index-public.php
  templates/index.php
Labels: 3. to review, design, enhancement

#1324 Fix "removeTabHeader" on Internet Explorer
  js/views/tabview.js
Labels: 3. to review, bug, feature: frontend

#1332 Fix Chat tab not shown in Files app if Sharing tab was not opened
  js/filesplugin.js
Labels: 3. to review, bug, feature: talk-sidebar

#1325 Extract view for empty content
  js/app.js
  js/connection.js
  js/embedded.js
  js/models/room.js
  js/publicshareauth.js
  js/signaling.js
  js/views/emptycontentview.js
  js/views/roomlistview.js
  js/webrtc.js
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 3. to review

#1340 Extract CSS styles for videos
  css/style.scss
  css/video.scss
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 3. to review

#1337 Fix acceptance tests regression from #1275
  tests/acceptance/features/conversation.feature
Labels: 3. to review, bug, feature: frontend

#1330 End pending signaling when user is no longer in the room
  lib/AppInfo/Application.php
  lib/Room.php
Labels: 3. to review, bug, feature: frontend, feature: signaling

#1326 Extract view for media controls
  css/style.scss
  js/app.js
  js/publicshareauth.js
  js/views/mediacontrolsview.js
  js/views/templates.js
  js/views/templates/mediacontrolsview.handlebars
  js/webrtc.js
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 2. developing

#1312 Add support for video calls to the talk sidebar in files app
  css/files.scss
  js/app.js
  js/connection.js
  js/embedded.js
  js/filesplugin.js
  js/publicshareauth.js
  js/views/emptycontentview.js
  js/views/mediacontrolsview.js
  js/webrtc.js
  lib/Files/TemplateLoader.php
Labels: 2. developing, enhancement, feature: talk-sidebar

#1343 Show "Chat" tab also when a file is not shared
  css/files.scss
  js/filesplugin.js
Labels: 3. to review, feature: talk-sidebar

#1345 Prevent breaking the call when the Files sidebar is closed in Chromium
  js/filesplugin.js
Labels: 3. to review, bug, feature: talk-sidebar

#1344 Persistent join file rooms
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/FilesController.php
  lib/Controller/RoomController.php
  lib/Exceptions/UnauthorizedException.php
  lib/Files/Listener.php
  lib/Room.php
Labels: 3. to review, enhancement, feature: talk-sidebar

#1335 Better integration testing
  .drone.yml
  tests/integration/features/conversation/add-participant.feature
  tests/integration/features/conversation/delete-room.feature
  tests/integration/features/conversation/one-to-one.feature
  tests/integration/features/conversation/promotion-demotion.feature
  tests/integration/features/conversation/public-private.feature
  tests/integration/features/conversation/remove-participant.feature
  tests/integration/features/conversation/remove-self.feature
  tests/integration/features/conversation/rename-room.feature
  tests/integration/features/conversation/set-password.feature
Labels: 3. to review

#1348 Improve readme
  .github/contributing.md
  README.md
  docs/call-in-action.png
Labels: 3. to review

#1346 Use special icons for rooms associated to objects
  css/style.scss
  js/views/roomlistview.js
Labels: 3. to review, design, feature: frontend

#1331 Increase max-version to 16
  .drone.yml
  appinfo/info.xml
Labels: 3. to review, enhancement

#1353 Fix unit tests
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, bug

#1360 Fix screensharing support in Chrome 71 and Iridium.
  js/simplewebrtc.js
  js/views/mediacontrolsview.js
Labels: 3. to review, backport-request, bug, feature: frontend, feature: webrtc

#1352 [stable14] Errors with system messages
  lib/Chat/SystemMessage/Parser.php
Labels: 3. to review, bug, feature: chat, feature: room-shares

#1357 Bump server version in the helper app for integration tests
  tests/integration/spreedcheats/appinfo/info.xml
Labels: 3. to review

#1368 Backport/1364/stable14
  js/app.js
  js/simplewebrtc.js
Labels: 3. to review, backport-request, bug, feature: webrtc

#1367 Send initial screensharing stream to participants that don't publish video.
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend

#1376 Add full Handlebars library
  js/vendor/handlebars/handlebars.min.js
  lib/Files/TemplateLoader.php
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 3. to review, bug, feature: frontend, regression

#1351 Adjust tests to check that updating a received share is forbidden
  tests/integration/features/sharing/update.feature
Labels: 4. to release, backport-request

#1383 Fix mentions being too close to the following text
  js/views/templates.js
  js/views/templates/richobjectstringparser_userlocal.handlebars
Labels: 3. to review, backport-request, bug, design

#1381 Fix multiple mentions which are used directly behind each others
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat, feature: frontend

#1384 Fix empty content message in Files app when WebRTC is not supported
  js/embedded.js
  js/filesplugin.js
  js/publicshareauth.js
Labels: 3. to review, backport-request, bug, feature: talk-sidebar

#1386 Fix position of input and edit button for room name
  css/style.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1387 Add icon to go to the file associated to a room
  css/style.scss
  js/views/callinfoview.js
Labels: 3. to review, backport-request, design, feature: frontend

#1389 Adjust tab header icons to changes in server
  css/style.scss
  js/views/tabview.js
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1388 Make rooms for files in shared folders accessible to shared folder users
  css/files.scss
  js/filesplugin.js
  lib/Controller/FilesController.php
  lib/Files/Listener.php
  lib/Files/Util.php
Labels: 3. to review, backport-request, bug, feature: talk-sidebar

#1385 Fix opacity of submit buttons
  css/authenticate.css
  css/chatview.scss
  css/style.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1405 Fix room name input width
  css/style.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend, regression

#1409 Pass empty list of session ids when notifying about removed guests.
  lib/AppInfo/Application.php
Labels: 3. to review, backport-request, bug, feature: signaling

#1419 Fix favorite icon.
  css/style.scss
Labels: backport-request, bug, design
