Repository nextcloud/spreed, pull requests merged in 2018-09, with the labels that each got.

#1170 Make possible to pick both folders and files
  js/views/chatview.js
Labels: 4. to release, feature: frontend

#1172 Add missing 'systemMessage' attribute to room's lastMessage.
  lib/Controller/RoomController.php
Labels: 3. to review, bug, feature: chat

#1176 Fix TURN credential generation.
  lib/Config.php
  tests/php/ConfigTest.php
Labels: 3. to review, backport-request, bug

#1173 WIP: Show user avatar in mentions
  css/comments.scss
  js/richobjectstringparser.js
  js/views/chatview.js
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/chat.feature
Labels: 4. to release, feature: chat

#1163 Show preview of shared files in system messages
  css/comments.scss
  js/richobjectstringparser.js
  js/views/chatview.js
  lib/Chat/SystemMessage/Parser.php
Labels: 4. to release, enhancement, feature: chat, feature: room-shares

#1095 Add and update API for standalone signaling server from wiki.
  docs/standalone-signaling-api-v1.md
Labels: 3. to review, backport-request

#1188 Fix position of contacts menu shown on mentions
  css/comments.scss
Labels: 3. to review, backport-request, bug, design, feature: chat

#1190 Add tooltips to submit and share buttons
  js/views/chatview.js
Labels: 4. to release, backport-request, bug, design, feature: chat

#1189 Make possible to run Docker integration tests on other databases
  tests/integration/run-docker.sh
Labels: 3. to review, backport-request

#1192 Ensure that "object_type" and "object_id" are strings
  lib/Manager.php
Labels: 3. to review, backport-request, bug

#1200 [stable13] Make sure the list of signaling messages is a JSON array
  lib/Controller/SignalingController.php
Labels: 3. to review, bug

#1199 [stable13] Allow single quote in date-separater for french translation
  js/views/chatview.js
Labels: 3. to review

#1203 [stable13] Fix TURN credential generation.
  lib/Config.php
  tests/php/ConfigTest.php
Labels: 3. to review, bug

#1201 [stable13] Fix the data type of the comment id
  lib/Controller/ChatController.php
Labels: 3. to review, bug

#1202 [stable13] Fix undefined index latest_comment
  lib/Chat/CommentsManager.php
Labels: 3. to review, bug

#1177 Add button to test TURN settings.
  .eslintignore
  css/settings-admin.scss
  js/admin/sha1.js
  js/admin/turn-server.js
  templates/settings/admin/turn-server.php
Labels: 3. to review, feature: settings

#1205 Fix integration tests with Docker image for PostgreSQL 10.5
  .drone.yml
  tests/integration/run-docker.sh
Labels: 3. to review, backport-request, bug

#1206 Trigger events before/after all received signaling messages.
  js/signaling.js
Labels: 3. to review, backport-request, feature: signaling

#1209 [stable13] Make possible to run Docker integration tests on other databases
  tests/integration/run-docker.sh
Labels: 3. to review

#1207 Make Participant class strict
  lib/Manager.php
  lib/Participant.php
Labels: 3. to review, backport-request

#1212 [stable13] Fix integration tests with Docker image for PostgreSQL 10.5
  .drone.yml
  tests/integration/run-docker.sh
Labels: 3. to review, bug

#1213 Make RoomController strict
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, technical debt

#1208 Fix rendering of the participant list
  js/models/participantcollection.js
  js/views/participantlistview.js
Labels: 4. to release, backport-request, bug, feature: frontend

#1168 Message parser
  lib/AppInfo/Application.php
  lib/Chat/Listener.php
  lib/Chat/MessageParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Notification/Notifier.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement, feature: chat

#1090 Allow to invite email addresses
  appinfo/routes.php
  css/style.scss
  docs/api-v1.md
  js/app.js
  js/views/participantview.js
  lib/Capabilities.php
  lib/Controller/RoomController.php
  lib/GuestManager.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api, mobile apps

#1222 [stable14] Fix rendering of the participant list
  js/models/participantcollection.js
  js/views/participantlistview.js
Labels: 3. to review, bug, feature: frontend

#1220 Add unit tests for collaborator search
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
Labels: 3. to review, backport-request, feature: room-shares

#1193 Add API documentation for "objectType" and "objectId"
  docs/api-v1.md
Labels: 3. to review
