Repository nextcloud/spreed, pull requests merged in 2018-11, with the labels that each got.

#1267 Better notifications for password shares
  lib/Controller/PublicShareAuthController.php
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug

#1280 Use short beautiful links for notifications
  lib/Notification/Notifier.php
Labels: 3. to review, bug

#1285 Fix room name in CallInfoView for "share:password" rooms
  js/views/callinfoview.js
Labels: 3. to review, backport-request, bug

#1268 Add ability to invite groups
  appinfo/routes.php
  docs/api-v1.md
  js/app.js
  js/views/participantview.js
  lib/Capabilities.php
  lib/Controller/RoomController.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, mobile apps

#1273 Add support for sending the password for a link share by Nextcloud Talk
  lib/Controller/PublicShareAuthController.php
  lib/Controller/RoomController.php
  lib/Notification/Notifier.php
Labels: 3. to review, enhancement, feature: talk-sidebar

#1240 Fix avatars of users in guest sytem messages
  js/richobjectstringparser.js
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat

#1287 Fix vertical position of contacts menu on author row
  css/comments.scss
Labels: 3. to review, backport-request, bug, design

#1254 Fix user mentions with spaces
  js/views/chatview.js
  lib/Chat/Parser/UserMention.php
Labels: 3. to review, bug, feature: chat

#1289 [stable14] Fix interaction with participant menu
  css/style.scss
  js/views/participantlistview.js
Labels: 3. to review, design, feature: frontend

#1290 [stable14] Fix room name in CallInfoView for "share:password" rooms
  js/views/callinfoview.js
Labels: 3. to review, bug

#1255 Move admin templates to compiled handlebars
  .eslintignore
  Makefile
  js/admin/signaling-server.js
  js/admin/stun-server.js
  js/admin/templates.js
  js/admin/templates/signaling-server.handlebars
  js/admin/templates/stun-server.handlebars
  js/admin/templates/turn-server.handlebars
  js/admin/turn-server.js
  templates/settings/admin/signaling-server.php
  templates/settings/admin/stun-server.php
  templates/settings/admin/turn-server.php
Labels: 3. to review, feature: settings

#1291 [stable14] Correctly cast the incall flag to integer
  js/views/callinfoview.js
  lib/Controller/RoomController.php
  lib/Manager.php
Labels: 3. to review, bug, feature: api

#1293 [stable14] Fix vertical position of contacts menu on author row
  css/comments.scss
Labels: 3. to review, bug, feature: chat

#1292 [stable14] Avatar on mentions from guests
  js/richobjectstringparser.js
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat

#1294 [stable14] Fix CSP eval problem in admin page
  .eslintignore
  Makefile
  css/settings-admin.scss
  js/admin/sha1.js
  js/admin/signaling-server.js
  js/admin/stun-server.js
  js/admin/templates.js
  js/admin/templates/signaling-server.handlebars
  js/admin/templates/stun-server.handlebars
  js/admin/templates/turn-server.handlebars
  js/admin/turn-server.js
  templates/settings/admin/signaling-server.php
  templates/settings/admin/stun-server.php
  templates/settings/admin/turn-server.php
Labels: 3. to review, bug, feature: settings, feature: webrtc

#1295 [stable14] Allow to reshare files again
  js/views/chatview.js
  lib/Chat/SystemMessage/Listener.php
  lib/Share/RoomShareProvider.php
Labels: 3. to review, enhancement, feature: room-shares

#1277 Fix signaling settings not loaded when requesting the password by Talk
  js/publicshareauth.js
  js/signaling.js
  lib/PublicShareAuth/TemplateLoader.php
Labels: 3. to review, backport-request, bug, feature: signaling, feature: talk-sidebar

#1296 [stable14] Better notifications for password shares
  lib/Controller/PublicShareAuthController.php
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, feature: talk-sidebar

#1297 [stable14] Signaling settings not loaded when requesting the password by talk
  js/publicshareauth.js
  js/signaling.js
  lib/PublicShareAuth/TemplateLoader.php
Labels: 3. to review, bug, feature: talk-sidebar, feature: webrtc

#1302 Fix the scroll position of the chat view in the sidebar
  js/app.js
  js/views/chatview.js
  js/views/sidebarview.js
  js/views/tabview.js
Labels: 3. to review, backport-request, bug, feature: chat, feature: frontend

#1286 Add session & participantFlags to participant
  lib/Activity/Hooks.php
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/HookListener.php
  lib/PublicShareAuth/Listener.php
  lib/Room.php
  lib/Share/Helper/DeletedShareAPIController.php
  lib/Share/Helper/ShareAPIController.php
  lib/Share/RoomShareProvider.php
  lib/Signaling/BackendNotifier.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
Labels: 3. to review, enhancement, feature: api, technical debt

#1300 Fix avatar position in mention box
  css/comments.scss
Labels: 3. to review, bug, feature: chat

#1304 Fix getting current tab ID when there are no tabs
  js/views/tabview.js
Labels: 3. to review, bug, feature: chat, feature: frontend

#1271 Improve performance of the list of chat messages
  css/comments.scss
  css/style.scss
  js/app.js
  js/models/chatmessagecollection.js
  js/views/chatview.js
  js/views/virtuallist.js
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
  tests/acceptance/features/bootstrap/ChatContext.php
Labels: 3. to review, bug, enhancement, feature: chat, feature: frontend

#1306 Add Drone step to check Handlebars templates
  .drone.yml
  Makefile
  check-handlebars-templates.sh
  compile-handlebars-templates.sh
  package.json
Labels: 3. to review

#1303 [stable14] Fix the scroll position of the chat view in the sidebar
  js/app.js
  js/views/chatview.js
  js/views/sidebarview.js
  js/views/tabview.js
Labels: 3. to review, bug, feature: chat, feature: frontend

#1261 Show again participants without streams in a call
  js/webrtc.js
Labels: 3. to review, backport-request, feature: frontend

#1310 Move ChatView and RichObjectStringParser to precompiled Handlebars templates
  Makefile
  compile-handlebars-templates.sh
  js/views/chatview.js
  js/views/richobjectstringparser.js
  js/views/templates.js
  js/views/templates/chatview.handlebars
  js/views/templates/chatview_add_comment.handlebars
  js/views/templates/chatview_comment.handlebars
  js/views/templates/richobjectstringparser_filepreview.handlebars
  js/views/templates/richobjectstringparser_unknown.handlebars
  js/views/templates/richobjectstringparser_unknownlink.handlebars
  js/views/templates/richobjectstringparser_userlocal.handlebars
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 3. to review

#1314 Extract view for call button
  js/views/callbutton.js
  js/views/callinfoview.js
  js/views/templates.js
  js/views/templates/callbutton.handlebars
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 3. to review

#1313 Fix avatar position in mention box.
  css/comments.scss
Labels: 3. to review, bug, feature: chat

#1315 Test against 15 for now
  .drone.yml
Labels: 3. to review

#1316 Rename "commentsTabView" to "chatView"
  css/chatview.scss
  css/publicshareauth.scss
  css/style.scss
  js/app.js
  js/views/chatview.js
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 3. to review

#1320 Fix room polling not stopped when leaving the current room
  js/signaling.js
Labels: 3. to review, bug

#1321 Add support for sharing fullscreen on Firefox.
  js/app.js
  js/simplewebrtc.js
  templates/index-public.php
  templates/index.php
Labels: 3. to review, backport-request, enhancement, feature: frontend
