Repository nextcloud/spreed, pull requests merged in 2018-03, with the labels that each got.

#685 pass if no valid user object was returned
  lib/ContactsMenu/Providers/CallProvider.php
Labels: 3. to review, backport-request, bug

#686 [stable13] pass if no valid user object was returned
  lib/ContactsMenu/Providers/CallProvider.php
Labels: 3. to review, bug

#663 cast userids to string to avoid issues with numerical IDs
  lib/Activity/Hooks.php
Labels: 3. to review, backport-request, bug

#694 [stable 13] cast userids to string to avoid issues with numerical IDs
  lib/Activity/Hooks.php
Labels: 3. to review, bug

#682 Remove https:// prefix from TURN URL placeholder
  js/admin/stun-server.js
  js/admin/turn-server.js
Labels: 3. to review, backport-request, bug, feature: settings

#696 [stable13] Strip protocol from stun and turn
  js/admin/stun-server.js
  js/admin/turn-server.js
Labels: 3. to review, bug

#697 Also delete rooms when the leaving user is the only non-guest
  appinfo/info.xml
  lib/BackgroundJob/RemoveEmptyRooms.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Room.php
Labels: 3. to review, backport-request, bug, feature: api

#699 Make sure users with numerical user ids/display names still show as u…
  js/views/participantlistview.js
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, feature: api

#700 Fix screensharing video position.
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#702 Fix local video shadow
  css/style.scss
Labels: 3. to review, backport-request, bug, design

#619 Support connecting without local media (#538).
  css/style.scss
  js/app.js
  js/connection.js
  js/init.js
  js/signaling.js
  js/simplewebrtc.js
  js/views/callinfoview.js
  js/views/roomlistview.js
  js/webrtc.js
  templates/index-public.php
  templates/index.php
Labels: 3. to review, backport-request, enhancement, feature: video call webrtc

#706 Improve guest handling in comments
  js/views/chatview.js
Labels: 3. to review, backport-request, enhancement, feature: chat

#500 Spelling: by a user that has since been deleted :)
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 4. to release, backport-request, bug, feature: chat

#705 Add shortcuts for calling
  js/app.js
Labels: 3. to review, backport-request, design, enhancement

#709 Fix undefined this.connection when creating a room
  js/app.js
Labels: 3. to review, backport-request, bug

#712 [stable 13] Fix screensharing video position.
  css/style.scss
Labels: 3. to review, bug

#713 [stable 13] Fix local video shadow.
  css/style.scss
Labels: 3. to review, bug, design

#718 Provide the app to logger
  lib/Signaling/BackendNotifier.php
Labels: 3. to review

#719 Remove unused dependency to logger
  lib/Controller/CallController.php
Labels: 3. to review

#720 Don't check for a password, when we didn't even find a room
  lib/Controller/PageController.php
Labels: 3. to review, backport-request, bug, feature: api

#710 Store guest names
  .eslintrc.yml
  appinfo/info.xml
  appinfo/routes.php
  bower.json
  css/style.scss
  docs/api-v1.md
  js/app.js
  js/models/chatmessage.js
  js/models/chatmessagecollection.js
  js/signaling.js
  js/vendor/jshashes/.bower.json
  js/vendor/jshashes/LICENSE
  js/vendor/jshashes/README.md
  js/vendor/jshashes/bower.json
  js/vendor/jshashes/component.json
  js/vendor/jshashes/hashes.js
  js/vendor/jshashes/hashes.min.js
  js/views/chatview.js
  js/views/participantlistview.js
  js/views/roomlistview.js
  js/webrtc.js
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/GuestController.php
  lib/Controller/RoomController.php
  lib/GuestManager.php
  lib/Migration/Version3002Date20180319104030.php
  templates/index-public.php
  templates/index.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, bug, feature: chat

#716 Disconnect media when leaving call
  js/connection.js
  js/signaling.js
  js/simplewebrtc.js
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: video call webrtc

#717 Fix join/leave with firefox aka. yay for autocomplete
  js/views/callinfoview.js
Labels: 3. to review, backport-request, bug

#725 Correctly focus editable content with firefox
  js/app.js
  js/views/chatview.js
  js/views/tabview.js
Labels: 3. to review, backport-request, bug, feature: chat

#724 Update participant list also when not in call
  appinfo/routes.php
  docs/api-v1.md
  js/app.js
  lib/AppInfo/Application.php
  lib/Controller/ChatController.php
  lib/Controller/GuestController.php
  lib/Controller/SignalingController.php
  lib/GuestManager.php
Labels: 4. to release, backport-request, bug, feature: chat

#726 Fix JS docs
  js/models/chatmessagecollection.js
  js/models/participantcollection.js
  js/models/roomcollection.js
  js/views/chatview.js
  js/views/sidebarview.js
  js/views/tabview.js
Labels: 3. to review, bug

#727 [stable13] Also delete rooms when the leaving user is the only non-guest
  appinfo/info.xml
  lib/BackgroundJob/RemoveEmptyRooms.php
  lib/BackgroundJob/ResetInCallFlags.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Room.php
Labels: 3. to review, bug, feature: api

#732 [stable13] Provide the app to logger
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, bug

#731 [stable13] Remove unused dependency to logger
  lib/Controller/CallController.php
Labels: 3. to review, bug

#738 [stable13] Fix JS docs
  js/models/chatmessagecollection.js
  js/models/participantcollection.js
  js/models/roomcollection.js
  js/views/chatview.js
  js/views/sidebarview.js
  js/views/tabview.js
Labels: 3. to review, bug

#736 [stable13] Fix join/leave with firefox aka. yay for autocomplete
  js/views/callinfoview.js
Labels: 3. to review, bug

#733 [stable13] Chat guest handling
  .eslintrc.yml
  appinfo/info.xml
  appinfo/routes.php
  bower.json
  css/style.scss
  docs/api-v1.md
  js/app.js
  js/models/chatmessage.js
  js/models/chatmessagecollection.js
  js/signaling.js
  js/vendor/jshashes/.bower.json
  js/vendor/jshashes/LICENSE
  js/vendor/jshashes/README.md
  js/vendor/jshashes/bower.json
  js/vendor/jshashes/component.json
  js/vendor/jshashes/hashes.js
  js/vendor/jshashes/hashes.min.js
  js/views/chatview.js
  js/views/participantlistview.js
  js/views/roomlistview.js
  js/webrtc.js
  lib/AppInfo/Application.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/GuestController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/GuestManager.php
  lib/Migration/Version3002Date20180319104030.php
  templates/index-public.php
  templates/index.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, bug, enhancement

#734 [stable13] Don't check for a password, when we didn't even find a room
  lib/Controller/PageController.php
Labels: 3. to review, bug

#735 [stable13] Disconnect media when leaving room
  js/connection.js
  js/signaling.js
  js/simplewebrtc.js
  js/webrtc.js
Labels: 3. to review, enhancement

#737 [stable13] Correctly focus editable content with firefox
  js/app.js
  js/views/chatview.js
  js/views/tabview.js
Labels: 3. to review, bug

#730 [stable13] Add shortcuts for calling
  js/app.js
Labels: 3. to review, enhancement

#729 [stable13] Spelling: by a user that has since been deleted
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug

#742 Add a notification when readding the default stun server
  js/admin/stun-server.js
Labels: 3. to review, backport-request, bug, feature: settings

#744 Fixed authenticate script
  css/authenticate.css
Labels: 4. to release, backport-request, bug, design, feature: frontend

#745 Do not cut popover on participant list
  css/style.scss
Labels: 3. to review, bug, design

#743 Remove chat when leaving active room
  js/signaling.js
  js/views/roomlistview.js
Labels: 3. to review, backport-request, bug, feature: webrtc

#647 Show password input field in a popover menu.
  css/style.scss
  js/views/callinfoview.js
  js/views/editabletextlabel.js
Labels: 3. to review, backport-request, design, enhancement

#748 Multiple room session support
  appinfo/routes.php
  css/style.scss
  docs/api-v1.md
  js/app.js
  js/connection.js
  js/models/roomcollection.js
  js/signaling.js
  js/views/callinfoview.js
  js/views/roomlistview.js
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/GuestController.php
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Room.php
  lib/TalkSession.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/group.feature
  tests/integration/features/callapi/one-to-one.feature
  tests/integration/features/callapi/password.feature
  tests/integration/features/callapi/public.feature
  tests/integration/features/one-to-one.feature
  tests/integration/features/remove-self.feature
  tests/integration/features/set-password.feature
  tests/php/CapabilitiesTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, backport-request, bug

#741 Allow screensharing even when alone
  css/style.scss
  js/app.js
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: webrtc

#750 Change keyboard shortcuts
  js/app.js
  templates/index-public.php
  templates/index.php
Labels: 3. to review, backport-request, bug, feature: frontend

#751 Unify naming in the UI: rooms are conversations
  js/app.js
  js/views/callinfoview.js
  js/views/participantview.js
  js/views/roomlistview.js
  templates/index.php
Labels: 3. to review, backport-request, enhancement, feature: frontend

#749 Improve fullscreen handling
  css/style.scss
  js/connection.js
  templates/index.php
Labels: 3. to review, backport-request, bug, feature: frontend

#754 Sort correctly room collection.
  js/models/roomcollection.js
Labels: 3. to review, backport-request, bug, regression

#756 Ignore shortcuts in chat
  js/app.js
Labels: 3. to review, backport-request, bug, feature: chat

#757 Fix screensharing button style when no local video.
  css/style.scss
  js/app.js
Labels: 3. to review, backport-request, bug, design
