Repository nextcloud/spreed, pull requests merged in 2019-01, with the labels that each got.

#1418 Add hook to allow returning additional data for clients joining a room.
  lib/Controller/SignalingController.php
  tests/php/Controller/SignalingControllerTest.php
Labels: 3. to review, feature: signaling

#1436 Remove notifications when they are done
  lib/AppInfo/Application.php
  lib/Notification/Hooks.php
Labels: 3. to review, backport-request, bug, feature: api

#1440 Update testing matrix
  .drone.yml
Labels: 3. to review, bug

#1433 Make Signaling\BackendNotifier strict
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, technical debt

#1451 Dark theme fixes
  css/chatview.scss
  css/style.scss
  img/no-password.svg
  js/app.js
  js/views/callinfoview.js
  js/views/participantview.js
  js/views/roomlistview.js
Labels: 3. to review, backport-request, bug, design, feature: talk-sidebar, help wanted

#1456 Fix browser history
  js/app.js
  js/connection.js
Labels: 3. to review, backport-request, bug, feature: frontend, feature: talk-sidebar

#1460 Add changelog for 5.0.1
  CHANGELOG.md
Labels: backport-request

#1461 Always use white icons on the avatar-alike-placeholders
  css/style.scss
  js/app.js
  js/views/participantview.js
  js/views/roomlistview.js
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1465 Make sure there is always a trailing slash
  lib/Config.php
Labels: 3. to review, backport-request, bug, regression

#1467 Fix page title not updated when room name is updated
  js/app.js
Labels: 3. to review, backport-request, bug, feature: frontend

#1471 Fix autocomplete on darktheme
  css/autocomplete.scss
Labels: 3. to review, backport-request, bug

#1480 Fix submit button in public share authentication page
  css/publicshareauth.scss
Labels: 3. to review, backport-request, bug, design, feature: talk-sidebar, regression

#1482 Show autocompletion as soon as "@" is typed
  js/views/chatview.js
Labels: 3. to review, feature: chat, feature: frontend

#1484 Make the seperator visible
  css/style.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1474 Correctly compare the correct user to the owner
  lib/Chat/Parser/SystemMessage.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, bug, feature: room-shares

#1491 [stable15] Reduce the number of loaded scripts
  css/merged-files.scss
  css/merged-share-auth.scss
  css/merged.scss
  js/merged-files.json
  js/merged-guest.json
  js/merged-share-auth.json
  js/merged.json
  lib/Files/TemplateLoader.php
  lib/PublicShareAuth/TemplateLoader.php
  templates/index-public.php
  templates/index.php
Labels: 3. to review

#1485 Fix icons for incall scene when dark mode is enabled
  css/style.scss
  css/video.scss
  js/views/sidebarview.js
  js/views/templates.js
  js/views/templates/mediacontrolsview.handlebars
  js/webrtc.js
  templates/index-public.php
  templates/index.php
Labels: 3. to review, backport-request, bug, feature: frontend

#1426 Fix display name of reshare with one-to-one room not invited to
  lib/Share/Helper/ShareAPIController.php
  tests/integration/features/sharing/get.feature
Labels: 3. to review, backport-request, bug, feature: room-shares

#1493 Cannot use OCP\Util as Util because the name is already in use
  lib/Files/TemplateLoader.php
Labels: 3. to review, bug, feature: talk-sidebar

#1496 Do not show room names when the user is not part of it
  lib/Share/Helper/ShareAPIController.php
  tests/integration/features/sharing/get.feature
Labels: 3. to review, backport-request, bug, feature: room-shares

#1500 Also add default stun server on valid but empty value
  lib/Config.php
Labels: 3. to review, backport-request, bug
