Repository nextcloud/spreed, pull requests merged in 2019-07, with the labels that each got.

#1923 Allow longer chat messages
  docs/api-v1.md
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Command/Executor.php
  lib/Chat/CommentsManager.php
  lib/Chat/Parser/SystemMessage.php
  lib/Notification/Notifier.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, bug, mobile apps

#1944 Bundle SimpleWebRTC with WebRTC adapter 7.2.4
  js/simplewebrtc/bundled.js
Labels: 3. to review, dependencies

#1929 Leave call and room when logging out
  lib/Listener.php
  lib/TalkSession.php
Labels: 3. to review, backport-request, bug

#1919 Allow to escape commands
  lib/Chat/Command/Listener.php
  lib/Chat/Parser/UserMention.php
  tests/integration/features/chat/commands.feature
Labels: 4. to release, enhancement, feature: bots & commands 🤖, feature: chat 💬

#1922 Fix CSP with wss:// and ws:// signaling server
  lib/Config.php
  tests/php/ConfigTest.php
Labels: 4. to release, backport-request, bug, feature: settings ⚙️

#1935 added a caption and improved the radio buttons descriptions
  css/style.scss
  js/views/roomlistview.js
  js/views/templates.js
  js/views/templates/roomlistview.handlebars
Labels: 4. to release, enhancement, feature: frontend 🖌️

#1941 Prevent sidebar and fullscreen icons from overlapping with the scrollbar (issue 1765)
  css/style.scss
Labels: 4. to release, bug, design, feature: frontend 🖌️

#1951 Make the app compliant again
  lib/Listener.php
Labels: 3. to review, bug, regression

#1953 Keep last visible message when new message field height changes
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#1949 Use shared Browserslist config
  js/simplewebrtc/bundled.js
  package-lock.json
  package.json
  vue/.babelrc.js
  vue/package-lock.json
  vue/package.json
Labels: 3. to review

#1946 Only react to shortcuts which can be used and make sense
  js/app.js
Labels: 3. to review, bug, feature: frontend 🖌️

#1961 Rebuild with node:lts
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
Labels: 3. to review

#1956 Prevent unwanted clickables for file names and others
  css/chatview.scss
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat 💬

#1957 Start converting to readthedocs
  .gitignore
  README.md
  docs/api-v1.md
  docs/call.md
  docs/capabilities.md
  docs/chat.md
  docs/commands.md
  docs/constants.md
  docs/conversation.md
  docs/index.md
  docs/internal-signaling.md
  docs/participant.md
  docs/standalone-signaling-api-v1.md
  mkdocs.yml
Labels: 3. to review

#1962 [stable16] Rebuild with node:lts
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
Labels: 3. to review

#1964 Sort mentions with the searched start first
  lib/Chat/AutoComplete/Sorter.php
  lib/Controller/ChatController.php
  tests/php/Chat/AutoComplete/SorterTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#1921 Retain one-to-one conversations when a user is deleted
  lib/Listener.php
  lib/Manager.php
  tests/integration/features/conversation/delete-user.feature
Labels: 3. to review, bug, feature: api 🛠️

#1918 Support symfony command lines with --help
  lib/Chat/Command/Executor.php
Labels: 3. to review, backport-request, bug, feature: bots & commands 🤖

#1969 Update VideoView on ICE disconnected/failed with MCU
  css/video.scss
  js/views/videoview.js
  js/webrtc.js
Labels: 3. to review, backport-request, bug, deployed on testing, feature: frontend 🖌️, feature: webrtc 🚡

#1980 Bundle SimpleWebRTC with WebRTC adapter 7.2.5
  Makefile
  js/simplewebrtc/bundled.js
  package-lock.json
  package.json
Labels: 3. to review, bug, dependencies, feature: frontend 🖌️

#1985 More hints for absolute paths
  docs/commands.md
  docs/constants.md
  lib/Command/Command/Add.php
  lib/Command/Command/Update.php
Labels: 3. to review

#1833 Remove development files from package
  Makefile
Labels: 3. to review, technical debt

#1822 Use the contacts menu in the participant list
  css/style.scss
  js/views/participantlistview.js
Labels: 3. to review, feature: frontend 🖌️, papercut

#1983 Check if SimpleWebRTC and VueJS are build correctly
  .drone.yml
  check-handlebars-templates.sh
  check-simplewebrtc-bundle.sh
  check-vuejs-builds.sh
Labels: 3. to review, backport-request, javascript, technical debt

#1988 Make build system compatible with /compile bot
  package.json
Labels: 3. to review, backport-request

#1954 Fixed inconsistent date tooltips in messages
  css/chatview.scss
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#1989 Fix parameter passed to OC.Notification
  js/views/mediacontrolsview.js
Labels: 4. to release, bug, feature: frontend 🖌️

#1999 [stable16] [Security] Bump lodash from 4.17.11 to 4.17.14
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  package-lock.json
  vue/package-lock.json
Labels: 4. to release, dependencies, security

#2005 Fix using "activeRoom" in the shortcut handler before joining a room
  js/app.js
Labels: 3. to review, bug, feature: frontend 🖌️

#2001 Docs/noid/no tests
  .drone.yml
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
Labels: 2. developing

#2004 Fix peer creation for participants no longer in the call
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: signaling 📶, feature: webrtc 🚡

#2011 Use dashes as list bullets in changelog
  lib/Chat/Changelog/Manager.php
Labels: 4. to release, bug, feature: chat 💬

#2013 Use the CSP event
  lib/AppInfo/Application.php
  lib/Listener/CSPListener.php
Labels: 3. to review, enhancement

#2003 Adjust notifier to Nextcloud 17
  lib/AppInfo/Application.php
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug, enhancement, feature: chat 💬

#1976 Fix room synchronization after failure
  js/signaling.js
Labels: 3. to review, backport-request, bug, deployed on testing, feature: frontend 🖌️, feature: signaling 📶

#1928 Don't retry signaling when the room was deleted or restricted
  js/signaling.js
Labels: 3. to review, bug, feature: signaling 📶

#2012 Add a new column to record who joined a call
  appinfo/info.xml
  lib/Activity/Listener.php
  lib/Manager.php
  lib/Migration/Version7000Date20190717141457.php
  lib/Participant.php
  lib/Room.php
Labels: 3. to review, bug, feature: chat 💬

#2021 Add volume indicator for the local audio
  css/video.scss
  js/views/mediacontrolsview.js
  js/views/templates.js
  js/views/templates/mediacontrolsview.handlebars
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: webrtc 🚡

#1971 Fix pending forced reconnection after WebSocket reconnection
  js/signaling.js
Labels: 2. developing, backport-request, bug, deployed on testing, feature: frontend 🖌️

#2031 Fix link detection
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2032 Push notifications are rendered pre joining the call
  lib/Notification/Notifier.php
Labels: 4. to release, bug, regression

#2017 Release v6.0.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
  vue/package-lock.json
  vue/package.json
Labels: 2. developing, technical debt

#2018 Show "Wrong password" info when the conversation password was wrong
  lib/Controller/PageController.php
  templates/authenticate.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/ConversationInfoContext.php
  tests/acceptance/features/bootstrap/ConversationListContext.php
  tests/acceptance/features/bootstrap/PublicConversationContext.php
  tests/acceptance/features/conversation-public.feature
Labels: 4. to release, bug, feature: frontend 🖌️

#2039 Run all tests on merges
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
Labels: 3. to review, bug, regression, technical debt

#1214 🆕 Read marker handling based on ID and settable via API
  appinfo/info.xml
  appinfo/routes.php
  docs/capabilities.md
  docs/chat.md
  docs/conversation.md
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version7000Date20190724121136.php
  lib/Migration/Version7000Date20190724121137.php
  lib/Participant.php
  lib/Room.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, feature: api 🛠️, feature: chat 💬, high, mobile apps

#2038 Check lock files for changes as well
  check-vuejs-builds.sh
Labels: 3. to review, bug, javascript

#2000 ↩️ Reply to messages
  docs/chat.md
  js/models/chatmessage.js
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Model/Message.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/reply.feature
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/NotifierTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 4. to release, design, enhancement, feature: chat 💬

#2045 [stable16] Bump nextcloud-vue-collections from 0.4.0 to 0.5.5 in /vue
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  vue/package-lock.json
  vue/package.json
Labels: 3. to review, bug, dependencies, feature: frontend 🖌️, javascript

#2047 Make links in brackets "(https://nextcloud.com/)" clickable
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2054 [stable16] Bump nextcloud-vue-collections from 0.5.5 to 0.5.6 in /vue
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  vue/package-lock.json
  vue/package.json
Labels: 3. to review, dependencies

#2055 Add acceptance tests for public conversations to Drone
  .drone.yml
Labels: 3. to review

#2050 Remove unused repair step
  lib/Migration/RegisterSampleCommands.php
Labels: 3. to review, backport-request, bug, regression

#2048 Correctly check if a user has access to a conversation
  appinfo/info.xml
  lib/Collaboration/Resources/ConversationProvider.php
  lib/Migration/ClearResourceAccessCache.php
  tests/php/Collaboration/Resources/ConversationProviderTest.php
Labels: 3. to review, backport-request, bug

#2035 Fix audio not played before video is received in Chromium
  js/simplewebrtc/bundled.js
  js/simplewebrtc/simplewebrtc.js
  js/views/videoview.js
  js/webrtc.js
Labels: 3. to review, backport-request, bug, deployed on testing, feature: frontend 🖌️, feature: webrtc 🚡
