Repository nextcloud/spreed, pull requests merged in 2019-10, with the labels that each got.

#2258 Use handlebar from node_modules
  .drone.yml
  compile-handlebars-templates.sh
Labels: 3. to review, javascript

#2257 Correctly set the unread counter when readding a user to a one-to-one…
  lib/Manager.php
  lib/Room.php
  tests/php/PasswordVerificationTest.php
Labels: 3. to review, bug, feature: chat 💬

#2245 Fix minor php issues
  appinfo/routes.php
  lib/Chat/SystemMessage/Listener.php
  lib/Collaboration/Collaborators/RoomPlugin.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/PublicShareController.php
  lib/Files/Listener.php
  lib/Files/Util.php
  lib/Notification/Notifier.php
  lib/Share/RoomShareProvider.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
Labels: 3. to review, bug, regression

#2239 Don't show a "left call" message when a user was not in the call and …
  lib/Listener.php
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: chat 💬

#2263 Fix server branch used in public share acceptance tests in stable17
  .drone.yml
Labels: 3. to review, bug

#2266 Add tooltip with start time format.
  js/views/callinfoview.js
Labels: 3. to review, backport-request, enhancement, feature: webinary 📺

#2265 Fix "MessageTooLongException" when mentioning someone in a long comment
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2268 [stable17] Fix "MessageTooLongException" when mentioning someone in a long comment
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug

#2276 Do not run tests when PHP files of other types of tests are modified
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
Labels: 3. to review, backport-request

#2275 Adjust integration test to changes in access to shares in server
  tests/integration/features/sharing/hooks.feature
Labels: 3. to review

#2270 Add section title to share-link options.
  js/views/callinfoview.js
  js/views/templates.js
  js/views/templates/callinfoview.handlebars
Labels: 3. to review, backport-request, enhancement, feature: webinary 📺

#2269 Add lobby checkbox instead of radio buttons for enabling lobby.
  css/publicshare.scss
  css/style.scss
  js/views/callinfoview.js
  js/views/templates.js
  js/views/templates/callinfoview.handlebars
  tests/acceptance/features/bootstrap/ConversationInfoContext.php
  tests/acceptance/features/lobby.feature
Labels: 3. to review, backport-request, enhancement, feature: webinary 📺

#2281 Better start call setting
  css/settings-admin.scss
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  vue/src/views/GeneralSettings.vue
Labels: 3. to review, bug, feature: settings ⚙️, regression

#2288 [stable17] Add lobby checkbox instead of radio buttons for enabling lobby
  css/publicshare.scss
  css/style.scss
  js/views/callinfoview.js
  js/views/templates.js
  js/views/templates/callinfoview.handlebars
  tests/acceptance/features/bootstrap/ConversationInfoContext.php
  tests/acceptance/features/lobby.feature
Labels: 3. to review, enhancement, feature: webinary 📺

#2296 Add ability to receive new messages.
  src/components/MessagesList/MessageBody/MessageBody.vue
  src/components/MessagesList/MessagesList.vue
  src/components/Navigation/ContactsList/ContactsList.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/services/conversationsService.js
  src/services/messagesService.js
  src/services/participantsService.js
  src/store/conversations.js
  src/store/messages.js
Labels: 2. developing, Hacktoberfest, feature: chat 💬, feature: frontend 🖌️

#2292 Make app navigation dark-mode compatible
  src/components/Navigation/ConversationsList/AppContentListItem/AppContentListItem.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2310 Fix spaces and units
  src/components/MessagesList/Message/Message.vue
  src/components/MessagesList/MessageBody/MessageBody.vue
  src/components/Navigation/AppNavigationSearch/AppNavigationSearch.vue
  src/components/Navigation/Navigation.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/store/conversations.js
  src/store/messages.js
  src/views/ChatView.vue
Labels: 3. to review, bug, project: Vue.JS, regression

#2291 Fix the conversations icons
  css/icons.scss
  src/components/ConversationIcon.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
Labels: 3. to review, bug, project: Vue.JS

#2315 Fix navigation design issues.
  src/components/MessagesList/MessageBody/MessageBody.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/components/Navigation/Navigation.vue
Labels: 3. to review

#2290 Fix all the docs
  appinfo/routes.php
  docs/call.md
  docs/chat.md
  docs/constants.md
  docs/conversation.md
  docs/integration.md
  docs/participant.md
  docs/webinar.md
  lib/Controller/CommandController.php
  lib/Controller/GuestController.php
  lib/Controller/RoomController.php
  lib/Controller/WebinarController.php
  mkdocs.yml
Labels: 3. to review, bug, regression, technical debt

#2316 Fix drone
  .drone.yml
Labels: 3. to review

#2319 Define all constants
  src/components/ConversationIcon.vue
  src/constants.js
  src/services/conversationsService.js
Labels: 3. to review, project: Vue.JS, technical debt

#2322 Uppercase all constants
  src/components/ConversationIcon.vue
  src/constants.js
  src/services/conversationsService.js
Labels: 3. to review

#2321 Use DI for the middleware
  lib/AppInfo/Application.php
  lib/Middleware/CanUseTalkMiddleware.php
  lib/Middleware/InjectionMiddleware.php
Labels: 4. to release, bug, technical debt

#2317 Correctly setup the Application class
  appinfo/app.php
Labels: 3. to review, bug, technical debt

#2320 [stable17] Fix position and size of avatars
  css/files.scss
  css/publicshare.scss
  css/video.scss
  js/publicshare.js
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️, regression

#2328 Ignore all compiled js items
  .gitattributes
  .l10nignore
  js/Talk.js
  js/Talk.js.map
  js/vueexample.js
  js/vueexample.js.map
Labels: 3. to review, bug, project: Vue.JS, regression

#2329 Remove unnecessary logic to show/hide the actions on mobile
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review

#2331 Move admin settings to src/ folder
  .drone.yml
  .eslintrc.js
  Makefile
  check-handlebars-templates.sh
  check-vuejs-builds.sh
  compile-handlebars-templates.sh
  package-lock.json
  package.json
  src/AllowedGroupsSettings.js
  src/App.vue
  src/CommandsSettings.js
  src/GeneralSettings.js
  src/SignalingServerSettings.js
  src/StunServerSettings.js
  src/TurnServerSettings.js
  src/collections.js
  src/collectionsintegration.js
  src/components/AdminSettings/Command.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/ConversationIcon.vue
  src/components/MessagesList/MessagesList.vue
  src/views/AdminSettings/AllowedGroups.vue
  src/views/AdminSettings/Commands.vue
  src/views/AdminSettings/GeneralSettings.vue
  src/views/AdminSettings/SignalingServers.vue
  src/views/AdminSettings/StunServers.vue
  src/views/AdminSettings/TurnServers.vue
  src/views/CollaborationView.vue
  src/views/RoomSelector.vue
  vue/.babelrc.js
  vue/.eslintrc.js
  vue/package-lock.json
  vue/package.json
  vue/webpack.common.js
  vue/webpack.dev.js
  vue/webpack.prod.js
  webpack.common.js
Labels: 3. to review, project: Vue.JS, technical debt

#2311 Conversation list
  package-lock.json
  package.json
  src/components/Navigation/ConversationsList/Conversation.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/main.js
  src/services/conversationsService.js
  src/store/conversations.js
Labels: 2. developing, enhancement, feature: frontend 🖌️, project: Vue.JS

#2327 Fix missing translation of the placeholder
  src/views/AdminSettings/GeneralSettings.vue
Labels: 4. to release, backport-request, bug

#2283 Allow to disable file rooms
  lib/Controller/FilesIntegrationController.php
  lib/Files/TemplateLoader.php
  lib/PublicShare/TemplateLoader.php
  lib/Settings/Admin/GeneralSettings.php
  src/views/AdminSettings/GeneralSettings.vue
Labels: 4. to release, enhancement, feature: settings ⚙️, feature: talk-sidebar ⬅️

#2343 Periodically refresh ConversationsList.
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/store/conversations.js
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️

#2342 [stable17] Better general setting
  css/settings-admin.scss
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  lib/Controller/FilesController.php
  lib/Files/TemplateLoader.php
  lib/PublicShare/TemplateLoader.php
  lib/Settings/Admin/GeneralSettings.php
  vue/src/views/GeneralSettings.vue
Labels: 3. to review, bug

#2339 Do not load Talk sidebar in public share page of folder shares
  lib/PublicShare/TemplateLoader.php
Labels: 3. to review, bug, feature: talk-sidebar ⬅️

#2340 [stable17] Do not load Talk sidebar in public share page of folder shares
  lib/PublicShare/TemplateLoader.php
Labels: 3. to review, bug, feature: talk-sidebar ⬅️

#2323 Add the conversation name to the page title
  src/App.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/services/EventBus.js
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, project: Vue.JS

#2330 Add quote-reply feature
  src/assets/variables.scss
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/Quote/Quote.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/services/messagesService.js
  src/store/conversationsStore.js
  src/store/index.js
  src/store/messagesStore.js
  src/store/quoteReplyStore.js
Labels: 2. developing, 3. to review, feature: chat 💬, feature: frontend 🖌️, project: Vue.JS

#2350 Use the display name for contacts
  src/components/Navigation/ContactsList/ContactsList.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2351 Fix searchbox style
  src/components/Navigation/AppNavigationSearch/AppNavigationSearch.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2349 Fix captions in navigation
  src/components/Navigation/Caption/Caption.vue
  src/components/Navigation/Navigation.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2346 Sort conversations by favorite and last activity
  src/components/Navigation/ConversationsList/Conversation.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2357 Better system messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: chat 💬, project: Vue.JS

#2356 Parse parameters in subtitle message
  src/components/Navigation/ConversationsList/Conversation.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️, project: Vue.JS

#2352 Do not fail hard when the conversation wasn't found (yet)
  src/App.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2358 Add missing default for systemMessage on new chat message
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, project: Vue.JS, regression

#2353 Immediately add a new conversation to the list
  docs/conversation.md
  lib/Controller/RoomController.php
  src/components/Navigation/ContactsList/ContactsList.vue
Labels: 3. to review, enhancement, feature: api 🛠️, feature: frontend 🖌️, project: Vue.JS

#2354 Filter the conversation list with the search term
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/components/Navigation/Navigation.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, project: Vue.JS

#2370 Add the favorite icon to the conversation list
  css/icons.scss
  src/components/ConversationIcon.vue
  src/components/Navigation/ConversationsList/Conversation.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2369 Finish action menu
  src/components/Navigation/ActionCaption/ActionCaption.vue
  src/components/Navigation/ConversationsList/Conversation.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2374 Remove dummy settings
  src/components/Navigation/Navigation.vue
Labels: 4. to release, bug, feature: frontend 🖌️, project: Vue.JS

#2361 Author avatar component with bots and guest support
  css/icons.scss
  src/assets/variables.scss
  src/components/ConversationIcon.vue
  src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/Navigation/ActionCaption/ActionCaption.vue
  src/components/Navigation/AppNavigationSearch/AppNavigationSearch.vue
  src/components/Navigation/Caption/Caption.vue
  src/components/Navigation/ContactsList/ContactsList.vue
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/components/Navigation/Navigation.vue
Labels: 4. to release, bug, feature: chat 💬, project: Vue.JS

#2375 Filter out contacts which are listed as conversations already
  src/components/Navigation/ConversationsList/ConversationsList.vue
  src/components/Navigation/Navigation.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2373 Remove FIXME hack for favorites
  src/components/Navigation/ConversationsList/Conversation.vue
Labels: 3. to review, bug, feature: frontend 🖌️, project: Vue.JS

#2360 Stop long polling requests when changing conversations.
  package-lock.json
  package.json
  src/App.vue
  src/components/ConversationIcon.vue
  src/components/MessagesList/MessagesList.vue
  src/components/Navigation/ConversationsList/Conversation.vue
  src/services/conversationsService.js
  src/services/messagesService.js
  src/services/participantsService.js
  src/views/AdminSettings/AllowedGroups.vue
  src/views/RoomSelector.vue
Labels: 2. developing, bug, feature: frontend 🖌️

#2379 Remove unused class name and css rules
  src/components/Navigation/Navigation.vue
Labels: 4. to release

#2380 Do not throw errors on 304s
  src/services/messagesService.js
Labels: 4. to release, bug

#2381 Bugfix/stop message history pending requests when changing conversation
  src/components/MessagesList/MessagesList.vue
  src/services/messagesService.js
Labels: 3. to review, bug

#2384 End execution of 'getNewMessages' method if the api call is canceled
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug
