Repository nextcloud/spreed, pull requests merged in 2019-02, with the labels that each got.

#1503 Add acceptance tests for room shares
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/bootstrap/FilesAppRoomSharingContext.php
  tests/acceptance/features/bootstrap/ParticipantListContext.php
  tests/acceptance/features/room-shares.feature
Labels: 3. to review, backport-request

#1507 Add acceptance tests for Files app
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/bootstrap/ConversationListContext.php
  tests/acceptance/features/bootstrap/FilesAppChatTabContext.php
Labels: 3. to review, backport-request

#1506 [stable14] Add acceptance tests for room shares
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/bootstrap/FilesAppRoomSharingContext.php
  tests/acceptance/features/bootstrap/ParticipantListContext.php
  tests/acceptance/features/room-shares.feature
Labels: 3. to review

#1514 Add acceptance tests for requesting the password of a link share
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/PublicSharePasswordRequestContext.php
  tests/acceptance/features/public-share-auth.feature
Labels: 3. to review

#1504 Fix the fix for icons in dark mode
  css/files.scss
  css/style.scss
  css/video.scss
  js/filesplugin.js
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1510 Fix editable text label for guest names
  css/publicshareauth.scss
  css/style.scss
Labels: 3. to review, bug, design, feature: frontend

#1502 Remove room information for users which are not a participant
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  tests/php/Controller/RoomControllerTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, backport-request, bug, feature: api, mobile apps

#1520 Allow to repost the last comment
  js/views/chatview.js
Labels: 3. to review, enhancement, feature: frontend

#1522 Fix current user not included in user list returned by signaling
  lib/Controller/SignalingController.php
Labels: 3. to review, backport-request, bug, feature: signaling

#1535 Strict controllers and migration
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/FilesController.php
  lib/Controller/GuestController.php
  lib/Controller/PageController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Migration/Version2000Date20170707093535.php
  lib/Migration/Version2000Date20171026140256.php
  lib/Migration/Version2000Date20171026140257.php
  lib/Migration/Version2001Date20170707115443.php
  lib/Migration/Version2001Date20170913104501.php
  lib/Migration/Version2001Date20170921145301.php
  lib/Migration/Version2001Date20170929092606.php
  lib/Migration/Version2001Date20171009132424.php
  lib/Migration/Version2001Date20171026134605.php
  lib/Migration/Version2001Date20171026141336.php
  lib/Migration/Version2001Date20171031102049.php
  lib/Migration/Version2001Date20180103144447.php
  lib/Migration/Version2001Date20180103150836.php
  lib/Migration/Version3002Date20180319104030.php
  lib/Migration/Version3003Date20180707222130.php
  lib/Migration/Version3003Date20180718112436.php
  lib/Migration/Version3003Date20180718133519.php
  lib/Migration/Version3003Date20180720162342.php
  lib/Migration/Version3003Date20180722152733.php
  lib/Migration/Version3003Date20180722152849.php
  lib/Migration/Version3003Date20180730080327.php
  lib/Migration/Version4099Date20181001123058.php
  tests/php/Controller/SignalingControllerTest.php
Labels: 3. to review, technical debt

#1538 Use the datetime factory everywhere
  lib/Activity/Hooks.php
  lib/AppInfo/Application.php
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/ChatController.php
  lib/Manager.php
  lib/Notification/Hooks.php
  lib/Share/Helper/ShareAPIController.php
  lib/Share/RoomShareProvider.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, enhancement, technical debt

#1533 Fix peer creation when wrong user list was sent to the other peer
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend

#1534 Fix slower active users not included in user list returned by signaling
  lib/Controller/SignalingController.php
Labels: 3. to review, backport-request, bug, feature: signaling

#1544 Use ITimeFactory instead of time()
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Manager.php
  lib/Room.php
  lib/Share/RoomShareProvider.php
  lib/Signaling/Messages.php
  tests/php/Controller/RoomControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/PasswordVerificationTest.php
Labels: 3. to review, technical debt

#1546 Fix "private const" on PHP 7.0
  lib/Controller/SignalingController.php
Labels: 3. to review, bug

#1547 Allow null sessions when getting participant by session
  lib/Room.php
Labels: 3. to review, bug

#1545 Do not load unnecessary classes in Application
  lib/Activity/Listener.php
  lib/AppInfo/Application.php
  lib/Chat/Listener.php
  lib/Chat/SystemMessage/Listener.php
  lib/Files/Listener.php
  lib/Files/TemplateLoader.php
  lib/Listener.php
  lib/Notification/Listener.php
  lib/PublicShareAuth/Listener.php
  lib/PublicShareAuth/TemplateLoader.php
  lib/Share/RoomShareProvider.php
  lib/Signaling/Listener.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, bug, technical debt

#1513 Extract view for a participant in a call
  js/merged-files.json
  js/merged-guest.json
  js/merged-share-auth.json
  js/merged.json
  js/views/templates.js
  js/views/templates/videoview.handlebars
  js/views/videoview.js
  js/webrtc.js
Labels: 3. to review

#1548 Fix last local media state not remembered when the UI is reloaded
  js/views/mediacontrolsview.js
Labels: 3. to review, backport-request, bug, feature: frontend, regression

#1549 Delay message sending when socket is null
  js/signaling.js
Labels: 3. to review, backport-request, bug, feature: signaling

#1508 Own video is too big, setting it to 22%
  css/video.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1453 🤖 Commands
  .eslintignore
  appinfo/info.xml
  appinfo/routes.php
  docs/commands.md
  js/admin/commands.js
  js/admin/commands.js.map
  js/views/chatview.js
  lib/AppInfo/Application.php
  lib/Chat/ChatManager.php
  lib/Chat/Command/Executor.php
  lib/Chat/Command/Listener.php
  lib/Chat/Command/ShellExecutor.php
  lib/Chat/MessageParser.php
  lib/Chat/Parser/Command.php
  lib/Chat/Parser/Listener.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Chat/SystemMessage/Listener.php
  lib/Command/Command/Add.php
  lib/Command/Command/Delete.php
  lib/Command/Command/ListCommand.php
  lib/Command/Command/TRenderCommand.php
  lib/Command/Command/Update.php
  lib/Controller/ChatController.php
  lib/Controller/CommandController.php
  lib/Controller/RoomController.php
  lib/Migration/CreateHelpCommand.php
  lib/Migration/Version5099Date20190121102337.php
  lib/Model/Command.php
  lib/Model/CommandMapper.php
  lib/Model/Message.php
  lib/Notification/Notifier.php
  lib/Service/CommandService.php
  lib/Settings/Admin/Commands.php
  templates/settings/admin/commands.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/Command/ExecutorTest.php
  tests/php/Chat/Command/ShellExecutorTest.php
  tests/php/Controller/ChatControllerTest.php
  vue/Makefile
  vue/package-lock.json
  vue/package.json
  vue/src/Commands.vue
  vue/src/commands.js
  vue/src/components/Command.vue
  vue/webpack.common.js
  vue/webpack.dev.js
  vue/webpack.prod.js
Labels: 2. developing, enhancement

#1539 Ensure all properties of rooms are set
  js/models/room.js
Labels: 3. to review, backport-request, bug, feature: signaling

#1569 Fix removal of stale peers when a screen is shared
  js/webrtc.js
Labels: 3. to review, bug, feature: webrtc, regression

#1553 Extract view for a shared screen
  js/merged-files.json
  js/merged-guest.json
  js/merged-share-auth.json
  js/merged.json
  js/views/screenview.js
  js/views/templates.js
  js/views/templates/screenview.handlebars
  js/webrtc.js
Labels: 3. to review, feature: frontend

#1531 Allow to mention everyone in the conversation
  css/chatview.scss
  css/style.scss
  js/views/chatview.js
  js/views/richobjectstringparser.js
  js/views/templates.js
  js/views/templates/richobjectstringparser_call.handlebars
  lib/Chat/Notifier.php
  lib/Chat/Parser/UserMention.php
  lib/Controller/ChatController.php
Labels: 3. to review, enhancement, feature: api, feature: chat, mobile apps

#1574 Fix disabling video when joining a call in a room with more than five participants
  js/app.js
  js/embedded.js
Labels: 3. to review, backport-request, bug, feature: frontend

#1572 Fix unit tests from #1453
  lib/Chat/MessageParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Notification/Notifier.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug

#1570 Allow multiline text insertion in chrome
  css/chatview.scss
Labels: 3. to review, backport-request, bug, feature: chat, feature: frontend

#1573 Fix missing guest names in chat
  lib/Chat/MessageParser.php
Labels: 3. to review, bug, feature: chat, regression

#1555 Extract view for local participant
  js/app.js
  js/embedded.js
  js/filesplugin.js
  js/merged-files.json
  js/merged-guest.json
  js/merged-share-auth.json
  js/merged.json
  js/publicshareauth.js
  js/views/localvideoview.js
  js/views/mediacontrolsview.js
  js/views/templates.js
  js/views/templates/localvideoview.handlebars
  js/webrtc.js
  templates/index-public.php
  templates/index.php
Labels: 3. to review, feature: frontend

#1580 Fix unit tests
  tests/php/Chat/Parser/UserMentionTest.php
Labels: 3. to review, bug

#1422 Add reason for removing participant from room
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Listener.php
  lib/Room.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, enhancement, feature: api

#1567 Make room names non-optional
  docs/api-v1.md
  js/app.js
  js/models/participantcollection.js
  js/models/room.js
  js/signaling.js
  js/views/editabletextlabel.js
  lib/Activity/Listener.php
  lib/Activity/Provider/Base.php
  lib/Activity/Provider/Invitation.php
  lib/Chat/Parser/UserMention.php
  lib/Collaboration/Collaborators/RoomPlugin.php
  lib/Controller/ChatController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/GuestManager.php
  lib/Manager.php
  lib/Notification/Notifier.php
  lib/Room.php
  lib/Share/Helper/DeletedShareAPIController.php
  lib/Share/Helper/ShareAPIController.php
  lib/Signaling/BackendNotifier.php
  tests/acceptance/features/bootstrap/ConversationListContext.php
  tests/acceptance/features/bootstrap/TalkAppContext.php
  tests/acceptance/features/chat.feature
  tests/acceptance/features/conversation.feature
  tests/acceptance/features/room-shares.feature
  tests/integration/features/callapi/password.feature
  tests/integration/features/callapi/public.feature
  tests/integration/features/chat/password.feature
  tests/integration/features/chat/public.feature
  tests/integration/features/chat/rich-messages.feature
  tests/integration/features/chat/system-messages.feature
  tests/integration/features/conversation/add-participant.feature
  tests/integration/features/conversation/delete-room.feature
  tests/integration/features/conversation/promotion-demotion.feature
  tests/integration/features/conversation/public-private.feature
  tests/integration/features/conversation/remove-participant.feature
  tests/integration/features/conversation/remove-self.feature
  tests/integration/features/conversation/rename-room.feature
  tests/integration/features/conversation/set-password.feature
  tests/integration/features/sharing/create.feature
  tests/integration/features/sharing/delete.feature
  tests/integration/features/sharing/get.feature
  tests/integration/features/sharing/hooks.feature
  tests/integration/features/sharing/move.feature
  tests/integration/features/sharing/restore.feature
  tests/integration/features/sharing/sharees.feature
  tests/integration/features/sharing/transfer-ownership.feature
  tests/integration/features/sharing/update.feature
  tests/php/Activity/Provider/BaseTest.php
  tests/php/Activity/Provider/InvitationTest.php
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
  tests/php/Controller/RoomControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Notification/NotifierTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, enhancement, feature: api, mobile apps

#1571 Fix sharing own screen when other peer is sharing the screen
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: webrtc, regression

#1590 Fix ESlint on master
  js/models/room.js
Labels: 3. to review, bug

#1586 Fix removing users when an old session id expires in the signaling server.
  lib/Controller/SignalingController.php
  lib/Room.php
  tests/php/Controller/SignalingControllerTest.php
Labels: 4. to release, backport-request, bug, feature: signaling
