Repository nextcloud/spreed, pull requests merged in 2019-03, with the labels that each got.

#1593 Fix missing room names in integration tests
  tests/integration/features/sharing/create.feature
Labels: 3. to review

#1588 Adjust the logic for delete/leave buttons
  docs/api-v1.md
  js/models/room.js
  js/views/roomlistview.js
  lib/Controller/RoomController.php
  lib/Room.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/conversation.feature
  tests/integration/features/conversation/delete-room.feature
  tests/integration/features/conversation/one-to-one.feature
  tests/integration/features/conversation/remove-participant.feature
Labels: 3. to review, bug, feature: api, feature: frontend

#1594 Fix empty content message when leaving a room
  js/views/emptycontentview.js
Labels: 3. to review, bug, feature: frontend, regression

#1581 Fix duplicated call summary message when multiple people leave at the…
  lib/Activity/Listener.php
  lib/Room.php
Labels: 3. to review, bug, feature: api

#1585 Allow to restrict to group
  .eslintignore
  appinfo/info.xml
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  lib/Activity/Provider/Base.php
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Config.php
  lib/Controller/PageController.php
  lib/Listener.php
  lib/Middleware/CanUseTalkMiddleware.php
  lib/Middleware/Exceptions/CanNotUseTalkException.php
  lib/Notification/Notifier.php
  lib/Settings/Admin/AllowedGroups.php
  templates/settings/admin/allowed-groups.php
  tests/php/Activity/Provider/BaseTest.php
  tests/php/Activity/Provider/InvitationTest.php
  tests/php/CapabilitiesTest.php
  tests/php/ConfigTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Notification/NotifierTest.php
  tests/php/Signaling/BackendNotifierTest.php
  vue/src/AllowedGroups.vue
  vue/src/allowed-groups.js
  vue/webpack.common.js
Labels: 3. to review, enhancement

#1598 Remove '@ all' mention in one2one rooms.
  lib/Controller/ChatController.php
Labels: enhancement, feature: chat

#1597 Use InitialState for admin settings
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/init.js
  js/admin/signaling-server.js
  js/admin/stun-server.js
  js/admin/turn-server.js
  lib/Config.php
  lib/Settings/Admin/Commands.php
  lib/Settings/Admin/SignalingServer.php
  lib/Settings/Admin/StunServer.php
  lib/Settings/Admin/TurnServer.php
  templates/settings/admin/signaling-server.php
  templates/settings/admin/stun-server.php
  templates/settings/admin/turn-server.php
  tests/php/Settings/Admin/SectionTest.php
  tests/php/Settings/Admin/StunServerTest.php
  tests/php/Settings/Admin/TurnServerTest.php
  vue/src/Commands.vue
Labels: 3. to review, enhancement, feature: settings

#1600 Ignore generated and minified JS files during l10n sync
  .l10nignore
Labels: 3. to review

#1599 [stable15] Fix duplicated call summary message when multiple people leave at the…
  lib/Activity/Hooks.php
  lib/Room.php
Labels: 3. to review, bug, feature: chat

#1601 Use the preview information for better fallback icons
  js/views/chatview.js
  js/views/templates.js
  js/views/templates/richobjectstringparser_filepreview.handlebars
  lib/Chat/Parser/SystemMessage.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, bug, feature: chat, feature: room-shares

#1602 Fix remote video visible behind avatar before being explicitly shown
  js/views/videoview.js
Labels: 3. to review, bug, feature: frontend

#1582 Force "Plan B" semantics with the MCU.
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: webrtc

#1609 Fix messages not sent due to datachannel not open.
  js/simplewebrtc.js
Labels: 3. to review, bug

#1612 Fix hardcoded `/call/{token}` handling
  lib/Controller/PageController.php
Labels: 3. to review, bug, feature: api, feature: frontend

#1591 Persistent one-to-one rooms
  docs/api-v1.md
  js/views/callinfoview.js
  js/views/participantview.js
  js/views/roomlistview.js
  lib/Capabilities.php
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Room.php
  tests/acceptance/features/conversation.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/one-to-one.feature
  tests/integration/features/chat/one-to-one.feature
  tests/integration/features/conversation/one-to-one.feature
  tests/integration/features/conversation/remove-participant.feature
  tests/integration/features/sharing/hooks.feature
  tests/integration/features/sharing/sharees.feature
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api, mobile apps

#1619 Update all NPM packages
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  vue/Makefile
  vue/package-lock.json
  vue/package.json
Labels: 3. to review

#1627 Fix hidding video causing audio to not be played
  css/video.scss
  js/views/videoview.js
Labels: 3. to review, bug, feature: frontend, feature: webrtc

#1638 Update all NPM packages
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/sha1.js
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  vue/package-lock.json
  vue/package.json
Labels: 3. to review

#1629 Reset the signaling server settings after unit tests
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, bug

#1626 Replace all the duplicate Room/Participant checks with an annotation
  lib/AppInfo/Application.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Middleware/Exceptions/NotAModeratorException.php
  lib/Middleware/InjectionMiddleware.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/RoomControllerTest.php
Labels: 3. to review, feature: api, technical debt

#1632 Fix duplicated call button when joining the same room again in Files app
  js/filesplugin.js
Labels: 3. to review, bug, feature: frontend, feature: talk-sidebar

#1631 Fix stopping local media when leaving a call
  js/signaling.js
  js/webrtc.js
Labels: 3. to review, bug, feature: MCU & SIP, feature: frontend, feature: webrtc

#1633 Base "PublicShareAuth" on "Embedded" instead of on "Application"
  css/publicshareauth.scss
  css/video.scss
  js/embedded.js
  js/merged-share-auth.json
  js/publicshareauth.js
Labels: 3. to review, feature: talk-sidebar

#1645 Update all npm
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/publicshareauth.js
  tests/acceptance/features/app-files.feature
  vue/package-lock.json
  vue/package.json
Labels: 3. to review, dependencies

#1646 Ignore also vendor and test files
  .l10nignore
Labels: 3. to review

#1641 Add users to file rooms on mentions
  lib/Chat/Notifier.php
Labels: 3. to review, bug, feature: chat, feature: talk-sidebar, regression

#1648 Don't send a notification when inviting a user because he was mentioned
  lib/Notification/Listener.php
Labels: 3. to review, bug, feature: chat, feature: talk-sidebar

#1649 Show a warning with many users without external signaling
  css/settings-admin.scss
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/signaling.js
  lib/Config.php
  lib/Settings/Admin/SignalingServer.php
  vue/src/views/SignalingServers.vue
Labels: 3. to review, bug, feature: frontend, feature: settings, feature: signaling

#1653 Less pushy warning
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/signaling.js
  vue/package-lock.json
  vue/package.json
  vue/src/views/SignalingServers.vue
  vue/webpack.common.js
Labels: 3. to review, bug, feature: frontend

#1654 Dont allow to move mountpoints into mountpoints
  tests/integration/features/sharing/move.feature
Labels: 3. to review, bug, feature: room-shares

#1640 Read only conversations
  appinfo/info.xml
  appinfo/routes.php
  css/chatview.scss
  docs/api-v1.md
  js/app.js
  js/embedded.js
  js/views/callbutton.js
  js/views/chatview.js
  js/views/templates.js
  js/views/templates/callbutton.handlebars
  js/views/templates/chatview_add_comment.handlebars
  lib/Capabilities.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Collaboration/Collaborators/RoomPlugin.php
  lib/Controller/AEnvironmentAwareController.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Middleware/Exceptions/ReadOnlyException.php
  lib/Middleware/InjectionMiddleware.php
  lib/Migration/Version5099Date20190319134820.php
  lib/Room.php
  lib/Share/RoomShareProvider.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/group-read-only.feature
  tests/integration/features/callapi/password.feature
  tests/integration/features/callapi/public-read-only.feature
  tests/integration/features/chat/group-read-only.feature
  tests/integration/features/chat/public-read-only.feature
  tests/php/CapabilitiesTest.php
  tests/php/PasswordVerificationTest.php
Labels: 3. to review, enhancement, feature: api, feature: chat

#1524 Add support for calls in other browsers
  .eslintignore
  Makefile
  js/merged-files.json
  js/merged-guest.json
  js/merged-share-auth.json
  js/merged.json
  js/simplewebrtc.js
  js/simplewebrtc/bundled.js
  js/simplewebrtc/getscreenmedia.js
  js/simplewebrtc/localmedia.js
  js/simplewebrtc/peer.js
  js/simplewebrtc/simplewebrtc.js
  js/simplewebrtc/webrtc.js
  js/webrtc.js
  package.json
Labels: 3. to review, enhancement, feature: frontend, feature: webrtc

#1611 Add a provider for linked collaboration resources
  .eslintignore
  .gitattributes
  .l10nignore
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/app.js
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  js/merged.json
  js/views/collectionsview.js
  lib/AppInfo/Application.php
  lib/Collaboration/Resources/ConversationProvider.php
  lib/Collaboration/Resources/Listener.php
  package.json
  templates/index.php
  vue/.eslintrc.js
  vue/Makefile
  vue/package-lock.json
  vue/package.json
  vue/src/collections.js
  vue/src/collectionsintegration.js
  vue/src/views/CollaborationView.vue
  vue/src/views/RoomSelector.vue
  vue/webpack.common.js
Labels: 3. to review, enhancement, feature: frontend, mobile apps

#1655 Readd the nick to the payloads of offer/answer
  js/signaling.js
Labels: 3. to review, bug, feature: signaling, feature: webrtc, regression
