Repository nextcloud/spreed, pull requests merged in 2019-04, with the labels that each got.

#1616 Start changelog implementation
  css/style.scss
  img/changelog.svg
  js/app.js
  js/collections.js
  js/collections.js.map
  js/views/callinfoview.js
  js/views/chatview.js
  js/views/roomlistview.js
  lib/AppInfo/Application.php
  lib/BackgroundJob/RemoveEmptyRooms.php
  lib/Chat/Changelog/Listener.php
  lib/Chat/Changelog/Manager.php
  lib/Chat/ChatManager.php
  lib/Chat/Parser/Changelog.php
  lib/Chat/Parser/Listener.php
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Room.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/php/Controller/RoomControllerTest.php
  vue/src/views/RoomSelector.vue
Labels: 3. to review, enhancement, feature: chat

#1656 Add a description to the commands admin settings
  css/settings-admin.scss
  js/admin/commands.js
  js/admin/commands.js.map
  lib/Chat/Command/Executor.php
  vue/src/views/Commands.vue
Labels: 3. to review, bug

#1657 Remove video constraints.
  js/webrtc.js
Labels: 3. to review, bug, feature: frontend, feature: webrtc

#1650 v6.0.0 - Changelog + Version bump
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 2. developing, bug, enhancement, overview

#1661 Bugfix/noid/adjust docs
  docs/api-v1.md
Labels: 3. to review, bug, spec

#1666 Fix links before line breaks
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat, feature: frontend

#1670 Add "copy link" option to the conversation list dropdown
  css/style.scss
  js/views/roomlistview.js
Labels: 3. to review, bug, feature: frontend

#1672 Add background color to unread messages counter.
  css/style.scss
Labels: 3. to review, bug, design

#1673 Fix ESLint for custom SimpleWebRTC
  .eslintignore
  js/simplewebrtc/bundled.js
  js/simplewebrtc/getscreenmedia.js
  js/simplewebrtc/localmedia.js
  js/simplewebrtc/peer.js
  js/simplewebrtc/simplewebrtc.js
  js/simplewebrtc/webrtc.js
Labels: 3. to review, feature: webrtc

#1674 Fix ICE failed indicator icon not forced to white in call
  css/video.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend

#1678 Adjust drone config for Drone 1.0
  .drone.yml
  js/tests/dummy_spec.js
  js/tests/main.js
  tests/php/Controller/SignalingControllerTest.php
Labels: 2. developing

#1679 Ignore node modules when running integration tests in Docker
  tests/integration/run-docker.sh
Labels: 3. to review, backport-request

#1689 [stable15] Adjust drone config for stable15
  .drone.yml
Labels: 4. to release

#1690 [stable14] Adjust drone config to stable14
  .drone.yml
  tests/integration/features/conversation/add-participant.feature
  tests/integration/features/conversation/delete-room.feature
  tests/integration/features/conversation/one-to-one.feature
  tests/integration/features/conversation/promotion-demotion.feature
  tests/integration/features/conversation/public-private.feature
  tests/integration/features/conversation/remove-participant.feature
  tests/integration/features/conversation/remove-self.feature
  tests/integration/features/conversation/rename-room.feature
  tests/integration/features/conversation/set-password.feature
Labels: 4. to release

#1681 Fix cursor on selected tab header
  css/style.scss
Labels: 3. to review, bug, design

#1676 Add integration tests for file rooms
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/conversation/files.feature
Labels: 3. to review, backport-request

#1677 Add integration tests for searching mentions
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/mentions.feature
Labels: 3. to review, backport-request

#1662 Add sample commands
  appinfo/info.xml
  lib/Command/Command/AddSamples.php
  lib/Migration/RegisterSampleCommands.php
  sample-commands/calc.sh
  sample-commands/hackernews.php
  sample-commands/wikipedia.php
Labels: 3. to review, enhancement, feature: chat, feature: commands

#1663 Rename linked collections to projects
  js/app.js
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  vue/package-lock.json
  vue/package.json
  vue/src/collections.js
  vue/src/views/RoomSelector.vue
Labels: 3. to review, bug

#1682 Fix duplicated candidate mentions in file rooms
  lib/Chat/AutoComplete/SearchPlugin.php
  tests/integration/features/chat/mentions.feature
Labels: 3. to review, backport-request, bug, feature: chat, feature: talk-sidebar

#1694 Resharing behaviour has been adjusted for 16
  tests/integration/features/sharing/get.feature
Labels: 3. to review, bug, regression

#1696 Fix links style in Talk sidebar in public share auth page
  css/publicshareauth.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend, feature: talk-sidebar

#1697 Fix misplaced chat view in public share auth page
  css/publicshareauth.scss
  js/views/templates.js
  js/views/templates/chatview_add_comment.handlebars
Labels: 3. to review, backport-request, bug, design, feature: frontend, feature: talk-sidebar

#1695 Project green for stable15
  tests/integration/features/sharing/create.feature
  tests/integration/features/sharing/move.feature
  tests/integration/features/sharing/transfer-ownership.feature
Labels: 3. to review, bug

#1700 [stable15] Fix misplaced chat view in public share auth page
  css/publicshareauth.scss
  js/views/templates.js
  js/views/templates/chatview_add_comment.handlebars
Labels: 3. to review, bug, design, feature: frontend, feature: talk-sidebar

#1702 Remove empty space when the "Add" button is not shown in the sidebar
  css/style.scss
Labels: 3. to review, backport-request, bug, design, feature: chat, feature: frontend

#1701 Do not show the CollectionsView when the participant list is shown
  js/app.js
Labels: 3. to review, bug, feature: frontend, regression

#1704 Fix participant actions not updated on current participant type changes
  js/views/participantlistview.js
Labels: 3. to review, backport-request, bug, feature: frontend

#1706 Move remaining views to precompiled Handlebars templates
  js/merged-files.json
  js/merged-guest.json
  js/merged-share-auth.json
  js/merged.json
  js/vendor/handlebars/handlebars.min.js
  js/views/callinfoview.js
  js/views/editabletextlabel.js
  js/views/participantlistview.js
  js/views/participantview.js
  js/views/roomlistview.js
  js/views/sidebarview.js
  js/views/tabview.js
  js/views/templates.js
  js/views/templates/callinfoview.handlebars
  js/views/templates/editabletextlabel.handlebars
  js/views/templates/participantlistview.handlebars
  js/views/templates/participantview.handlebars
  js/views/templates/roomlistview.handlebars
  js/views/templates/sidebarview.handlebars
  js/views/templates/tabview.handlebars
  js/views/templates/tabview_header.handlebars
Labels: 3. to review, feature: frontend

#1707 Do not allow JavaScript "eval"
  lib/Controller/PageController.php
Labels: 2. developing

#1708 Do not include unneeded JavaScript files
  js/merged-guest.json
  js/merged-share-auth.json
Labels: 4. to release, feature: frontend

#1699 Remove conversation names and tokens from reshares when you are not a participant
  lib/Manager.php
  lib/Share/Helper/ShareAPIController.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/sharing/create.feature
  tests/integration/features/sharing/get.feature
  tests/integration/features/sharing/transfer-ownership.feature
Labels: 4. to release, bug, feature: room-shares, regression

#1660 Final release
  CHANGELOG.md
  README.md
  appinfo/info.xml
  js/views/chatview.js
  lib/Chat/Changelog/Manager.php
  lib/Command/Command/Add.php
Labels: 2. developing, overview

#1709 Move underscore template to precompiled Handlebars template
  js/views/collectionsview.js
  js/views/templates.js
  js/views/templates/collectionsview.handlebars
Labels: 4. to release, bug, regression

#1712 Adjust room name input to default height for inputs from server
  css/style.scss
Labels: 3. to review, bug, feature: frontend, regression

#1718 Add Babel presets to make Vue compatible with IE11
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  vue/.babelrc.js
  vue/package-lock.json
  vue/package.json
Labels: 4. to release, backport-request, bug, feature: frontend, regression

#1728 Fix sidebar and fullscreen in IE11
  css/style.scss
Labels: 3. to review, backport-request, bug, feature: frontend

#1729 Fix WebRTC not supported handling
  js/app.js
  js/embedded.js
  js/simplewebrtc/bundled.js
  js/simplewebrtc/getscreenmedia.js
  js/simplewebrtc/localmedia.js
  js/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend, feature: webrtc, regression

#1731 Prefer standard API for screen sharing
  js/simplewebrtc/bundled.js
  js/simplewebrtc/getscreenmedia.js
  js/simplewebrtc/simplewebrtc.js
  js/views/mediacontrolsview.js
Labels: 3. to review, backport-request, bug, feature: frontend, feature: webrtc

#1737 Dont focus chat on small screens
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat, feature: frontend

#1738 Fix signaling messages with no payload and with unserialized attributes
  js/signaling.js
  js/simplewebrtc/bundled.js
  js/simplewebrtc/peer.js
Labels: 3. to review, backport-request, bug, feature: frontend, feature: webrtc, regression

#1730 Fix stopping screensharing from the browser
  js/simplewebrtc/bundled.js
  js/simplewebrtc/simplewebrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend, feature: webrtc, regression

#1748 Do not "load" conversations without a token
  lib/Manager.php
Labels: 3. to review, backport-request, bug, feature: api

#1745 Fix screensharing offer sent to peers not in the call
  js/webrtc.js
Labels: 4. to release, backport-request, bug, feature: frontend, feature: webrtc, regression

#1746 [stable15] Fix removal of stale peers when a screen is shared
  js/webrtc.js
Labels: 3. to review, bug, feature: webrtc, regression
