Repository nextcloud/spreed, pull requests merged in 2019-09, with the labels that each got.

#2142 Add coTURN setup documentation
  docs/TURN.md
  mkdocs.yml
Labels: 3. to review

#2147 Fix setting again the same lobby state in the UI
  js/views/callinfoview.js
Labels: 3. to review, bug

#2135 Allow to include the last known message as well
  docs/chat.md
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Controller/ChatController.php
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, bug, feature: chat 💬

#2137 Fix volume indicator shown when audio is not available
  js/views/mediacontrolsview.js
Labels: 4. to release, bug, feature: frontend 🖌️, feature: webrtc 🚡

#2148 Use the new rich object type guest
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug, feature: chat 💬, regression

#2119 [stable16] Add user to file room when joining it instead of when getting its token
  lib/Controller/FilesController.php
  lib/Files/Listener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/mentions.feature
  tests/integration/features/conversation/files.feature
  tests/integration/features/conversation/join-leave.feature
Labels: 3. to review

#2136 [stable16] Fixes for keyboard navigation
  css/style.scss
  js/views/callinfoview.js
  js/views/editabletextlabel.js
  js/views/tabview.js
  js/views/templates.js
  js/views/templates/callinfoview.handlebars
  js/views/templates/editabletextlabel.handlebars
  js/views/templates/participantlistview.handlebars
  js/views/templates/sidebarview.handlebars
  js/views/templates/tabview_header.handlebars
  tests/acceptance/features/bootstrap/ParticipantListContext.php
Labels: 3. to review, bug, feature: frontend 🖌️

#2151 Better command debugging
  lib/Chat/Command/Executor.php
  lib/Chat/Command/ShellExecutor.php
Labels: 3. to review, bug

#2153 Update stable17 testing version
  .drone.yml
  package.json
  vue/package.json
Labels: 3. to review, bug

#2156 Update version in package-lock.json files
  package-lock.json
  vue/package-lock.json
Labels: 3. to review, bug

#2157 Update stable17 version in package-lock.json files
  package-lock.json
  vue/package-lock.json
Labels: 3. to review, bug

#1952 Prevent the chat from compressing too much on narrow screens
  css/style.scss
Labels: 2. developing, backport-request, bug, feature: frontend 🖌️

#2161 Fix mentions with numeric users
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2175 Show a call summary when only guests joined
  lib/Activity/Listener.php
  lib/Chat/Parser/SystemMessage.php
  lib/Room.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2174 [stable16] Fix mentions with numeric users
  js/views/chatview.js
Labels: 3. to review, bug, feature: chat 💬

#2189 Free FilesController
  appinfo/routes.php
  lib/Controller/FilesIntegrationController.php
Labels: 3. to review, technical debt

#2190 Allow to mention "all" by autocompleting the room name
  lib/Controller/ChatController.php
Labels: 3. to review, backport-request, enhancement, feature: chat 💬

#2186 Unify lobby with mobile clients
  css/style.scss
  img/lobby.svg
  js/views/emptycontentview.js
  tests/acceptance/features/lobby.feature
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: webinary 📺

#2200 Add changelog messages for Talk7
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2197 Unify the handling of the guest avatars
  js/views/chatview.js
  js/views/templates.js
  js/views/templates/chatview_comment.handlebars
  js/views/templates/richobjectstringparser_userlocal.handlebars
  lib/Chat/Parser/SystemMessage.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2205 Load old chat messages on request
  js/models/chatmessagecollection.js
  js/signaling.js
  js/views/chatview.js
  js/views/virtuallist.js
Labels: 3. to review, backport-request, bug

#2206 [stable17] Load old chat messages on request
  js/models/chatmessagecollection.js
  js/signaling.js
  js/views/chatview.js
  js/views/virtuallist.js
Labels: 3. to review, bug

#2213 Fix eslint issues and rebuild JavaScript files
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  js/models/chatmessagecollection.js
  js/views/chatview.js
  js/views/virtuallist.js
Labels: 4. to release, backport-request, bug

#2215 [stable17] Fix eslint issues and rebuild JavaScript files
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  js/models/chatmessagecollection.js
  js/views/chatview.js
  js/views/virtuallist.js
Labels: 3. to review, bug

#2214 Fix check for guests on the comment field
  js/views/chatview.js
  js/views/templates.js
  js/views/templates/chatview_add_comment.handlebars
Labels: 3. to review, bug, feature: chat 💬, regression

#2220 Fix chat jumping back when typing a new message
  js/app.js
  js/views/chatview.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#2219 Render call button again when "canStartCall" changes
  js/views/callbutton.js
Labels: 4. to release, backport-request, bug

#2221 Show volume indicator in greyscale when speaking while muted
  css/video.scss
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: webrtc 🚡

#2216 Use the shared eslint config
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  vue/.eslintrc.js
  vue/package-lock.json
  vue/package.json
  vue/src/AllowedGroupsSettings.js
  vue/src/CommandsSettings.js
  vue/src/GeneralSettings.js
  vue/src/SignalingServerSettings.js
  vue/src/StunServerSettings.js
  vue/src/TurnServerSettings.js
  vue/src/collections.js
  vue/src/components/Command.vue
  vue/src/components/SignalingServer.vue
  vue/src/components/StunServer.vue
  vue/src/components/TurnServer.vue
  vue/src/views/AllowedGroups.vue
  vue/src/views/CollaborationView.vue
  vue/src/views/Commands.vue
  vue/src/views/GeneralSettings.vue
  vue/src/views/RoomSelector.vue
  vue/src/views/SignalingServers.vue
  vue/src/views/StunServers.vue
  vue/src/views/TurnServers.vue
  vue/webpack.common.js
Labels: 4. to release, javascript, technical debt

#2227 Final changelog for 7.0.0
  CHANGELOG.md
Labels: 3. to review, backport-request, overview

#2229 Do not remove other event handlers when setting the active room
  js/app.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, regression

#2207 Make sure we first check if the user can start a call
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  lib/Listener/RestrictStartingCalls.php
  vue/src/views/GeneralSettings.vue
Labels: 4. to release, bug, feature: webrtc 🚡

#2231 [stable17] Use the shared eslint config
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  vue/.eslintrc.js
  vue/package-lock.json
  vue/package.json
  vue/src/AllowedGroupsSettings.js
  vue/src/CommandsSettings.js
  vue/src/GeneralSettings.js
  vue/src/SignalingServerSettings.js
  vue/src/StunServerSettings.js
  vue/src/TurnServerSettings.js
  vue/src/collections.js
  vue/src/components/Command.vue
  vue/src/components/SignalingServer.vue
  vue/src/components/StunServer.vue
  vue/src/components/TurnServer.vue
  vue/src/views/AllowedGroups.vue
  vue/src/views/CollaborationView.vue
  vue/src/views/Commands.vue
  vue/src/views/GeneralSettings.vue
  vue/src/views/RoomSelector.vue
  vue/src/views/SignalingServers.vue
  vue/src/views/StunServers.vue
  vue/src/views/TurnServers.vue
  vue/webpack.common.js
Labels: 3. to review, javascript, technical debt

#2235 [stable17] Make sure we first check if the user can start a call
  js/admin/allowed-groups.js
  js/admin/allowed-groups.js.map
  js/admin/commands.js
  js/admin/commands.js.map
  js/admin/general-settings.js
  js/admin/general-settings.js.map
  js/admin/signaling-server.js
  js/admin/signaling-server.js.map
  js/admin/stun-server.js
  js/admin/stun-server.js.map
  js/admin/turn-server.js
  js/admin/turn-server.js.map
  js/collections.js
  js/collections.js.map
  js/collectionsintegration.js
  js/collectionsintegration.js.map
  lib/Listener/RestrictStartingCalls.php
  vue/src/views/GeneralSettings.vue
Labels: 3. to review, bug

#2241 Prepend the conversation mention only if it start with the match
  lib/Controller/ChatController.php
Labels: 3. to review, bug, feature: chat 💬
