Repository nextcloud/spreed, pull requests merged in 2020-11, with the labels that each got.

#4495 Inject MimeTypeLoader into RoomShareProvider to not query it on each …
  lib/Share/RoomShareProvider.php
Labels: 3. to review, enhancement

#4517 Fix psalm issues plus extras
  composer.json
  composer.lock
  tests/psalm-baseline.xml
Labels: 4. to release, bug

#4514 [stable20] Update nextcloud-vue from 2.6.8 to 2.8.2
  package-lock.json
  package.json
  src/components/CallView/shared/VideoBackground.vue
Labels: 3. to review

#4451 Remember grid view state per call
  src/components/TopBar/CallButton.vue
  src/store/callViewStore.js
Labels: 3. to review, enhancement, feature: call 👥

#4522 Use standard size for new group conversation modal
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#4532 Add push to talk and push to mute instructions
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4542 Fix remembered grid state per call
  src/store/callViewStore.js
Labels: 4. to release, bug, feature: call 👥, feature: frontend 🖌️

#4539 Only autorename uploads on paste
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: chat 💬

#4541 Focus on submit button by default in upload dialog
  src/components/UploadEditor.vue
Labels: 3. to review, bug, feature: chat 💬

#4537 Fix mime icon and failed icon height
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 4. to release, bug, feature: chat 💬

#4547 Bump node-sass and sass-loader to support node v15.0.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#4550 Fix uploading same file twice in a row in Chromium
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: upload & shares 📤

#4291 Adjust Files sidebar tab to changes in server
  src/mainFilesSidebarLoader.js
  src/views/FilesSidebarTab.vue
Labels: 3. to review, feature: talk-sidebar ⬅️, regression

#4531 Rework scroll into view of conversation after post
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: chat 💬

#4534 Move the filename of attachments to a tooltip
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 4. to release, enhancement, feature: chat 💬

#4568 Bump @nextcloud/vue to 2.9.0
  package-lock.json
  package.json
Labels: 4. to release, enhancement

#4567 Bump @nextcloud/vue to 3.2.0
  package-lock.json
  package.json
Labels: 4. to release, enhancement

#4195 Use new app settings components
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: settings ⚙️

#4275 Fix handling of unavailable commands
  lib/Chat/Command/Executor.php
  lib/Chat/Command/Listener.php
Labels: 3. to review, backport-request, bug, feature: bots & commands 🤖

#4475 Politer language for call notifications for private calls
  lib/Notification/Notifier.php
Labels: 4. to release, enhancement, feature: call 👥

#4521 Remember call view state during presentation
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/TopBar/TopBar.vue
  src/store/callViewStore.js
Labels: 3. to review, enhancement, feature: call 👥

#4548 Fix long participant name + status in participant list with tooltip
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#4530 Fix sidebar chat scroll container + size
  src/components/ChatView.vue
Labels: 3. to review, bug, feature: chat 💬

#4580 Fix build production
  package.json
Labels: 3. to review, bug

#4538 Add play button on top of video or gif previews
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 4. to release, enhancement, feature: chat 💬

#4551 Add tooltip for long room names.
  src/components/RightSidebar/RightSidebar.vue
Labels: 2. developing, enhancement

#4591 Increase top bar space from the right
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, design, feature: chat 💬

#4554 Improve loading placeholder animation performance
  src/components/LoadingPlaceholder.vue
Labels: 3. to review, bug, feature: chat 💬

#4588 Fix casing of IURLGenerator to fix DI
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, bug

#4590 Fix call button overlap in sidebar chat
  src/FilesSidebarTabApp.vue
Labels: 3. to review, bug, design, feature: call 👥, regression

#4593 Don't leave conversation on URL hash change
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
Labels: 4. to release, backport-request, bug, feature: chat 💬

#4598 Allow regular users to filter participants
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, enhancement, feature: chat 💬

#4585 Highlight quote after scrolling to it
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/Quote.vue
Labels: 3. to review, enhancement, feature: chat 💬

#4611 [stable18] Also delete the room if the last moderator leaves
  lib/Controller/RoomController.php
Labels: 4. to release, bug, feature: api 🛠️

#4600 Fix preview spacing
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/Quote.vue
Labels: 3. to review, bug, feature: chat 💬

#4620 Adjust call icon positioning in participant list
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, backport-request, bug

#4625 Sort call participants up
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
Labels: 3. to review, bug, feature: call 👥

#4619 Add changelogs for 10.0.2, 9.0.6 and 8.0.13
  CHANGELOG.md
Labels: 3. to review

#4632 Don't show big screen share while in grid mode
  src/components/CallView/CallView.vue
Labels: 3. to review, bug, feature: call 👥, regression

#4640 Grab the token from the correct attribute
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
Labels: 3. to review, backport-request, feature: chat 💬, regression

#4637 [stable20] Add a phone icon for SIP phone users
  lib/Participant.php
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/constants.js
Labels: 3. to review, feature: chat 💬

#4644 Add changelog entries for 10.0.3
  CHANGELOG.md
Labels: 3. to review, backport-request

#4182 Stop sending the nick through data channels after some time
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: call 👥

#4643 Fix public page calls
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/CallView/CallView.vue
Labels: 3. to review, bug, feature: chat 💬, regression

#4669 Add Vincent to authors
  appinfo/info.xml
Labels: 3. to review, enhancement

#4641 Fix "Copy link" button not clickable (resend)
  src/components/CallView/shared/EmptyCallView.vue
Labels: 4. to release, bug

#4621 Add tooltips to call icons in participant list
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, design, feature: call 👥, feature: chat 💬

#4652 A few accessibility tweaks
  src/components/Caption.vue
  src/components/ChatView.vue
  src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/Quote.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug

#4672 Introduce participant mixin
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/PublicShareSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/TopBar/CallButton.vue
  src/mixins/isInCall.js
  src/mixins/participant.js
  src/views/MainView.vue
Labels: 3. to review, technical debt

#4496 🤙 SIP Bridge
  appinfo/info.xml
  appinfo/routes.php
  img/phone.png
  lib/Activity/Listener.php
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/ChatManager.php
  lib/Chat/Command/Executor.php
  lib/Chat/MessageParser.php
  lib/Chat/Notifier.php
  lib/Chat/Parser/Changelog.php
  lib/Chat/Parser/Command.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Chat/SystemMessage/Listener.php
  lib/Command/Room/TRoomCommand.php
  lib/Config.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Controller/WebinarController.php
  lib/Files/Listener.php
  lib/GuestManager.php
  lib/Manager.php
  lib/MatterbridgeManager.php
  lib/Migration/Version10000Date20201015134000.php
  lib/Migration/Version10000Date20201015150000.php
  lib/Model/Attendee.php
  lib/Model/Message.php
  lib/Model/Session.php
  lib/Notification/Listener.php
  lib/Participant.php
  lib/Room.php
  lib/Search/MessageSearch.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  lib/Service/SessionService.php
  lib/Settings/Admin/AdminSettings.php
  lib/Signaling/BackendNotifier.php
  lib/TInitialState.php
  psalm.xml
  src/components/AdminSettings/SIPBridge.vue
  src/components/CallView/CallView.vue
  src/components/CallView/shared/Video.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SipSettings.vue
  src/components/TopBar/TopBar.vue
  src/constants.js
  src/services/callsService.js
  src/store/participantsStore.js
  src/utils/signaling.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/webrtc.js
  src/views/AdminSettings.vue
  tests/integration/features/command/active-calls.feature
  tests/php/Controller/SignalingControllerTest.php
  tests/psalm-baseline.xml
Labels: 3. to review, enhancement, feature: SFU & SIP ☎️

#4682 Load new participants by actor when the session does not exist yet
  lib/Controller/SignalingController.php
Labels: 3. to review, bug, feature: SFU & SIP ☎️, feature: call 👥

#4685 Unregister refreshPeerList on unmount
  src/components/CallView/CallView.vue
Labels: bug

#4656 Fix user management in password request rooms
  docs/participant.md
  lib/Controller/RoomController.php
  lib/PublicShareAuth/Listener.php
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/password-request.feature
Labels: 3. to review, backport-request, bug, regression

#4680 Bump @nextcloud/vue from 3.2.0 to 3.3.0
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#4695 Add "No response" bot
  .github/no-response.yml
Labels: 3. to review

#4696 Adjust local media control position in sidebar
  src/components/CallView/CallView.vue
Labels: 3. to review, bug

#4697 Remove duplicate top bar height scss variable
  src/assets/variables.scss
Labels: 3. to review, technical debt

#4698 Techdebt/noid/allow picking api versions in integration tests
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, technical debt

#4699 Disallow following self in sidebar mode
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalVideo.vue
Labels: 3. to review, bug

#4576 Move conversation menu options to a dialog
  src/App.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/ModerationSettings.vue
  src/components/ConversationSettings/SipSettings.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
  src/store/conversationsStore.js
Labels: 3. to review, enhancement, feature: chat 💬
