Repository nextcloud/spreed, pull requests merged in 2020-10, with the labels that each got.

#4256 Fixed contact selection bubble wrapping
  src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4253 Show icon only with dnd status in the message
  package-lock.json
  package.json
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/mixins/userStatus.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#4261 Combine the changelog for 10.0.0 in the appstore
  CHANGELOG.md
Labels: 3. to review, backport-request, technical debt

#4277 Don't load the user_status in big conversations
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, security

#4264 Fix participants list search box overlap
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, design, feature: frontend 🖌️

#4287 Import dialogs scss
  package-lock.json
  package.json
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthRequestPasswordButton.vue
  src/PublicShareSidebar.vue
  webpack.common.js
Labels: 3. to review, bug, feature: frontend 🖌️

#4293 Add style loader
  package-lock.json
  package.json
Labels: 4. to release, bug, feature: frontend 🖌️, javascript

#4296 Remove pulse animation from call button
  src/components/TopBar/CallButton.vue
Labels: bug, feature: chat 💬, feature: frontend 🖌️

#4300 Clarify participant search box in conversation
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, bug, design, feature: chat 💬, feature: frontend 🖌️

#4288 Fix IRC bridge connection password and add channel password field
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
Labels: 3. to review, bug, feature: integration 📦

#4263 Update list of integrated apps and update some version examples
  README.md
Labels: 3. to review, technical debt

#4304 Fix key name in collaboration resource listener for add user event
  lib/Collaboration/Resources/Listener.php
Labels: 4. to release, backport-request, bug

#4309 Fix menu position for left sidebar avatars
  src/components/ConversationIcon.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#4316 Comments manager uses the PSR logger now
  lib/Chat/CommentsManager.php
Labels: 3. to review, technical debt

#4321 Fix lobby date not shown in moderation menu
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: webinar 📺

#4328 Add push to talk and push to mute
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#4332 EventDispatcher uses PSR Logger now
  tests/php/RoomTest.php
Labels: 4. to release, technical debt

#4266 Focus message field after upload or sharing file
  src/components/NewMessageForm/NewMessageForm.vue
  src/store/fileUploadStore.js
Labels: 3. to review, design, enhancement, feature: chat 💬, feature: frontend 🖌️

#4334 Update conversation name directly after call returns
  src/components/RightSidebar/RightSidebar.vue
  src/store/conversationsStore.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#4325 Don't show the HPB trial form when a HPB is configured and the trial …
  src/components/AdminSettings/HostedSignalingServer.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️

#4360 Fix buttons height
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, design, feature: frontend 🖌️

#4358 Max width on call view tooltips
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, bug

#4331 Add checkbox for locking conversation
  src/components/ChatView.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
  src/services/conversationsService.js
  src/store/conversationsStore.js
Labels: 3. to review, enhancement, feature: chat 💬, feature: frontend 🖌️

#4367 Fix entropy calculation and missing default values for lobby
  lib/Controller/RoomController.php
  lib/Manager.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#4336 Add Psalm
  .github/workflows/psalm.yml
  Makefile
  composer.json
  composer.lock
  lib/Config.php
  lib/Migration/Version2001Date20170707115443.php
  lib/Migration/Version7000Date20190724121137.php
  lib/Room.php
  lib/Service/HostedSignalingServerService.php
  lib/Share/RoomShareProvider.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#4181 Improve setting initial audio and video status when the HPB is used
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: call 👥

#4379 Cache hasAvatar to avoid call background flickering
  src/components/CallView/shared/VideoBackground.vue
Labels: 3. to review

#4329 Bump @nextcloud/vue
  package-lock.json
  package.json
Labels: 3. to review

#4383 Don't render extra videos when selecting promoted
  src/components/CallView/CallView.vue
Labels: 3. to review, feature: call 👥

#4410 Skip psalm issues related to hook names
  lib/Chat/SystemMessage/Listener.php
  lib/Share/Listener.php
Labels: 3. to review, bug

#4363 Add ability to collapse the grid view
  src/assets/variables.scss
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
Labels: 3. to review, enhancement, feature: call 👥

#4408 Fix empty call background color
  src/components/CallView/shared/EmptyCallView.vue
Labels: 3. to review, design, feature: call 👥

#4359 Use generic syntax when calling 'ps' command
  lib/MatterbridgeManager.php
Labels: 3. to review, backport-request, bug, feature: integration 📦

#4416 Adjust empty call view colors
  src/components/CallView/shared/EmptyCallView.vue
Labels: bug, design, feature: call 👥

#4380 Fix chat scrolling
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#4424 Update comments manager constructor
  lib/Chat/CommentsManager.php
Labels: 4. to release, bug, technical debt

#4422 Fix isolated modules in Files app sidebar
  lib/Files/TemplateLoader.php
  webpack.common.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#4430 Update info.xml
  tests/integration/spreedcheats/appinfo/info.xml
Labels: 3. to review, regression

#4431 Abort integration tests if Talk or helper apps can not be installed
  tests/integration/run.sh
Labels: 3. to review

#4429 Fix empty call view position in sidebar
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/EmptyCallView.vue
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#4411 Fix bug when being muted by a moderator while on push to talk
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#4374 Only show the conflict warning when the session was in a call
  lib/Controller/RoomController.php
  src/App.vue
  src/views/SessionConflictView.vue
Labels: 3. to review, bug, feature: chat 💬, feature: signaling 📶

#4444 Add changelog for 10.0.1, 9.0.5 and 8.0.12
  CHANGELOG.md
Labels: 3. to review, backport-request, overview

#4447 [stable18] Add changelog for 8.0.12
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#4446 [stable19] Add changelog for 9.0.5 and 8.0.12
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#4449 Correctly leave the room not the call in integration tests
  tests/integration/features/conversation/set-password.feature
Labels: 3. to review, backport-request, technical debt

#4439 Don't copy array for reverse iteration
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, feature: chat 💬, technical debt

#4474 Show favorite conversations at the top of the dashboard empty content
  src/views/Dashboard.vue
Labels: 4. to release, enhancement, feature: frontend 🖌️

#4425 Upstream our comments manager extensions to server
  composer.lock
  lib/Chat/AutoComplete/Sorter.php
  lib/Chat/CommentsManager.php
Labels: 3. to review, feature: chat 💬, technical debt

#4472 Improve previews for guests + GIF support
  docs/capabilities.md
  lib/Capabilities.php
  lib/Chat/Parser/SystemMessage.php
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  tests/php/CapabilitiesTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, enhancement

#4483 Always use CommentsManager from the app
  lib/Chat/AutoComplete/Sorter.php
  lib/Chat/ChatManager.php
  lib/Chat/Parser/UserMention.php
  lib/Manager.php
  lib/Notification/Notifier.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/oc_comments_manager.php
Labels: 3. to review, technical debt

#4473 Bump @nextcloud/vue to 3.1.0
  package-lock.json
  package.json
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 4. to release, enhancement

#4409 Improve call error messages UX
  src/components/CallView/shared/LocalVideo.vue
  src/utils/webrtc/webrtc.js
Labels: 4. to release, bug, feature: call 👥

#4485 Auto-rename pasted files
  src/components/NewMessageForm/NewMessageForm.vue
  src/store/fileUploadStore.js
  src/utils/fileUpload.js
  src/utils/temporaryMessage.js
Labels: 3. to review, enhancement, feature: upload & shares 📤

#4493 Remove double scrollbar in call chat view
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, design, feature: call 👥

#4489 Also delete the room if the last moderator leaves …
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️
