Repository nextcloud/spreed, pull requests merged in 2020-09, with the labels that each got.

#4064 Use v-tooltip instead of popover for new group conversation's tooltip
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 3. to review, bug, design

#4082 Show other persons video when they share their screen
  src/components/CallView/CallView.vue
Labels: 3. to review, bug, feature: call 👥

#4090 Fix focus state after pasting something into the chat input
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#4084 Fix scroll to bottom aria label
  src/components/CallView/Grid/Grid.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4091 Improve promoted view wording
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4092 No statuses for guests
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
Labels: 3. to review, bug, feature: chat 💬

#4083 Show bridge process state and log
  appinfo/routes.php
  lib/Controller/MatterbridgeController.php
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
  src/services/matterbridgeService.js
Labels: 3. to review, enhancement, feature: integration 📦

#4079 Make sure matterbridge binary is executable
  lib/Controller/MatterbridgeSettingsController.php
  lib/Exceptions/WrongPermissionsException.php
  lib/MatterbridgeManager.php
  lib/Settings/Admin/AdminSettings.php
  src/components/AdminSettings/MatterbridgeIntegration.vue
Labels: 3. to review, bug, feature: integration 📦

#4075 Add version recommendation, quota notes and test details to TURN server documentation
  docs/TURN.md
Labels: 3. to review

#4095 Bump @nextcloud/vue to 2.6.4
  package-lock.json
  package.json
Labels: 3. to review, dependencies, technical debt

#4094 Add changelog for 10.0.0-beta.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, overview

#3955 Keyboard navigation for conversation search
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/mixins/arrowNavigation.js
Labels: 3. to review, bug, feature: frontend 🖌️

#4120 Give low priority to matterbridge processes
  lib/MatterbridgeManager.php
Labels: 3. to review, enhancement, feature: integration 📦

#4122 Kill matterbridge before editing the config file
  lib/MatterbridgeManager.php
Labels: 3. to review, bug, feature: integration 📦

#4117 Matterbridge adjustments
  lib/Controller/MatterbridgeController.php
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Matterbridge/BridgePart.vue
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
Labels: 3. to review, enhancement, feature: integration 📦

#4124 Remove colon before style tag
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
Labels: 3. to review, bug

#4118 Add link to doc explaining how to customize matterbridge binary path
  docs/matterbridge.md
  mkdocs.yml
  src/components/AdminSettings/MatterbridgeIntegration.vue
Labels: 4. to release, enhancement, feature: integration 📦

#4127 Add a default on NotNull column
  lib/Migration/Version2001Date20180103144447.php
Labels: 3. to review, backport-request, bug

#4121 Log matterbridge start/stop actions in related room
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/MatterbridgeController.php
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
Labels: 4. to release, enhancement, feature: integration 📦, help wanted

#4135 Bump @nextcloud/vue lib to 2.6.5
  package-lock.json
  package.json
Labels: 3. to review, bug, feature: frontend 🖌️, javascript

#4137 Don't leak the status when the app is disabled for the user
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, bug, feature: chat 💬

#4136 Bump vue-dashboard library
  package-lock.json
  package.json
  src/views/Dashboard.vue
Labels: 3. to review, bug

#4134 Avatar menu of chat in sidebar underflows video layout
  src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#4139 Fix memory leak in message list
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#4155 Fix event handler deregistration in TopBar
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#4153 Listen to the user status event to update the status immediately
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/store/participantsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️

#4140 Fix memory and event handler leaks in calls
  src/components/CallView/shared/LocalMediaControls.vue
  src/utils/webrtc/SpeakingWhileMutedWarner.js
  src/utils/webrtc/analyzers/CallAnalyzer.js
  src/utils/webrtc/analyzers/ParticipantAnalyzer.js
  src/utils/webrtc/models/CallParticipantCollection.js
  src/utils/webrtc/models/CallParticipantModel.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#4154 Fix getting messages again after the component was destroyed
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#4150 Fix scrolling of sidebar's chat
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug

#4076 Ignore "forceMute" message if already muted
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#4152 Reduce load on room refreshing
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Room.php
  lib/Search/ConversationSearch.php
  lib/Service/RoomService.php
Labels: 3. to review, feature: api 🛠️, technical debt

#4165 Be more robust against failures when trying to get the owner of the s…
  lib/Share/Listener.php
Labels: 3. to review, bug, deployed on testing, feature: upload & shares 📤

#4166 Better title for search results in one-to-one conversations
  lib/Search/MessageSearch.php
Labels: 3. to review, bug, feature: search 🔎

#4170 Update statuses when we got new information with a participant refresh
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4167 Add changelog for 8.0.11
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#4168 Add changelog for 9.0.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#4169 Add changelog for 10.0.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 2. developing, technical debt

#4172 Don't update packages on npm-init or dev-setup
  Makefile
Labels: technical debt

#4185 Fix IRC nickserv credentials
  lib/MatterbridgeManager.php
Labels: 3. to review, bug, feature: integration 📦

#4190 If there are no sessions, we don't need to run a query
  lib/GuestManager.php
Labels: 3. to review, feature: api 🛠️, technical debt

#4188 Also return the conversation data when the room exists already
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#4197 Fix missing parent constructor call
  lib/BackgroundJob/ResetAssignedSignalingServer.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#4200 Save the "count unread messages" query, when the last read is the las…
  lib/Controller/RoomController.php
Labels: 3. to review, bug, deployed on testing, feature: api 🛠️

#4198 Change the upload button name from upload to send
  src/components/UploadEditor.vue
Labels: 3. to review, enhancement

#4189 Less participant queries
  lib/Collaboration/Resources/ConversationProvider.php
  lib/Controller/PageController.php
  lib/Controller/SignalingController.php
  lib/Manager.php
  lib/Notification/Notifier.php
  lib/Share/Helper/DeletedShareAPIController.php
  lib/Share/Helper/ShareAPIController.php
  lib/Share/RoomShareProvider.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, feature: upload & shares 📤, technical debt

#4187 Cache the last msg id of a chat in MemoryCache to save O(n) queries p…
  lib/Chat/ChatManager.php
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, backport-request, deployed on testing, enhancement, feature: api 🛠️

#4196 Bugfix/noid/matterbridge
  appinfo/info.xml
  lib/BackgroundJob/CheckMatterbridges.php
  lib/MatterbridgeManager.php
  lib/Migration/Version11000Date20200922161218.php
Labels: 3. to review, bug, feature: integration 📦

#4207 Online > User type
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/mixins/userStatus.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#4209 Fix update query
  lib/Migration/Version11000Date20200922161218.php
Labels: 4. to release, backport-request, bug

#4203 Save the query to count the user for moderators per room every 30sec
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#4217 Add missing parent::__construct() call to all background jobs
  lib/BackgroundJob/ExpireSignalingMessage.php
  lib/BackgroundJob/RemoveEmptyRooms.php
Labels: 4. to release, backport-request, bug, regression, technical debt

#4216 Add "New in Talk 10" section
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#4218 Remember selected input devices
  src/utils/webrtc/MediaDevicesManager.js
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#4222 Fix height in Talk sidebar in Files app
  src/FilesSidebarTabApp.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#4226 Add changelog for 10.0.0-rc.2
  CHANGELOG.md
Labels: 3. to review, backport-request, overview

#4232 Small fixes for Matterbridge documentation
  docs/matterbridge.md
Labels: 3. to review, enhancement

#4229 Make the "Scroll to bottom" button non-primary
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#4214 Set the user status when a mobile client polls for messages
  lib/Controller/ChatController.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#4247 Improved status update handling for mobile apps
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, client: 🤖🍏 mobile, feature: api 🛠️

#4251 Bump @nextcloud/vue to 2.6.6 for the status avatar updates
  package-lock.json
  package.json
Labels: 3. to review, backport-request, bug
