Repository nextcloud/spreed, pull requests merged in 2020-02, with the labels that each got.

#2892 End search operation when selecting a conversation
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, bug

#2879 Bugfix/noid/fix chatview layout glitches
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/Quote.vue
Labels: 3. to review

#2899 Also scroll on inactive tabs
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2858 1st try default group notification setting
  lib/Chat/Notifier.php
  lib/Controller/RoomController.php
  lib/Settings/Admin/GeneralSettings.php
  src/views/AdminSettings/GeneralSettings.vue
  tests/php/Chat/NotifierTest.php
  tests/php/Controller/RoomControllerTest.php
Labels: 4. to release, enhancement, feature: chat 💬, feature: settings ⚙️

#2895 Immediately update last message preview in conversation list
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/store/conversationsStore.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#2902 [stable18] Improve chat loading
  src/components/MessagesList/MessagesList.vue
  src/services/messagesService.js
  src/store/messagesStore.js
  src/utils/signaling.js
Labels: 3. to review, bug

#2906 Add missing IDs to sidebar tabs
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, backport-request, bug, regression

#2907 Fix joining a call with internal signaling
  src/utils/signaling.js
Labels: 3. to review, backport-request, bug, feature: signaling 📶

#2905 Add a red camera icon for conversations with an ongoing call
  css/icons.scss
  src/components/ConversationIcon.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, backport-request, enhancement, feature: call 👥, feature: frontend 🖌️

#2911 Add changelog for 8.0.2
  CHANGELOG.md
Labels: 3. to review, bug

#2923 Only show the call or the favorite icon
  src/components/ConversationIcon.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#2925 Fix signaling from move to axios
  src/services/signalingService.js
  src/utils/signaling.js
Labels: 2. developing, backport-request, bug, feature: call 👥, feature: signaling 📶, regression

#2926 Fix guest collisions
  src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, regression

#2924 Fix vuex store modification issue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/store/conversationsStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#2931 Changelog for v8.0.3
  CHANGELOG.md
Labels: backport-request

#2934 Fix sidebars integrations
  CHANGELOG.md
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/mainFilesSidebar.js
  src/mainFilesSidebarLoader.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/views/FilesSidebarTab.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️, regression

#2936 Bring back the fullscreen option
  css/icons.scss
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, regression

#2939 Update changelog for 8.0.4
  CHANGELOG.md
Labels: 3. to review, backport-request

#2942 Send the notifications after joining the call
  lib/Notification/Listener.php
Labels: 3. to review, bug, feature: call 👥, technical debt

#2949 Also end teh call state when a user leaves
  lib/Activity/Listener.php
Labels: 3. to review, bug

#2950 Await that the call was left before leaving the conversation
  src/utils/signaling.js
Labels: 3. to review, bug, feature: call 👥, feature: signaling 📶, regression

#2898 Fix font-size of the chat input
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, backport-request, bug, design, feature: chat 💬, feature: frontend 🖌️

#2962 Make sure the secondary view has an id
  src/views/FilesSidebarCallView.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#2970 Add "Go to file" link to conversation info
  css/icons.scss
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#2973 Focus the chat input in the sidebars
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#2965 Only leave and join real conversations
  src/FilesSidebarTabApp.vue
  src/mainFilesSidebarLoader.js
  src/services/filesIntegrationServices.js
Labels: 3. to review, backport-request, bug, feature: talk-sidebar ⬅️

#2953 Use vue-richtext lib
  lib/Chat/Parser/SystemMessage.php
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/DefaultParameter.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/PlainText.vue
Labels: 4. to release, backport-request, enhancement, feature: chat 💬

#2976 Print sharing error on correct level
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: room-shares 📁

#2978 Fix copy-pasting into chrome/chromium/safari
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#2967 Fix leaving a call on logout
  lib/Listener.php
  lib/TalkSession.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#2891 File upload
  package-lock.json
  package.json
  src/components/NewMessageForm/NewMessageForm.vue
  src/services/DavClient.js
  src/services/filesSharingServices.js
Labels: 3. to review, feature: frontend 🖌️, feature: upload & shares 📤

#2992 Update @juliushaertl/vue-richtext
  package-lock.json
  package.json
Labels: 3. to review, backport-request, bug, feature: chat 💬

#2880 Cancel getparticipants requests once changing conversation
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/services/participantsService.js
Labels: 4. to release, bug, feature: frontend 🖌️, technical debt

#2997 Don't provide a stun without internet connection
  lib/Config.php
  tests/php/ConfigTest.php
Labels: 4. to release, backport-request, bug, feature: settings ⚙️

#2988 Feature/noid/upload store
  src/components/NewMessageForm/NewMessageForm.vue
  src/services/filesSharingServices.js
  src/store/fileUploadStore.js
  src/store/index.js
Labels: 3. to review, feature: frontend 🖌️, feature: upload & shares 📤

#2983 Allow to select an attachment folder
  appinfo/routes.php
  docs/capabilities.md
  lib/Capabilities.php
  lib/Config.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/services/settingsService.js
  src/store/fileUploadStore.js
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: frontend 🖌️, feature: settings ⚙️, feature: upload & shares 📤

#2985 Add an icon to the call button to draw more attention
  css/icons.scss
  src/components/TopBar/CallButton.vue
Labels: 3. to review, backport-request, enhancement, feature: call 👥, feature: frontend 🖌️, papercut

#3005 Prevent resharing of the same file
  src/components/NewMessageForm/NewMessageForm.vue
  src/store/fileUploadStore.js
Labels: 3. to review, bug, feature: upload & shares 📤

#3007 Fix mentions inserted by vue-at
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 4. to release, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#3009 Remove upload button from read only conversations
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 4. to release, backport-request, bug, feature: frontend 🖌️, feature: upload & shares 📤

#3002 Filtering of participant suggestions
  lib/AppInfo/Application.php
  lib/Collaboration/Collaborators/Listener.php
  lib/Listener.php
Labels: 3. to review, bug, feature: api 🛠️

#3001 Don't add default stun in UI on removal
  lib/Settings/Admin/StunServer.php
  src/views/AdminSettings/StunServers.vue
  tests/php/CapabilitiesTest.php
  tests/php/Settings/Admin/StunServerTest.php
Labels: 4. to release, backport-request, bug, feature: settings ⚙️

#3014 Get rid of underscore, jQuery and the console.log statements
  src/utils/signaling.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, feature: WebRTC 🚡, feature: signaling 📶, technical debt

#3022 Fix search box to add participants shown to regular participants
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#3021 Correctly get new messages for guests
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: chat 💬, regression

#3024 Only update the named session if it is a guest
  lib/Room.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️
