Repository nextcloud/spreed, pull requests merged in 2020-12, with the labels that each got.

#4689 Follow up for SIP changes
  appinfo/routes.php
  docs/capabilities.md
  docs/conversation.md
  docs/internal-signaling.md
  docs/webinar.md
  lib/Capabilities.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Controller/WebinarController.php
  lib/Service/ParticipantService.php
  src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
  src/components/RightSidebar/RightSidebar.vue
  src/services/conversationsService.js
  src/services/signalingService.js
  src/store/conversationsStore.js
  tests/php/CapabilitiesTest.php
Labels: 4. to release, bug, feature: SFU & SIP ☎️, feature: call 👥, feature: frontend 🖌️

#4704 Help psalm find context when running single files
  composer.json
Labels: bug

#4703 Vertically align participant indicator
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, design

#4700 Fix follow self + remember state after unfollowing + collapse stripe
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.vue
Labels: 3. to review, bug

#4709 Bump @nextcloud-vue from 3.3.0 to 3.3.1
  package-lock.json
  package.json
Labels: 3. to review

#4708 Don't select timestamp but selecting messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug

#4711 Don't repeat calls to handler when using short keys
  src/App.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review

#4712 Fix volume indicator performance
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, bug

#4702 Integration tests for sip
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/sip-dialin.feature
Labels: 3. to review, technical debt

#4723 Update Spreed Cheats for 21
  tests/integration/spreedcheats/appinfo/routes.php
  tests/integration/spreedcheats/lib/AppInfo/Application.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, technical debt

#4587 Add backend for conversation descriptions
  appinfo/info.xml
  appinfo/routes.php
  docs/conversation.md
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Command/Room/Create.php
  lib/Command/Room/TRoomCommand.php
  lib/Command/Room/Update.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version11000Date20201011082810.php
  lib/Room.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Listener.php
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/system-messages.feature
  tests/integration/features/command/create.feature
  tests/integration/features/conversation/lobby.feature
  tests/integration/features/conversation/set-description.feature
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/RoomTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, enhancement, feature: api 🛠️

#4654 Remove bridge bot from room when bridge is disabled
  lib/MatterbridgeManager.php
Labels: 3. to review, enhancement, feature: integration 📦

#4727 Fix telegram channel config key
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
Labels: 3. to review, backport-request, bug, feature: integration 📦

#4730 Prevent issues with utf8mb4 chars on update
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#4231 ✔️✔️ Read status for chat messages
  appinfo/info.xml
  docs/capabilities.md
  docs/chat.md
  docs/constants.md
  docs/conversation.md
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Config.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Controller/SettingsController.php
  lib/Migration/Version11000Date20201204110210.php
  lib/Model/Attendee.php
  lib/Model/AttendeeMapper.php
  lib/Participant.php
  lib/Service/ParticipantService.php
  lib/TInitialState.php
  psalm.xml
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/constants.js
  src/services/messagesService.js
  src/services/settingsService.js
  src/store/conversationsStore.js
  src/store/index.js
  src/store/settingsStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/read-status.feature
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: chat 💬

#4740 Link shared room in the files sidebar sharing tab
  lib/Share/Helper/ShareAPIController.php
Labels: 3. to review, enhancement

#4753 Add changelog for 10.1.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#4756 Document read-status privacy setting
  docs/settings.md
Labels: 3. to review, bug, feature: api 🛠️

#4706 Add listable scope attribute for conversations
  .drone.yml
  appinfo/info.xml
  appinfo/routes.php
  docs/capabilities.md
  docs/chat.md
  docs/constants.md
  docs/conversation.md
  docs/events.md
  lib/Capabilities.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Command/Room/Create.php
  lib/Command/Room/TRoomCommand.php
  lib/Command/Room/Update.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version11000Date20201201102528.php
  lib/Room.php
  lib/Service/ParticipantService.php
  lib/Signaling/Listener.php
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/ListableSettings.vue
  src/components/ConversationSettings/LobbySettings.vue
  src/components/ConversationSettings/LockingSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/constants.js
  src/services/conversationsService.js
  src/services/participantsService.js
  src/store/conversationsStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/system-messages.feature
  tests/integration/features/command/create.feature
  tests/integration/features/conversation/find-listed.feature
  tests/integration/features/conversation/join-listable.feature
  tests/integration/features/conversation/set-listable.feature
  tests/integration/run.sh
  tests/integration/spreedcheats/appinfo/routes.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/RoomTest.php
  tests/php/Signaling/BackendNotifierTest.php
  tests/psalm-baseline.xml
Labels: 3. to review, backport-request, enhancement

#4757 Use a unique index name
  lib/Migration/Version11000Date20201209142525.php
Labels: 3. to review, bug, regression

#4759 [stable20.1] Abort php test server on ctrl+c
  tests/integration/run.sh
Labels: 3. to review, backport-request

#4760 Add a capability for the phonebook search
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement

#4745 Fix MsTeams and Steam Matterbridge config
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
Labels: 3. to review, bug, feature: integration 📦

#4742 Cancel search while typing
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/services/conversationsService.js
  src/utils/cancelableRequest.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: search 🔎

#4763 Display hint when no participant found in right sidebar
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
Labels: 3. to review, bug, feature: chat 💬

#4653 Improve Matterbridge settings design
  img/bridge-bot.png
  img/bridge-services/discord.svg
  img/bridge-services/irc.svg
  img/bridge-services/matrix.svg
  img/bridge-services/mattermost.svg
  img/bridge-services/msteams.svg
  img/bridge-services/rocketchat.svg
  img/bridge-services/slack.svg
  img/bridge-services/steam.svg
  img/bridge-services/telegram.svg
  img/bridge-services/xmpp.svg
  img/bridge-services/zulip.svg
  img/phone.png
  lib/Chat/Parser/SystemMessage.php
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Matterbridge/BridgePart.vue
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
Labels: 3. to review, design, enhancement, feature: integration 📦

#4762 Allow to respond with modified common read value on "not modified" messages
  docs/chat.md
  lib/Controller/ChatController.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, bug, feature: api 🛠️

#4765 Close participant context menu after action
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: chat 💬

#4589 Test against oracle
  .github/workflows/oci.yml
  lib/Manager.php
  lib/Migration/CreateHelpCommand.php
  lib/Model/CommandMapper.php
  lib/Model/SelectHelper.php
  lib/Room.php
  lib/Service/CommandService.php
  lib/Service/ParticipantService.php
Labels: 3. to review, bug, technical debt

#4746 Use proc_open to run system commands in bridge manager
  lib/MatterbridgeManager.php
Labels: 3. to review, enhancement, feature: integration 📦

#4569 Added "Raise Hand" feature
  docs/capabilities.md
  lib/Capabilities.php
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/store/callViewStore.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/webrtc.js
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: call 👥

#4767 Update nextcloud-vue to 3.3.2 and fix avatar menu
  package-lock.json
  package.json
Labels: 3. to review, bug

#4769 Remove request password button when verif disabled
  lib/PublicShareAuth/TemplateLoader.php
Labels: 3. to review, bug

#4741 Message status ux improvements
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, feature: frontend 🖌️

#4678 Fix Chromium performance hit in calls due to blur filter
  lib/Listener/CSPListener.php
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/Video.vue
  src/components/CallView/shared/VideoBackground.vue
  src/store/callViewStore.js
  src/utils/imageBlurrer.js
  src/utils/imageBlurrerWorker.js
  webpack.common.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️, regression

#4772 Disable PIP for non-promoted videos
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Screen.vue
  src/components/CallView/shared/Video.vue
  src/components/MediaDevicesPreview.vue
Labels: 3. to review, bug

#4768 Move PHPUnit to GitHub actions 🚛
  .drone.yml
  .github/workflows/dependabot-approve.yml
  .github/workflows/lint.yml
  .github/workflows/oci.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/test.yml
Labels: 3. to review, technical debt

#4796 [stable18] Fix user management in password request rooms
  docs/participant.md
  lib/Controller/RoomController.php
  lib/PublicShareAuth/Listener.php
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/password-request.feature
Labels: 3. to review, bug, regression

#4797 [stable19] Fix user management in password request rooms
  docs/participant.md
  lib/Controller/RoomController.php
  lib/PublicShareAuth/Listener.php
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/password-request.feature
Labels: 3. to review, bug, regression

#4798 [stable20] Fix user management in password request rooms
  docs/participant.md
  lib/Controller/RoomController.php
  lib/PublicShareAuth/Listener.php
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/password-request.feature
Labels: 3. to review, bug, regression

#4801 [stable20.1] Fix user management in password request rooms
  docs/participant.md
  lib/Controller/RoomController.php
  lib/PublicShareAuth/Listener.php
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/password-request.feature
Labels: 3. to review, bug, regression

#4802 Add changelog for 11.0.0-alpha.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#4806 [stable18] Add changelog for 8.0.14
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#4805 [stable19] Add changelog for 9.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#4804 [stable20.1] Add changelog for 10.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#4546 Conversation description - front-end
  package-lock.json
  package.json
  src/components/RightSidebar/Description/Description.vue
  src/components/RightSidebar/RightSidebar.vue
  src/services/conversationsService.js
  src/store/conversationsStore.js
Labels: 3. to review, feature: frontend 🖌️

#4791 Make bridge bot password more complex
  lib/MatterbridgeManager.php
Labels: 3. to review, bug, feature: integration 📦

#4764 Integration tests use occ guests:add to create guests
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/find-listed.feature
  tests/integration/features/conversation/join-listable.feature
  tests/integration/features/conversation/set-listable.feature
  tests/integration/spreedcheats/appinfo/routes.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, technical debt

#4821 Revert "Bump @babel/preset-env from 7.12.10 to 7.12.11"
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: 3. to review, bug

#4835 Fix listable search request
  src/services/conversationsService.js
Labels: bug, feature: chat 💬, high

#4836 Scroll to conversation only in specific cases
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug

#4840 Hide password hint when guest not allowed
  src/components/ConversationSettings/LinkShareSettings.vue
Labels: 3. to review, bug

#4841 Fix row wrapping on hover
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug, feature: chat 💬

#4843 Remove unused newMessagePosted event
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, feature: chat 💬

#4845 Fix console error about missing hash in sidebar mode
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug

#4844 Call warning + empty call view tweaks
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/EmptyCallView.vue
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, design

#4825 Fix notifications based on the notification level
  lib/Service/ParticipantService.php
Labels: 3. to review, backport-request, bug, regression

#4864 Lower names font sizes in calls
  src/components/CallView/shared/VideoBottomBar.vue
Labels: 3. to review, design, enhancement

#4868 Collapse descriptions on mousedown only
  package-lock.json
  package.json
  src/components/RightSidebar/Description/Description.vue
  src/main.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
Labels: 3. to review, bug, feature: frontend 🖌️

#4848 Fix notifications based on the participants not in a call
  lib/Service/ParticipantService.php
Labels: 3. to review, backport-request, bug, regression
