Repository nextcloud/spreed, pull requests merged in 2020-08, with the labels that each got.

#3962 Only show browser warning when interacting with talk
  src/FilesSidebarCallViewApp.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthRequestPasswordButton.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#3968 Pass base URL of Nextcloud to signaling server in backend requests.
  docs/standalone-signaling-api-v1.md
  lib/Signaling/BackendNotifier.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, backport-request, enhancement, feature: signaling 📶

#3963 Fix Internet Explorer 11 not loading because Element.append() does no…
  src/FilesSidebarCallViewApp.vue
  src/collections.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
Labels: 4. to release, backport-request, bug, feature: frontend 🖌️

#3960 Conversations in Unified Search
  css/unified-search.scss
  lib/AppInfo/Application.php
  lib/Search/ConversationSearch.php
  lib/Search/ConversationSearchResult.php
  lib/Search/UnifiedSearchCSSLoader.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: integration 📦

#3966 Move to Psr\Log\LoggerInterface
  lib/Activity/Listener.php
  lib/BackgroundJob/CheckHostedSignalingServer.php
  lib/BackgroundJob/RemoveEmptyRooms.php
  lib/Chat/Command/Executor.php
  lib/Controller/HostedSignalingServerController.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Notification/Listener.php
  lib/Service/HostedSignalingServerService.php
  lib/Signaling/BackendNotifier.php
  tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
  tests/php/Chat/Command/ExecutorTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, technical debt

#3989 Add Changelog for 9.0.3
  CHANGELOG.md
Labels: 3. to review, backport-request

#3987 Downgrade CSS Loader to 3.6 for now to fix IE11
  package-lock.json
  package.json
Labels: 3. to review, bug, feature: frontend 🖌️, regression

#3913 Make possible to select input media devices before calls
  src/components/MediaDevicesPreview.vue
  src/components/MediaDevicesSelector.vue
  src/components/RightSidebar/RightSidebar.vue
  src/utils/webrtc/MediaDevicesManager.js
  src/utils/webrtc/index.js
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, enhancement, feature: call 👥, feature: frontend 🖌️

#3992 Adjust search provider to recent changes
  lib/Search/ConversationSearch.php
  lib/Search/ConversationSearchResult.php
Labels: 3. to review, bug, feature: search 🔎

#3994 😍 Emoji picker vue
  img/emoji-smile.svg
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 4. to release

#3993 💬 Status adaption for Nextcloud 20
  css/At.scss
  docs/chat.md
  docs/participant.md
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/mixins/userStatus.js
  src/services/mentionsService.js
  src/services/participantsService.js
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/RoomControllerTest.php
Labels: 4. to release, enhancement, feature: api 🛠️, feature: frontend 🖌️

#3995 Fix search order
  lib/Search/ConversationSearch.php
Labels: 3. to review, bug, feature: search 🔎

#3890 🍱 Dashboard adaption for Nextcloud 20
  css/icons.scss
  lib/AppInfo/Application.php
  lib/Dashboard/TalkWidget.php
  package-lock.json
  package.json
  src/App.vue
  src/dashboard.js
  src/views/Dashboard.vue
  webpack.common.js
Labels: 2. developing, enhancement

#3988 Feature/3949/allow editing before upload
  src/App.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/UploadEditor.vue
  src/store/fileUploadStore.js
  src/utils/fileUpload.js
  src/utils/temporaryMessage.js
Labels: 3. to review, enhancement, feature: frontend 🖌️

#4020 Relabel the sections to high-performance backend to avoid confusion
  src/components/AdminSettings/HostedSignalingServer.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/SignalingServers.vue
Labels: 3. to review, bug

#4021 Show date on hover of time
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#4018 Remove duplicated slashes
  src/views/Dashboard.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4024 Multiple fixes to the conversation selector for projects
  src/views/RoomSelector.vue
Labels: 3. to review, bug, feature: integration 📦

#4028 Fix forced reconnections for guests when the HPB is used
  src/utils/signaling.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: signaling 📶

#4027 Add a combined settings tab
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#3884 Allow using media controls on videos without selecting video
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Video.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/mixins/video.js
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#4034 Fix translation
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug

#4032 Move talk global settings to settings dialog
  package-lock.json
  src/App.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MediaDevicesPreview.vue
  src/components/MediaDevicesSelector.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#4023 Make possible to select input media devices during calls
  src/components/MediaDevicesPreview.vue
  src/utils/webrtc/MediaDevicesManager.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/shims/MediaStream.js
  src/utils/webrtc/shims/MediaStreamTrack.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, enhancement, feature: WebRTC 🚡, feature: call 👥, feature: frontend 🖌️

#4033 Better empty content on dashboard
  src/views/Dashboard.vue
Labels: 3. to review, bug

#4031 Fix semantic markup for replies
  src/components/Quote.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4052 Add button to moderation menu to mute all the other participants
  src/components/TopBar/TopBar.vue
Labels: 3. to review, feature: call 👥, feature: frontend 🖌️

#4053 Fix eslint warnings
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/views/Dashboard.vue
Labels: 3. to review, bug

#4038 Fix MediaDevicesSelector not updated when mounted
  src/components/MediaDevicesSelector.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4055 Do not use "finally" on promises returned by "getUserMedia"
  src/components/MediaDevicesPreview.vue
  src/utils/webrtc/MediaDevicesManager.js
Labels: 3. to review, bug, feature: frontend 🖌️

#4037 Feature/noid/allow scrolling to messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
  src/components/Quote.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#4057 Add anchor ids to conversations
  src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, feature: frontend 🖌️

#4010 [PoC] [WIP] Matterbridge integration
  appinfo/info.xml
  appinfo/routes.php
  css/settings-admin.scss
  img/bridge-bot.png
  lib/Controller/MatterbridgeController.php
  lib/Controller/MatterbridgeSettingsController.php
  lib/Controller/PageController.php
  lib/Exceptions/ImpossibleToKillException.php
  lib/MatterbridgeManager.php
  lib/Migration/Version10000Date20200819121721.php
  lib/Settings/Admin/AdminSettings.php
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/RightSidebar/Matterbridge/BridgePart.vue
  src/components/RightSidebar/Matterbridge/MatterbridgeSettings.vue
  src/components/RightSidebar/RightSidebar.vue
  src/services/matterbridgeService.js
  src/views/AdminSettings.vue
  tests/php/Settings/Admin/AdminSettingsTest.php
Labels: 2. developing, enhancement, feature: integration 📦, integration

#4056 Fix search anchor
  lib/Search/MessageSearch.php
Labels: 3. to review, bug, feature: search 🔎

#4058 Conversations list auto scrolling
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, feature: frontend 🖌️

#4059 Fix pagination of message search
  lib/Search/CurrentMessageSearch.php
  lib/Search/MessageSearch.php
Labels: 3. to review, bug, feature: search 🔎

#3814 Add abilitiy to select localvideo
  src/components/CallView/CallView.vue
Labels: 3. to review, enhancement, feature: call 👥, feature: frontend 🖌️

#4016 Show the status on avatars
  css/At.scss
  package-lock.json
  package.json
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/AvatarWrapper/AvatarWrapperSmall.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Video.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
  src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/LoadingParticipant.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4061 Bugfix/noid/fix buttons
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
Labels: 2. developing

#4062 Bump @nextcloud/vue-dashboard to 0.1.8
  package-lock.json
  package.json
Labels: 3. to review, bug

#4063 Do not show the status in the new group conversation flow
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug

#3882 Prevent infinite loop in datachannel open re-transmission
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, bug, feature: WebRTC 🚡

#4067 Add changelog for 10.0.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#4068 Get rid of "hark" data channel
  src/utils/webrtc/simplewebrtc/webrtc.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, feature: WebRTC 🚡, feature: call 👥

#4071 Make sidebars' captions bold
  src/components/Caption.vue
Labels: 3. to review, bug

#3931 Add scroll to bottom button
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/Video.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/UploadEditor.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#4081 Fix button color with bright primary color
  src/components/MessagesList/MessagesList.vue
  src/components/TopBar/CallButton.vue
Labels: 3. to review, bug, design
