Repository nextcloud/spreed, pull requests merged in 2020-07, with the labels that each got.

#3591 "409 Conflict" on joining a second time in the same conversation
  appinfo/routes.php
  docs/participant.md
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Room.php
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/TopBar/CallButton.vue
  src/mixins/duplicateSessionHandler.js
  src/mixins/isInCall.js
  src/router/router.js
  src/services/SessionStorage.js
  src/services/participantsService.js
  src/store/participantsStore.js
  src/utils/signaling.js
  src/views/MainView.vue
  src/views/SessionConflictView.vue
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#3822 Services: Start room service
  lib/Command/Room/Create.php
  lib/Command/Room/TRoomCommand.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Service/RoomService.php
  tests/php/Command/Room/AddTest.php
  tests/php/Command/Room/CreateTest.php
  tests/php/Command/Room/DeleteTest.php
  tests/php/Command/Room/DemoteTest.php
  tests/php/Command/Room/PromoteTest.php
  tests/php/Command/Room/RemoveTest.php
  tests/php/Command/Room/UpdateTest.php
  tests/php/Controller/RoomControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Service/RoomServiceTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, feature: api 🛠️, technical debt

#3863 Fix logout failure if active session was removed from room
  lib/Listener/BeforeUserLoggedOutListener.php
Labels: 4. to release, backport-request, bug, feature: api 🛠️

#3869 [stable19] Fix logout failure if active session was removed from room
  lib/Listener.php
Labels: 3. to review, backport-request, bug

#3865 Run server's build/image-optimization.sh on this repo
  docs/HPB-P2P.svg.png
  docs/chat.png
  docs/screensharing.png
  docs/video-verfication.png
  img/app-dark.png
  img/app-dark.svg
  img/app.svg
  img/bell-outline.svg
  img/changelog.svg
  img/clip-add-file.svg
  img/emoji-smile.svg
  img/favicon-mask.svg
  img/favicon-touch.svg
  img/favicon.svg
  img/grid-view.svg
  img/lobby.svg
  img/menu-people.svg
  img/no-password.svg
  img/reply.svg
  img/share-window.svg
Labels: 3. to review, technical debt

#3872 Document system requirements
  docs/system-requirements.md
  mkdocs.yml
Labels: 3. to review, bug, technical debt

#3885 Correctly initialise blur in chrome/chromium
  src/components/CallView/shared/VideoBackground.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#3889 Add documentation about call experience
  docs/call-experience.md
  mkdocs.yml
Labels: 3. to review, technical debt

#3839 Warn user on high load
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
  src/utils/webrtc/analyzers/AverageStatValue.js
  src/utils/webrtc/analyzers/CallAnalyzer.js
  src/utils/webrtc/analyzers/ParticipantAnalyzer.js
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, enhancement, feature: call 👥, feature: frontend 🖌️

#3911 Fix duplicated event listeners in ParticipantAnalyzer
  src/utils/webrtc/analyzers/ParticipantAnalyzer.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#3909 Use new BeforeTemplateRenderedEvent for share template loading
  lib/AppInfo/Application.php
  lib/PublicShare/TemplateLoader.php
  lib/PublicShareAuth/TemplateLoader.php
Labels: 3. to review, feature: frontend 🖌️, feature: talk-sidebar ⬅️, technical debt

#3912 Do not reuse media constraints between independent media requests
  src/components/CallView/shared/LocalVideo.vue
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#3901 Don't trimm displayname in selection
  src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#3907 Dedicated connection warning icon
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
Labels: 3. to review, enhancement, feature: call 👥, feature: frontend 🖌️

#3925 [stable18] Bump @juliushaertl/vue-richtext from 0.3.0 to 0.3.2
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#3926 [stable18] Do not reuse media constraints between independent media requests
  src/components/CallView/LocalVideo.vue
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#3899 [stable18] Warn user on high load
  package-lock.json
  package.json
  src/components/CallView/LocalMediaControls.vue
  src/components/CallView/LocalVideo.vue
  src/utils/webrtc/analyzers/AverageStatValue.js
  src/utils/webrtc/analyzers/CallAnalyzer.js
  src/utils/webrtc/analyzers/ParticipantAnalyzer.js
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/webrtc.js
  webpack.common.js
Labels: 3. to review, enhancement, feature: call 👥, feature: frontend 🖌️

#3927 Changelog of july 21 updates
  CHANGELOG.md
Labels: 3. to review, backport-request, overview

#3938 bump @nextcloud/vue
  package-lock.json
  package.json
Labels: 3. to review

#3936 Fix wrong argument in the upload store
  src/store/fileUploadStore.js
Labels: 3. to review, bug

#3944 Fix spinner position
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, regression

#3864 Feature/3423/show upload progress
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/store/fileUploadStore.js
  src/store/messagesStore.js
  src/utils/fileUpload.js
  src/utils/temporaryMessage.js
Labels: 3. to review, enhancement, feature: frontend 🖌️

#3941 Display multiple simultaneous uploads
  src/store/fileUploadStore.js
  src/utils/fileUpload.js
Labels: 4. to release, enhancement, feature: frontend 🖌️

#3940 Fix speaker promotion with newer Janus versions
  src/utils/webrtc/models/CallParticipantModel.js
Labels: 3. to review, backport-request, bug, feature: WebRTC 🚡, feature: call 👥

#3948 Handle referenceId for system messages e.g. when uploading a file
  lib/Chat/ChatManager.php
  lib/Chat/SystemMessage/Listener.php
  src/services/filesSharingServices.js
  src/utils/fileUpload.js
  src/utils/temporaryMessage.js
Labels: 4. to release, bug, feature: chat 💬, feature: upload & shares 📤

#3910 Presort the mention suggestions to fix postgres integration tests
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
Labels: 4. to release, technical debt

#3743 Defer sending the notifications when we interact multiple times
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Controller/PageController.php
  lib/Notification/Listener.php
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, enhancement, technical debt

#3956 Use `babel-loader-exclude-node-modules-except`
  package-lock.json
  package.json
  webpack.common.js
Labels: 3. to review, javascript, technical debt

#3958 Fix opacity of offline-user avatar menu
  src/components/AvatarWrapper/AvatarWrapper.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#3961 Make IE11 render the page again
  webpack.common.js
Labels: 3. to review, bug, feature: frontend 🖌️

#3953 Always allow local HPBs
  lib/Controller/SignalingController.php
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: signaling 📶
