Repository nextcloud/spreed, pull requests merged in 2021-12, with the labels that each got.

#6634 Fix devices not released when got after the dialog was closed
  src/mixins/devices.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6641 Await adding the participant before updating the user status
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/store/participantsStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6645 Reduce filecache hits for Talk/ folder creation
  lib/TInitialState.php
Labels: 4. to release, backport-request, technical debt

#6644 Expose message id for desktop client and notifications quick reply
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, feature: chat 💬, technical debt

#6555 l10n: Add dot to the end of the sentence
  src/components/AdminSettings/WebServerSetupChecks.vue
Labels: 4. to release, bug, feature: frontend 🖌️

#6652 Disable emoji picker in locked conversations
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#6640 Add command to remove users from all rooms
  appinfo/info.xml
  lib/Command/User/Remove.php
  lib/Listener/UserDeletedListener.php
  lib/Manager.php
  tests/integration/features/command/user-remove.feature
  tests/psalm-baseline.xml
Labels: 4. to release, feature: bots & commands 🤖, php

#6661 Replace deprecated method
  composer.lock
  lib/Activity/Listener.php
  lib/AppInfo/Application.php
  lib/Chat/Changelog/Listener.php
  lib/Chat/Command/Listener.php
  lib/Chat/Parser/Listener.php
  lib/Chat/SystemMessage/Listener.php
  lib/Collaboration/Resources/Listener.php
  lib/Files/Listener.php
  lib/Listener/RestrictStartingCalls.php
  lib/Notification/Listener.php
  lib/Share/Listener.php
  lib/Share/RoomShareProvider.php
  lib/Signaling/Listener.php
  tests/php/Activity/SettingTest.php
  tests/php/ConfigTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Signaling/BackendNotifierTest.php
  tests/psalm-baseline.xml
Labels: 4. to release, php

#6664 Reduce psalm info
  lib/BackgroundJob/RetryJob.php
  lib/Chat/AutoComplete/Sorter.php
  lib/Chat/Command/Executor.php
  lib/Chat/Parser/UserMention.php
  lib/Config.php
  lib/Events/GetTurnServersEvent.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Migration/Version2001Date20170707115443.php
  lib/Model/SessionMapper.php
  lib/Settings/Admin/AdminSettings.php
  tests/php/Federation/FederationTest.php
Labels: 3. to review, php

#6625 Recognize voice messages, object and file shares as unread messages
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Chat/MessageParser.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/unread-messages.feature
  tests/php/Chat/ChatManagerTest.php
Labels: 4. to release, backport-request, bug, feature: chat 💬

#6667 Bump behat
  tests/integration/composer.json
  tests/integration/composer.lock
Labels: 3. to review, php

#6668 Add changelog for 11.3.4 and 12.2.2
  CHANGELOG.md
Labels: 3. to review, backport-request, technical debt

#6671 Release 12.2.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#6672 Release 11.3.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#6674 Make conversation settings scrollable
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, backport-request, bug, high, feature: settings ⚙️, feature: frontend 🖌️

#6687 Fix output track when disabling virtual background
  src/utils/media/pipeline/TrackSourceMixin.js
  src/utils/media/pipeline/VirtualBackground.js
  src/utils/media/pipeline/VirtualBackground.spec.js
Labels: 4. to release, backport-request, bug, feature: frontend 🖌️

#6686 Use something more stable so we don't toggle the chatIdentifier when …
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#6690 Fix unsubscribing listener for status updates
  src/components/MessagesList/MessagesList.vue
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️

#6649 Improve grid pagination buttons
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#6693 [stable23] Fix unsubscribing listener for status updates
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, bug, regression, feature: frontend 🖌️

#6699 Add changelog for 13.0.1
  CHANGELOG.md
Labels: 3. to review, backport-request

#6694 Restore default terser config and get mapfiles back
  webpack.js
Labels: 3. to review, backport-request, technical debt

#6704 Fix enabling background blur when input track is disabled
  src/utils/media/pipeline/VirtualBackground.js
  src/utils/media/pipeline/VirtualBackground.spec.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6606 Show active in conversation status in one-on-one conversations
  src/components/ConversationIcon.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/TopBar/TopBar.vue
  src/mixins/getParticipants.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#6701 Allow joining open conversations with passwords
  lib/Service/ParticipantService.php
  tests/integration/features/conversation/join-listable.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#6716 Prevent handleScroll on initial loading of a conversation
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, high, feature: chat 💬, feature: frontend 🖌️, performance 🚀

#6707 Fix signaling events roomlist
  lib/Room.php
  lib/Signaling/Listener.php
  src/utils/signaling.js
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, backport-request, bug, high, feature: signaling 📶, deployed on testing, performance 🚀

#6713 Improve talk sounds
  img/COPYING
  img/LibremEmailNotification.ogg
  img/LibremPowerOn.ogg
  img/LibremTextMessage.ogg
  img/LibremVideoCall.ogg
  img/join_call.ogg
  img/leave_call.ogg
  src/utils/sounds.js
Labels: 3. to review, backport-request, feature: frontend 🖌️

#6721 FIx path to files
  src/utils/sounds.js
Labels: 3. to review, bug, regression, feature: call 👥
