Repository nextcloud/spreed, pull requests merged in 2021-04, with the labels that each got.

#5445 Notnull Boolean fields break oracle
  lib/Migration/Version10000Date20201015134000.php
  lib/Migration/Version12000Date20210401124139.php
Labels: 3. to review, bug

#5453 Don't fail loading the store when some initial states are not there
  src/services/settingsService.js
  src/store/fileUploadStore.js
  src/store/helper.js
  src/store/settingsStore.js
  src/store/soundsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: settings ⚙️

#5454 Handle failed server responses more gracefully
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/ConversationSettings/DangerZone.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/services/conversationsService.js
  src/services/filesSharingServices.js
  src/services/participantsService.js
  src/utils/signaling.js
Labels: 4. to release, backport-request, bug, feature: frontend 🖌️

#5455 [stable21.1] Handle failed server responses more gracefully
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/services/conversationsService.js
  src/services/filesSharingServices.js
  src/services/participantsService.js
  src/utils/signaling.js
Labels: 3. to review, bug

#4810 Sync group members with conversation participants
  lib/AppInfo/Application.php
  lib/Collaboration/Collaborators/Listener.php
  lib/Command/Room/TRoomCommand.php
  lib/Controller/RoomController.php
  lib/Listener/GroupMembershipListener.php
  lib/Manager.php
  lib/Model/Attendee.php
  lib/Service/ParticipantService.php
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/constants.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/command/create.feature
  tests/integration/features/conversation/add-participant.feature
  tests/integration/features/conversation/group-participants.feature
Labels: 3. to review, enhancement, feature: api 🛠️

#5460 l10n: Correct spelling
  src/components/AdminSettings/HostedSignalingServer.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
Labels: 4. to release

#5469 Changelog for 11.2.0, 11.1.2, 10.1.4 and 10.0.7
  CHANGELOG.md
Labels: 4. to release, overview

#5470 [stable20] Changelog for 10.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#5471 [stable20.1] Changelog for 10.1.4 and 10.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#5472 [stable21] Changelog for 11.1.2, 10.1.4 and 10.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#5473 [stable21.1] Changelog for 11.2.0, 11.1.2, 10.1.4 and 10.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#5476 Issue templates | Add empty line to details blocks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/issue_template.md
Labels: 3. to review, bug

#4246 Allow to mention groupfolder users in file chats
  lib/Controller/FilesIntegrationController.php
  lib/Files/Listener.php
  lib/Files/Util.php
  psalm.xml
  tests/integration/features/chat/mentions.feature
  tests/integration/features/conversation/files.feature
  tests/php/Files/UtilTest.php
Labels: 3. to review, bug, feature: chat 💬, feature: talk-sidebar ⬅️

#5459 Log conversation deletions in the audit.log
  composer.lock
  lib/Manager.php
  lib/Room.php
  tests/php/RoomTest.php
Labels: 3. to review, enhancement, feature: api 🛠️

#5482 Fix raised hand detection for multiple session, adjusted participant list response
  docs/participant.md
  lib/Controller/RoomController.php
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/store/callViewStore.js
  src/store/conversationsStore.js
Labels: 3. to review, bug

#5483 Remove deleted groups from settings
  lib/AppInfo/Application.php
  lib/Listener/GroupDeletedListener.php
  lib/Settings/Admin/AdminSettings.php
Labels: 3. to review, bug, feature: settings ⚙️

#5484 Fix flickering of description overflow when switching between one-to-…
  src/components/RightSidebar/Description/Description.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5485 Disable avatar menu in messages as guest
  src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
Labels: 3. to review, bug, feature: chat 💬

#5487 Reset page title when not found
  src/App.vue
Labels: 3. to review, bug

#5488 Make tooltips work in fullscreen mode
  src/main.js
Labels: 3. to review, bug

#5501 l10n: Change to capital letter
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5505 Add more varied JS test cases
  .github/workflows/jest.yml
  jest.config.js
  package-lock.json
  package.json
  src/__mocks__/axios.js
  src/services/conversationsService.js
  src/services/conversationsService.spec.js
  src/store/actorStore.spec.js
  src/test-setup.js
Labels: technical debt

#5507 No actions on temporary messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5508 Added more JS tests for services
  src/services/filesSharingServices.js
  src/services/filesSharingServices.spec.js
  src/services/messagesService.js
  src/services/messagesService.spec.js
  src/services/participantsService.js
Labels: 3. to review, technical debt

#5516 Fix missing screenshare icon
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#5506 Show an error when sharing fails
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/fileUploadStore.js
Labels: 3. to review, bug, feature: frontend 🖌️

#5519 Fix loading the correct sound setting for users
  src/components/SettingsDialog/SettingsDialog.vue
  src/store/fileUploadStore.js
  src/store/soundsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: settings ⚙️

#5512 More JS tests for stores
  jest.config.js
  package-lock.json
  package.json
  src/store/callViewStore.spec.js
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
  src/store/index.js
  src/store/storeConfig.js
Labels: 3. to review, technical debt

#5521 Always group system messages, independent from author
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5532 Remove play button in reply to for video previews
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, bug, design

#5528 Fix cancelling postNewMessage
  src/services/messagesService.js
  src/services/messagesService.spec.js
Labels: 3. to review, bug

#5530 Register visibility observer in all entry points
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
Labels: 3. to review, bug

#5531 Decouple fileupload and createTemporaryMessage from the global store module
  src/components/ChatView.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/UploadEditor.vue
  src/store/fileUploadStore.js
  src/store/messagesStore.js
  src/utils/fileUpload.js
  src/utils/temporaryMessage.js
Labels: 3. to review, technical debt

#5533 Fix sorting of users that are online with user status offline
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5524 Remove store usage in settingsService
  src/services/settingsService.js
  src/store/soundsStore.js
Labels: 3. to review, technical debt

#5529 Decouple participantsService from the store
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/mainFilesSidebarLoader.js
  src/services/participantsService.js
  src/store/participantsStore.js
Labels: 3. to review, technical debt

#5537 Fix discard upload call + naming tweaks
  src/store/fileUploadStore.js
Labels: 3. to review, bug

#5539 Don't allow to manually interact with the bridge bot user
  lib/Collaboration/Collaborators/Listener.php
  lib/Command/Room/TRoomCommand.php
  lib/Controller/RoomController.php
  lib/MatterbridgeManager.php
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/constants.js
Labels: 3. to review, bug, feature: integration 📦

#5522 More JS store tests featuring fileUploadStore and a few simple ones
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  src/store/fileUploadStore.spec.js
  src/store/guestNameStore.spec.js
  src/store/newGroupConversationStore.js
  src/store/newGroupConversationStore.spec.js
  src/store/quoteReplyStore.spec.js
  src/store/sidebarStore.spec.js
  src/test-setup.js
Labels: 4. to release, technical debt

#5544 Fix "dipatch" typo
  src/store/participantsStore.js
Labels: 3. to review, bug, high, regression
