Repository nextcloud/spreed, pull requests merged in 2021-10, with the labels that each got.

#6319 Fix null stream given to RTCPeerConnection.addTrack
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, backport-request, bug, feature: WebRTC 🚡, feature: frontend 🖌️, feature: call 👥

#6320 Extract common emitter code to mixin
  src/utils/EmitterMixin.js
  src/utils/webrtc/MediaDevicesManager.js
  src/utils/webrtc/analyzers/CallAnalyzer.js
  src/utils/webrtc/analyzers/ParticipantAnalyzer.js
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
  src/utils/webrtc/models/CallParticipantCollection.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/models/LocalMediaModel.js
Labels: 3. to review, feature: frontend 🖌️, feature: call 👥

#6324 [stable22.1] Fix null stream given to RTCPeerConnection.addTrack
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 4. to release, backport-request, bug

#6325 [stable22] Fix null stream given to RTCPeerConnection.addTrack
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, bug

#6326 [stable21] Fix null stream given to RTCPeerConnection.addTrack
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, bug

#6327 [stable20] Fix null stream given to RTCPeerConnection.addTrack
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, bug

#6303 Don't allow to get pushes for Talk activity
  lib/Activity/Setting.php
Labels: 3. to review, backport-request, bug

#6300 Ignore sessions older than 30 seconds on notifications again
  lib/Chat/Notifier.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Model/Session.php
  lib/Service/ParticipantService.php
  tests/php/Chat/NotifierTest.php
Labels: 4. to release, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: call 👥

#6105 Add sending room shares support
  lib/BackgroundJob/RetryJob.php
  lib/Chat/Notifier.php
  lib/Controller/RoomController.php
  lib/Exceptions/CannotReachRemoteException.php
  lib/Exceptions/RoomHasNoModeratorException.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/FederationManager.php
  lib/Federation/Notifications.php
  lib/Manager.php
  lib/Model/AttendeeMapper.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  tests/php/Federation/FederationTest.php
Labels: 4. to release, enhancement, feature: federation 🌐

#6215 🖥️ Device check screen
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareSidebar.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/DeviceChecker/DeviceChecker.vue
  src/components/MediaDevicesPreview.vue
  src/components/MediaDevicesSelector.vue
  src/components/TopBar/CallButton.vue
  src/components/VolumeIndicator/VolumeIndicator.vue
  src/mixins/devices.js
Labels: 3. to review, enhancement, feature: call 👥

#6329 [stable22.1] Ignore sessions older than 30 seconds on notifications again
  lib/Chat/Notifier.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Model/Session.php
  lib/Service/ParticipantService.php
  tests/php/Chat/NotifierTest.php
Labels: 3. to review, bug, feature: chat 💬, feature: api 🛠️, feature: call 👥

#6308 Implement remove file room of removed file
  lib/BackgroundJob/RemoveEmptyRooms.php
  tests/php/BackgroundJob/RemoveEmptyRoomsTest.php
Labels: 3. to review, bug, enhancement, feature: api 🛠️

#6332 Bump psalm version
  composer.json
  composer.lock
  psalm.xml
  tests/psalm-baseline.xml
Labels: 4. to release, enhancement, feature: api 🛠️

#6405 Always allow guests to start a call in video verification
  lib/Listener/RestrictStartingCalls.php
  tests/php/Listener/RestrictStartingCallsTest.php
Labels: 3. to review, bug, feature: talk-sidebar ⬅️
