Repository nextcloud/spreed, pull requests merged in 2021-02, with the labels that each got.

#5057 Allow to post in completely empty chats
  src/store/messagesStore.js
Labels: 3. to review, bug, feature: chat 💬

#5052 Allow resending invitation emails
  appinfo/routes.php
  docs/participant.md
  lib/Controller/RoomController.php
  lib/GuestManager.php
  lib/Service/ParticipantService.php
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/constants.js
  src/services/participantsService.js
  src/store/participantsStore.js
Labels: 3. to review, enhancement, feature: chat 💬

#5059 Bring up the "new group conv" dialog for group results
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 4. to release, backport-request, bug, feature: frontend 🖌️

#5019 Allow other apps to register message actions
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/init.js
  src/main.js
  src/mainFilesSidebar.js
  src/mainFilesSidebarLoader.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/store/index.js
  src/store/messageActionsStore.js
Labels: 2. developing, feature: frontend 🖌️

#4861 Delete chat messages
  appinfo/routes.php
  docs/capabilities.md
  docs/chat.md
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Parser/Listener.php
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/ChatController.php
  lib/Model/Message.php
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
  src/services/messagesService.js
  src/store/messagesStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/delete.feature
  tests/php/CapabilitiesTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 4. to release, design, enhancement

#5063 Update favorite dark icon
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 4. to release, backport-request, bug, design, feature: frontend 🖌️

#5071 Fix new conversation dialog when no item is selected
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, regression

#5034 Allow to share RichObjects to chats
  appinfo/routes.php
  docs/capabilities.md
  docs/chat.md
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/ChatController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/rich-object-share.feature
  tests/php/CapabilitiesTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 4. to release, enhancement, feature: chat 💬, feature: upload & shares 📤

#5075 Improve deleted messages look
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, design, enhancement, feature: frontend 🖌️

#5076 Fix "Talk/ folder not working for attachments"
  appinfo/info.xml
Labels: 3. to review, backport-request, bug, feature: upload & shares 📤

#5058 Replace call icons in buttons bar with material design icons
  css/icons.scss
  src/PublicShareAuthRequestPasswordButton.vue
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/MediaDevicesPreview.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, design, feature: call 👥

#5065 Fix forced active action looks
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, bug, design

#5061 Fix unwanted background changes in some buttons
  .github/workflows/phpunit.yml
  src/App.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, design

#5086 Add support for "turns:" scheme
  lib/Config.php
  lib/Controller/SignalingController.php
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/TurnServers.vue
  tests/php/ConfigTest.php
Labels: 3. to review, backport-request, bug, feature: call 👥

#5081 Drone set CORE_BRANCH to stable21
  .drone.yml
Labels: 3. to review

#5098 [stable21] Explcitly install gd and zip PHP extensions in CI
  .github/workflows/phpunit.yml
Labels: 3. to review

#5072 [stable21] Fix find-listed integration test outline
  tests/integration/features/conversation/find-listed.feature
Labels: 4. to release

#5103 Split reporting of candidates by protocol
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️

#5102 [stable20.1] Fix local video not shown in grid view
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️, regression

#5101 Prevent current page in grid to become negative
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️, regression

#4535 Add upload editor in files sidebar mode
  src/FilesSidebarTabApp.vue
  src/components/UploadEditor.vue
  src/store/fileUploadStore.js
Labels: 2. developing, backport-request, bug, feature: talk-sidebar ⬅️, regression

#5074 Improve deck card UI
  src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#5121 Run all tests on info.xml modifications
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
Labels: 3. to review, backport-request, technical debt

#5122 Fix sharing tests to work with attachment folders fix
  tests/integration/features/sharing/get.feature
  tests/integration/features/sharing/hooks.feature
  tests/integration/features/sharing/move.feature
  tests/integration/features/sharing/restore.feature
  tests/integration/features/sharing/update.feature
Labels: 3. to review, backport-request, bug, high

#5129 Provide information for incoming call screens
  appinfo/info.xml
  lib/Activity/Listener.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version11001Date20210211111527.php
  lib/Model/SelectHelper.php
  lib/Room.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/group.feature
  tests/php/RoomTest.php
Labels: 3. to review, bug, feature: api 🛠️, feature: call 👥

#5119 Store and use display name from attendees table
  lib/AppInfo/Application.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Listener/UserDisplayNameListener.php
  lib/Service/ParticipantService.php
Labels: 3. to review, enhancement, feature: api 🛠️

#5118 Show "Guest" instead of session hash for guests
  lib/Controller/CallController.php
  src/components/CallView/shared/Video.vue
Labels: 4. to release, backport-request, bug, feature: call 👥

#5105 Make sure that project resources scripts event is properly emitted
  lib/Controller/PageController.php
  templates/index.php
Labels: 4. to release, backport-request, bug

#5135 Populate the display name when adding logged in users
  lib/Chat/Notifier.php
  lib/Command/Room/TRoomCommand.php
  lib/Controller/RoomController.php
  lib/Files/Listener.php
  lib/Manager.php
  lib/MatterbridgeManager.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  tests/php/Service/RoomServiceTest.php
Labels: 3. to review, bug, feature: api 🛠️

#5137 Reuse attendee for guests
  lib/Activity/Listener.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Model/AttendeeMapper.php
  lib/Room.php
  lib/Service/ParticipantService.php
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/components/Quote.vue
  src/components/SetGuestUsername.vue
  src/store/actorStore.js
  src/utils/temporaryMessage.js
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, enhancement, feature: api 🛠️

#5145 Add guests app in CI runs that need it
  .drone.yml
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
Labels: 3. to review, backport-request, bug, high

#5136 Add a repair step that updates the display name for existing users
  appinfo/info.xml
  lib/Migration/CacheUserDisplayNames.php
Labels: 4. to release, enhancement, feature: api 🛠️

#5149 Changelog for 11.0.0-RC1
  CHANGELOG.md
Labels: 3. to review, backport-request

#5153 Close left sidebar menu after leave or delete
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, backport-request, bug

#5157 Fix IE11
  webpack.common.js
Labels: 3. to review, backport-request, high, regression

#5161 Sort alphabetically
  webpack.common.js
Labels: 3. to review

#4934 Update the left sidebar design
  src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, design, feature: frontend 🖌️

#5110 Add sharing deck card with a conversation
  lib/AppInfo/Application.php
  lib/Deck/DeckPluginLoader.php
  src/collections.js
  src/deck.js
  src/main.js
  src/services/messagesService.js
  src/views/RoomSelector.vue
  webpack.common.js
Labels: 4. to release, enhancement

#5171 [stable20.1] Retrigger full CI when drone.yml was changed
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
Labels: 3. to review, backport-request, bug

#5172 Fix js error when posting as guest
  src/components/NewMessageForm/NewMessageForm.vue
  src/services/participantsService.js
  src/store/messagesStore.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#5178 Fix missing delete icon
  css/icons.scss
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#5146 Store guest display names on attendees
  appinfo/info.xml
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/MessageParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Controller/CallController.php
  lib/Controller/GuestController.php
  lib/Controller/RoomController.php
  lib/GuestManager.php
  lib/Migration/Version11000Date20201209142525.php
  lib/Migration/Version11001Date20210212105406.php
  lib/Model/Attendee.php
  lib/Model/AttendeeMapper.php
  lib/Notification/Notifier.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, feature: api 🛠️, technical debt

#5181 Help translators
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: settings ⚙️

#5185 Add docs and capability for callFlag of conversations
  docs/capabilities.md
  docs/constants.md
  docs/conversation.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#5186 Add a screenshot mode with images and fake audio/video states
  docs/screenshotplaceholders/placeholder-0.jpeg
  docs/screenshotplaceholders/placeholder-1.jpeg
  docs/screenshotplaceholders/placeholder-2.jpeg
  docs/screenshotplaceholders/placeholder-3.jpeg
  docs/screenshotplaceholders/placeholder-4.jpeg
  docs/screenshotplaceholders/placeholder-5.jpeg
  docs/screenshotplaceholders/placeholder-6.jpeg
  docs/screenshotplaceholders/placeholder-7.jpeg
  docs/screenshotplaceholders/placeholder-8.jpeg
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, technical debt

#5189 Limit the session list on the database instead of selecting all attendees
  lib/Controller/CallController.php
  lib/Service/ParticipantService.php
Labels: 3. to review, bug, feature: api 🛠️

#5191 Fix API documentation
  docs/call.md
  docs/chat.md
  docs/constants.md
  docs/conversation.md
  docs/internal-signaling.md
  docs/participant.md
  docs/settings.md
  docs/webinar.md
  lib/Controller/RoomController.php
  mkdocs.yml
Labels: 3. to review, feature: api 🛠️, technical debt

#5190 Update Room object last message after setting
  lib/Room.php
Labels: 3. to review, bug

#5196 Sort by isFavorite and lastActivity instead of lastPing
  docs/conversation.md
Labels: 4. to release, technical debt

#5198 Prevent loading old messages twice on scroll
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug

#5212 Replace all message parameters and not only the last one
  lib/Search/MessageSearch.php
Labels: 4. to release, backport-request, bug, feature: search 🔎

#5213 Drop guest moderators when changing a conversation to group conversation
  lib/Room.php
Labels: 4. to release, bug, feature: api 🛠️

#5210 Changelog for 11.0 and 11.1
  CHANGELOG.md
  docs/capabilities.md
Labels: 3. to review, technical debt

#5232 Add changelog for 9.0.8, 10.0.6 and 10.1.2
  CHANGELOG.md
Labels: 3. to review, technical debt

#5236 Revert "Split reporting of candidates by protocol"
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, bug, feature: WebRTC 🚡, regression

#5237 Revert "[stable21] Split reporting of candidates by protocol"
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, bug, feature: WebRTC 🚡, regression

#5235 [stable19] Add changelog for 9.0.9
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5234 [stable20] Add changelog for 9.0.8 and 10.0.6
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5233 [stable20.1] Add changelog for 9.0.8, 10.0.6 and 10.1.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5239 Adjust screenshoting
  CHANGELOG.md
  README.md
  appinfo/info.xml
  docs/call-in-action.jpg
  docs/call-in-action.png
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, technical debt

#5242 Try to catch the unique constraint violation on migrating the data
  lib/Migration/Version10000Date20201015134000.php
Labels: 3. to review, backport-request, bug

#5246 [stable20] Fix toast timeout
  src/components/CallView/shared/LocalVideo.vue
  src/utils/webrtc/webrtc.js
Labels: 3. to review, bug, feature: frontend 🖌️

#4855 Private reply without quote
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 4. to release, design, enhancement

#5255 l10n: Delete space
  src/components/LeftSidebar/NewGroupConversation/SetConversationType/SetConversationType.vue
Labels: 4. to release, bug

#5256 Reduce complexity for autocomplete suggestions
  lib/Command/Room/TRoomCommand.php
Labels: 4. to release, technical debt

#5257 Use addMessageForAllParticipants instead of looping manually
  lib/Signaling/Listener.php
Labels: 4. to release, feature: signaling 📶, technical debt

#5258 Base queries on sessions where it makes sense
  lib/Controller/SignalingController.php
  lib/Service/ParticipantService.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Messages.php
Labels: 4. to release, feature: signaling 📶, technical debt

#5084 Fix conversation switching lag
  src/components/ChatView.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/TopBar/CallButton.vue
  src/init.js
  src/store/tokenStore.js
Labels: 2. developing, bug, enhancement, feature: frontend 🖌️

#4935 Copy actions in conversation menu into the new conversation settings dialog
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/DangerZone.vue
  src/components/ConversationSettings/NotificationsSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/TopBar/TopBar.vue
  src/store/conversationsStore.js
Labels: 3. to review, design, feature: frontend 🖌️

#5262 Check viewer handlers before using them
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#5264 Bump @nextcloud/vue from 3.5.4 to 3.6.0
  package-lock.json
  package.json
Labels: 3. to review

#5265 Hide call icon when blocked by lobby
  lib/Controller/RoomController.php
Labels: 3. to review, bug
