Repository nextcloud/spreed, pull requests merged in 2021-05, with the labels that each got.

#5542 Make sure the user we are testing with exists
  tests/integration/features/conversation-2/set-description.feature
Labels: 4. to release

#5541 Fix conversation search focus
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5550 Fix quality warning tooltip not staying dismissed
  src/components/CallView/shared/LocalMediaControls.vue
  src/store/callViewStore.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5551 Fix initial camera quality
  src/utils/webrtc/VideoConstrainer.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5538 Only show public messages as last messages
  lib/Chat/ChatManager.php
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/store/conversationsStore.js
Labels: 3. to review, bug, feature: chat 💬

#5561 Allow to copy the link of an open conversation
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 4. to release, backport-request, bug, feature: frontend 🖌️

#5526 Decouple conversations and messages services from the global store
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/services/conversationsService.js
  src/services/messagesService.js
  src/store/conversationsStore.js
  src/store/messagesStore.js
  src/store/talkHashStore.js
Labels: 4. to release, technical debt

#5543 Add test for participants store
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
Labels: 3. to review, technical debt

#5564 Added talk hash store and fetchConversations tests
  src/store/conversationsStore.spec.js
  src/store/talkHashStore.spec.js
Labels: 3. to review, technical debt

#5560 Remove old firefox screenshare fallback and allow to see other screens
  README.md
  appinfo/info.xml
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#5567 Added tests for RoomSelector
  src/test-setup.js
  src/views/RoomSelector.spec.js
  src/views/RoomSelector.vue
Labels: 3. to review, technical debt

#5569 [stable21.1] Fix sorting of users that are online with user status offline
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5520 Disable use of deprecated "Plan-B" semantics if HPB is used.
  src/utils/webrtc/webrtc.js
Labels: 3. to review, client: 🤖🍏 mobile, feature: WebRTC 🚡, feature: call 👥

#5574 Add changelog for 11.2.1
  CHANGELOG.md
Labels: 4. to release, backport-request, technical debt

#5565 Added JS tests for messages store
  src/components/NewMessageForm/NewMessageForm.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, technical debt

#5577 Update list of system messages
  docs/chat.md
  lib/Chat/Parser/SystemMessage.php
Labels: 3. to review, bug

#5579 Fix switching devices in Firefox
  src/utils/webrtc/MediaDevicesManager.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#5584 Remove the description from the system message
  docs/chat.md
  lib/Chat/Parser/SystemMessage.php
  tests/integration/features/conversation/lobby.feature
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, bug, feature: chat 💬

#5585 Add versions to API docs (sorry for cleaning up)
  docs/call.md
  docs/chat.md
  docs/conversation.md
  docs/integration.md
  docs/internal-signaling.md
  docs/participant.md
  docs/settings.md
  docs/webinar.md
  lib/Controller/RoomController.php
Labels: 3. to review, technical debt

#5592 Add geo-location-sharing capability
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: upload & shares 📤

#5503 Provide multiple STUN servers to webrtc client
  lib/Config.php
  lib/Controller/SignalingController.php
  tests/php/ConfigTest.php
Labels: 4. to release, client: 🤖🍏 mobile, enhancement, feature: WebRTC 🚡

#5491 Provide multiple TURN servers to webrtc client
  lib/Config.php
  lib/Controller/SignalingController.php
  tests/php/ConfigTest.php
Labels: 4. to release, client: 🤖🍏 mobile, enhancement, feature: WebRTC 🚡

#5570 JS tests for Message component
  jest.config.js
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/test-setup.js
Labels: 3. to review, technical debt

#5573 Location sharing frontend
  lib/Controller/PageController.php
  lib/Listener/CSPListener.php
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue
  src/main.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
Labels: 3. to review, enhancement, feature: chat 💬

#5598 JS tests for MessagesList
  src/components/MessagesList/MessagesList.spec.js
  src/components/MessagesList/MessagesList.vue
  src/constants.js
  src/test-setup.js
Labels: 4. to release, technical debt

#5602 Fix guests without a name in system messages
  lib/Chat/Parser/SystemMessage.php
Labels: 4. to release, bug, feature: chat 💬

#5490 Fix compatibility with nextcloud-vue v4.0.0 alpha
  webpack.common.js
Labels: 3. to review, bug

#5605 Move description editor to conversation settings dialog
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/Description/Description.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, enhancement

#5608 JS tests for LeftSidebar
  jest.config.js
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, technical debt

#5632 Remove leftover routeChange handlers
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, regression

#5634 Fix expected HTTP status code for OCS 403
  tests/integration/features/sharing/create.feature
  tests/integration/features/sharing/update.feature
Labels: 3. to review, bug

#5633 Reusable user ids one to one chats
  lib/Chat/SystemMessage/Listener.php
  lib/Listener/UserDeletedListener.php
  lib/Manager.php
  lib/Room.php
  tests/integration/features/conversation/delete-user.feature
Labels: 4. to release, bug, feature: api 🛠️

#5599 Add JS tests for conversation component
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/test-setup.js
Labels: 2. developing, technical debt

#5636 Regenerate session id after entering password
  lib/Controller/PageController.php
  lib/TalkSession.php
Labels: 3. to review, backport-request, enhancement, security

#5582 Unify stun and turn server urls
  appinfo/routes.php
  docs/internal-signaling.md
  lib/Capabilities.php
  lib/Controller/SignalingController.php
  src/services/signalingService.js
  src/utils/signaling.js
  tests/php/CapabilitiesTest.php
Labels: 4. to release, client: 🤖🍏 mobile, feature: WebRTC 🚡, feature: api 🛠️, feature: settings ⚙️

#5645 Remove unused userId in Participant component
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug

#5647 Credit where credit is due
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue
Labels: 3. to review, bug, high

#5637 JS tests for Participant component
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/test-helpers.js
Labels: 3. to review, technical debt

#5648 Add Message.vue test for passing in geo-location object
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
Labels: 3. to review, technical debt

#5649 Register flow operation via dedicated event
  lib/AppInfo/Application.php
  lib/Flow/Operation.php
  lib/Flow/RegisterOperationsListener.php
Labels: 3. to review, bug

#5596 Add meaningful conversation info to topbar.
  src/App.vue
  src/assets/variables.scss
  src/components/ChatView.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/TopBar.vue
Labels: 2. developing, enhancement, feature: frontend 🖌️

#5652 Fix chatview
  src/components/ChatView.vue
Labels: 3. to review, bug, regression

#5661 Fix switching devices during a call if started without audio nor video
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5664 Force capability documentation
  docs/capabilities.md
  tests/php/CapabilitiesTest.php
Labels: 3. to review, bug, feature: api 🛠️

#5653 JS tests for FilePreview component
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/test-setup.js
Labels: 3. to review, technical debt

#5668 Don't cancel editing when clicking outside description
  src/components/Description/Description.vue
Labels: 3. to review, bug

#5673 Encode dav path segments for direct preview
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, bug

#5671 Remove groups as participants when deleted
  lib/Listener/GroupDeletedListener.php
Labels: 3. to review, bug, feature: api 🛠️

#5675 Fix raised hand handler not detached when peer is destroyed
  src/utils/webrtc/models/CallParticipantModel.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5678 Use GHCR for PHP 7.3 images
  .drone.yml
Labels: 4. to release, bug

#5686 Migrate more build images to GHCR
  .drone.yml
Labels: 3. to review

#5688 Update version to alpha 1
  appinfo/info.xml
Labels: 3. to review, technical debt

#5674 [stable21.1] Encode dav path segments for direct preview
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, bug

#5616 Allow to specify meta-data for sharing
  docs/chat.md
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  tests/psalm-baseline.xml
Labels: 2. developing, 3. to review, client: 🤖🍏 mobile, enhancement, feature: upload & shares 📤
