Repository nextcloud/spreed, pull requests merged in 2021-07, with the labels that each got.

#5905 Listen to token changes instead of conversation object
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, regression

#5902 Fix recording voice messages on Safari
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: upload & shares 📤

#5885 Fix connection quality warning shown due to stalled stats
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5903 Use extended mediarecorder
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/PageController.php
  lib/Listener/CSPListener.php
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
  src/test-setup.js
Labels: 3. to review, bug, feature: chat 💬, feature: upload & shares 📤

#5535 Add support for simulcast streams.
  src/components/CallView/CallView.vue
  src/constants.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
  src/utils/webrtc/simplewebrtc/webrtc.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, feature: WebRTC 🚡

#5913 Add changelog for 12.0.0-rc.1
  CHANGELOG.md
Labels: 3. to review, backport-request

#5924 [stable21] Fix connection quality warning shown due to stalled stats
  src/utils/webrtc/analyzers/AverageStatValue.js
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Labels: 4. to release, bug, feature: call 👥, feature: frontend 🖌️

#5939 Prevent submitting the message when the user is composing
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, bug, feature: chat 💬

#5942 Add missing import
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5936 fix links to documentation
  lib/Controller/SignalingController.php
  src/components/AdminSettings/Commands.vue
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/AdminSettings/TurnServers.vue
  src/utils/webrtc/webrtc.js
Labels: 3. to review, bug

#5926 Use memcache to save the query for unread message count
  lib/Chat/ChatManager.php
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, feature: api 🛠️, feature: chat 💬, technical debt

#5950 Fix guest avatars
  src/components/AvatarWrapper/AvatarWrapper.spec.js
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/AvatarWrapper/AvatarWrapperSmall.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️

#5954 Fix changelog, version and date for 12.0.0
  CHANGELOG.md
Labels: 3. to review, backport-request

#5956 Fix invisible emoji picker
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug

#5437 Use ListItem component
  src/components/ConversationsOptionsList.vue
  src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, technical debt

#5966 Initialize the wav encoder in the entry points instead of in the audiorecorder component
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
Labels: 3. to review, bug

#5799 Enh/noid/simplify sidebar in one to one conversations
  src/App.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#5964 Never show read marker on the very last message
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#5889 🗑️ 💬 Clear chat history - Backend
  appinfo/routes.php
  docs/chat.md
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/ChatController.php
  lib/Service/ParticipantService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/delete.feature
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/NotifierTest.php
Labels: 4. to release, backport-request, enhancement, feature: api 🛠️, feature: chat 💬

#5975 [stable22] Unshare all items directly when deleting a room
  lib/Chat/ChatManager.php
  lib/Controller/ChatController.php
  tests/integration/features/chat/delete.feature
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, bug, feature: api 🛠️

#5963 Fix read marker and counter issues with pending pages
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 4. to release, backport-request, bug, feature: chat 💬

#5945 Use visual last read message id in scroll handler
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#5982 Fix date picker z-index
  css/app.scss
Labels: 3. to review, backport-request, bug, high, regression

#5986 Fix constant names
  lib/Room.php
Labels: 3. to review, technical debt

#5985 Add "missed call" chat system message for one-to-one
  docs/chat.md
  lib/Activity/Listener.php
  lib/Chat/Parser/SystemMessage.php
Labels: 3. to review, bug, feature: call 👥

#5974 Use async import for vue component on collections entrypoint
  src/collections.js
Labels: 3. to review, enhancement

#5932 Fix initial camera quality with Chromium
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️, high

#5970 Wait for the wav encoder to be initialized before allowing recordings
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
  src/store/audioRecorderStore.js
  src/store/storeConfig.js
Labels: 3. to review, backport-request, bug

#5997 Add skip TLS option for XMPP and Rocketchat
  lib/MatterbridgeManager.php
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
Labels: 3. to review, enhancement, feature: integration 📦

#6005 Fix displaying moderation options in one-to-ones
  src/components/ConversationSettings/ConversationSettingsDialog.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: settings ⚙️

#6009 [stable22.1] "Fix" CI with mariadb
  .github/workflows/phpunit.yml
Labels: backport-request

#6011 [stable21] "Fix" CI with mariadb
  .github/workflows/phpunit.yml
Labels: 3. to review, technical debt

#6016 Add changelog for 12.0.1, 11.3.1, 10.1.5, 10.0.9
  CHANGELOG.md
Labels: 3. to review, technical debt

#6019 Add changelog for 11.3.1, 10.1.6, 10.0.9
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#6022 Fix version typo
  CHANGELOG.md
Labels: backport-request

#6020 Add changelog for 10.1.6, 10.0.9
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#6021 Add changelog for 10.0.9
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#6023 Add capability for clear history feature
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, backport-request, enhancement, feature: chat 💬

#6024 Check circles membership when trying to add
  lib/Controller/RoomController.php
  lib/Service/ParticipantService.php
  psalm.xml
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#5667 Show name for bridged messages
  docs/constants.md
  lib/Chat/MessageParser.php
  lib/Controller/ChatController.php
  lib/MatterbridgeManager.php
  lib/Model/Attendee.php
  src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
  src/components/MessagesList/MessagesList.vue
  src/constants.js
Labels: 3. to review, client: 🤖🍏 mobile, enhancement, feature: chat 💬, feature: integration 📦

#5775 Implement Recieving Room Shares
  appinfo/info.xml
  appinfo/routes.php
  lib/BackgroundJob/RemoveEmptyRooms.php
  lib/Controller/FederationController.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/FederationManager.php
  lib/Manager.php
  lib/Migration/Version13000Date20210625232111.php
  lib/Model/Attendee.php
  lib/Model/AttendeeMapper.php
  lib/Model/Invitation.php
  lib/Model/InvitationMapper.php
  lib/Model/SelectHelper.php
  lib/Notification/Notifier.php
  lib/Room.php
  lib/Service/ParticipantService.php
  psalm.xml
  tests/php/Notification/NotifierTest.php
  tests/php/RoomTest.php
Labels: 4. to release, feature: federation 🌐

#6045 Add "New in Talk" entries for version 12
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, enhancement

#6047 Clear history: front-end
  src/components/ConversationSettings/DangerZone.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Forwarder.vue
  src/services/conversationsService.js
  src/store/conversationsStore.js
  src/store/messagesStore.js
  src/views/RoomSelector.vue
Labels: 3. to review, backport-request, enhancement

#6055 Bugfix/noid/forward message followup
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Forwarder.vue
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug
