Repository nextcloud/spreed, pull requests merged in 2021-01, with the labels that each got.

#4839 Add conversation-v3 capability for API v3
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, backport-request, bug

#4867 Fix counters
  src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, bug, design

#4883 Only allow dev quality for christophwurst/nextcloud
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#4880 Fix description fade-out on dark mode
  src/components/RightSidebar/Description/Description.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4854 Remove undefined variable from spreedcheats controller cleanup
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, bug

#4870 Add capability for room descriptions
  docs/capabilities.md
  docs/conversation.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 4. to release, bug

#4889 Unregister "refreshPeerList" event when CallView is destroyed
  src/components/CallView/CallView.vue
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️, regression

#4892 Don't remove a chat when a self-joined user leaves
  lib/Controller/RoomController.php
  tests/integration/features/conversation/remove-self.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#4822 Fix loading worker on browsers without CSP "worker-src" directive
  src/utils/imageBlurrer.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, regression

#4884 Only scroll to conversations when clicking on search results/listed c…
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, design, feature: frontend 🖌️, regression

#4885 Fix always expandable descriptions
  src/components/RightSidebar/Description/Description.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4888 Do not load the blurred background source if not needed
  src/components/CallView/shared/VideoBackground.vue
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#4779 Feature/noid/center system messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
Labels: 4. to release, enhancement, feature: chat 💬, feature: frontend 🖌️

#4906 Fix settings confusion
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, design, feature: frontend 🖌️

#4905 Avoid double quotes in bridge bot app password
  lib/MatterbridgeManager.php
Labels: 4. to release, bug, feature: integration 📦

#4856 Do not load full room object for share queries
  lib/Manager.php
  lib/Share/RoomShareProvider.php
  tests/psalm-baseline.xml
Labels: 4. to release, bug

#4908 Fix call view errors
  src/components/CallView/Grid/Grid.vue
  src/store/callViewStore.js
Labels: 2. developing, bug, feature: call 👥, feature: frontend 🖌️

#4918 Update code to work with doctrine/dbal 3.0
  lib/Controller/GuestController.php
  lib/GuestManager.php
  lib/Migration/Version10000Date20200819121721.php
  lib/Migration/Version10000Date20201012144235.php
  lib/Migration/Version10000Date20201015134000.php
  lib/Migration/Version11000Date20200922161218.php
  lib/Migration/Version11000Date20201011082810.php
  lib/Migration/Version2000Date20170707093535.php
  lib/Migration/Version2001Date20170707115443.php
  lib/Migration/Version2001Date20170913104501.php
  lib/Migration/Version2001Date20170921145301.php
  lib/Migration/Version2001Date20171009132424.php
  lib/Migration/Version2001Date20171026134605.php
  lib/Migration/Version2001Date20171031102049.php
  lib/Migration/Version2001Date20180103144447.php
  lib/Migration/Version3003Date20180707222130.php
  lib/Migration/Version3003Date20180718112436.php
  lib/Migration/Version3003Date20180718133519.php
  lib/Migration/Version3003Date20180720162342.php
  lib/Migration/Version3003Date20180722152849.php
  lib/Migration/Version3003Date20180730080327.php
  lib/Migration/Version4099Date20181001123058.php
  lib/Migration/Version5099Date20190121102337.php
  lib/Migration/Version5099Date20190319134820.php
  lib/Migration/Version6099Date20190627172429.php
  lib/Migration/Version7000Date20190717141457.php
  lib/Migration/Version7000Date20190724121136.php
  lib/Migration/Version8000Date20200407115318.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#4838 Sort participants by raised hands
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/store/callViewStore.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, feature: call 👥

#4915 Changelog for 8.0.15
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#4914 Changelog for 9.0.8
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#4913 Changelog for 10.0.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#4584 New message form facelift
  src/assets/variables.scss
  src/components/ChatView.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/RightSidebar/Description/Description.vue
Labels: 3. to review, design, enhancement, feature: frontend 🖌️

#4912 Changelog for 10.1.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#4911 Changelog for 11.0.0-alpha.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#4907 Move matterbridge settings into the conversation settings dialog
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/Matterbridge/BridgePart.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#4933 No system message when a self-joined user leaves
  lib/Chat/SystemMessage/Listener.php
Labels: 3. to review, bug

#4940 Added quote border difference when own message is quoted
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/Quote.vue
Labels: 3. to review, design, enhancement, feature: chat 💬

#4942 Properly initialize descriptionText with description
  src/components/RightSidebar/Description/Description.vue
Labels: 3. to review, bug, feature: chat 💬

#4941 Allow single video in stripe if screen share in progress
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, bug, feature: call 👥

#4944 Show unread 1-1 messages in dashboard widget
  src/views/Dashboard.vue
Labels: 3. to review, feature: frontend 🖌️

#4932 Add deck cards as dedicated simple rich object string parameters
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
Labels: 3. to review, enhancement, feature: chat 💬, feature: integration 📦

#4943 Correctly use the displayname for groups in admin settings
  lib/Settings/Admin/AdminSettings.php
  src/components/AdminSettings/AllowedGroups.vue
Labels: 3. to review, bug, feature: settings ⚙️

#4948 Add an integration test for when the last moderator leaves
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/remove-self.feature
Labels: 3. to review, bug, feature: api 🛠️

#4951 Cannot disable sip
  src/components/ConversationSettings/LockingSettings.vue
  src/components/ConversationSettings/SipSettings.vue
Labels: 3. to review, backport-request, bug, feature: SFU & SIP ☎️, feature: frontend 🖌️, feature: settings ⚙️

#4952 Add mapping between Nextcloud session id and signaling server session id
  docs/standalone-signaling-api-v1.md
  lib/Signaling/BackendNotifier.php
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/webrtc.js
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, bug, feature: signaling 📶

#4954 Allow SIP dial-in in non-public conversations too
  lib/Controller/RoomController.php
  lib/Manager.php
Labels: 4. to release, backport-request, bug, feature: SFU & SIP ☎️, feature: api 🛠️

#4829 Transpile more deps for IE 11
  .github/dependabot.yml
  package-lock.json
  package.json
  webpack.common.js
Labels: 4. to release, bug

#4963 Fix dashboard for IE11
  webpack.common.js
Labels: 4. to release, bug

#4949 Delete messages from store for deleted conversation
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/store/conversationsStore.js
  src/store/messagesStore.js
Labels: 3. to review, bug

#4771 Updated wording for conversation visibility
  docs/chat.md
  lib/Chat/Parser/SystemMessage.php
  lib/TInitialState.php
  src/components/ConversationSettings/ListableSettings.vue
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 4. to release, enhancement, feature: chat 💬

#4958 Enable pagination for main grid view
  src/components/CallView/Grid/Grid.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#4968 Bump @nextcloud/vue from 3.3.2 to 3.4.0
  package-lock.json
  package.json
Labels: 3. to review

#4965 Make the dial-in info better readable
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/SipSettings.vue
  src/mixins/readableNumber.js
Labels: 3. to review, bug, feature: frontend 🖌️

#4960 Allow line breaks and links in the description
  src/components/RightSidebar/Description/Description.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#4969 Fix "user has avatar" flag set as false for default user avatars
  src/components/CallView/shared/VideoBackground.vue
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#4956 Fix display names with sip users
  lib/Controller/CallController.php
  src/components/CallView/CallView.vue
  src/components/CallView/shared/Video.vue
  src/utils/webrtc/webrtc.js
Labels: 3. to review, bug, feature: SFU & SIP ☎️, feature: call 👥

#4973 Fix open conversations heading
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug

#4977 allow some more padding for the search abort button
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 3. to review, design, feature: chat 💬, low

#4979 Fix scrolling chat when in the background
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#4978 Close at-mention dropdown on blur
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, bug, feature: chat 💬

#4976 Bump @nextcloud-vue to 3.5.1
  package-lock.json
  package.json
Labels: 3. to review

#4974 Remove "unsupported browser" warning for Opera
  README.md
  src/mixins/browserCheck.js
Labels: 4. to release, enhancement

#4987 Fix "Argument 1 passed to Room::getDisplayName() must be of the type …
  lib/Controller/RoomController.php
Labels: 4. to release, bug, deployed on testing

#4988 Fix "Undefined index: userId"
  lib/Collaboration/Resources/Listener.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#4990 Fix lobby time input
  src/components/ConversationSettings/LobbySettings.vue
Labels: 3. to review, bug, feature: chat 💬

#4980 Initial state service is deprecated
  lib/Controller/PageController.php
  lib/Files/TemplateLoader.php
  lib/PublicShare/TemplateLoader.php
  lib/PublicShareAuth/TemplateLoader.php
  lib/Settings/Admin/AdminSettings.php
  lib/TInitialState.php
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/AdminSettings/AllowedGroups.vue
  src/components/AdminSettings/Commands.vue
  src/components/AdminSettings/GeneralSettings.vue
  src/components/AdminSettings/HostedSignalingServer.vue
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/AdminSettings/SIPBridge.vue
  src/components/AdminSettings/SignalingServers.vue
  src/components/AdminSettings/StunServers.vue
  src/components/AdminSettings/TurnServers.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/ListableSettings.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/SipSettings.vue
  src/store/fileUploadStore.js
  src/store/settingsStore.js
  src/utils/webrtc/simplewebrtc/peer.js
  tests/php/Settings/Admin/AdminSettingsTest.php
Labels: 3. to review, technical debt

#4975 Allow to resend temporary messages if the failure was not permissions
  src/assets/buttons.scss
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/services/messagesService.js
  src/store/messagesStore.js
  src/utils/temporaryMessage.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#4997 New button to disable lobby in sidebar
  src/components/RightSidebar/LobbyStatus.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, feature: chat 💬

#4999 Fix local video positioning
  src/components/CallView/shared/LocalVideo.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#4991 [stable20.1] Enable pagination for main grid view
  src/components/CallView/Grid/Grid.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#5008 Bump @nextcloud-vue from 3.5.2 to 3.5.3
  package-lock.json
  package.json
Labels: 3. to review, bug, regression

#4998 Fix description icon sizes
  css/icons.scss
  src/assets/buttons.scss
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/RightSidebar/Description/Description.vue
Labels: 3. to review, bug, design, feature: frontend 🖌️

#4985 Replace blur with average color in video backgrounds
  lib/Listener/CSPListener.php
  package-lock.json
  package.json
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/Video.vue
  src/components/CallView/shared/VideoBackground.vue
  src/store/callViewStore.js
  src/utils/imageBlurrer.js
  src/utils/imageBlurrerWorker.js
  webpack.common.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5014 Bump version and add changelog
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5031 Catch upload 507 errors
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/fileUploadStore.js
Labels: 3. to review, bug, feature: upload & shares 📤

#5033 Fix capabilities checks
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug

#5035 Fix free space wording
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/fileUploadStore.js
Labels: 3. to review, bug

#5037 [stable20.1] Fix local video positioning
  src/components/CallView/shared/LocalVideo.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#5030 Add Changelog for 11
  CHANGELOG.md
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, bug, feature: chat 💬

#5038 l10n: Add word "file"
  src/store/fileUploadStore.js
Labels: 3. to review, bug

#5042 Prevent duplicate call summaries
  lib/Room.php
Labels: 3. to review, backport-request, bug, feature: call 👥

#5046 Bump @nextcloud/vue from 3.5.3 to 3.5.4 and fix scrollbar
  package-lock.json
  package.json
Labels: 3. to review, bug, regression

#5041 Mention sub name users
  lib/Chat/Parser/UserMention.php
  tests/integration/features/chat/rich-messages.feature
  tests/php/Chat/Parser/UserMentionTest.php
Labels: 4. to release, backport-request, bug, feature: chat 💬

#5040 Recreate matterbridge config file if missing when launching
  lib/MatterbridgeManager.php
Labels: 3. to review, bug, feature: integration 📦

#5036 Hide upload button with zero quota
  lib/TInitialState.php
  src/components/NewMessageForm/NewMessageForm.vue
  src/store/fileUploadStore.js
Labels: 4. to release, bug, feature: upload & shares 📤

#5015 Make background black again
  src/assets/variables.scss
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/EmptyCallView.vue
Labels: 4. to release, bug, feature: call 👥, feature: frontend 🖌️

#5017 Add hover effects for grid collapser
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️
