Repository nextcloud/spreed, pull requests merged in 2021-06, with the labels that each got.

#5695 Wait for async test functions
  src/store/participantsStore.spec.js
Labels: 4. to release, bug

#5679 Remove unneeded webrtc code
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, feature: WebRTC 🚡, feature: call 👥, feature: frontend 🖌️

#5691 Deduplicate and bug-fix circles integration
  lib/Controller/RoomController.php
  lib/Service/ParticipantService.php
  psalm.xml
Labels: 3. to review, bug, feature: integration 📦

#5697 Upload icon is now material design "attachment"
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, technical debt

#5698 Fix color of screen share menu icons
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, bug

#5702 Changelog for 11.3.0, 11.2.2, 10.1.5, 10.0.8 and 9.0.10
  CHANGELOG.md
Labels: 3. to review, technical debt

#5703 [stable21.1] Changelog for 11.3.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5704 [stable21] Changelog for 11.2.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5705 [stable20.1] Changelog for 10.1.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5706 [stable20] Changelog for 10.0.8
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#5707 [stable19] Changelog for 9.0.10
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#4686 Fix not sending signaling messages to participants without a Peer object
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
  src/utils/webrtc/simplewebrtc/webrtc.js
  src/utils/webrtc/webrtc.js
Labels: 4. to release, bug, feature: frontend 🖌️

#5716 Update API docs index.md links + extra constants
  docs/constants.md
  docs/index.md
Labels: 3. to review, technical debt

#5699 Cancel temporary messages individually and warn before leaving while sending
  src/App.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, bug

#5700 Fix call flags updates
  appinfo/routes.php
  docs/call.md
  lib/Controller/CallController.php
  lib/Room.php
  lib/Service/ParticipantService.php
  lib/Signaling/Listener.php
  src/utils/signaling.js
  src/utils/webrtc/webrtc.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/update-call-flags.feature
Labels: 4. to release, bug, feature: call 👥, feature: frontend 🖌️

#5717 Document circles too
  docs/constants.md
  docs/conversation.md
  docs/participant.md
  lib/Model/Attendee.php
  src/constants.js
Labels: 3. to review, bug, client: 🤖🍏 mobile, feature: api 🛠️

#5659 Do not add tracks for receiver only peers
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
Labels: 3. to review, bug, feature: WebRTC 🚡, feature: call 👥, feature: frontend 🖌️

#5718 Fix casing of exported initWebRTC function
  src/utils/webrtc/webrtc.js
Labels: 3. to review, technical debt

#5720 FIx "Using / for division is deprecated"
  src/assets/avatar.scss
  src/assets/variables.scss
  src/components/ConversationIcon.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/LoadingParticipant.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5719 Inviting users appear offline
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5724 Include sass explicitly
  package-lock.json
  package.json
Labels: 3. to review, bug

#5728 Set permissions on Matterbridge config and log
  lib/MatterbridgeManager.php
Labels: 3. to review, bug, feature: integration 📦

#5739 Don't show delete option for object shares
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug, client: 🤖🍏 mobile, feature: chat 💬, feature: frontend 🖌️

#5738 Fall back get participant in case session is gone
  lib/Middleware/InjectionMiddleware.php
Labels: 3. to review, backport-request, bug

#5737 Update nextcloud-vue to version 4.0.0
  jest.config.js
  package-lock.json
  package.json
  src/test-setup.js
  webpack.common.js
Labels: 3. to review, dependencies

#5741 Add voice message capability
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, bug, feature: chat 💬, feature: upload & shares 📤

#5742 Only allow audio voice messages
  lib/Chat/SystemMessage/Listener.php
Labels: 3. to review, bug, feature: chat 💬, feature: upload & shares 📤

#5744 Listed conversation search doesn't work
  src/services/conversationsService.js
Labels: 4. to release, bug, feature: frontend 🖌️, regression

#5745 Fix coding style of translations
  src/components/Description/Description.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/views/NotFoundView.vue
  src/views/SessionConflictView.vue
  src/views/WelcomeView.vue
Labels: 3. to review, bug

#5669 Display audio elements in the message list
  src/components/MessagesList/MessagesGroup/Message/MessagePart/AudioPlayer.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, bug, feature: chat 💬, feature: upload & shares 📤

#5610 Voice messages
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/UploadEditor.vue
  src/services/filesSharingServices.js
  src/store/fileUploadStore.js
  src/store/messagesStore.js
Labels: 3. to review, enhancement, feature: chat 💬, feature: upload & shares 📤

#5746 Add "Go to file" link
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, enhancement, feature: chat 💬, feature: upload & shares 📤

#5748 Fix file link for guests
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug, feature: chat 💬, feature: upload & shares 📤

#5743 Add JS test for AverageStatValue
  src/utils/webrtc/analyzers/AverageStatValue.spec.js
Labels: 3. to review, technical debt

#5750 Ignore current participant when listing rooms if removed concurrently
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug

#5760 Bump @nextcloud/vue to v4.0.1
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#5759 Allow to open files with ctrl+click
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#5736 Don't trigger leave event when deleting conversation
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, backport-request, bug

#5762 Fix newmessageform layout bug
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, regression

#5766 Fix advanced input border radius
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 4. to release, bug, design, regression

#5751 Fix connection quality stats not reset when setting a new peer connection
  src/utils/webrtc/analyzers/ParticipantAnalyzer.js
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5749 Add system messages for group attendees
  docs/chat.md
  lib/AppInfo/Application.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Events/AttendeesAddedEvent.php
  lib/Events/AttendeesEvent.php
  lib/Events/AttendeesRemovedEvent.php
  lib/Service/ParticipantService.php
  tests/integration/features/chat/reply.feature
  tests/integration/features/chat/system-messages.feature
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 4. to release, bug, feature: api 🛠️, feature: chat 💬

#5646 Initial Talkbuchet version
  docs/Talkbuchet.js
Labels: 3. to review, enhancement, feature: WebRTC 🚡, feature: call 👥

#5771 fix audio player layout
  src/components/MessagesList/MessagesGroup/Message/MessagePart/AudioPlayer.vue
Labels: 3. to review, design, enhancement, feature: chat 💬

#5781 Slow down the participant list update when not visible
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug

#5778 Add debug logs to allow finding out what kind of requests are sent
  lib/Controller/SignalingController.php
  tests/php/Controller/SignalingControllerTest.php
Labels: 3. to review, feature: signaling 📶, technical debt

#5782 Only slow, not additional
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, bug

#5783 Stop polling rooms in the dashboard when the document is hidden
  src/views/Dashboard.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#5780 Don't refresh the room when the participant list changes
  src/App.vue
Labels: 3. to review, bug, feature: call 👥

#5787 Display voice message preview before uploading
  src/components/MessagesList/MessagesGroup/Message/MessagePart/AudioPlayer.vue
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/UploadEditor.vue
  src/store/fileUploadStore.js
Labels: 3. to review, enhancement, feature: chat 💬

#5731 Better vcard files
  lib/Chat/Parser/SystemMessage.php
  psalm.xml
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 4. to release, enhancement, feature: frontend 🖌️, feature: upload & shares 📤

#5320 Use caption component from vue library
  src/components/Caption.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 2. developing, technical debt

#5303 Use nc-vue ActionCaption component
  src/components/LeftSidebar/ActionCaption/ActionCaption.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
Labels: 3. to review, bug, technical debt

#5793 Fix build
  .github/workflows/node.yml
  package-lock.json
  webpack.js
Labels: 3. to review, bug, dependencies, high

#5788 Add TLS, setup details and Talk 12 changes to TURN server documentation
  docs/TURN.md
Labels: 3. to review

#5534 New messages indicator while in call
  src/components/TopBar/TopBar.vue
  src/store/conversationsStore.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, enhancement

#5794 Offset toastify when top bar is visible
  src/App.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug

#5796 Remove stray debug log in Message vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug

#5779 Add UI feedback when local participant is not connected
  src/components/CallView/shared/LocalVideo.vue
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/webrtc.js
Labels: 4. to release, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#5801 Correctly fallback in case of missing data
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
Labels: 4. to release, bug, feature: chat 💬

#5809 fix cell of publishingPermissions description
  docs/conversation.md
  docs/participant.md
Labels: 3. to review

#5795 Fix concurrency when cancelling lookForNewMessages
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, bug, high, regression

#5821 Fix toastify offset approach
  src/App.vue
Labels: 3. to review, bug, regression

#5824 Adjust viewer and sidebar to changes in Nextcloud 22
  src/components/RightSidebar/RightSidebar.vue
  src/main.js
Labels: 4. to release, bug, feature: frontend 🖌️, regression

#5822 Fix disabling videos and selecting the screen of others
  src/components/CallView/shared/VideoBottomBar.vue
Labels: 4. to release, bug, feature: call 👥

#5823 Set focus to message only when anchor is set
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 4. to release, bug, regression

#5825 Bring back voice-message icon after chat input is cleared
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: chat 💬

#5827 Replace settings button icons with material design icons
  src/components/ConversationSettings/LinkShareSettings.vue
Labels: 3. to review, bug

#5828 Populate user status for one to one conversations via the backend call already
  docs/conversation.md
  lib/Controller/RoomController.php
  src/components/ConversationIcon.vue
  src/services/conversationsService.js
Labels: 4. to release, enhancement, feature: api 🛠️

#5831 Fix asterix conflict with notifications
  src/App.vue
Labels: 3. to review, bug, feature: chat 💬

#5660 Stop sent streams when media is disabled
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, enhancement, feature: WebRTC 🚡, feature: call 👥, feature: frontend 🖌️

#5836 Move conversation icon out of conversation header
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, design

#5837 Disable avatar menu in most conversation lists
  src/components/ConversationIcon.vue
  src/components/ConversationsOptionsList.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/views/Dashboard.vue
  src/views/RoomSelector.vue
Labels: 3. to review, bug, design

#5840 Fix left sidebar click event handling
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
Labels: 3. to review, bug, feature: chat 💬

#5839 Fix scrolling to bottom in already read conversations
  src/components/MessagesList/MessagesList.vue
Labels: 4. to release, bug, feature: chat 💬

#5850 Fix emoji picker icon in guest mode
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, regression

#5849 Also have sending requests marked as hpb
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, feature: signaling 📶, technical debt

#5844 Scroll participant list to top on token change
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, feature: chat 💬

#5852 Fix saving sound settings
  src/components/SettingsDialog/SettingsDialog.vue
  src/store/soundsStore.js
Labels: 3. to review, bug, feature: settings ⚙️

#5851 Remove voice recording for guests
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 4. to release, bug

#5854 Fix conversation icon visibility while in call
  src/components/TopBar/TopBar.vue
Labels: 4. to release, bug

#5856 Fix removing temp message after retry
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: chat 💬

#5843 Fix unload warning with pending messages
  src/App.vue
Labels: 3. to review, bug, feature: chat 💬

#5862 Safely import lodash function
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug

#5860 Fix screenshare icon not crossing out when a screen is shared
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/missingMaterialDesignIcons/CancelPresentation.vue
  src/components/missingMaterialDesignIcons/PresentToAll.vue
Labels: 3. to review, bug, feature: call 👥

#5865 Fix selecting the own screen in the gridview
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.vue
Labels: 3. to review, bug, feature: call 👥, feature: frontend 🖌️

#5863 Only scroll to focussed message once
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug

#5866 Don't spam the log when matterbridge is disabled
  lib/BackgroundJob/CheckMatterbridges.php
  lib/MatterbridgeManager.php
Labels: 3. to review, bug

#5871 Fix emoji picker vertical position
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, design

#5873 Fix initial scroll of unread messages marker
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#5881 Add a debug command to generate an arbitrary number of chat message
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, feature: chat 💬, technical debt

#5896 Catch the correct exception in case of UniqueConstraintViolationExcep…
  lib/Controller/SignalingController.php
  lib/Service/SessionService.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: signaling 📶

#5893 Add icons for Mark as read and unread
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, design

#5899 Fix missing "Open conversations" caption
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#5884 Add logs for connection quality warning
  src/utils/webrtc/analyzers/AverageStatValue.js
  src/utils/webrtc/analyzers/AverageStatValue.spec.js
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Labels: 4. to release, feature: call 👥, feature: frontend 🖌️
