Repository nextcloud/spreed, pull requests merged in 2021-11, with the labels that each got.

#6439 Fix grid when the number of videos is below the limit
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 👥

#5981 📅 End meeting for all
  docs/chat.md
  lib/Activity/Listener.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/CallController.php
  lib/Events/ModifyEveryoneEvent.php
  lib/Events/ModifyRoomEvent.php
  lib/Room.php
  lib/Service/ParticipantService.php
  src/components/TopBar/CallButton.vue
  src/services/callsService.js
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
  src/utils/signaling.js
  src/utils/webrtc/index.js
  src/utils/webrtc/webrtc.js
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, enhancement, feature: call 👥

#6424 Use public API of trusted domain helper
  composer.lock
  lib/Controller/ChatController.php
  psalm.xml
  tests/php/Controller/ChatControllerTest.php
Labels: 4. to release, bug, feature: api 🛠️

#6442 Show an error/warning when the HPB is incompatible
  lib/Controller/SignalingController.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Manager.php
  src/components/AdminSettings/SignalingServer.vue
  src/utils/signaling.js
Labels: 4. to release, bug, feature: signaling 📶

#6437 Use a more descriptive displayId
  lib/Profile/TalkAction.php
Labels: 3. to review, design, enhancement, feature: frontend 🖌️

#6444 Fix connection analyzer when using simulcast with Chromium
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Labels: 3. to review, backport-request, bug, feature: WebRTC 🚡, feature: frontend 🖌️, feature: call 👥

#6382 Add ability to set default permissions for a conversation
  src/components/ConversationSettings/ConversationPermissionsSettings.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/PermissionsEditor/PermissionsEditor.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.spec.js
  src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
  src/services/conversationsService.js
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
Labels: 4. to release, feature: settings ⚙️, feature: frontend 🖌️

#6448 Ignore preference for H.264 when simulcast is used
  lib/TInitialState.php
  package-lock.json
  package.json
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6450 Reconnect when permissions change with internal signaling
  lib/Controller/SignalingController.php
Labels: 4. to release, bug, feature: signaling 📶

#6457 Change grammar of sentences
  docs/call-experience.md
  docs/constants.md
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/ConversationSettings/ConversationPermissionsSettings.vue
Labels: 4. to release, bug

#6459 Add ability to set default participant permissions
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, feature: frontend 🖌️

#6461 Fix joining call without media devices
  src/utils/media/pipeline/MediaDevicesSource.js
Labels: 3. to review, bug, regression, feature: frontend 🖌️, feature: call 👥

#6463 Fix permissions editor dialog for unnamed guests
  src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️

#6462 Always mount the slow so it is reactive to the state
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#6427 Start with integration tests for invites
  lib/AppInfo/Application.php
  lib/Config.php
  lib/Controller/RoomController.php
  lib/Federation/FederationManager.php
  lib/Federation/Notifications.php
  lib/TInitialState.php
  src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
  src/services/conversationsService.js
  src/services/conversationsService.spec.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/invite.feature
  tests/php/Federation/FederationTest.php
Labels: 3. to review, bug, feature: api 🛠️, feature: federation 🌐

#6460 Call view improvements
  css/icons.scss
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
Labels: 4. to release, feature: frontend 🖌️

#6465 Only show "End meeting for all" when starting is restricted
  src/components/TopBar/CallButton.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: meetings 📅, feature: call 👥

#6471 Update version on master
  appinfo/info.xml
  package.json
  tests/integration/spreedcheats/appinfo/info.xml
Labels: 4. to release

#6470 Update stable23 target versions
  .drone.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: 4. to release

#6466 Show message about problems in the connection with another participant
  src/components/CallView/shared/Video.vue
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6476 Add empty changelog for Talk 13 rc1
  CHANGELOG.md
Labels: backport-request

#6483 Don't "End meeting" when onclick event is the all parameter :P
  src/components/TopBar/CallButton.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 👥

#6485 Round videos
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Video.vue
Labels: 3. to review, feature: call 👥

#6474 Update npm and node engines versions
  package.json
Labels: backport-request, dependencies

#6479 Fix topbar buttons design and mobile layout
  src/assets/variables.scss
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️

#6501 Only run unit tests when php is affected
  .github/workflows/phpunit.yml
Labels: 3. to review, technical debt

#6488 Fix empty video when blur background model could not be loaded
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/DeviceChecker/DeviceChecker.vue
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.worker.js
  src/utils/media/pipeline/VirtualBackground.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6505 Fix device checker on shorter screens
  src/components/DeviceChecker/DeviceChecker.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6507 Overwrite hasCall based on chat messages
  lib/Activity/Listener.php
  src/components/TopBar/CallButton.vue
  src/store/conversationsStore.js
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: call 👥

#6512 Add changelog for 13 and "What's new"
  CHANGELOG.md
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request

#6515 Update screenshots 13
  docs/call-in-action.jpg
  docs/call-in-action.png
  docs/chat.png
  docs/file-darg-and-drop.png
  docs/screensharing.png
  docs/screenshotplaceholders/placeholder-1.jpeg
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, backport-request, overview

#6519 Add the topbar in the sidebars
  css/icons.scss
  src/FilesSidebarCallViewApp.vue
  src/PublicShareAuthSidebar.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, bug, feature: talk-sidebar ⬅️, feature: call 👥

#6523 Fix non-themed video-verification button
  src/PublicShareAuthRequestPasswordButton.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#6522 Update video-verification screenshot
  docs/video-verfication.png
Labels: 3. to review, backport-request

#6517 Add setup check for background blur
  docs/system-requirements.md
  src/components/AdminSettings/WebServerSetupChecks.vue
  src/utils/media/pipeline/VirtualBackground.js
  src/views/AdminSettings.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️

#6533 Reduce the bluring so it's not "You on a single color" and disable by default
  src/components/DeviceChecker/DeviceChecker.vue
  src/utils/media/pipeline/VirtualBackground.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/LocalMediaModel.js
Labels: 3. to review, backport-request, bug, feature: call 👥

#6536 [stable23] Only run unit tests when php is affected
  .github/workflows/phpunit.yml
Labels: 3. to review, technical debt

#6528 [stable22.1] Don't allow to get pushes for Talk activity
  lib/Activity/Setting.php
Labels: 3. to review, bug

#6537 Use the same default for the device checker in the conversation settings
  src/components/ConversationSettings/ConversationSettingsDialog.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#6529 [stable21] accept SHA256 hash sums for reference id as documented
  lib/Chat/ChatManager.php
  src/services/messagesService.js
  src/utils/temporaryMessage.js
  tests/integration/features/chat/reference-id.feature
Labels: 3. to review, bug, feature: chat 💬

#6521 Add breathing room to stripe
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Video.vue
  src/components/CallView/shared/VideoBackground.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6542 Bugfix/noid/fix margins on 1on1s
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Video.vue
Labels: 3. to review, backport-request, bug

#6545 Do not apply constraints again until the previous operation finished
  src/utils/webrtc/VideoConstrainer.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6544 Do not emit "change" events if attribute did not change
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/models/LocalMediaModel.js
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️, feature: call 👥

#6538 Fix connection warning positioning
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 4. to release, backport-request, bug, regression, feature: frontend 🖌️

#6549 Add changelog for 13.0.0-rc.2
  CHANGELOG.md
Labels: 3. to review, backport-request

#6552 Fix buttons in the topbar
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6559 A missed call is only when there was only 1 user
  lib/Activity/Listener.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#6560 No individual leave message when the meeting was ended for all
  lib/Chat/SystemMessage/Listener.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: meetings 📅

#6558 Only enable devices when the device selection is shown
  src/components/DeviceChecker/DeviceChecker.vue
Labels: 3. to review, backport-request, bug, regression, feature: settings ⚙️, feature: frontend 🖌️, feature: call 👥

#6568 Make the volume indicator grey again when mic is disabled
  src/components/CallView/shared/LocalMediaControls.vue
Labels: 4. to release, backport-request, bug, regression, feature: call 👥

#6573 Fix video container sizing (Again)
  src/components/CallView/CallView.vue
  src/components/CallView/shared/Video.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6574 Fix topbar height
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, bug, design, feature: frontend 🖌️

#6583 Always open the conversation settings with the right data
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/TopBar/TopBar.vue
  src/store/tokenStore.js
Labels: 3. to review, bug, papercut, regression, feature: settings ⚙️

#6467 Create appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
  Makefile
Labels: backport-request

#6569 Fix flickering with background blur when changing quality
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.worker.js
  src/utils/media/pipeline/VirtualBackground.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6588 Add changelog 13.0.0-rc.3
  CHANGELOG.md
Labels: 3. to review, backport-request, overview

#6591 Fix video zoom jump with background blur when changing resolution
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6596 Replace virtual background segmentation model
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.worker.js
  src/utils/media/effects/virtual-background/index.js
  src/utils/media/effects/virtual-background/vendor/README.md
  src/utils/media/effects/virtual-background/vendor/models/Model Card MediaPipe Selfie Segmentation.pdf
  src/utils/media/effects/virtual-background/vendor/models/segm_full_v679.tflite
  src/utils/media/effects/virtual-background/vendor/models/segm_lite_v681.tflite
  src/utils/media/effects/virtual-background/vendor/models/selfie_segmentation_landscape.tflite
  src/utils/media/pipeline/VirtualBackground.js
Labels: 4. to release, backport-request, bug

#6599 Make background blur proportional to the input video size
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
Labels: 4. to release, backport-request, bug, feature: frontend 🖌️

#6598 Fix media never requested again when changing again to current device
  src/utils/media/pipeline/MediaDevicesSource.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6604 Fix automatic removal of streams when ended
  src/utils/media/pipeline/TrackSourceMixin.js
Labels: 4. to release, backport-request, bug, regression, feature: frontend 🖌️, feature: call 👥

#6603 Return room token
  lib/Command/Room/Create.php
Labels: 3. to review, enhancement, feature: bots & commands 🤖

#6612 Correctly populate the modal with default permissions
  src/components/PermissionsEditor/PermissionsEditor.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.spec.js
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#6605 Fix pending device not requested once current request finishes
  src/utils/media/pipeline/MediaDevicesSource.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6617 Add changelog for 13.0.0-rc.4
  CHANGELOG.md
Labels: 3. to review, backport-request

#6613 Implement tests on command create room
  lib/Command/Room/Create.php
  tests/integration/features/command/create.feature
Labels: 2. developing, feature: bots & commands 🤖, php

#6623 Better routes files
  appinfo/routes.php
  appinfo/routes/routesCallController.php
  appinfo/routes/routesChatController.php
  appinfo/routes/routesCommandController.php
  appinfo/routes/routesFederationController.php
  appinfo/routes/routesFilesIntegrationController.php
  appinfo/routes/routesGuestController.php
  appinfo/routes/routesHostedSignalingServerController.php
  appinfo/routes/routesMatterbridgeController.php
  appinfo/routes/routesMatterbridgeSettingsController.php
  appinfo/routes/routesPageController.php
  appinfo/routes/routesPublicShareAuthController.php
  appinfo/routes/routesRoomController.php
  appinfo/routes/routesSettingsController.php
  appinfo/routes/routesSignalingController.php
  appinfo/routes/routesTempAvatarController.php
Labels: 3. to review, technical debt
