Repository nextcloud/spreed, pull requests merged in 2021-08, with the labels that each got.

#6065 Fix forwarding mentions
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Forwarder.vue
  src/store/messagesStore.js
Labels: 3. to review, bug

#6051 Bugfix/6044/disable voice recording on readonly conversations
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 4. to release, backport-request, bug

#3732 Send offer again when own peer is not initially connected
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: call 👥, feature: frontend 🖌️

#6041 Revert "Fix TURN's url in README.md"
  README.md
Labels: 4. to release, bug

#6040 Revert "fix links to documentation"
  lib/Controller/SignalingController.php
  src/components/AdminSettings/Commands.vue
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/AdminSettings/TurnServers.vue
  src/utils/webrtc/webrtc.js
Labels: 4. to release, bug

#6079 Remove div tags from safari messages
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug

#6064 Fixed typo.
  src/components/ConversationSettings/DangerZone.vue
Labels: 3. to review, backport-request, bug

#6101 Fix infinite loop when the constraints can not be decreased
  src/utils/webrtc/VideoConstrainer.js
Labels: 3. to review, backport-request, bug

#6107 Fix blocked audio recording preview when Talk is embedded in the sidebar
  lib/Listener/CSPListener.php
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#6103 Fix duplicated registration of audio encoder
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6054 Update TURN server documentation
  docs/TURN.md
Labels: 3. to review

#6135 Add changelog of 12.1.0
  CHANGELOG.md
Labels: 4. to release, backport-request

#6142 Hide forward action for guests
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#6118 Fix connection quality warning still shown after media is stopped
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6152 Add some logging to the device selection
  src/utils/webrtc/MediaDevicesManager.js
Labels: 3. to review, backport-request, bug, feature: call 👥

#6170 Improve eslint
  src/components/CallView/shared/VideoBackground.vue
  src/components/ConversationSettings/NotificationsSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/deck.js
  src/init.js
  src/services/callsService.js
  src/services/conversationsService.js
  src/services/filesIntegrationServices.js
  src/services/messagesService.js
  src/services/participantsService.js
  src/services/publicShareAuthService.js
  src/services/settingsService.js
  src/store/actorStore.js
  src/store/callViewStore.js
  src/store/fileUploadStore.js
  src/store/messagesStore.js
  src/store/participantsStore.js
  src/store/settingsStore.js
  src/store/tokenStore.js
  src/utils/webrtc/analyzers/AverageStatValue.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, technical debt

#6169 Work around Chromium bug of iceConnectionState stuck as "disconnected"
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6173 Fix unneeded top margin in Files sidebar chat
  src/FilesSidebarTabApp.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#6115 Rename language strings to camelCase
  lib/Settings/Admin/AdminSettings.php
  src/components/AdminSettings/HostedSignalingServer.vue
Labels: 3. to review, feature: settings ⚙️

#6166 Add changelog for 12.1.1
  CHANGELOG.md
Labels: 3. to review, backport-request, overview

#6178 Fix audio recordings in conversations with special chars and long names
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: upload & shares 📤

#6160 Don't save device selection when there is only one device
  src/components/MediaDevicesSelector.vue
  src/utils/webrtc/MediaDevicesManager.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6171 Improve ESLint part 2
  .eslintrc.js
  babel.config.js
  src/components/AdminSettings/Commands.vue
  src/components/AdminSettings/HostedSignalingServer.vue
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/AdminSettings/TurnServers.vue
  src/init.js
  src/services/conversationsService.js
  src/services/filesIntegrationServices.js
  src/services/messagesService.js
  src/services/participantsService.js
  src/store/callViewStore.js
  src/store/conversationsStore.js
  src/store/fileUploadStore.js
  src/store/guestNameStore.js
  src/store/messagesStore.js
  src/store/newGroupConversationStore.js
  src/store/participantsStore.js
  src/store/quoteReplyStore.js
  src/store/tokenStore.js
  src/store/uiModeStore.js
  src/utils/signaling.js
  src/utils/webrtc/MediaDevicesManager.js
  src/utils/webrtc/SentVideoQualityThrottler.js
  src/utils/webrtc/SpeakingWhileMutedWarner.js
  src/utils/webrtc/VideoConstrainer.js
  src/utils/webrtc/analyzers/CallAnalyzer.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
  src/utils/webrtc/simplewebrtc/webrtc.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, technical debt

#6179 [stable22.1] Don't save device selection when there is only one device
  src/components/MediaDevicesSelector.vue
  src/utils/webrtc/MediaDevicesManager.js
Labels: 3. to review, bug
