Repository nextcloud/spreed, pull requests merged in 2022-07, with the labels that each got.

#7498 Add schemes to turn OCC commands
  lib/Command/Turn/Add.php
  lib/Command/Turn/Delete.php
  tests/php/Command/Turn/AddTest.php
  tests/php/Command/Turn/DeleteTest.php
Labels: 4. to release, bug, feature: settings ⚙️

#7327 Implement time to live
  appinfo/info.xml
  appinfo/routes/routesRoomController.php
  composer.lock
  docs/capabilities.md
  docs/chat.md
  docs/conversation.md
  lib/BackgroundJob/ExpireChatMessages.php
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Migration/Version15000Date20220506005058.php
  lib/Model/SelectHelper.php
  lib/Room.php
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/message-expiration.feature
  tests/integration/spreedcheats/appinfo/routes.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Service/RoomServiceTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, enhancement, feature: api 🛠️

#7505 Improve docs
  docs/call-experience.md
  docs/call.md
  docs/chat.md
  docs/commands.md
  docs/conversation.md
  docs/integration.md
  docs/internal-signaling.md
  docs/participant.md
  docs/poll.md
  docs/reaction.md
  docs/settings.md
  docs/webinar.md
Labels: 3. to review, bug, feature: api 🛠️

#7510 Update iOS requirements
  docs/system-requirements.md
Labels: 3. to review

#7513 Add pending column
  lib/Manager.php
Labels: 3. to review, feature: api 🛠️

#7511 Adjust logs during calls
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#7504 Add brute force protection to conversation passwords
  lib/Controller/FilesIntegrationController.php
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Middleware/InjectionMiddleware.php
  psalm.xml
  templates/authenticate.php
Labels: 4. to release, backport-request, enhancement, feature: api 🛠️

#7517 Fix postgres integration tests
  .drone.jsonnet
  .drone.yml
  composer.lock
  lib/Chat/ChatManager.php
  lib/Manager.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 4. to release, feature: chat 💬, feature: api 🛠️

#7537 [stable22] Add brute force protection to conversation passwords
  lib/Controller/FilesIntegrationController.php
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Middleware/InjectionMiddleware.php
  psalm.xml
  templates/authenticate.php
Labels: 3. to review, enhancement, feature: api 🛠️

#7538 Add changelog for 12.2.7, 13.0.7 and 14.0.3
  CHANGELOG.md
Labels: 3. to review

#7540 Release 13.0.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7541 Release 12.2.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7548 Add aria labels to "Remove input" buttons
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 3. to review, feature: frontend 🖌️, accessibility

#7547 Move to single button and add label to "Cancel quote" button
  src/components/Quote.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, accessibility

#7545 Fix locations not showing in chat due to missing height
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue
  src/components/RightSidebar/SharedItems/SharedItems.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#7551 Fix syntax
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 4. to release, bug, feature: frontend 🖌️

#7552 Fix package-lock.json
  package-lock.json
Labels: 4. to release, bug

#7512 📊 Poll follow ups
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/ChatController.php
  lib/Controller/PollController.php
  lib/Model/Attachment.php
  lib/Service/AttachmentService.php
  tests/integration/features/chat/poll.feature
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: polls 📊

#7576 Fix missing CSS due to SCSS cacher removal
  css/At.css
  css/At.scss
  css/app.scss
  css/icons.css
  css/icons.scss
  css/merged-files.scss
  css/merged-public-share.scss
  css/merged-share-auth.scss
  css/merged.scss
  css/publicshare.css
  css/publicshareauth.css
  css/unified-search.css
  css/unified-search.scss
  img/bell-outline.svg
  img/grid-view.svg
  img/icon-contacts-white.svg
  img/icon-mail-white.svg
  img/icon-password-white.svg
  img/icon-public-white.svg
  img/icon-text-white.svg
  img/icon-user-white.svg
  img/lobby.svg
  img/promoted-view.svg
  lib/Files/TemplateLoader.php
  lib/PublicShare/TemplateLoader.php
  lib/PublicShareAuth/TemplateLoader.php
  lib/Search/ConversationSearch.php
  src/App.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/ConversationIcon.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LobbyScreen.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
  src/components/missingMaterialDesignIcons/GridView.vue
  src/components/missingMaterialDesignIcons/Lobby.vue
  src/components/missingMaterialDesignIcons/MenuPeople.vue
  src/components/missingMaterialDesignIcons/PromotedView.vue
  templates/index.php
Labels: 3. to review, bug, feature: frontend 🖌️

#7554 Fix avatar size to be a legal value
  lib/Search/ConversationSearch.php
  lib/Search/MessageSearch.php
Labels: 3. to review, backport-request, feature: chat 💬

#7577 Move settings-admin.scss to vue files
  css/settings-admin.scss
  src/components/AdminSettings/Commands.vue
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/SignalingServers.vue
  src/views/AdminSettings.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️

#7571 Expire messages part 2: a background job for all rooms
  appinfo/info.xml
  lib/BackgroundJob/ExpireChatMessages.php
  lib/Chat/ChatManager.php
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/message-expiration.feature
  tests/integration/spreedcheats/appinfo/routes.php
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, feature: api 🛠️

#7582 Add more search attributes
  lib/Search/MessageSearch.php
Labels: 3. to review, backport-request, enhancement, feature: search 🔎

#7585 Fix guest names in search results
  lib/Search/MessageSearch.php
Labels: 3. to review, backport-request, bug, feature: search 🔎

#7586 Fix HTML validation of meta element
  lib/TInitialState.php
Labels: 3. to review, bug

#7598 Correctly forward avatar container
  src/components/AvatarWrapper/AvatarWrapper.vue
Labels: 3. to review, bug, feature: frontend 🖌️, accessibility

#7600 Fix HTML validation of material design icons
  src/components/ConversationSettings/ConversationPermissionsSettings.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/NotificationsSettings.vue
  src/components/DeviceChecker/DeviceChecker.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, accessibility

#7594 Restore deleted method
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, feature: api 🛠️

#7595 Listener to send message expiration message
  lib/Chat/SystemMessage/Listener.php
  lib/Controller/RoomController.php
  lib/Service/RoomService.php
Labels: 3. to review, feature: api 🛠️

#7603 Remove unknown attribute menu-align
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, accessibility

#7601 Remove invalid attribute icon from button
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 3. to review, bug, accessibility

#7614 Fix keyboard navigation in the settings
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, bug, feature: settings ⚙️, accessibility

#7596 occ command to set expire message
  lib/Command/Room/Create.php
  lib/Command/Room/TRoomCommand.php
  lib/Command/Room/Update.php
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/command/create.feature
  tests/integration/features/command/update.feature
Labels: 3. to review, feature: api 🛠️

#7621 Fix error getting poll without votes
  lib/Controller/PollController.php
  lib/Service/PollService.php
  tests/integration/features/chat/poll.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: polls 📊

#7615 Fix invalid setting sections IDs
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 4. to release, bug

#7627 Fix issues mentioned in the polls review
  docs/chat.md
  docs/poll.md
  lib/Chat/Parser/SystemMessage.php
  lib/Service/PollService.php
Labels: 3. to review, bug, feature: api 🛠️, feature: polls 📊

#7624 [Documentation] Set proper header for requesting JSON response
  docs/chat.md
  docs/conversation.md
  docs/poll.md
Labels: 4. to release

#7640 Fix video verification layout
  src/PublicShareAuthRequestPasswordButton.vue
  src/mainPublicShareAuthSidebar.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#7625 Keep DND and Invisible when automatically setting status to "In a call"
  lib/Status/Listener.php
Labels: 3. to review, bug, feature: call 👥

#7644 Move Matterbridge install to vue button
  src/components/AdminSettings/MatterbridgeIntegration.vue
Labels: 3. to review, bug, feature: frontend 🖌️, accessibility

#7646 Move TURN and STUN to Vue components
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/StunServers.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/TurnServers.vue
  src/components/missingMaterialDesignIcons/CategoryMonitoring.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️, accessibility

#7649 Move Hosted signaling server to Vue button
  src/components/AdminSettings/HostedSignalingServer.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️, accessibility

#7650 Move SIP bridge settings to Vue button
  src/components/AdminSettings/SIPBridge.vue
Labels: 4. to release, bug, feature: settings ⚙️, feature: frontend 🖌️, accessibility

#7643 Fix checkboxes in general admin settings
  src/components/AdminSettings/GeneralSettings.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️, accessibility

#7648 Add `$shallow` arg to `RoomShareProvider::getSharesInFolder`
  lib/Share/RoomShareProvider.php
Labels: 3. to review, enhancement

#7641 Fix forwarding the menu-container for avatars
  src/components/AvatarWrapper/AvatarWrapper.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️

#7652 Fix HTML validations in admin settings
  package-lock.json
  package.json
  src/components/AdminSettings/AllowedGroups.vue
  src/components/AdminSettings/Command.vue
  src/components/AdminSettings/GeneralSettings.vue
  src/components/AdminSettings/HostedSignalingServer.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7629 Expire shared link when expire message
  lib/Chat/ChatManager.php
  lib/Chat/SystemMessage/Listener.php
  tests/integration/features/chat/message-expiration.feature
Labels: 3. to review, feature: api 🛠️

#7626 Adapte guest page to NC 25
  templates/authenticate.php
Labels: 4. to release, feature: frontend 🖌️

#7602 Fix HTML validation DIV not allowed inside UL
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, accessibility
