Repository nextcloud/spreed, pull requests merged in 2022-01, with the labels that each got.

#6724 Bugfix/fix selection when someone is screensharing
  src/components/CallView/CallView.vue
Labels: 3. to review, regression, feature: frontend 🖌️

#6743 Add attributes in search results
  lib/Search/ConversationSearch.php
  lib/Search/MessageSearch.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#6750 docs(readme): point to SimpleWebRTC library
  README.md
Labels: 4. to release, bug

#6648 Enh/noid/improve videos bottom bar
  src/components/CallView/shared/VideoBottomBar.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️

#6770 Fix empty name for unnamed guests in permissions change notifications
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6771 Make own peer related code more robust
  src/components/CallView/shared/LocalVideo.vue
  src/utils/signaling.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6790 4310: fixed emoticon displaying after selection
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️, javascript

#6789 6318: fixed mention complete with mouse clicking
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️, javascript

#6791 5094: fixed special symbols for translation
  src/components/ConversationSettings/DangerZone.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, javascript, feature: call 👥

#6787 Fix some stylelint warnings
  src/components/ConversationIcon.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  stylelint.config.js
Labels: 3. to review, bug

#6796 Reduce the set of avatar sizes used
  src/components/CallView/shared/VideoBackground.vue
Labels: 3. to review, feature: frontend 🖌️, feature: call 👥

#6797 Remove temporary function after server merge
  lib/Chat/CommentsManager.php
Labels: 3. to review, technical debt

#6675 Refactor notifyMentionedUsers method
  lib/Chat/Notifier.php
  tests/php/Chat/NotifierTest.php
Labels: 3. to review, php

#6777 Don't update the participant list when only you joined
  src/utils/signaling.js
Labels: 3. to review, backport-request, bug, feature: signaling 📶, performance 🚀

#6769 6607: fixed scrolling issue to latest message
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, javascript

#6768 6154: fixed copy link issue for public call
  src/components/CallView/shared/EmptyCallView.vue
Labels: 3. to review, backport-request, javascript, feature: call 👥

#6772 Bump @nextcloud/vue to v5.0.0-beta.0
  package-lock.json
  package.json
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/DeviceChecker/DeviceChecker.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/PermissionsEditor/PermissionsEditor.vue
  src/components/UploadEditor.vue
Labels: 3. to review, dependencies

#6602 Check share restrictions on one to one conversation
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-2/one-to-one.feature
  tests/integration/features/conversation-2/sip-dialin.feature
  tests/integration/features/conversation/limit-creation.feature
  tests/integration/features/federation/invite.feature
  tests/php/Service/RoomServiceTest.php
Labels: 4. to release, feature: api 🛠️, php

#6807 Allow to mark a conversation as unread
  appinfo/routes/routesChatController.php
  docs/capabilities.md
  docs/chat.md
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Controller/ChatController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/unread-messages.feature
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#6815 Move to unified linting
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
Labels: 3. to review, technical debt

#6814 Fix peer user not showing as offline in one-to-one conversations
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6812 Don't force signaling mode when HPB trial is used
  lib/BackgroundJob/CheckHostedSignalingServer.php
  lib/Controller/HostedSignalingServerController.php
  tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
Labels: 3. to review, backport-request, bug, feature: signaling 📶

#6830 Changelog for 11.3.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#6832 Remove unneeded SimpleWebRTC code
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, bug, feature: WebRTC 🚡, feature: frontend 🖌️

#6810 Allow to share audio of screenshares
  src/components/CallView/shared/Screen.vue
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/simplewebrtc/getscreenmedia.js
Labels: 3. to review, enhancement, feature: WebRTC 🚡, feature: call 👥

#6835 Fix mentions inside brackets
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#6763 6417: added search feature to forward modal
  src/views/RoomSelector.vue
Labels: 4. to release, feature: chat 💬, javascript

#6795 Revert "6318: fixed mention complete with mouse clicking"
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#6837 Only send 1 HPB request for the "end call for everyone" case
  lib/Events/EndCallForEveryoneEvent.php
  lib/Service/ParticipantService.php
  lib/Signaling/Listener.php
Labels: 3. to review, bug, feature: signaling 📶, feature: call 👥, performance 🚀

#6840 Fix eslint after #6763
  src/views/RoomSelector.vue
Labels: 3. to review, bug

#6847 Change all phpunit versions and fix accidental revert
  .github/workflows/phpunit.yml
Labels: 3. to review, bug

#6831 Fix switching between screenshares
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6853 Remove custom method after server merge
  lib/Chat/CommentsManager.php
Labels: 3. to review, feature: chat 💬
