Repository nextcloud/spreed, pull requests merged in 2022-06, with the labels that each got.

#7338 Allow the HPB to group session pinging across rooms
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/SignalingController.php
  tests/php/CapabilitiesTest.php
  tests/php/Controller/SignalingControllerTest.php
Labels: 4. to release, backport-request, enhancement, feature: signaling 📶, performance 🚀

#7447 l10n: Delete shortcut
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7434 Route to the first search result upon pressing enter
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, enhancement

#7449 [stable23] Add a capability for the unified-search
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, feature: api 🛠️

#7450 [stable22] Add a capability for the unified-search
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, feature: api 🛠️

#7448 [stable24] Add a capability for the unified-search
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, feature: api 🛠️

#7416 Support "Silent call" on API
  docs/call.md
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/CallController.php
  lib/Events/SilentModifyParticipantEvent.php
  lib/Notification/Listener.php
  lib/Service/ParticipantService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/notifications.feature
  tests/php/CapabilitiesTest.php
Labels: 3. to review, feature: api 🛠️, feature: call 👥

#7413 Move setDescription to room service
  lib/Command/Room/TRoomCommand.php
  lib/Controller/RoomController.php
  lib/Room.php
  lib/Service/RoomService.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, technical debt

#7445 Silent calls front end
  src/PublicShareAuthSidebar.vue
  src/components/DeviceChecker/DeviceChecker.vue
  src/components/TopBar/CallButton.vue
  src/services/callsService.js
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
Labels: 3. to review, enhancement, feature: frontend 🖌️

#7454 Use better name for silent call option
  src/components/DeviceChecker/DeviceChecker.vue
Labels: 3. to review, enhancement

#7463 Fixed crash when saving status without conversation selected
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
Labels: 3. to review, backport-request, bug

#7470 do not open the right sidebar on mobile automatically
  src/App.vue
Labels: 3. to review, enhancement

#7477 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#7464 Test remote invite notifications and try to send the accept/decline on invites
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/invite.feature
  tests/integration/run.sh
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Federation/FederationTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, feature: api 🛠️, feature: federation 🌐

#7306 📊 Simple polls API
  appinfo/info.xml
  appinfo/routes.php
  appinfo/routes/routesPollController.php
  docs/constants.md
  docs/poll.md
  lib/Chat/ChatManager.php
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/PollController.php
  lib/GuestManager.php
  lib/Listener/UserDisplayNameListener.php
  lib/Migration/Version15000Date20220503121308.php
  lib/Model/Poll.php
  lib/Model/PollMapper.php
  lib/Model/Vote.php
  lib/Model/VoteMapper.php
  lib/Service/PollService.php
  mkdocs.yml
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/poll.feature
  tests/integration/spreedcheats/lib/Controller/ApiController.php
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, enhancement, feature: polls 📊

#7372 Require firebase JWT lib
  Makefile
  composer.json
  composer.lock
  lib/AppInfo/Application.php
Labels: 4. to release, enhancement, feature: signaling 📶

#7489 Add app version to capabilities
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api 🛠️

#7486 Bump packages
  composer.lock
Labels: 3. to review, feature: api 🛠️, php

#7117 Add CLI to run Talkbuchet
  docs/Talkbuchet-cli.py
  docs/Talkbuchet-run.sh
  docs/Talkbuchet.js
Labels: 3. to review

#7497 Document poll system messages
  docs/chat.md
Labels: 3. to review, enhancement, feature: api 🛠️, feature: polls 📊

#7500 Fix the array structure of "voted" attribute with PHP json_encode
  docs/poll.md
  lib/Model/Poll.php
  tests/integration/features/chat/poll.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: polls 📊

#7473 Implement password policy checker
  docs/conversation.md
  lib/Command/Room/TRoomCommand.php
  lib/Controller/RoomController.php
  lib/Room.php
  lib/Service/RoomService.php
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/LeftSidebar/NewGroupConversation/PasswordProtect/PasswordProtect.vue
  src/services/conversationsService.js
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, bug, feature: settings ⚙️, feature: api 🛠️
