Repository nextcloud/spreed, pull requests merged in 2022-09, with the labels that each got.

#7834 Fix voted guests handling
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/AvatarWrapper/AvatarWrapperSmall.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
  src/store/pollStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: polls 📊

#7724 Improve new group conversation modal
  src/components/ConversationSettings/ListableSettings.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue
  src/components/LeftSidebar/NewGroupConversation/SetConversationType/SetConversationType.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#7846 ✨ Update to @nextcloud/vue 7
  package-lock.json
  package.json
  src/App.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7848 Changelog for 15.0.0 beta.2
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7853 Move composer-bin-plugin to normal deps
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#7864 Bump @nextcloud/event-bus from 3.0.1 to 3.0.2
  package-lock.json
Labels: 3. to review, bug

#7877 Adjust public share authentication page to layout changes in NC25
  css/publicshareauth.css
Labels: 3. to review, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#7871 Fix visibility of sidebar toggle
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7875 Add titles to settings dialogs
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️

#7868 Adjust videos border radius
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 👥

#7865 Adjust public share page to layout changes in Nextcloud 25
  css/publicshare.css
Labels: 3. to review, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#7873 Update callview backdrop
  src/App.vue
  src/assets/variables.scss
  src/components/CallView/CallView.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 👥

#7870 Bugfix/noid/polish navigation
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7881 Changelog for 15.0.0 beta.3
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7882 Bump @nextcloud/vue from 7.0.0-beta.0 to 7.0.0-beta.2
  package-lock.json
Labels: 3. to review

#7889 [master] Update christophwurst/nextcloud dependency
  composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#7890 [stable22] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#7898 Dispatch reference rendering event
  lib/Controller/PageController.php
Labels: 3. to review, bug, feature: frontend 🖌️

#7897 Add container to all NcModal components
  src/components/DeviceChecker/DeviceChecker.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/NewMessageForm/SimplePollsEditor/SimplePollsEditor.vue
  src/components/PermissionsEditor/PermissionsEditor.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7900 Fix dashboard icon on dark mode again
  css/icons.css
Labels: 3. to review, bug, feature: frontend 🖌️

#7903 Remove old import of admin css
  lib/Settings/Admin/AdminSettings.php
  templates/settings/admin-settings.php
Labels: 3. to review, bug

#7910 Bump @nextcloud/vue to 7.0.0-beta.3
  package-lock.json
  package.json
Labels: 3. to review, bug, feature: frontend 🖌️

#7911 Fix unclear translation "You voted"
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
Labels: 3. to review, bug, feature: polls 📊

#7912 Fix deleted users in polls
  lib/Listener/UserDeletedListener.php
  lib/Service/PollService.php
  src/components/AvatarWrapper/AvatarWrapperSmall.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
  tests/integration/features/chat/poll.feature
  tests/integration/features/reaction/react.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: frontend 🖌️, feature: polls 📊

#7918 Remove expired message and when there are too many from the Vue store
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#7920 Bugfix/7916/fix participant search
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue
  src/components/UploadEditor.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7923 Bump @nextcloud/vue to 7.0.0-beta.4
  package-lock.json
  package.json
Labels: 4. to release, bug, feature: frontend 🖌️

#7925 Update vue-richtext to 2.0.1
  package-lock.json
  package.json
Labels: 3. to review, bug, feature: frontend 🖌️

#7922 Show polls in own section of shared items
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/constants.js
  src/mixins/sharedItems.js
  src/store/sharedItemsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️, feature: polls 📊

#7929 Fix missing bottom+right frame when following in a 2 person call
  src/components/CallView/CallView.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 👥

#7914 Allow to "Send call notification" for owners
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 👥

#7930 Changelog for 13.0.9 and 14.0.5
  CHANGELOG.md
Labels: 3. to review, technical debt

#7789 Add related resources panel to shared items sidebar
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
Labels: 3. to review, enhancement, high, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#7895 Fix username overlap with localvideo
  src/components/CallView/shared/LocalVideo.vue
Labels: 3. to review, bug

#7915 Fix message forwarding
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#7931 Changelog for 14.0.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#7932 Changelog for 13.0.9
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#7935 Changelog for 15.0.0 beta.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#7917 Fix flow and chat permissions
  lib/Flow/Operation.php
  src/views/FlowPostToConversation.vue
Labels: 4. to release, bug, feature: api 🛠️, feature: frontend 🖌️, feature: flow 🔀

#7936 Disable keyboard shortcuts when the user opted-out
  src/App.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/components/TopBar/TopBar.vue
Labels: 4. to release, bug, feature: frontend 🖌️, accessibility

#7940 Fix poll voter details
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7951 [master] Update christophwurst/nextcloud dependency
  composer.lock
  vendor-bin/phpunit/composer.lock
Labels: 3. to review, dependencies

#7944 Close menu when favoriting
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 4. to release, bug, feature: frontend 🖌️

#7942 Implement dashboard IAPIWidget
  .drone.jsonnet
  .drone.yml
  .gitignore
  lib/Dashboard/TalkWidget.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/integration/dashboard.feature
Labels: 3. to review, enhancement, feature: api 🛠️

#7961 Fix reaction buttons due to remove CSS variable
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️, feature: reactions 👍, accessibility

#7960 Reduce preview size of non images/videos
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#7954 Fix chat endpoints with empty reactions in XML format
  lib/Controller/AEnvironmentAwareController.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Model/Message.php
Labels: 3. to review, bug, feature: chat 💬, feature: api 🛠️

#7958 Migrate warning toggle to NcCheckboxRadioSwitch
  src/components/AdminSettings/SignalingServers.vue
Labels: 3. to review, bug, high, feature: settings ⚙️, feature: frontend 🖌️

#7959 Restrict polls from one-to-one chats
  docs/poll.md
  lib/Controller/PollController.php
  src/components/NewMessageForm/NewMessageForm.vue
  tests/integration/features/chat/poll.feature
Labels: 4. to release, bug, feature: polls 📊

#7965 Fix size of upload modal
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/UploadEditor.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#7969 Show shareWithDisplayNameUnique for users
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7968 Fix console error '[vuex] duplicate getter key: reactionsLoaded' in jest
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
Labels: 3. to review, bug

#7972 Update "Enabled or disable SIP dial-in" documentation.
  docs/webinar.md
Labels: 4. to release, bug

#7971 Remove vue-clipboard2
  package-lock.json
  package.json
  src/components/CallView/shared/EmptyCallView.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/NewGroupConversation/Confirmation/Confirmation.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/TopBar/TopBar.vue
  src/main.js
Labels: 3. to review, bug, feature: frontend 🖌️

#7966 Fix console error 'Missing required prop: "isForwarderOpen"' in jest
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
Labels: 3. to review, bug

#7957 Color status icons of STUN, TURN and HPB
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️

#7963 Show empty content when all messages expired
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
Labels: 4. to release, bug, feature: chat 💬, feature: frontend 🖌️

#7964 Quote again when retrying to send a failed message
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#7974 Fix participant sessions not sent to the HPB
  lib/Signaling/Listener.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, bug, feature: signaling 📶

#7924 Fix room length to make compatible with database length
  docs/conversation.md
  lib/Controller/RoomController.php
  lib/Service/RoomService.php
  tests/integration/features/chat/public.feature
  tests/php/Service/RoomServiceTest.php
Labels: 4. to release, feature: api 🛠️

#7977 Fix new-conversation padding
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7978 Add Talk Changelog chat messages
  lib/Chat/Changelog/Manager.php
Labels: 4. to release, enhancement

#7976 Don't use shortcut "admin"
  lib/Controller/TempAvatarController.php
Labels: 4. to release, bug

#7975 Bump @nextcloud/vue@7.0.0-beta.5
  package-lock.json
  package.json
Labels: 3. to review

#7876 Fix action menus being cut
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesList.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7979 Adjust testing matrix for Nextcloud 25 on stable25
  .drone.jsonnet
  .drone.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/update-christophwurst-nextcloud.yml
Labels: 2. developing

#7982 [stable25] Fix action menus being cut
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesList.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, feature: frontend 🖌️

#7983 [stable25] Fix clipped link previews
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
Labels: 3. to review, feature: frontend 🖌️

#7985 Release 15.0.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7981 Fix clipped link previews
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7984 Add changelog for 15.0.0-rc.1
  CHANGELOG.md
Labels: 3. to review

#7992 Fix missing reaction summary when hovering
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 4. to release, bug, feature: frontend 🖌️, feature: reactions 👍

#7999 Improve emojipicker placement
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7998 Editing only works persistent with git add....
  tests/integration/spreedcheats/appinfo/info.xml
Labels: 3. to review, feature: api 🛠️

#8007 [stable25] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
  vendor-bin/phpunit/composer.lock
Labels: 3. to review, dependencies

#8006 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#8005 [master] Update christophwurst/nextcloud dependency
  composer.lock
  vendor-bin/phpunit/composer.lock
Labels: 3. to review, dependencies

#8015 Migrate to nextcloud/OCP package in master
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
  composer.lock
Labels: 3. to review, feature: api 🛠️, technical debt

#8017 Migrate to nextcloud/OCP package in stable24
  .github/workflows/psalm.yml
  composer.json
  composer.lock
Labels: 3. to review, feature: api 🛠️, technical debt

#8018 Migrate to nextcloud/OCP package in stable23
  .github/workflows/psalm.yml
  composer.json
  composer.lock
Labels: 3. to review, feature: api 🛠️, technical debt

#8022 Bump nextcloud/ocp package
  composer.lock
Labels: 4. to release

#8023 [stable25] Bump nextcloud/ocp package
  composer.lock
Labels: 4. to release

#8028 Recursion with lobby timer expiring
  lib/Room.php
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/lobby.feature
Labels: 4. to release, backport-request, bug, feature: api 🛠️, feature: meetings 📅, deployed on testing

#8031 Fix missing "Leave call" button for moderators
  src/components/TopBar/CallButton.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#8039 Updated the phpunit.xml to newest schema
  tests/php/phpunit.xml
Labels: 3. to review, feature: api 🛠️, php

#8011 Fix quotes of expired messages
  lib/Controller/ChatController.php
  src/components/Quote.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#8010 Remove references for deleted messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#8001 🏷️ /call/ reference provider
  lib/AppInfo/Application.php
  lib/Chat/ChatManager.php
  lib/Collaboration/Reference/ReferenceInvalidationListener.php
  lib/Collaboration/Reference/TalkReferenceProvider.php
  lib/Room.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Collaboration/Reference/TalkReferenceProviderTest.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#8045 Bump @nextcloud/vue to v7.0.0-beta.7
  package-lock.json
  package.json
Labels: 3. to review, backport-request

#8037 Fix left sidebar padding
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️

#7986 Allow to count the participants per call
  appinfo/info.xml
  lib/Command/Monitor/Calls.php
  lib/Command/Monitor/HasActiveCalls.php
  lib/Command/Monitor/Room.php
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/command/active-calls.feature
  tests/integration/features/command/monitor-calls.feature
  tests/integration/features/command/monitor-room.feature
  tests/psalm-baseline.xml
Labels: 3. to review, enhancement, feature: api 🛠️

#8049 Add changelog for 15.0.0-rc.2
  CHANGELOG.md
Labels: 3. to review, backport-request

#8057 Don't search in lobbied conversations
  .drone.jsonnet
  .drone.yml
  lib/Search/CurrentMessageSearch.php
  lib/Search/MessageSearch.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/notifications.feature
  tests/integration/features/callapi/password.feature
  tests/integration/features/chat-2/poll.feature
  tests/integration/features/chat-2/public-read-only.feature
  tests/integration/features/chat-2/public.feature
  tests/integration/features/chat-2/reaction.feature
  tests/integration/features/chat-2/read-status.feature
  tests/integration/features/chat-2/reference-id.feature
  tests/integration/features/chat-2/reply.feature
  tests/integration/features/chat-2/rich-messages.feature
  tests/integration/features/chat-2/rich-object-share.feature
  tests/integration/features/chat-2/search.feature
  tests/integration/features/chat-2/system-messages.feature
  tests/integration/features/chat-2/unread-messages.feature
  tests/integration/features/chat/delete.feature
  tests/integration/features/chat/file-share.feature
  tests/integration/features/chat/message-expiration.feature
  tests/integration/features/command/create.feature
  tests/integration/features/command/user-remove.feature
  tests/integration/features/conversation-2/one-to-one.feature
  tests/integration/features/conversation-2/password-request.feature
  tests/integration/features/conversation-2/promotion-demotion.feature
  tests/integration/features/conversation-2/public-private.feature
  tests/integration/features/conversation-2/remove-participant.feature
  tests/integration/features/conversation-2/remove-self.feature
  tests/integration/features/conversation-2/rename-room.feature
  tests/integration/features/conversation-2/set-description.feature
  tests/integration/features/conversation-2/set-listable.feature
  tests/integration/features/conversation-2/set-participant-permissions.feature
  tests/integration/features/conversation-2/set-password.feature
  tests/integration/features/conversation-2/set-permissions.feature
  tests/integration/features/conversation-2/sip-dialin.feature
  tests/integration/features/conversation/add-participant.feature
  tests/integration/features/conversation/delete-room.feature
  tests/integration/features/conversation/group-participants.feature
  tests/integration/features/conversation/limit-creation.feature
Labels: 4. to release, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: meetings 📅, feature: search 🔎
