Repository nextcloud/spreed, pull requests merged in 2022-04, with the labels that each got.

#7082 Bump @nextcloud/vue to 5.3.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6980 6927: updated button for message list
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, javascript

#7083 Fix closing MessageButtonsBar on Firefox
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug

#7034 Fix reconnections on single media permission changes
  src/utils/media/pipeline/MediaDevicesSource.js
  src/utils/media/pipeline/MediaDevicesSource.spec.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#7054 Replace deprecated String.prototype.substr()
  docs/Talkbuchet.js
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/StunServers.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/TurnServers.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/utils/signaling.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#7080 Fix forced reconnections when the HPB is not used
  src/utils/signaling.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#6962 6927: updated button for room selector
  src/components/MessagesList/MessagesList.vue
  src/views/RoomSelector.spec.js
  src/views/RoomSelector.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, javascript

#7093 Add integration tests for notifications
  .drone.jsonnet
  .drone.yml
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/notifications.feature
  tests/integration/features/conversation/add-participant.feature
  tests/integration/run.sh
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, feature: chat 💬, feature: api 🛠️, technical debt

#7107 Remove notifications for deleted messages
  lib/Notification/Notifier.php
  tests/integration/features/chat/notifications.feature
Labels: 3. to review, bug, feature: chat 💬, feature: api 🛠️

#7096 Make tests fail when deprecated php functions are used
  tests/php/phpunit.xml
Labels: 3. to review, technical debt

#7109 Followup: Use PHP7.4 property typehinting where possible
  lib/Chat/ChatManager.php
  lib/Chat/Command/Executor.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/ReactionManager.php
  lib/Command/ActiveCalls.php
  lib/Controller/ChatController.php
  lib/Events/CommandEvent.php
  lib/Events/EndCallForEveryoneEvent.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Notification/Notifier.php
  lib/Signaling/BackendNotifier.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
  tests/php/Chat/AutoComplete/SorterTest.php
  tests/php/Chat/NotifierTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Notification/NotifierTest.php
  tests/php/Settings/Admin/AdminSettingsTest.php
  tests/php/Settings/Admin/SectionTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, technical debt

#7102 Remove reactions from deleted messages
  lib/Chat/Parser/SystemMessage.php
  tests/integration/features/reaction/react.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: reactions 👍

#7112 Remove unused status code from documentation
  docs/reaction.md
Labels: 3. to review, feature: api 🛠️, feature: reactions 👍

#7101 Reset reaction details list when a reaction is added or removed
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/messagesStore.js
  src/store/reactionsStore.js
Labels: 3. to review, feature: frontend 🖌️, feature: reactions 👍

#7111 Fix message button bar for deleted messages
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#7116 Adjust Talkbuchet to be runnable with different parameters
  docs/Talkbuchet.js
Labels: 3. to review

#7113 Convert to null coalescing assignment operator
  lib/Share/RoomShareProvider.php
Labels: 3. to review, feature: api 🛠️, standardisation

#7119 Remove undefined property or method usage
  src/views/Dashboard.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7124 Adjust packaging exclude list for 24
  Makefile
Labels: 3. to review, technical debt

#7120 Add changelog for 12.2.5 and 13.0.5
  CHANGELOG.md
Labels: 3. to review, technical debt

#7126 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#7128 [stable22] Add changelog for 12.2.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, technical debt

#7122 Changelog for 14.0.0 beta.1
  CHANGELOG.md
Labels: 3. to review, technical debt

#7118 Use tertiary-no-background for emoji picker
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7131 Bump version to 14.0.0-beta.1
  appinfo/info.xml
Labels: 3. to review, technical debt

#7114 Add constants for the verbs in the oc_comments table
  lib/Chat/ChatManager.php
  lib/Chat/Command/Executor.php
  lib/Chat/MessageParser.php
  lib/Chat/Parser/Listener.php
  lib/Chat/Parser/ReactionParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/ReactionManager.php
  lib/Controller/ChatController.php
  lib/Model/Message.php
  lib/Notification/Notifier.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, technical debt

#7135 Expose an attribute "self" in the reaction summary with the list of o…
  docs/chat.md
  lib/Chat/CommentsManager.php
  lib/Chat/ReactionManager.php
  lib/Controller/ChatController.php
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/messagesStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/reaction/react.feature
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, enhancement, feature: reactions 👍

#7115 3299: updated unread mentions viewport of conversation list
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, javascript

#7136 Fix menu overlap
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug, papercut, feature: frontend 🖌️

#7076 🗃️ Shared Items tab
  css/icons.scss
  img/folder-multiple-image.svg
  lib/Controller/ChatController.php
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/services/conversationSharedItemsService.js
  src/store/conversationSharedItemsStore.js
  src/store/storeConfig.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#7141 Fix category selection in reactions emoji picker
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: reactions 👍

#7143 Add changelog and bump version
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7146 Only switch to the participant tab when the token changes not any oth…
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, regression

#7142 Don't update last message of conversation with invisible message
  lib/Chat/ChatManager.php
  lib/Chat/ReactionManager.php
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#7149 Add item shares from chat messages directly to the store
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/constants.js
  src/store/conversationSharedItemsStore.js
  src/store/messagesStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#7151 7104: removing of heading auther name
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, javascript

#7130 Remove event to delete shares when user leave of room
  lib/Share/RoomShareProvider.php
  tests/integration/features/sharing-2/hooks.feature
Labels: 3. to review, feature: api 🛠️

#7169 Fix store stuff
  src/services/conversationSharedItemsService.js
  src/store/conversationSharedItemsStore.js
Labels: 3. to review, bug, feature: upload & shares & voice 📤🎙️

#7175 Changelog 24.0.0-rc.2
  CHANGELOG.md
Labels: backport-request

#7173 Move message.reactions.self to message.reactionsSelf to not merge different data structures
  docs/chat.md
  lib/Controller/ChatController.php
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/messagesStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/reaction/react.feature
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: reactions 👍

#7182 [stable24] Move message.reactions.self to message.reactionsSelf to not merge different data structures
  docs/chat.md
  lib/Controller/ChatController.php
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/messagesStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/reaction/react.feature
Labels: 4. to release, feature: reactions 👍

#7171 Move collaboration listener annonymous function to static
  lib/Collaboration/Collaborators/Listener.php
Labels: 3. to review, enhancement, feature: api 🛠️

#7170 Move changelog listener anonymous function to static
  lib/Chat/Changelog/Listener.php
Labels: 3. to review, enhancement, feature: api 🛠️

#7172 Move command listener anonymous function to static
  lib/Chat/Command/Listener.php
Labels: 3. to review, enhancement, feature: api 🛠️

#7184 Use actor and time information from the reaction not the message author
  lib/Chat/Notifier.php
Labels: 3. to review, backport-request, bug, feature: reactions 👍

#7185 Fix CSS variable name
  src/components/Description/Description.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️

#7193 Document that the lastMessage attribute is limited
  docs/conversation.md
Labels: 3. to review, backport-request, feature: api 🛠️

#7186 Fix access to undefined key
  lib/Controller/ChatController.php
Labels: 3. to review, feature: api 🛠️

#7180 Fix migration of attachment types for media
  appinfo/info.xml
  lib/Migration/Version14000Date20220330141647.php
Labels: 4. to release, bug, papercut, feature: upload & shares & voice 📤🎙️

#7197 Only set header when the value changed and the status is not 304
  lib/Controller/ChatController.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#7199 Open chat when in a call
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, backport-request, papercut, feature: frontend 🖌️, feature: call 👥

#7203 Add changelog for 14.0.0-rc.3
  CHANGELOG.md
Labels: backport-request

#7206 Fix upgrade with Postgres and Oracle
  lib/Migration/Version14000Date20220330141647.php
Labels: 3. to review, backport-request, bug

#7205 Fix reactions endpoints not accessible by guests
  lib/Controller/ReactionController.php
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/guestNameStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/reaction/react.feature
Labels: 4. to release, bug, feature: reactions 👍

#7214 Move status listeners anonymous functions to static
  lib/Status/Listener.php
Labels: 3. to review, feature: api 🛠️

#7215 Move sharing listeners to static
  lib/Listener/RestrictStartingCalls.php
  tests/php/Listener/RestrictStartingCallsTest.php
Labels: 3. to review, feature: api 🛠️

#7213 Move signaling listeners anonymous functions to static
  lib/Signaling/Listener.php
Labels: 3. to review, feature: api 🛠️, feature: signaling 📶

#7183 Move system message listeners to static methods
  lib/Chat/SystemMessage/Listener.php
  lib/Events/AlreadySharedEvent.php
  lib/Share/RoomShareProvider.php
  tests/psalm-baseline.xml
Labels: 3. to review, enhancement, feature: api 🛠️

#7154 Shared Items browser
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser/SharedItemsBrowser.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/mixins/sharedItems.js
  src/services/sharedItemsService.js
  src/store/sharedItemsStore.js
  src/store/storeConfig.js
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#7223 Add JSON option to active-calls command
  lib/Command/ActiveCalls.php
Labels: 3. to review, enhancement, feature: api 🛠️

#7225 Only request reactions once
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, feature: reactions 👍

#7234 Allow to get Reactions summary and media tab in read-only rooms
  lib/Controller/ChatController.php
  lib/Controller/ReactionController.php
Labels: 4. to release, backport-request, bug, feature: api 🛠️, feature: upload & shares & voice 📤🎙️, feature: reactions 👍

#6862 Disconnect received videos when not needed
  src/__mocks__/attachmediastream.js
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/Video.spec.js
  src/components/CallView/shared/Video.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/utils/signaling.js
  src/utils/webrtc/RemoteVideoBlocker.js
  src/utils/webrtc/RemoteVideoBlocker.spec.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, feature: WebRTC 🚡, feature: signaling 📶, feature: frontend 🖌️, feature: call 👥

#7235 🛃 Chat permission
  appinfo/info.xml
  docs/capabilities.md
  docs/constants.md
  lib/Capabilities.php
  lib/Collaboration/Collaborators/RoomPlugin.php
  lib/Controller/ChatController.php
  lib/Controller/ReactionController.php
  lib/Exceptions/PermissionsException.php
  lib/Middleware/InjectionMiddleware.php
  lib/Migration/Version15000Date20220427183026.php
  lib/Model/Attendee.php
  lib/Share/RoomShareProvider.php
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/PermissionsEditor/PermissionsEditor.vue
  src/constants.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/delete.feature
  tests/integration/features/chat/file-share.feature
  tests/integration/features/chat/group.feature
  tests/integration/features/chat/public.feature
  tests/integration/features/chat/rich-object-share.feature
  tests/integration/features/conversation-2/set-participant-permissions.feature
  tests/integration/features/conversation-2/set-permissions.feature
  tests/integration/features/reaction/react.feature
  tests/php/CapabilitiesTest.php
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
  tests/psalm-baseline.xml
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#7239 Theming adjustments to latest master
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/ConversationSettings/Matterbridge/BridgePart.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#7241 Use a normal link and open in new tab by default
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#7245 Add changelog for 14.0.0-rc.4
  CHANGELOG.md
Labels: 3. to review, backport-request

#7246 Adjust reactions order after server merge
  tests/integration/features/reaction/react.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#7240 Add changelog chat messages
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, bug

#7248 Move Room::verifyPassword() to the RoomService
  lib/Command/Room/TRoomCommand.php
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
  lib/Room.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  tests/php/Chat/SystemMessage/ListenerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/RoomTest.php
  tests/php/Service/RoomServiceTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, feature: api 🛠️, technical debt
