Repository nextcloud/spreed, pull requests merged in 2022-11, with the labels that each got.

#8270 Show voters count on voting screen for moderators
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
Labels: 4. to release, bug, feature: frontend 🖌️, feature: polls 📊

#8272 No notification for voting
  lib/Controller/PollController.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: polls 📊

#8278 Add changelog 12.2.8, 13.0.10, 14.0.6 and 15.0.1
  CHANGELOG.md
Labels: 3. to review, backport-request

#8274 Revert "[stable25] Bump @nextcloud/vue to 7.0.1"
  package-lock.json
  package.json
Labels: 4. to release, feature: frontend 🖌️

#8280 Add changelog 12.2.8, 13.0.10 and 14.0.6
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#8281 Add changelog 12.2.8 and 13.0.10
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#8282 Add changelog 12.2.8
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#8285 Only group messages for 5 minutes
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#8308 [stable25] Update nextcloud/ocp dependency
  vendor-bin/csfixer/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8307 [master] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8306 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8209 Reduce two menus to one
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/TopBar/TopBar.vue
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review, design, enhancement, feature: frontend 🖌️

#8284 Welcome on board
  appinfo/info.xml
Labels: 3. to review

#8286 Use the fallback of initial state directly
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
  src/store/helper.js
  src/store/settingsStore.js
  src/store/soundsStore.js
Labels: 4. to release, technical debt, feature: frontend 🖌️

#8261 Fix missing header
  lib/Controller/CommandController.php
  lib/Migration/CreateHelpCommand.php
  lib/Migration/Version7000Date20190724121137.php
  lib/OCP/Conversation.php
  lib/OCP/TalkBackend.php
  lib/Service/AttachmentService.php
Labels: 3. to review, technical debt

#8283 Make apache configuration check less error prone
  lib/Settings/Admin/AdminSettings.php
  src/components/AdminSettings/WebServerSetupChecks.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: api 🛠️

#8305 Fix permissions returned by getSharesInFolder
  lib/Share/RoomShareProvider.php
Labels: 3. to review, bug, feature: api 🛠️, feature: upload & shares & voice 📤🎙️

#8313 Move general CI to 8.0
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, technical debt

#8317 Fix bottom stripe of speaker view with high DPI
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, bug, regression, feature: frontend 🖌️, feature: call 👥

#8318 👋 Improve readme and JS actions
  .github/workflows/jest.yml
  .github/workflows/node.yml
  README.md
  docs/HPB-P2P.png
Labels: 3. to review, bug

#8291 Fix chat "not loading" and performance issue with many reactions or v…
  src/components/MessagesList/MessagesList.vue
  src/constants.js
  src/services/messagesService.js
  src/services/messagesService.spec.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#8330 Fix signaling server check when admin is blocked from talk
  lib/Middleware/CanUseTalkMiddleware.php
Labels: 4. to release, backport-request, bug, feature: settings ⚙️

#8335 Create pull request template
  .github/pull_request_template.md
Labels: 3. to review

#8348 [master] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8349 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8350 [stable25] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8359 Bump @nextcloud/vue to 7.1.0-beta.0
  package-lock.json
  package.json
Labels: 4. to release, bug, dependencies

#8360 [stable25] Bump @nextcloud/vue to 7.1.0-beta.0
  package-lock.json
  package.json
Labels: 4. to release, bug, dependencies

#8351 Remove poll data when deleting the message
  lib/Chat/ChatManager.php
  lib/Model/PollMapper.php
  lib/Model/VoteMapper.php
  lib/Service/PollService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/poll.feature
Labels: 4. to release, backport-request, bug, feature: api 🛠️, feature: frontend 🖌️, feature: polls 📊

#8213 Fix link and password option of new conversations
  package-lock.json
  package.json
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/NewGroupConversation/PasswordProtect/PasswordProtect.vue
Labels: 2. developing, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#8368 Make sure to initialise the in call flag with the default we use later…
  lib/Service/SessionService.php
Labels: 3. to review, backport-request, bug

#8369 Add callStartTime to room API
  lib/Controller/RoomController.php
Labels: 3. to review, enhancement, feature: api 🛠️

#8382 [master] Update nextcloud/ocp dependency
  vendor-bin/csfixer/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8383 [stable25] Update nextcloud/ocp dependency
  vendor-bin/csfixer/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8373 Document all used app config values
  docs/constants.md
  docs/settings.md
  lib/Settings/Admin/AdminSettings.php
Labels: 3. to review, bug

#8341 ⏺️ Recording part 1 - Add useful information to the top-bar
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/CallTime.vue
  src/components/TopBar/TopBar.vue
  src/store/participantsStore.js
Labels: 4. to release, enhancement, feature: frontend 🖌️, feature: call 👥

#8391 Move all API version requirements to the same format
  appinfo/routes/routesCallController.php
  appinfo/routes/routesChatController.php
  appinfo/routes/routesCommandController.php
  appinfo/routes/routesFilesIntegrationController.php
  appinfo/routes/routesGuestController.php
  appinfo/routes/routesMatterbridgeController.php
  appinfo/routes/routesPageController.php
  appinfo/routes/routesPollController.php
  appinfo/routes/routesPublicShareAuthController.php
  appinfo/routes/routesReactionController.php
  appinfo/routes/routesRoomController.php
  appinfo/routes/routesSignalingController.php
Labels: 3. to review, feature: api 🛠️, technical debt

#8265 Don't keep the session open when joining/leaving a room to reduce the…
  lib/Controller/RoomController.php
  lib/TalkSession.php
Labels: 3. to review, bug, feature: api 🛠️

#8401 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8402 Remove unused prop
  src/components/TopBar/CallTime.vue
Labels: 3. to review, bug
