Repository nextcloud/spreed, pull requests merged in 2022-10, with the labels that each got.

#8058 fix and improve mobile UX
  src/App.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue
Labels: 3. to review, feature: frontend 🖌️

#8059 Add "--database-custom-command" option to Docker helper script
  tests/integration/run-docker.sh
Labels: 3. to review

#8077 [stable25] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8076 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8075 [master] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8074 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8073 Fix disappearing conversation settings
  src/components/AdminSettings/GeneralSettings.vue
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/LobbySettings.vue
  src/components/ConversationSettings/LockingSettings.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/ConversationSettings/SipSettings.vue
  src/store/conversationsStore.js
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#8081 Fix chats not updating the read marker
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#8090 Resort participant actions
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
Labels: 3. to review, feature: frontend 🖌️

#8093 Re-group conversation settings
  src/components/ConversationSettings/ConversationPermissionsSettings.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/DangerZone.vue
  src/components/ConversationSettings/ExpirationSettings.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/ListableSettings.vue
  src/components/ConversationSettings/LobbySettings.vue
  src/components/ConversationSettings/LockingSettings.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/ConversationSettings/NotificationsSettings.vue
  src/components/ConversationSettings/SipSettings.vue
Labels: 3. to review, backport-request, bug, design, feature: settings ⚙️, feature: frontend 🖌️

#8087 Move setActiveSince to RoomService
  lib/Activity/Listener.php
  lib/Room.php
  lib/Service/RoomService.php
Labels: 3. to review, feature: api 🛠️, technical debt

#8085 Move to new event syntax
  lib/AppInfo/Application.php
  lib/Controller/PageController.php
Labels: 4. to release, feature: api 🛠️, technical debt

#8101 Improve resend invitations performance
  lib/Controller/RoomController.php
Labels: 3. to review, bug, feature: api 🛠️

#8102 Move get paricipant method
  lib/Chat/MessageParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Collaboration/Collaborators/Listener.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Listener/CircleDeletedListener.php
  lib/Listener/GroupDeletedListener.php
  lib/Manager.php
  lib/Middleware/InjectionMiddleware.php
  lib/Notification/Notifier.php
  lib/Room.php
  lib/Service/ParticipantService.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Notification/NotifierTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 4. to release, feature: api 🛠️, technical debt

#8097 Make the lobby opening a positive action
  src/components/RightSidebar/LobbyStatus.vue
Labels: 3. to review, backport-request, bug

#8096 Move share password to NcPasswordField
  src/components/ConversationSettings/LinkShareSettings.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#8103 Move more methods away from room model
  lib/Chat/ChatManager.php
  lib/Command/Room/TRoomCommand.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/Room.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
  tests/php/Service/RoomServiceTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, feature: api 🛠️, technical debt

#8112 Use new NcTextField component for Forwarder search
  src/views/RoomSelector.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#8114 [stable22] Fix participant sessions not sent to the HPB
  lib/Signaling/Listener.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, bug, feature: signaling 📶

#8089 😄 Frequently used emojis
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️

#8131 Changelog for 15.0.0-rc.3
  CHANGELOG.md
Labels: 3. to review, backport-request

#8133 Handle invalid browser versions more gracefully and fix Safari iPadOS…
  src/mixins/browserCheck.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#8129 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/Model/Message.php
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 4. to release, dependencies

#8130 [stable25] Update nextcloud/ocp dependency
  composer.lock
  lib/Model/Message.php
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 4. to release, dependencies

#8138 Fix silent call
  src/utils/signaling.js
  src/utils/webrtc/index.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#8141 Add changelog for 15.0.0-rc.4
  CHANGELOG.md
Labels: 3. to review, backport-request

#8147 Fix emoji picker version
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, backport-request, bug

#8146 Keep emoji picker open
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, bug, papercut, feature: frontend 🖌️

#8161 ✨ Upgrade to vue 7.0.0 final + 🤖 Reduce CI time
  .github/workflows/jest.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  package-lock.json
  package.json
Labels: 3. to review, backport-request, bug

#8166 Allow expiration in 1-1
  src/components/ConversationSettings/ConversationSettingsDialog.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#8183 [stable25] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8185 Test against postgres 14
  .github/workflows/phpunit.yml
Labels: backport-request

#8177 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#8179 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#8180 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#8181 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: backport-request, dependencies

#8191 [stable25] Test against postgres 14
  .github/workflows/phpunit.yml
Labels: 3. to review, bug

#8192 [stable24] Test against postgres 14
  .github/workflows/phpunit.yml
Labels: 3. to review, bug

#8193 [stable23] Test against postgres 14
  .github/workflows/phpunit.yml
Labels: 3. to review, bug

#8152 Add changelog for 15.0.0
  CHANGELOG.md
  docs/chat.png
  docs/file-darg-and-drop.png
  docs/screensharing.png
  docs/video-verfication.png
Labels: 2. developing, 3. to review, backport-request

#8196 Fix broken size of raise hand icon
  src/components/CallView/shared/VideoBottomBar.vue
Labels: 3. to review, backport-request, bug, high, feature: frontend 🖌️

#8195 Fix screenshot mode for grid view
  docs/call-in-action.jpg
  docs/call-in-action.png
  docs/screenshotplaceholders/placeholder-7.jpeg
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, bug, high, technical debt

#8199 Add expiration to the changelog
  CHANGELOG.md
Labels: 3. to review, backport-request

#8201 Fix requirements for RoomController routes
  appinfo/routes/routesRoomController.php
Labels: backport-request

#8210 Bump @nextcloud/vue to 7.0.1
  package-lock.json
  package.json
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#8220 Query in sqlite returning wrong result.
  lib/Command/Monitor/Calls.php
Labels: 3. to review, bug, feature: api 🛠️, php

#8226 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8225 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8224 added displayName to pending call message in 1on1 calls
  src/components/CallView/shared/EmptyCallView.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 👥

#8233 Hide the talk dashboard widget when the user is not allowed to use talk
  lib/Dashboard/TalkWidget.php
  lib/Exceptions/NotAllowedToUseTalkException.php
Labels: 4. to release, backport-request, bug, feature: api 🛠️

#8231 Do not show Talk sidebar if Talk is disabled for the user
  lib/Files/TemplateLoader.php
  src/PublicShareSidebar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#8245 Take the devicePixelRatio into consideration for the grid size calculation
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 👥

#8259 [stable25] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8258 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8257 [master] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#8239 Disable the dashboard widget with proper API
  lib/Dashboard/TalkWidget.php
  lib/Exceptions/NotAllowedToUseTalkException.php
Labels: 4. to release, bug, feature: api 🛠️

#8262 Add conversation delete support via OCP API
  lib/OCP/Conversation.php
  lib/OCP/TalkBackend.php
Labels: 4. to release, bug, feature: api 🛠️
