Repository nextcloud/spreed, pull requests merged in 2023-07, with the labels that each got.

#9809 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9901 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#9938 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9912 Use PHP8's constructor property promotion
  lib/Files/Listener.php
  lib/Files/TemplateLoader.php
  lib/Files/Util.php
  lib/Flow/Operation.php
  lib/Flow/RegisterOperationsListener.php
  lib/Listener/AMembershipListener.php
  lib/Listener/BeforeUserLoggedOutListener.php
  lib/Listener/CSPListener.php
  lib/Listener/CircleDeletedListener.php
  lib/Listener/CircleMembershipListener.php
  lib/Listener/DisplayNameListener.php
  lib/Listener/GroupDeletedListener.php
  lib/Listener/RestrictStartingCalls.php
  lib/Listener/UserDeletedListener.php
  lib/Maps/MapsPluginLoader.php
Labels: 3. to review

#9174 Chromium recording
  recording/server.conf.in
  recording/src/nextcloud/talk/recording/Config.py
  recording/src/nextcloud/talk/recording/Participant.py
  recording/src/nextcloud/talk/recording/Service.py
Labels: 3. to review, enhancement, feature: recordings ⏺️

#9657 Add background job to check TURN certificate
  appinfo/info.xml
  appinfo/routes.php
  appinfo/routes/routesCertificateController.php
  lib/BackgroundJob/CheckCertificates.php
  lib/Controller/CertificateController.php
  lib/Controller/RecordingController.php
  lib/Controller/SignalingController.php
  lib/Notification/Notifier.php
  lib/Service/CertificateService.php
  src/components/AdminSettings/RecordingServer.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/TurnServer.vue
  src/services/certificateService.js
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Service/CertificateServiceTest.php
Labels: 3. to review, enhancement, feature: settings ⚙️, feature: signaling 📶

#9939 Raise exception if the Nextcloud server responded with an HTTP error
  recording/src/nextcloud/talk/recording/BackendNotifier.py
Labels: 3. to review, bug, regression, feature: recordings ⏺️

#9940 Adjust user agent for recording server to not match with desktop client
  recording/src/nextcloud/talk/recording/__init__.py
Labels: 3. to review, bug, regression, feature: recordings ⏺️

#9913 Use PHP8's constructor property promotion
  lib/Middleware/InjectionMiddleware.php
  lib/Migration/CacheUserDisplayNames.php
  lib/Migration/ClearResourceAccessCache.php
  lib/Migration/CreateHelpCommand.php
  lib/Migration/FixNamespaceInDatabaseTables.php
  lib/Migration/Version10000Date20201015134000.php
  lib/Migration/Version11000Date20200922161218.php
  lib/Migration/Version14000Date20220217115327.php
  lib/Migration/Version14000Date20220330141647.php
  lib/Migration/Version15000Date20220427183026.php
  lib/Migration/Version2000Date20171026140256.php
  lib/Migration/Version2000Date20171026140257.php
  lib/Migration/Version2001Date20170707115443.php
  lib/Migration/Version2001Date20170929092606.php
  lib/Migration/Version2001Date20171026134605.php
  lib/Migration/Version2001Date20180103144447.php
  lib/Migration/Version3003Date20180718112436.php
  lib/Migration/Version3003Date20180718133519.php
  lib/Migration/Version7000Date20190724121136.php
  lib/Migration/Version7000Date20190724121137.php
Labels: 2. developing

#9941 chore(Jest) - clear jest output
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/test-setup.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#9945 Use PHP8's constructor property promotion
  lib/Settings/Admin/AdminSettings.php
  lib/Settings/Admin/Section.php
  lib/Settings/Personal.php
  lib/Share/Helper/DeletedShareAPIController.php
  lib/Share/Helper/ShareAPIController.php
  lib/Share/Listener.php
  lib/Share/RoomShareProvider.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Manager.php
  lib/Signaling/Messages.php
  lib/Status/Listener.php
Labels: 3. to review

#9910 fix(NewGroupConversation) - refactoring & focus on Confirmation page
  src/components/LeftSidebar/NewGroupConversation/Confirmation/Confirmation.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
Labels: backport-request, bug, feature: frontend 🖌️, accessibility

#9895 fix(MessagesList) - scroll sticky list to bottom, if reaction was added
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#9961 fix(CI): Fix occ-command-documentation.yml when running on GARM
  .github/workflows/occ-command-documentation.yml
Labels: 3. to review, backport-request, technical debt

#9964 feat(CI): Sign .drone.yml
  .drone.jsonnet
  .drone.yml
Labels: 3. to review

#9965 [stable27] feat(CI): Sign .drone.yml
  .drone.jsonnet
  .drone.yml
Labels: 3. to review

#9951 feat(recording): Make automatic call recording transcription opt-in
  docs/settings.md
  lib/Service/RecordingService.php
  tests/php/Service/RecordingServiceTest.php
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: recordings ⏺️

#9948 Refactor lib [Part1]
  lib/Activity/Setting.php
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/ChatManager.php
  lib/Chat/Command/Executor.php
  lib/Chat/Command/Listener.php
  lib/Chat/Command/ShellExecutor.php
  lib/Chat/Parser/UserMention.php
Labels: 3. to review, feature: api 🛠️, technical debt

#9969 Update nextcloud/ocp
  composer.lock
Labels: 3. to review, dependencies

#9970 Enable less/more specific errors
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review

#9973 Revert "Update nextcloud/ocp"
  composer.lock
Labels: 3. to review

#9972 chore(deps) - bump @nextcloud/event-bus from 3.0.2 to 3.1.0
  package-lock.json
  package.json
Labels: dependencies, javascript

#9975 chore(deps) - remove unused dependencies
  package-lock.json
  package.json
  webpack.common.config.js
Labels: feature: frontend 🖌️, dependencies, javascript

#9946 Use PHP8's constructor property promotion
  lib/Config.php
  lib/GuestManager.php
  lib/Manager.php
  lib/MatterbridgeManager.php
  lib/Participant.php
  lib/Room.php
  lib/TalkSession.php
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#9978 fix(chat)!: Remove threads v1 API changes
  docs/capabilities.md
  docs/chat.md
  lib/Capabilities.php
  lib/Model/Message.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/reply.feature
Labels: 3. to review, bug, feature: chat 💬, feature: api 🛠️

#9992 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9993 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9979 [stable27] chore(deps) - remove unused dependencies
  package-lock.json
  package.json
  webpack.common.config.js
Labels: feature: frontend 🖌️, dependencies, javascript

#9996 [stable27] fix(CI): Fix OCP package conflicting psr/container version
  composer.lock
  lib/BackgroundJob/CheckHostedSignalingServer.php
  lib/Config.php
  lib/MatterbridgeManager.php
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review

#9977 fix(status): Don't emit event when the user status did not update
  src/store/conversationsStore.js
Labels: 3. to review, backport-request, feature: frontend 🖌️, performance 🚀, feature: conversations 👥

#10004 Fix trying to use an audio sink as source
  recording/src/nextcloud/talk/recording/Benchmark.py
  recording/src/nextcloud/talk/recording/RecorderArgumentsBuilder.py
  recording/src/nextcloud/talk/recording/Service.py
Labels: 3. to review, bug, feature: recordings ⏺️

#9892 feat(store) replace Vuex `settingsStore` with equivalent Pinia store
  package-lock.json
  package.json
  src/components/NewMessage/NewMessage.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/main.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/mainRecording.js
  src/store/settingsStore.js
  src/store/storeConfig.js
  src/stores/__tests__/settings.spec.js
  src/stores/settings.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, dependencies

#9897 fix(MessagesList) - performance, search fixes and minor refactoring
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesList.vue
  src/services/messagesService.js
  src/services/messagesService.spec.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#10014 [stable26] fix(CI): Fix occ-command-documentation.yml when running on GARM
  .github/workflows/occ-command-documentation.yml
Labels: 3. to review

#10018 chore(deps): add @types/jest
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#10015 chore(release): Add changelog for 15.0.7, 16.0.5 and 17.0.2
  CHANGELOG.md
Labels: 2. developing

#10025 Release 16.0.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10026 Release 15.0.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10022 Don't require a global backened secret when allowall is not set
  recording/src/nextcloud/talk/recording/Config.py
Labels: 3. to review, bug, feature: recordings ⏺️

#9955 feat(OpenConversationsList) - Make list of open conversations discoverable and usable
  src/collections.js
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/OpenConversationsList/OpenConversationsList.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
  src/components/RoomSelector.spec.js
  src/components/RoomSelector.vue
  src/deck.js
  src/maps.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: conversations 👥

#10021 Revert mapping of cjs module
  jest.config.js
Labels: regression, feature: frontend 🖌️, dependencies, javascript

#10039 fix(MessagesList) - check if list is rendered before scrolling
  src/components/MessagesList/MessagesList.vue
Labels: bug, feature: chat 💬, feature: frontend 🖌️

#10037 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10048 fix(MessagesList) - check for temporary messages while soft updating
  src/components/MessagesList/MessagesList.vue
Labels: bug, regression, feature: chat 💬, feature: frontend 🖌️

#9995 fix(CI): Fix OCP package conflicting psr/container version
  composer.lock
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  vendor-bin/mozart/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review

#10052 follow-up(MessageList) - simplify id comparing for messages groups
  src/components/MessagesList/MessagesList.vue
Labels: enhancement, feature: chat 💬, feature: frontend 🖌️

#9980 fix(LeftSidebar) redo arrow navigation
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
  src/composables/useArrowNavigation.js
  src/mixins/arrowNavigation.js
Labels: bug, feature: frontend 🖌️, feature: conversations 👥

#10056 hide description and status from 1-1 conversation settings
  src/components/ConversationIcon.vue
  src/components/ConversationSettings/BasicInfo.vue
  src/components/ConversationSettings/ConversationAvatarEditor.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#10040 feat(CI): Create a GitHub issue on nextcloud/ocp update error
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#10062 fix(SIP): Show SIP info also when enabled without user PIN
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: SFU & SIP ☎️

#10067 feat(chat): Add a property to indicate whether markdown should be ren…
  docs/chat.md
  lib/Model/Message.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#10063 feat(Message) - support Markdown in messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 2. developing, enhancement, feature: chat 💬, feature: frontend 🖌️

#10058 Fix duplicating messages and improve performance
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
  src/utils/__tests__/objectUtils.spec.js
  src/utils/objectUtils.js
Labels: 3. to review, bug

#10072 chore(release): Add changelog for 17.0.3
  CHANGELOG.md
Labels: 3. to review, backport-request

#9997 fix(searchBox) - Conversation search UX improvements
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 3. to review, bug, feature: frontend 🖌️
