Repository nextcloud/spreed, pull requests merged in 2023-12, with the labels that each got.

#10925 Remove label from talk search input
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#11073 get text color from theme for unread marker
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️, accessibility

#11060 fix(SetContacts ): Remove unnecessary scroll
  src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
Labels: backport-request, bug, feature: frontend 🖌️, feature: search 🔎

#11064 fix(participants): cancel scheduled request when requesting new one
  src/mixins/getParticipants.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, performance 🚀

#11100 feat(NewGroupConversation): Always show create conversation button
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: enhancement, feature: frontend 🖌️, feature: conversations 👥

#11113 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11112 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11114 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11122 fix(shares): handle silent sending and input paste correctly
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11062 fix(chat): Only load current absence not future ones
  src/services/participantsService.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#11119 fix(activeSession): minor fixes
  src/composables/useActiveSession.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#11120 Fix file share with caption quote reply
  src/components/NewMessage/NewMessage.vue
  src/components/Quote.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11093 Add metadata to file parameters
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/ChatController.php
  lib/Share/Helper/FilesMetadataCache.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: upload & shares & voice 📤🎙️

#11040 fix(App): switch toggle button to dark theme in call
  src/App.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#11132 Fix(File share authentication): Remove unnecessary options
  src/PublicShareAuthRequestPasswordButton.vue
  src/PublicShareAuthSidebar.vue
  src/components/MediaSettings/MediaSettings.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#11127 fix(session): track mouse movement activity
  src/composables/useActiveSession.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#11136 [stable27] refactor: make browserCheck an util
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthRequestPasswordButton.vue
  src/PublicShareSidebar.vue
  src/components/TopBar/CallButton.vue
  src/mixins/browserCheck.js
  src/utils/browserCheck.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11142 [stable27] fix(ci): Update CI workflows
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/integration-summary-when-unrelated.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#11145 [stable27] Fix lost audio track on safari
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, bug, feature: WebRTC 🚡, feature: call 📹, browser: Safari

#10978 fix(activeSession): remove toast message
  src/composables/useActiveSession.js
Labels: 4. to release, backport-request, feature: chat 💬, feature: frontend 🖌️

#11144 [stable26] fix(CI): Test integration tests on GA
  .drone.jsonnet
  .drone.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  lib/Chat/Command/Executor.php
  lib/Service/CommandService.php
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
  tests/integration/config/behat.yml
  tests/integration/run.sh
Labels: 3. to review

#11152 chore(release): Add changelog for 18.0.0-rc.3
  CHANGELOG.md
Labels: 3. to review

#11155 fix(openapi): Bump openapi-extractor for improved API results
  lib/Controller/BreakoutRoomController.php
  openapi.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, bug, feature: api 🛠️

#11156 fix(settings): apply correct conditions to expiration settings
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/ExpirationSettings.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/ListableSettings.vue
  src/components/ConversationSettings/RecordingConsentSettings.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️, feature: conversations 👥

#11160 [stable28] Improve conversation test split to have more even execution times
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  tests/integration/features/chat-1/bots.feature
  tests/integration/features/chat-1/commands.feature
  tests/integration/features/chat-1/delete.feature
  tests/integration/features/chat-1/file-share.feature
  tests/integration/features/chat-1/group-read-only.feature
  tests/integration/features/chat-1/group.feature
  tests/integration/features/chat-1/mentions.feature
  tests/integration/features/chat-1/message-expiration.feature
  tests/integration/features/chat-1/note-to-self.feature
  tests/integration/features/chat-1/notifications.feature
  tests/integration/features/chat-1/one-to-one.feature
  tests/integration/features/chat-1/password.feature
  tests/integration/features/conversation-1/add-participant.feature
  tests/integration/features/conversation-1/avatar.feature
  tests/integration/features/conversation-1/breakout-rooms.feature
  tests/integration/features/conversation-1/bruteforce-protection.feature
  tests/integration/features/conversation-1/delete-room.feature
  tests/integration/features/conversation-1/delete-user.feature
  tests/integration/features/conversation-2/files.feature
  tests/integration/features/conversation-2/find-listed.feature
  tests/integration/features/conversation-2/join-listable.feature
  tests/integration/features/conversation-3/group-participants.feature
  tests/integration/features/conversation-3/invite-email.feature
  tests/integration/features/conversation-3/join-leave.feature
  tests/integration/features/conversation-3/limit-creation.feature
  tests/integration/features/conversation-3/lobby.feature
  tests/integration/features/conversation-3/one-to-one.feature
  tests/integration/features/conversation-3/public-private.feature
  tests/integration/features/conversation-4/password-request.feature
  tests/integration/features/conversation-4/promotion-demotion.feature
  tests/integration/features/conversation-4/remove-participant.feature
  tests/integration/features/conversation-4/remove-self.feature
  tests/integration/features/conversation-4/rename-room.feature
  tests/integration/features/conversation-5/set-description.feature
  tests/integration/features/conversation-5/set-listable.feature
  tests/integration/features/conversation-5/set-participant-permissions.feature
  tests/integration/features/conversation-5/set-password.feature
  tests/integration/features/conversation-5/set-permissions.feature
  tests/integration/features/conversation-5/sip-dialin.feature
  tests/integration/features/conversation-5/sip-dialout.feature
  tests/integration/features/sharing-1/create.feature
  tests/integration/features/sharing-1/delete.feature
  tests/integration/features/sharing-1/move.feature
  tests/integration/features/sharing-1/restore.feature
  tests/integration/features/sharing-3/hooks.feature
  tests/integration/features/sharing-4/sharees.feature
  tests/integration/features/sharing-4/transfer-ownership.feature
  tests/integration/features/sharing-4/update.feature
Labels: 3. to review

#11161 fix(messages): apply ltr styles to system messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, regression, feature: chat 💬, feature: frontend 🖌️

#11157 [stable27] fix(settings): apply correct conditions to expiration settings
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/ExpirationSettings.vue
Labels: 3. to review, regression, feature: frontend 🖌️, feature: conversations 👥

#11179 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11180 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11183 fix(CI): Make psalm more happy about not returning null
  lib/Share/Helper/FilesMetadataCache.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#11181 Add backend url to connection error
  src/utils/signaling.js
Labels: 3. to review, feature: signaling 📶, feature: frontend 🖌️

#11164 Release 18.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, overview

#11191 fix(OCC): Avoid using \OC::$server
  lib/Command/Developer/UpdateDocs.php
Labels: 3. to review, feature: api 🛠️, technical debt

#11188 fix(OCC): Fix error reporting and success message when adding a STUN …
  lib/Command/Stun/Add.php
Labels: 3. to review, backport-request, bug, feature: WebRTC 🚡, feature: api 🛠️

#11190 fix(matterbridge): Simplify "string starts with" check
  lib/Config.php
  lib/Controller/SignalingController.php
  lib/Deck/DeckPluginLoader.php
  lib/Flow/Operation.php
  lib/Maps/MapsPluginLoader.php
  lib/MatterbridgeManager.php
  lib/Migration/FixNamespaceInDatabaseTables.php
  lib/Recording/BackendNotifier.php
  lib/Room.php
  lib/Search/ConversationSearch.php
  lib/Search/MessageSearch.php
  lib/Service/CommandService.php
  lib/Settings/Admin/AdminSettings.php
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, feature: api 🛠️, technical debt

#11149 fix(shares): reserve space for file preview while it's loading
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, bug, enhancement, technical debt, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11192 fix(API): Remove unused member variables
  lib/Chat/Notifier.php
  lib/Federation/FederationManager.php
  lib/Service/RoomService.php
  tests/php/Chat/NotifierTest.php
Labels: 3. to review, feature: api 🛠️, technical debt

#11146 [stable27] chore(deps): audit dependencies
  package-lock.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#11072 feat(chat): Rate limit guests when mentioning others
  docs/chat.md
  lib/Chat/ChatManager.php
  lib/Controller/BotController.php
  lib/Controller/BreakoutRoomController.php
  lib/Controller/ChatController.php
  lib/Flow/Operation.php
  lib/Service/BreakoutRoomService.php
  openapi.json
  tests/php/Chat/ChatManagerTest.php
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#11202 fix(middleware): Add types as per OCP class we extend
  lib/Middleware/CanUseTalkMiddleware.php
  lib/Middleware/InjectionMiddleware.php
Labels: enhancement

#11201 fix(OCP): Move away from deprecated RedirectToDefaultAppResponse
  lib/Middleware/CanUseTalkMiddleware.php
  lib/Middleware/InjectionMiddleware.php
Labels: 3. to review, technical debt

#11210 fix(shares): accept returned value from function
  src/components/MediaSettings/VideoBackgroundEditor.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️, feature: call 📹

#11213 fix(chat): attach button position to invisible wrapper
  src/components/ChatView.vue
Labels: 3. to review, bug, regression, feature: chat 💬, feature: frontend 🖌️

#11165 feat(Pinia): migrate quoteReplyStore (Vuex) to chatExtrasStore (Pinia)
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/NewMessage/NewMessage.vue
  src/components/Quote.vue
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
  src/store/quoteReplyStore.js
  src/store/quoteReplyStore.spec.js
  src/store/storeConfig.js
  src/stores/__tests__/chatExtras.spec.js
  src/stores/chatExtras.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11217 [stable27] fix(chat): attach button position to invisible wrapper
  src/components/ChatView.vue
Labels: bug, regression, feature: chat 💬, feature: frontend 🖌️

#11220 fix(call): add safeguard for remote screen checking
  src/components/CallView/shared/ViewerOverlayCallView.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️, feature: call 📹

#11199 replace missing MDI icons with existing ones
  src/PublicShareSidebarTrigger.vue
  src/assets/missingMaterialDesignIcons/MenuPeople.vue
  src/assets/missingMaterialDesignIcons/PromotedView.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/LobbyScreen.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
  src/components/missingMaterialDesignIcons/CancelPresentation.vue
  src/components/missingMaterialDesignIcons/CategoryMonitoring.vue
  src/components/missingMaterialDesignIcons/GridView.vue
  src/components/missingMaterialDesignIcons/Lobby.vue
  src/components/missingMaterialDesignIcons/PresentToAll.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11226 fix(call): reset Media settings checkbox on modal close
  src/components/MediaSettings/MediaSettings.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹, feature: recordings ⏺️

#11166 Fix(Quote): Don't trim the quote when it is not image share with caption
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/Quote.vue
Labels: 3. to review, bug, regression, feature: chat 💬, feature: frontend 🖌️

#11228 fix(notifications): Fix the order of event listeners
  lib/AppInfo/Application.php
Labels: 3. to review, backport-request, bug, regression, feature: call 📹

#11219 Fix(ParticipantsStore): Purge the store so it deletes the removed conversation
  src/store/conversationsStore.js
Labels: backport-request, bug, feature: frontend 🖌️, feature: conversations 👥

#11225 fix(preview): preview size and semantic inside `a` element
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, bug, design, papercut

#11224 fix(shares): reply to message with attachments
  docs/chat.md
  lib/Chat/ChatManager.php
  lib/Chat/ReactionManager.php
  lib/Chat/SystemMessage/Listener.php
  src/components/NewMessage/NewMessage.vue
  src/store/fileUploadStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/chat-1/file-share.feature
  tests/integration/features/chat-1/notifications.feature
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
Labels: 3. to review, backport-request, regression, feature: api 🛠️, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11242 [stable28] fix(shares): reply to message with attachments
  docs/chat.md
  lib/Chat/ChatManager.php
  lib/Chat/ReactionManager.php
  lib/Chat/SystemMessage/Listener.php
  src/components/NewMessage/NewMessage.vue
  src/store/fileUploadStore.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/chat-1/file-share.feature
  tests/integration/features/chat-1/notifications.feature
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
Labels: 3. to review, bug, feature: api 🛠️, feature: frontend 🖌️

#11244 chore(release): Add changelog for 18.0.1
  CHANGELOG.md
Labels: 3. to review

#11245 Release 18.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#11253 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11107 fix(shares): allow to retry failed uploads
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11257 feat(bots): Add "Stable diffusion" bot to the list
  docs/bot-list.md
  docs/botscreenshots/stable-diffusion.png
Labels: 3. to review, feature: bots 🤖

#11222 fix: use body element if not the fullscreen
  src/App.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/ChatView.vue
  src/components/TopBar/TopBarMenu.vue
  src/store/uiModeStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#11260 [stable27] fix: use body element if not the fullscreen
  src/App.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/ChatView.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
  src/components/TopBar/TopBarMenu.vue
  src/store/uiModeStore.js
Labels: bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#11262 chore(release): Add changelog for 16.0.9 and 17.1.4
  CHANGELOG.md
Labels: 3. to review, backport-request

#11263 Release 17.1.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#11264 Release 16.0.9
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#11280 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11283 fix(mixins): remove unused `participant` mixin
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/PublicShareSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/TopBar/CallButton.vue
  src/mixins/participant.js
  src/views/MainView.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11292 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11291 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11297 fix(shares): use FilePicker component directly
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageAttachments.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11300 chore(deps): bump `vue` libraries from 2.7.15 to v2.7.16
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#11308 fix(vue3): migrate sessionIssueHandler mixin to composable
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/composables/useSessionIssueHandler.js
  src/mixins/sessionIssueHandler.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11301 chore(mixins): remove `video` mixin
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoVue.vue
  src/mixins/video.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11302 chore(deps): Bump nextcloud/vue to 8.4.0
  package-lock.json
  package.json
  src/App.vue
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/ConversationSettings/EditableTextField.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/NewMessage/NewMessage.vue
  src/stores/__tests__/sharedItems.spec.js
  src/stores/sharedItems.js
Labels: 3. to review, bug, feature: frontend 🖌️, dependencies

#11306 chore(pinia): migrate integrationsStore to Pinia
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
  src/init.js
  src/store/integrationsStore.js
  src/store/storeConfig.js
  src/stores/__tests__/integrations.spec.js
  src/stores/integrations.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11309 chore(pinia): migrate talk hash mixin and store
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/TopBar/CallButton.vue
  src/composables/useHashCheck.js
  src/mixins/talkHashCheck.js
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
  src/store/storeConfig.js
  src/store/talkHashStore.js
  src/stores/__tests__/talkHash.spec.js
  src/stores/talkHash.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11325 follow-up: adjust talkHash store
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/composables/useHashCheck.js
Labels: bug, technical debt, feature: frontend 🖌️
