Repository nextcloud/spreed, pull requests merged in 2023-10, with the labels that each got.

#10610 fix(NcAvatar) increase avatar sizes in call
  src/assets/avatar.scss
  src/assets/variables.scss
  src/components/AvatarWrapper/AvatarWrapper.spec.js
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/ChatView.vue
  src/components/ConversationIcon.vue
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/ConversationSettings/EditableTextField.vue
  src/components/ConversationSettings/Matterbridge/BridgePart.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageTypingIndicator.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/components/Quote.vue
  src/components/TopBar/TopBar.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
  src/constants.js
  src/views/MainView.vue
Labels: enhancement, technical debt, feature: frontend 🖌️, feature: call 📹

#10606 fix(note-to-self): Prevent creating duplicate "Note to self" conversa…
  lib/Participant.php
  lib/Service/NoteToSelfService.php
  lib/Service/RoomFormatter.php
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#10625 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10624 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#8788 Add support for building packages for the recording server
  .gitignore
  recording/README.md
  recording/docs/encoders.md
  recording/docs/index.md
  recording/docs/installation.md
  recording/packaging/Makefile
  recording/packaging/build.sh
  recording/packaging/nextcloud-talk-recording/MANIFEST.in
  recording/packaging/nextcloud-talk-recording/debian/nextcloud-talk-recording.install
  recording/packaging/nextcloud-talk-recording/debian/nextcloud-talk-recording.postinst
  recording/packaging/nextcloud-talk-recording/debian/nextcloud-talk-recording.service
  recording/packaging/nextcloud-talk-recording/debian/py3dist-overrides
  recording/packaging/nextcloud-talk-recording/setup.py
  recording/packaging/nextcloud-talk-recording/stdeb.cfg
  recording/packaging/selenium/MANIFEST.in
  recording/packaging/selenium/debian/py3dist-overrides
  recording/pyproject.toml
  recording/src/nextcloud/talk/recording/__main__.py
Labels: 3. to review, enhancement, feature: recordings ⏺️

#10632 fix(email): Fix sending re-invites to all emails
  lib/Controller/RoomController.php
  lib/Service/ParticipantService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/invite-email.feature
Labels: 3. to review, bug, feature: settings ⚙️, feature: api 🛠️, feature: conversations 👥

#10603 feat(conversation) - add Note to self conversation
  docs/constants.md
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/CallButton.vue
  src/constants.js
  src/services/conversationsService.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: enhancement, feature: conversations 👥

#10636 chore(PR): Split PR templates for UI and API work
  .github/pull_request_template.md
Labels: 3. to review

#10639 fix(docs): Add typing to capabilities
  composer.json
  lib/Capabilities.php
Labels: 3. to review, feature: api 🛠️, technical debt

#10186 Add OpenAPI
  .github/workflows/openapi.yml
  appinfo/routes/routesAvatarController.php
  appinfo/routes/routesBotController.php
  appinfo/routes/routesBreakoutRoomController.php
  appinfo/routes/routesCallController.php
  appinfo/routes/routesCertificateController.php
  appinfo/routes/routesChatController.php
  appinfo/routes/routesCommandController.php
  appinfo/routes/routesFederationController.php
  appinfo/routes/routesFilesIntegrationController.php
  appinfo/routes/routesGuestController.php
  appinfo/routes/routesHostedSignalingServerController.php
  appinfo/routes/routesMatterbridgeController.php
  appinfo/routes/routesMatterbridgeSettingsController.php
  appinfo/routes/routesPollController.php
  appinfo/routes/routesPublicShareAuthController.php
  appinfo/routes/routesReactionController.php
  appinfo/routes/routesRecordingController.php
  appinfo/routes/routesRoomController.php
  appinfo/routes/routesSettingsController.php
  appinfo/routes/routesSignalingController.php
  composer.json
  lib/Chat/ReactionManager.php
  lib/Controller/AvatarController.php
  lib/Controller/BotController.php
  lib/Controller/BreakoutRoomController.php
  lib/Controller/CallController.php
  lib/Controller/CertificateController.php
  lib/Controller/ChatController.php
  lib/Controller/CommandController.php
  lib/Controller/FederationController.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/GuestController.php
  lib/Controller/HostedSignalingServerController.php
  lib/Controller/MatterbridgeController.php
  lib/Controller/MatterbridgeSettingsController.php
  lib/Controller/PageController.php
  lib/Controller/PollController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/ReactionController.php
  lib/Controller/RecordingController.php
  lib/Controller/RoomController.php
  lib/Controller/SettingsController.php
  lib/Controller/SignalingController.php
  lib/Controller/TempAvatarController.php
  lib/MatterbridgeManager.php
  lib/Model/BotServer.php
  lib/Model/Command.php
  lib/Model/Message.php
  lib/Model/Poll.php
  lib/Model/Reminder.php
  lib/Model/Vote.php
  lib/ResponseDefinitions.php
  lib/Service/RoomFormatter.php
  openapi.json
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 2. developing, feature: api 🛠️, technical debt

#10646 chore(recording): Split recording server code into new repo
  recording/LICENSE.txt
  recording/README.md
  recording/docker-compose/Dockerfile
  recording/docker-compose/docker-compose.yml
  recording/docker-compose/wrap_chromium_binary
  recording/docs/encoders.md
  recording/docs/index.md
  recording/docs/installation.md
  recording/docs/recording-api.md
  recording/packaging/Makefile
  recording/packaging/build.sh
  recording/packaging/nextcloud-talk-recording/MANIFEST.in
  recording/packaging/nextcloud-talk-recording/debian/nextcloud-talk-recording.install
  recording/packaging/nextcloud-talk-recording/debian/nextcloud-talk-recording.postinst
  recording/packaging/nextcloud-talk-recording/debian/nextcloud-talk-recording.service
  recording/packaging/nextcloud-talk-recording/debian/py3dist-overrides
  recording/packaging/nextcloud-talk-recording/setup.py
  recording/packaging/nextcloud-talk-recording/stdeb.cfg
  recording/packaging/selenium/MANIFEST.in
  recording/packaging/selenium/debian/py3dist-overrides
  recording/pyproject.toml
  recording/server.conf.in
  recording/src/nextcloud/talk/recording/BackendNotifier.py
  recording/src/nextcloud/talk/recording/Benchmark.py
  recording/src/nextcloud/talk/recording/Config.py
  recording/src/nextcloud/talk/recording/Participant.py
  recording/src/nextcloud/talk/recording/RecorderArgumentsBuilder.py
  recording/src/nextcloud/talk/recording/Server.py
  recording/src/nextcloud/talk/recording/Service.py
  recording/src/nextcloud/talk/recording/__init__.py
  recording/src/nextcloud/talk/recording/__main__.py
  recording/start-container.sh
Labels: 3. to review, technical debt

#10635 feat(recording): ⏺️ Add API for recording consent Version2
  appinfo/info.xml
  appinfo/routes/routesRoomController.php
  docs/call.md
  docs/capabilities.md
  docs/constants.md
  docs/conversation.md
  docs/settings.md
  lib/Capabilities.php
  lib/Config.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Events/BeforeRoomModifiedEvent.php
  lib/Events/RoomModifiedEvent.php
  lib/Manager.php
  lib/Migration/Version18000Date20231005091416.php
  lib/Model/SelectHelper.php
  lib/ResponseDefinitions.php
  lib/Room.php
  lib/Service/RecordingService.php
  lib/Service/RoomFormatter.php
  lib/Service/RoomService.php
  lib/Settings/Admin/AdminSettings.php
  openapi.json
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/recording.feature
  tests/php/CapabilitiesTest.php
  tests/php/Service/RoomServiceTest.php
Labels: 3. to review, enhancement, feature: settings ⚙️, feature: api 🛠️, feature: recordings ⏺️

#10662 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10664 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10661 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10663 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10666 PHP 8.3 is now allowed by server
  .github/workflows/integration-pgsql.yml
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review, feature: api 🛠️, technical debt

#10668 Remove old and unmaintained junit extension
  tests/integration/composer.json
  tests/integration/composer.lock
  tests/integration/config/behat.yml
Labels: 3. to review, feature: api 🛠️, technical debt

#10640 fix(messagesStore) - Mentions in forwarded messages
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: bug, feature: chat 💬, feature: api 🛠️

#10638 Fix(MessageForwarder + NewGroupConversation) - The confirmation page enhancement
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
Labels: enhancement, technical debt, feature: frontend 🖌️

#10671 Use new workflow templates
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
Labels: 3. to review, technical debt

#10672 fix(Psalm): Move away from private and deprecated classes
  lib/Migration/Version10000Date20200819121721.php
  lib/Migration/Version10000Date20201012144235.php
  lib/Migration/Version10000Date20201015134000.php
  lib/Migration/Version11000Date20200922161218.php
  lib/Migration/Version11000Date20201011082810.php
  lib/Migration/Version11000Date20201201102528.php
  lib/Migration/Version11000Date20201204110210.php
  lib/Migration/Version11000Date20201209142525.php
  lib/Migration/Version11001Date20210211111527.php
  lib/Migration/Version12000Date20210528100404.php
  lib/Migration/Version13000Date20210625232111.php
  lib/Migration/Version13000Date20210901164235.php
  lib/Migration/Version13000Date20210921142733.php
  lib/Migration/Version13000Date20211007192733.php
  lib/Migration/Version14000Date20211203132513.php
  lib/Migration/Version14000Date20220330141647.php
  lib/Migration/Version2000Date20170707093535.php
  lib/Migration/Version2001Date20170707115443.php
  lib/Migration/Version2001Date20170913104501.php
  lib/Migration/Version2001Date20170921145301.php
  lib/Migration/Version2001Date20171009132424.php
  lib/Migration/Version2001Date20171026134605.php
  lib/Migration/Version2001Date20171031102049.php
  lib/Migration/Version2001Date20180103144447.php
  lib/Migration/Version3003Date20180707222130.php
  lib/Migration/Version3003Date20180718112436.php
  lib/Migration/Version3003Date20180718133519.php
  lib/Migration/Version3003Date20180720162342.php
  lib/Migration/Version3003Date20180722152849.php
  lib/Migration/Version3003Date20180730080327.php
  lib/Migration/Version4099Date20181001123058.php
  lib/Migration/Version5099Date20190121102337.php
  lib/Migration/Version5099Date20190319134820.php
  lib/Migration/Version6099Date20190627172429.php
  lib/Migration/Version7000Date20190717141457.php
  lib/Migration/Version7000Date20190724121136.php
  lib/Migration/Version8000Date20200407115318.php
  psalm.xml
Labels: 4. to release, feature: api 🛠️, technical debt

#10673 [stable27] - Mentions in forwarded messages
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
Labels: 4. to release, bug, feature: chat 💬, feature: frontend 🖌️

#7514 🌐 Talk federation auth
  lib/Chat/MessageParser.php
  lib/Controller/AEnvironmentAwareController.php
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  lib/Events/BeforeFederatedUserJoinedRoomEvent.php
  lib/Events/FederatedUserJoinedRoomEvent.php
  lib/Federation/FederationManager.php
  lib/Manager.php
  lib/Middleware/InjectionMiddleware.php
  lib/Room.php
  lib/Service/ParticipantService.php
  lib/Service/RoomFormatter.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/invite.feature
  tests/psalm-baseline.xml
Labels: 2. developing, enhancement, feature: federation 🌐

#10626 chore: bump @nextcloud/vue to v8.0.0-beta.8
  jest.config.js
  package-lock.json
  package.json
  src/App.vue
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
  src/components/BreakoutRoomsEditor/SendMessageDialog.vue
  src/components/ConversationIcon.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/LobbySettings.vue
  src/components/ConversationSettings/Matterbridge/BridgePart.vue
  src/components/ConversationSettings/NotificationsSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
  src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/components/RoomSelector.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/CallTime.vue
  src/components/TopBar/TopBar.vue
  src/test-helpers.js
  src/types/vendor/@nextcloud/vue.d.ts
Labels: 2. developing, design, feature: frontend 🖌️, dependencies

#10682 fix(federation): Fix federation invite system messages
  css/icons.css
  docs/chat.md
  lib/Chat/Parser/SystemMessage.php
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  tests/integration/features/federation/invite.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: frontend 🖌️, feature: federation 🌐

#10683 fix(federation): Error the POST /participant request when federation failed
  lib/BackgroundJob/RetryJob.php
  lib/Controller/RoomController.php
  lib/Federation/BackendNotifier.php
  lib/Federation/FederationManager.php
  lib/Service/ParticipantService.php
  tests/integration/features/federation/invite.feature
  tests/php/Federation/FederationTest.php
  tests/php/Service/ParticipantServiceTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, feature: api 🛠️, feature: federation 🌐

#10678 fix(federation): Don't remove federation rooms while waiting for accept/reject
  lib/BackgroundJob/RemoveEmptyRooms.php
  lib/Controller/FederationController.php
  lib/Federation/FederationManager.php
  lib/Model/InvitationMapper.php
  lib/Notification/Notifier.php
  lib/ResponseDefinitions.php
  openapi.json
  tests/integration/features/federation/invite.feature
  tests/php/BackgroundJob/RemoveEmptyRoomsTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, feature: api 🛠️, feature: federation 🌐

#10685 fix(notification): Render the actions and remove notification on click
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/FederationManager.php
  lib/Notification/Notifier.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug, feature: api 🛠️, feature: federation 🌐

#10690 fix(CI): Fix conditions when to wait for integration tests results like with PHPUnit
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/integration-summary-when-unrelated.yml
Labels: 3. to review, feature: api 🛠️, technical debt

#10637 feat(MediaSettings) start recording together with call
  src/components/MediaSettings/MediaSettings.vue
  src/components/TopBar/CallButton.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: recordings ⏺️

#10693 fix(federation): Use constants for magic strings
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/FederationManager.php
Labels: 3. to review, feature: api 🛠️, technical debt, feature: federation 🌐

#10694 fix(participants): Don't throw an exception when inviting the same em…
  lib/Controller/RoomController.php
  tests/integration/features/conversation/invite-email.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#10688 Fix "silent" parameter not sent again when reconnecting
  src/utils/signaling.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#10687 Add minor RTL support for chat messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/components/Quote.vue
Labels: 3. to review, enhancement, feature: chat 💬, feature: frontend 🖌️

#10709 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10710 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10708 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10711 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10712 fix(messagesStore): clear deleted messages from replies
  src/store/messagesStore.js
Labels: backport-request, bug, regression, feature: chat 💬, feature: frontend 🖌️

#10717 fix(SIPBridge): fix typo when sending shared secret as payload
  src/components/AdminSettings/SIPBridge.vue
Labels: 4. to release, backport-request, bug, regression, feature: settings ⚙️

#10647 feat(ConversationSettings): expose conversation settings to non-moderators
  docs/chat.md
  docs/constants.md
  lib/Chat/Parser/SystemMessage.php
  lib/Manager.php
  lib/Room.php
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/ListableSettings.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: conversations 👥

#10589 Add key prop to NclistItem to re-render conversation with the appropr…
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: bug, regression, feature: frontend 🖌️, feature: conversations 👥

#10727 Fix consent in breakout rooms and missing updates on the room list
  lib/AppInfo/Application.php
  lib/Service/RoomService.php
  lib/Signaling/Listener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/breakout-rooms.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: recordings ⏺️

#10725 feat(consent): Save recording consent to DB and allow retrieving with OCC
  appinfo/info.xml
  docs/occ.md
  lib/AppInfo/Application.php
  lib/Command/Recording/Consent.php
  lib/Controller/CallController.php
  lib/Events/BeforeRoomDeletedEvent.php
  lib/Events/RoomDeletedEvent.php
  lib/Listener/UserDeletedListener.php
  lib/Migration/Version18000Date20231018065816.php
  lib/Model/Consent.php
  lib/Model/ConsentMapper.php
  lib/Recording/Listener.php
  lib/Service/ConsentService.php
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/recording.feature
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: recordings ⏺️

#10724 show MediaSettings if coming from notification "Join call"
  lib/Notification/Notifier.php
  src/App.vue
Labels: 3. to review, enhancement, feature: api 🛠️, feature: frontend 🖌️, feature: call 📹

#10669 Add presenter overlay when sharing screen
  src/components/CallView/CallView.vue
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: call 📹

#10679 Fix(LeftSidebar): Show hint when no filtered results
  src/components/LeftSidebar/LeftSidebar.vue
  src/store/conversationsStore.js
  src/utils/conversation.js
Labels: 3. to review, bug, feature: conversations 👥

#10633 feat(recording) - add frontend support for recording consent
  src/App.vue
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/AdminSettings/RecordingServers.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/RecordingConsentSettings.vue
  src/components/MediaDevicesSelector.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBarMenu.vue
  src/constants.js
  src/services/callsService.js
  src/services/conversationsService.js
  src/store/conversationsStore.js
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
  src/stores/__tests__/settings.spec.js
  src/stores/settings.js
  src/utils/signaling.js
  src/utils/webrtc/index.js
  src/views/FilesSidebarChatView.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: call 📹, feature: recordings ⏺️

#10754 [master] Update nextcloud/ocp dependency
  composer.lock
  psalm.xml
  tests/stubs/oca_circles.php
Labels: 3. to review, dependencies

#10736 Update README.md
  README.md
Labels: Hacktoberfest-ignore

#10714 fix(useActiveSession): adjust behavior of inactive session
  src/composables/useActiveSession.js
Labels: bug, regression, feature: conversations 👥

#10757 fix(docs): Add readthedocs config to try fixing the build
  .readthedocs.yaml
  Makefile
Labels: 3. to review, bug

#10730 feat(NewMessageUploadEditor) - caption to file share
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10760 fix(LeftSidebar): Adjust wording to be less email like
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: conversations 👥

#10762 fix(ChatView): minor fixes
  src/components/MessagesList/MessagesList.vue
  src/store/participantsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️

#10756 fix(event): Strict type the event after clarification with event cons…
  lib/Controller/SignalingController.php
  lib/Events/BeforeSignalingResponseSentEvent.php
Labels: 3. to review, feature: api 🛠️, technical debt

#10608 feat(sip-dialout): ☎️ API "SIP dial-out"
  appinfo/info.xml
  appinfo/routes/routesCallController.php
  appinfo/routes/routesRoomController.php
  composer.json
  composer.lock
  docs/call.md
  docs/capabilities.md
  docs/constants.md
  docs/participant.md
  docs/settings.md
  img/icon-conversation-phone-bright.svg
  img/icon-conversation-phone-dark.svg
  lib/Capabilities.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Config.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Migration/Version18000Date20230928131717.php
  lib/Model/Attendee.php
  lib/Model/AttendeeMapper.php
  lib/Model/SelectHelper.php
  lib/PublicShareAuth/Listener.php
  lib/ResponseDefinitions.php
  lib/Room.php
  lib/Service/AvatarService.php
  lib/Service/ParticipantService.php
  lib/Service/SIPDialOutService.php
  lib/Settings/Admin/AdminSettings.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Responses/DialOut.php
  lib/Signaling/Responses/DialOutError.php
  lib/Signaling/Responses/Response.php
  openapi.json
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/RecordingTrait.php
  tests/integration/features/callapi/sip-dialout.feature
  tests/integration/features/conversation-2/sip-dialout.feature
  tests/integration/features/conversation/invite-email.feature
  tests/integration/mocks/FakeRecordingServer.php
  tests/integration/mocks/FakeSignalingServer.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Service/SIPDialOutServiceTest.php
  tests/php/Signaling/BackendNotifierTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: SFU & SIP ☎️

#10675 Migrate to NcEmptyContent
  .eslintrc.js
  src/components/EmptyView.vue
  src/views/NotFoundView.vue
  src/views/SessionConflictView.vue
  src/views/WelcomeView.vue
  webpack.common.config.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#10764 fix(deps): Update CuyZ/Valinor after upstream fixed the regression from 1.6.1
  composer.json
  composer.lock
Labels: 3. to review, bug, feature: api 🛠️, feature: SFU & SIP ☎️

#10763 fix(NewGroupConversation): minor fix
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: regression, feature: conversations 👥

#10767 fix(Mention): show correct size according to font
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#10737 fix(LeftSidebar): Disable blur event in order to click on a conversation
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: search 🔎

#10696 [stable26] - fix message grouping for all locales
  src/components/MessagesList/MessagesList.vue
Labels: 4. to release, bug, feature: chat 💬, feature: frontend 🖌️

#10777 [stable26] Fix "silent" parameter not sent again when reconnecting
  src/utils/signaling.js
Labels: 3. to review, bug, feature: call 📹

#10778 [stable27] fix(Mention): show correct size according to font
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug

#10779 [Stable27] Add key prop to NclistItem to re-render conversation with the appropr…
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 4. to release, feature: frontend 🖌️, feature: conversations 👥

#10783 Remove disabled behat acceptance tests
  tests/acceptance/config/behat.yml
  tests/acceptance/features/app-files.feature
  tests/acceptance/features/bootstrap/ChatAncestorSetter.php
  tests/acceptance/features/bootstrap/ChatContext.php
  tests/acceptance/features/bootstrap/ConversationInfoContext.php
  tests/acceptance/features/bootstrap/ConversationListContext.php
  tests/acceptance/features/bootstrap/FilesAppChatTabContext.php
  tests/acceptance/features/bootstrap/FilesAppRoomSharingContext.php
  tests/acceptance/features/bootstrap/ParticipantListContext.php
  tests/acceptance/features/bootstrap/PublicConversationContext.php
  tests/acceptance/features/bootstrap/PublicSharePasswordRequestContext.php
  tests/acceptance/features/bootstrap/TalkAppContext.php
  tests/acceptance/features/bootstrap/TalkPublicShareContext.php
  tests/acceptance/features/chat.feature
  tests/acceptance/features/conversation-public.feature
  tests/acceptance/features/conversation.feature
  tests/acceptance/features/lobby.feature
  tests/acceptance/features/public-share-auth.feature
  tests/acceptance/features/public-share.feature
  tests/acceptance/features/room-shares.feature
  tests/acceptance/installAndConfigureServer.sh
  tests/acceptance/run.sh
Labels: 3. to review, technical debt, feature: frontend 🖌️

#10785 fix(recording): Fail the recording server check when a HPB is configured
  lib/Controller/RecordingController.php
  src/components/AdminSettings/RecordingServer.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: signaling 📶, feature: recordings ⏺️

#10782 techdebt(context): Use injectFn instead of accessing IServerContainer
  lib/AppInfo/Application.php
  tests/psalm-baseline.xml
Labels: 3. to review, feature: api 🛠️, technical debt

#10784 chore(release): Add changelog for 16.0.7 and 17.1.2
  CHANGELOG.md
Labels: 3. to review

#10772 feat(ReactionToaster): Change to animated emojis 🎉
  img/emojis/Clap.gif
  img/emojis/Concerned.gif
  img/emojis/Heart.gif
  img/emojis/Joy.gif
  img/emojis/Party.gif
  img/emojis/Star-struck.gif
  img/emojis/Surprised.gif
  img/emojis/Thinking-face.gif
  img/emojis/Thumbs-down.gif
  img/emojis/Thumbs-up.gif
  src/components/CallView/shared/ReactionToaster.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: call 📹

#10797 Fix(MessageButtonsBar): hide delete message button for guests
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug, feature: chat 💬

#8546 Allow to prepare virtual participants without immediately joining the call
  docs/Talkbuchet-cli.py
Labels: 3. to review, enhancement, feature: WebRTC 🚡, feature: signaling 📶

#10805 refactor(signaling): Rename sendMessages endpoint for clarification
  appinfo/routes/routesSignalingController.php
  lib/Controller/SignalingController.php
  openapi.json
Labels: 3. to review, feature: api 🛠️, feature: signaling 📶

#10809 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10808 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10810 chore(deps): Update openapi-extractor
  openapi.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, feature: api 🛠️, dependencies

#10811 ci: Turn off builds for pushes and merges to master/stable*
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/occ-command-documentation.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: 3. to review

#10804 fix(signaling): Fix pullMessages return type
  lib/Controller/SignalingController.php
  lib/Signaling/Messages.php
  openapi.json
Labels: 3. to review, bug, feature: api 🛠️, feature: signaling 📶

#10799 techdebt(events): Migrate more event handling to `registerEventListener()` and typed events
  lib/AppInfo/Application.php
  lib/Chat/Command/Listener.php
  lib/Collaboration/Reference/ReferenceInvalidationListener.php
  lib/Collaboration/Resources/Listener.php
  lib/Files/Listener.php
  lib/Files/TemplateLoader.php
  lib/Share/Listener.php
  lib/Share/RoomShareProvider.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/oca_files_events.php
Labels: 3. to review, feature: api 🛠️, technical debt

#10729 feat(federation): Send room modifications via OCM notifications to re…
  lib/AppInfo/Application.php
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/FederationManager.php
  lib/Federation/Listener.php
  lib/Model/InvitationMapper.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/invite.feature
  tests/php/Federation/FederationTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: federation 🌐, feature: conversations 👥

#10733 feat(SIP Dial-out): frontend support
  css/icons.css
  img/icon-phone-white.svg
  lib/Chat/Parser/SystemMessage.php
  lib/Controller/CallController.php
  lib/Controller/SignalingController.php
  lib/Exceptions/DialOutFailedException.php
  lib/Service/ParticipantService.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Manager.php
  openapi.json
  package-lock.json
  package.json
  psalm.xml
  src/App.vue
  src/components/AdminSettings/SIPBridge.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/CallView/shared/EmptyCallView.vue
  src/components/ConversationIcon.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/DialpadPanel.vue
  src/components/LeftSidebar/CallPhoneDialog/CallPhoneDialog.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SipSettings.vue
  src/components/RoomSelector.vue
  src/components/SelectPhoneNumber.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBarMenu.vue
  src/composables/useSortParticipants.js
  src/constants.js
  src/mixins/readableNumber.js
  src/regionCodes.js
  src/services/callsService.js
  src/services/conversationsService.js
  src/store/conversationsStore.js
  src/store/participantsStore.js
  src/store/soundsStore.js
  src/utils/readableNumber.js
  src/utils/signaling.js
  src/utils/webrtc/index.js
  src/views/Dashboard.vue
  tests/stubs/GuzzleHttp_Exception_ServerException.php
  tests/stubs/oc_http_client_response.php
Labels: 2. developing, enhancement, feature: frontend 🖌️, feature: SFU & SIP ☎️

#10814 chore: Switch from master to main branch
  .github/contributing.md
  CHANGELOG.md
  Makefile
  README.md
  appinfo/info.xml
  docs/bot-list.md
Labels: 3. to review

#10816 techdebt(events): Migrate more event handling to `registerEventListener()` and typed events
  lib/Activity/Listener.php
  lib/AppInfo/Application.php
  lib/Notification/Listener.php
  lib/PublicShareAuth/Listener.php
Labels: 3. to review, feature: api 🛠️, technical debt
