Repository nextcloud/spreed, pull requests merged in 2023-09, with the labels that each got.

#10445 Change to border in focus
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️, feature: conversations 👥

#10447 fix(Message) - correctly show users reacted to message
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/store/messagesStore.js
  src/store/reactionsStore.js
Labels: backport-request, bug, feature: chat 💬, feature: frontend 🖌️, feature: reactions 👍

#10415 Add frontend bundle analyzing scripts
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#10464 perf(CallView) - add an option to disable background blur in call
  src/components/CallView/CallView.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: call 📹, performance 🚀

#10473 [stable26] perf(CallView) - add an option to disable background blur in call
  src/components/CallView/CallView.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: feature: frontend 🖌️, feature: call 📹, performance 🚀

#10474 [stable25] perf(CallView) - add an option to disable background blur in call
  src/components/CallView/CallView.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: feature: frontend 🖌️, feature: call 📹, performance 🚀

#10475 (guestNameStore) - Migrate to Pinia in guestNameStore
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/ReactionToaster.vue
  src/components/CallView/shared/Screen.vue
  src/components/CallView/shared/VideoVue.spec.js
  src/components/CallView/shared/VideoVue.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/NewMessage/NewMessageTypingIndicator.vue
  src/components/SetGuestUsername.vue
  src/mixins/getParticipants.js
  src/store/guestNameStore.js
  src/store/guestNameStore.spec.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
  src/store/storeConfig.js
  src/stores/__tests__/guestName.spec.js
  src/stores/guestName.js
Labels: feature: frontend 🖌️

#10323 Lazy load files sidebar of Talk
  src/FilesSidebarCallViewApp.vue
  src/FilesSidebarTabApp.vue
  src/components/LoadingComponent.vue
  src/views/FilesSidebarChatView.vue
  webpack.config.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#10488 [stable27] Lazy load files sidebar of Talk
  src/FilesSidebarCallViewApp.vue
  src/FilesSidebarTabApp.vue
  src/components/LoadingComponent.vue
  src/views/FilesSidebarChatView.vue
  webpack.config.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#10467 Add a welcome window to set username for guests
  src/components/ChatView.vue
  src/components/GuestWelcomeWindow.vue
  src/components/LobbyScreen.vue
  src/components/SetGuestUsername.vue
  src/stores/__tests__/guestName.spec.js
  src/stores/guestName.js
Labels: enhancement, feature: chat 💬, feature: frontend 🖌️, feature: meetings 📅

#10491 Hide message expiration set-up for non-moderators
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/ExpirationSettings.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#10476 techdebt(ParticipantsTab) - refactor participants list
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/TopBar/TopBar.vue
  src/composables/useSortParticipants.js
  src/mixins/userStatus.js
  src/utils/userStatus.js
Labels: backport-request, technical debt, feature: frontend 🖌️, performance 🚀

#10495 fix(Pinia) - move guestNameStore initialisation from mixin to components
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/TopBar/TopBar.vue
  src/mixins/getParticipants.js
Labels: 3. to review, bug, regression, feature: frontend 🖌️

#10489 techdebt(LoadingPlaceholder) - rewrite skeleton component
  src/components/LoadingPlaceholder.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/LoadingParticipant.vue
  src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
Labels: enhancement, feature: frontend 🖌️

#10494 feat(ParticipantsTab) - virtual scrolling for participants list
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
  src/components/RightSidebar/Participants/ParticipantsList/ParticipantsListVirtual.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, feature: frontend 🖌️, performance 🚀

#10514 chore(deps): bump nextcloud/vue from 7.12.4 to 7.12.5
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, feature: frontend 🖌️, dependencies, javascript

#10515 [stable27] chore(deps): bump nextcloud/vue from 7.12.4 to 7.12.5
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, feature: frontend 🖌️, dependencies, javascript

#10517 chore(release): Add changelog for 17.1.0
  CHANGELOG.md
Labels: 3. to review

#10519 Release 17.1.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, overview

#10521 [Docs] Replace ActivityPub mention by ActivityStreams
  docs/bots.md
Labels: 3. to review

#10524 fix(leftSidebar)- Keep the opened conversation in the list
  src/components/LeftSidebar/LeftSidebar.vue
Labels: backport-request, bug, regression, feature: conversations 👥

#10528 fix(bots): Fix notifications of bot messages and reactions
  lib/Listener/BotListener.php
  lib/Model/BotServerMapper.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/bots.feature
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug, feature: chat 💬, feature: bots 🤖

#10530 [stable27] fix(bots): Fix notifications of bot messages and reactions
  lib/Listener/BotListener.php
  lib/Model/BotServerMapper.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/bots.feature
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, bug, feature: bots 🤖

#10490 Allow non-moderators to leave conversation with enabled lobby
  lib/Service/RoomFormatter.php
Labels: backport-request, bug, feature: api 🛠️, feature: meetings 📅

#10459 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10461 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10485 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10460 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10525 Add a copy function for code blocks
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, enhancement, feature: chat 💬, feature: frontend 🖌️

#10532 fix(API): Reuse participant objects we already created
  lib/Chat/ChatManager.php
  lib/Chat/MessageParser.php
  lib/Chat/Parser/Changelog.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Manager.php
  lib/Model/Attendee.php
  lib/Service/ParticipantService.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: conversations 👥

#10523 fix(participantsStore) - handle participants fetch through the store
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/TopBar.vue
  src/mixins/getParticipants.js
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: conversations 👥

#10539 fix(Message | JSDOC) - trim space, fix lint warnings
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/utils/webrtc/simplewebrtc/getscreenmedia.js
Labels: regression, feature: frontend 🖌️

#9432 feat(ffmpeg): allow custom common options
  recording/docs/encoders.md
  recording/server.conf.in
  recording/src/nextcloud/talk/recording/Benchmark.py
  recording/src/nextcloud/talk/recording/Config.py
  recording/src/nextcloud/talk/recording/RecorderArgumentsBuilder.py
Labels: 3. to review, enhancement, feature: recordings ⏺️

#10543 feat(Viewer) - allow to list shared media
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageNewFileDialog.vue
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser/SharedItemsBrowser.vue
  src/composables/useViewer.js
  src/store/sharedItemsStore.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10546 [stable27] fix(page): Decouple the index controller from the executing method
  lib/Controller/PageController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/bruteforce-protection.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#10547 [stable26] fix(page): Decouple the index controller from the executing method
  .drone.jsonnet
  .drone.yml
  lib/Controller/PageController.php
  tests/integration/run.sh
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#10548 [stable25] fix(page): Decouple the index controller from the executing method
  .drone.jsonnet
  .drone.yml
  lib/Controller/PageController.php
  tests/integration/run.sh
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#10537 techdebt(SharedItemsTab) - refactoring of shared items tab
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Location.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/components/Quote.vue
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/components/RightSidebar/SharedItems/sharedItemsConstants.js
  src/mixins/sharedItems.js
  src/store/messagesStore.js
  src/store/sharedItemsStore.js
  src/utils/getItemTypeFromMessage.js
Labels: 3. to review, technical debt, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10553 chore(release): Add changelog for 15.0.8, 16.0.6 and 17.1.1
  CHANGELOG.md
Labels: 3. to review, overview

#10557 fix(RightSidebar) update active tab on mount and conversation change
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
Labels: 4. to release, backport-request, bug, regression, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10568 fix(ConversationIcon) adjust fallback icon size
  src/components/ConversationIcon.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: conversations 👥

#10571 techdebt(CI): Prepare unit tests for PHPUnit 10
  composer.json
  tests/php/Activity/Provider/BaseTest.php
  tests/php/Activity/Provider/InvitationTest.php
  tests/php/Activity/SettingTest.php
  tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
  tests/php/BackgroundJob/RemoveEmptyRoomsTest.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
  tests/php/Chat/AutoComplete/SorterTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/Command/ExecutorTest.php
  tests/php/Chat/Command/ShellExecutorTest.php
  tests/php/Chat/NotifierTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
  tests/php/Collaboration/Reference/TalkReferenceProviderTest.php
  tests/php/Collaboration/Resources/ConversationProviderTest.php
  tests/php/ConfigTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Listener/RestrictStartingCallsTest.php
  tests/php/Model/AttendeeMapperTest.php
  tests/php/Notification/NotifierTest.php
  tests/php/Service/AvatarServiceTest.php
  tests/php/Service/BreakoutRoomServiceTest.php
  tests/php/Service/ChecksumVerificationServiceTest.php
  tests/php/Service/RecordingServiceTest.php
  tests/php/Service/RoomServiceTest.php
  tests/php/Settings/Admin/AdminSettingsTest.php
  tests/php/TalkSessionTest.php
Labels: 3. to review, feature: api 🛠️, technical debt

#10586 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10588 fix(RightSidebar) - Optimize update active tab ( sharedItems)
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
Labels: regression, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10573 techdebt(sharedItems) migrate store to Pinia
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/store/messagesStore.js
  src/store/sharedItemsStore.js
  src/store/storeConfig.js
  src/stores/__tests__/sharedItems.spec.js
  src/stores/sharedItems.js
Labels: 2. developing, technical debt, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10591 [stable26] Optimize update active tab ( sharedItems)
  src/components/LoadingComponent.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
Labels: 3. to review, feature: frontend 🖌️

#10544 fix(notifications): Allow sessions to mark themselves as inactive
  appinfo/info.xml
  appinfo/routes/routesRoomController.php
  docs/capabilities.md
  docs/constants.md
  docs/participant.md
  lib/Capabilities.php
  lib/Controller/RoomController.php
  lib/Migration/Version18000Date20230920182747.php
  lib/Model/Session.php
  lib/Service/ParticipantService.php
  lib/Service/SessionService.php
  src/App.vue
  src/composables/useActiveSession.js
  src/constants.js
  src/services/messagesService.js
  src/services/messagesService.spec.js
  src/services/participantsService.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/notifications.feature
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#10593 feat(user_status): Increase participant limit to 1k users
  lib/Config.php
  lib/Controller/RoomController.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#10317 Fix capabilities endpoint with openai translation integration
  docs/capabilities.md
  lib/Capabilities.php
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
  tests/php/CapabilitiesTest.php
Labels: 2. developing, bug, feature: chat 💬, feature: api 🛠️, feature: frontend 🖌️

#10541 feat(note-to-self): Add API for note-to-self
  appinfo/routes/routesRoomController.php
  docs/capabilities.md
  docs/conversation.md
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Events/BeforeRoomsFetchEvent.php
  lib/Listener/NoteToSelfListener.php
  lib/Room.php
  lib/Service/NoteToSelfService.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/php/CapabilitiesTest.php
  tests/php/Service/RoomServiceTest.php
  tests/php/phpunit.xml
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#10471 Accept insecure certificates in the browser if "skipverify" is enabled
  recording/src/nextcloud/talk/recording/Participant.py
Labels: 3. to review, bug, feature: recordings ⏺️

#10598 fix(tests): Fix integration tests after merge of Translation capabili…
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/integration/capabilities.feature
Labels: 2. developing, high, feature: api 🛠️

#10604 fix(CI): Make sure the "when unrelated" fake summaries work correctly
  .github/workflows/integration-summary-when-unrelated.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
Labels: 3. to review, bug, feature: api 🛠️, technical debt, feature: frontend 🖌️

#10602 techdebt(NcAvatar) - optimize avatar wrappers
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/ConversationIcon.vue
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/GuestWelcomeWindow.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RoomSelector.vue
  src/components/TopBar/TopBar.vue
  src/views/Dashboard.vue
Labels: backport-request, regression, technical debt, feature: frontend 🖌️, client: 💻 desktop, feature: call 📹, feature: conversations 👥

#10607 deps: Add Valinor as dependency
  composer.json
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, enhancement, feature: api 🛠️, technical debt
