Repository nextcloud/spreed, pull requests merged in 2023-06, with the labels that each got.

#9632 feat(API): Allow to block older clients
  docs/global.md
  docs/index.md
  lib/Middleware/CanUseTalkMiddleware.php
  lib/Middleware/Exceptions/UnsupportedClientVersionException.php
  mkdocs.yml
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/integration/outdated-client.feature
Labels: 4. to release, enhancement, feature: api 🛠️

#9671 Correct Font weight for Subtitle
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, browser: Firefox

#9672 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#9684 chore(release): Add changelog for 17.0.0-rc.3
  CHANGELOG.md
Labels: 3. to review, backport-request, technical debt

#9687 Release/17.0.0 rc.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#9711 Responsive layout for `ConversationAvatarEditor`
  src/components/ConversationSettings/ConversationAvatarEditor.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, browser: Mobile View

#9709 Fix error when creating a conversation from search results
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️, feature: conversations 👥

#9715 Add fallback if label for background fileName doesn't exist
  src/components/MediaSettings/VideoBackgroundEditor.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️

#9689 Adjust typing indicator behaviour
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageTypingIndicator.vue
  src/store/participantsStore.js
  src/store/quoteReplyStore.js
  src/utils/SignalingTypingHandler.js
  src/utils/SignalingTypingHandler.spec.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#9721 Fix dark/light theme in `LoadingPlaceholder` and refactor dark theme detection
  src/components/ConversationIcon.vue
  src/components/LoadingPlaceholder.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/components/NewMessage/NewMessage.vue
  src/utils/isDarkTheme.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#9733 Fix CI with backports from master
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies

#9724 chore(release): Add changelog for 17.0.0-rc.4
  CHANGELOG.md
Labels: 2. developing, technical debt

#9734 Release/17.0.0 rc.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 2. developing, technical debt

#9762 Close sidebar on mobile resolution immediately after changing the route
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: conversations 👥

#9731 Fix displaying 'Screensharing' button after reject and refactor `TopBar` controls for 'Raise hand' and 'Screensharing'
  src/components/TopBar/TopBar.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#9727 Make pagination buttons in call (grid, stripe views) visible on call view hover
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️, feature: call 📹

#9770 chore(release): Add changelog for 17.0.0
  CHANGELOG.md
Labels: technical debt

#9771 Release/17.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: technical debt

#9778 Make conversation name and description selectable
  src/components/ConversationSettings/EditableTextField.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: frontend 🖌️

#9729 [stable26] Fix dark/light theme in `LoadingPlaceholder`
  src/components/LoadingPlaceholder.vue
Labels: bug, feature: frontend 🖌️

#9788 Adjust navigation buttons offset for call in Grid view
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: call 📹

#9787 Show `Guest` to self when guest reacts in call with no name
  src/components/CallView/shared/ReactionToaster.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#9774 Prevent the navigation bar from floating
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: backport-request, bug, feature: frontend 🖌️, feature: conversations 👥

#9795 fix(LeftSidebar): fix scroll with new created conversations
  src/components/LeftSidebar/LeftSidebar.vue
Labels: backport-request, bug, feature: frontend 🖌️

#9815 fix(Poll) - hide voters number from open poll if user has not voted
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: polls 📊

#9812 fix(NewMessageNewFileDialog) - fix creation of file from Blank template
  src/components/NewMessage/NewMessageNewFileDialog.vue
  src/services/filesSharingServices.js
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#9820 follow-up (Poll) - change description for open polls
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: polls 📊

#9824 [stable26] fix(CI): Backport updated actions
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/occ-command-documentation.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#9825 [stable25] fix(CI): Backport updated actions
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/dependabot-approve.yml
  .github/workflows/fixup.yml
  .github/workflows/jest.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
Labels: 3. to review

#9827 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#9823 fix(Grid) - finetune columns calculations
  src/components/CallView/Grid/Grid.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#9837 fix(participants): Update cached displayname when a group is renamed
  lib/AppInfo/Application.php
  lib/Listener/DisplayNameListener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/group-participants.feature
Labels: 3. to review, backport-request, feature: api 🛠️, feature: conversations 👥

#9832 Optimize conversations update on Frontend
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
Labels: 3. to review, backport-request, feature: frontend 🖌️, performance 🚀

#9834 Chore(deps): Bump emoji-mart-vue-fast from 12.0.5 to 15.0.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies, javascript, feature: reactions 👍

#9844 chore(release): Add changelog for 17.0.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, backport-request

#9845 Releasing 17.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9826 fix(styles): prevent typing indicator overlay
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageTypingIndicator.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#9810 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9860 Update phpunit-mysql.yml to latest
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review, backport-request

#9862 [stable27] Update phpunit-mysql.yml
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review

#9863 [stable26] Update phpunit-mysql.yml
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review

#9828 Documentation: Add eturnal as a second TURN server example
  docs/TURN.md
  docs/coturn.md
  docs/eturnal.md
  docs/index.md
  mkdocs.yml
Labels: 3. to review

#9688 Filter conversation list for unread / mentioned conversations only
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/mixins/arrowNavigation.js
Labels: 2. developing, enhancement, feature: frontend 🖌️, feature: conversations 👥

#9870 fix(ParticipantsTab) replace v-model for SearchBox component
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, regression, feature: frontend 🖌️

#9861 follow-up(ChatView) - align scroll button position with mobile clients
  src/components/ChatView.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, regression, feature: chat 💬, feature: frontend 🖌️
