Repository nextcloud/spreed, pull requests merged in 2023-05, with the labels that each got.

#9401 dev(frontend): Add "npm run serve" which allows to run with HMR
  README.md
  package.json
Labels: 3. to review, technical debt, feature: frontend 🖌️

#9383 fix(chat): Conversation avatar for mention chips
  css/icons.css
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#9067 Fix json output
  docs/occ.md
  lib/Command/Command/Add.php
  lib/Command/Command/AddSamples.php
  lib/Command/Command/ListCommand.php
  lib/Command/Command/TRenderCommand.php
  lib/Command/Command/Update.php
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/command/command-list.feature
Labels: 3. to review, backport-request

#9384 Refactor Administrator settings for Talk
  src/components/AdminSettings/AllowedGroups.vue
  src/components/AdminSettings/CommandVue.vue
  src/components/AdminSettings/Commands.vue
  src/components/AdminSettings/GeneralSettings.vue
  src/components/AdminSettings/HostedSignalingServer.vue
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/AdminSettings/RecordingServer.vue
  src/components/AdminSettings/RecordingServers.vue
  src/components/AdminSettings/SIPBridge.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/SignalingServers.vue
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/StunServers.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/TurnServers.vue
  src/views/AdminSettings.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#9411 Fix diverging user status
  docs/conversation.md
  lib/Controller/RoomController.php
  lib/Service/RoomFormatter.php
  src/store/conversationsStore.js
Labels: 3. to review, backport-request, feature: api 🛠️, feature: frontend 🖌️, feature: conversations 👥

#9409 Fix mentions of groups and guests as well as users with spaces
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#9413 fix(permissions): Reset custom permissions on promotion
  appinfo/info.xml
  lib/Migration/Version16000Date20230502145340.php
  lib/Service/ParticipantService.php
  tests/integration/features/conversation-2/promotion-demotion.feature
Labels: 3. to review, feature: api 🛠️

#9412 Keep guest attendees with values
  lib/Controller/RoomController.php
  lib/Service/ParticipantService.php
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, bug, feature: chat 💬

#9424 feat(avatar): Use the first emoji of room names as avatar emoji
  lib/Service/AvatarService.php
  tests/php/Service/AvatarServiceTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#9429 chore(front): make unit-testing cross-platform
  jest.config.js
  jest.global.setup.js
  package.json
  src/__mocks__/styles.js
Labels: 3. to review, technical debt

#9433 Updates lib/Config.php PHPDoc comments.
  lib/Config.php
Labels: 3. to review, bug, feature: api 🛠️

#9436 feat(chat): Highlight own group mentions with primary
  lib/Controller/PageController.php
  lib/Files/TemplateLoader.php
  lib/PublicShare/TemplateLoader.php
  lib/PublicShareAuth/TemplateLoader.php
  lib/TInitialState.php
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#9423 Expose if the room has a custom avatar
  docs/avatar.md
  docs/conversation.md
  lib/Service/AvatarService.php
  lib/Service/RoomFormatter.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/one-to-one.feature
  tests/integration/features/conversation/avatar.feature
  tests/integration/features/integration/dashboard.feature
  tests/php/Service/AvatarServiceTest.php
Labels: 3. to review, feature: api 🛠️, php

#9439 chore(deps): Bump @nextcloud/vue to v7.11.1
  package-lock.json
  package.json
Labels: 3. to review, dependencies, javascript

#9336 Editor/Viewer while in a call (Viewer Overlay Call View)
  package-lock.json
  package.json
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/PublicShareSidebar.vue
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalMediaControls.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBarMenu.vue
  src/composables/useIsInCall.js
  src/composables/useStore.js
  src/composables/useViewer.js
  src/mixins/isInCall.js
  src/store/callViewStore.js
  src/views/MainView.vue
Labels: 3. to review, feature: frontend 🖌️

#9371 `RightSidebar` improvements and bug fixes (participant tabs)
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#9408 Replace native inputs with NcTextfield
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/SetGuestUsername.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/views/WelcomeView.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, accessibility

#9452 fix(tests): Fix capability unit tests after merge of custom avatar upload
  tests/php/CapabilitiesTest.php
Labels: 3. to review, bug, feature: api 🛠️

#9385 Create a data-channel when testing the turn setup
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, bug, feature: WebRTC 🚡, browser: Safari

#9443 feat(avatar): Allow to select an emoji + color as avatar
  appinfo/routes/routesAvatarController.php
  docs/avatar.md
  lib/Controller/AvatarController.php
  lib/Service/AvatarService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/avatar.feature
Labels: 3. to review, enhancement, feature: conversations 👥

#9334 Fix signaling messages sent to all participants
  src/utils/webrtc/simplewebrtc/webrtc.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, bug, feature: signaling 📶, feature: call 📹

#9459 fix(CI): Fix Psalm and CS
  lib/Controller/AvatarController.php
  lib/Service/AvatarService.php
Labels: 3. to review, bug

#9461 fix(deps): Update @nextcloud/vue to 7.11.2
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#9447 Allow to select an emoji + color as avatar [web client]
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/services/conversationsService.js
  src/store/conversationsStore.js
Labels: 3. to review, enhancement, feature: frontend 🖌️

#9453 Release 17.0.0 beta.1
  CHANGELOG.md
  Makefile
  appinfo/info.xml
  lib/Chat/Changelog/Manager.php
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#9457 Techdebt: add ESLint rules to prepare for Vue 3 migration
  .eslintrc.js
  src/FilesSidebarCallViewApp.vue
  src/PublicShareSidebarTrigger.vue
  src/components/AdminSettings/RecordingServer.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
  src/components/BreakoutRoomsEditor/SendMessageDialog.vue
  src/components/CallView/Grid/Grid.vue
  src/components/ConversationSettings/EditableTextField.vue
  src/components/ConversationSettings/ListableSettings.vue
  src/components/ConversationSettings/Matterbridge/BridgePart.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/components/MediaDevicesSelector.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessageForm/AudioRecorder/AudioRecorder.vue
  src/components/NewMessageForm/NewMessageForm.vue
  src/components/NewMessageForm/SimplePollsEditor/PollOption.vue
  src/components/NewMessageForm/SimplePollsEditor/SimplePollsEditor.vue
  src/components/NewMessageForm/TemplatePreview.vue
  src/components/PermissionsEditor/PermissionsEditor.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
  src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
  src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser/SharedItemsBrowser.vue
  src/components/missingMaterialDesignIcons/CancelPresentation.vue
  src/components/missingMaterialDesignIcons/CategoryMonitoring.vue
  src/components/missingMaterialDesignIcons/GridView.vue
  src/components/missingMaterialDesignIcons/Lobby.vue
  src/components/missingMaterialDesignIcons/MenuPeople.vue
  src/components/missingMaterialDesignIcons/PresentToAll.vue
  src/components/missingMaterialDesignIcons/PromotedView.vue
  src/views/FlowPostToConversation.vue
  src/views/RoomSelector.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#9456 techdebt(api): Make the checksum verification generic so it can be re…
  lib/Controller/RoomController.php
  lib/Service/ChecksumVerificationService.php
  tests/php/Service/ChecksumVerificationServiceTest.php
Labels: 3. to review, technical debt

#9441 refactor: replace `indexOf` with `includes`
  src/components/AdminSettings/TurnServer.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MediaDevicesSelector.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/NewMessageForm/TemplatePreview.vue
  src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/ParticipantPermissionsEditor/ParticipantPermissionsEditor.vue
  src/components/TopBar/CallButton.vue
  src/mixins/devices.js
  src/utils/media/pipeline/TrackToStream.spec.js
  src/utils/webrtc/webrtc.js
Labels: 3. to review, feature: frontend 🖌️

#9487 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9486 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9485 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9465 Add Avatar editor to new conversation dialog
  jest.config.js
  src/components/ConversationIcon.vue
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: conversations 👥

#9490 Mention "Firefox Multi-Account Containers" in Readme
  README.md
Labels: 3. to review

#9462 Add messageId to richObject in ReferenceProvider
  lib/Collaboration/Reference/TalkReferenceProvider.php
Labels: 3. to review, feature: api 🛠️, feature: integration 📦

#9494 Block fixup and squash commits
  .github/workflows/fixup.yml
Labels: 3. to review, backport-request, technical debt

#9492 Add capability check around avatar handling
  src/components/ConversationIcon.vue
  src/components/ConversationSettings/BasicInfo.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️, feature: conversations 👥

#9498 Add .editorconfig with same rules as Nextcloud server
  .editorconfig
Labels: 3. to review

#9460 fix/9446/add-empty-call-view-to-viewer-overlay
  src/components/CallView/CallView.vue
  src/components/CallView/shared/EmptyCallView.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
Labels: 4. to release, bug, feature: frontend 🖌️

#9500 Release 17.0.0 beta.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9509 fix(chat): Prevent empty chat messages
  lib/Controller/ChatController.php
  src/components/NewMessageForm/NewMessageForm.vue
  tests/integration/features/chat/group.feature
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: frontend 🖌️

#9518 Update license file
  img/backgrounds/COPYING
Labels: 3. to review, bug

#9508 fix closing the left sidebar on click automatically
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, regression, feature: frontend 🖌️

#9517 Fix clearing of guests
  lib/Service/ParticipantService.php
Labels: 3. to review, feature: api 🛠️, feature: conversations 👥

#9513 fix(call): Fix incorrectly selected media when actually joining a call
  src/App.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/init.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/LocalMediaModel.js
Labels: 3. to review, bug, high, regression, feature: WebRTC 🚡, feature: frontend 🖌️, feature: call 📹

#9523 fix(deps): Bump @nextcloud/vue to 7.11.4
  package-lock.json
  package.json
Labels: 3. to review, enhancement, feature: frontend 🖌️

#9524 fix(settings): Fix recording server check for blocked admins
  lib/Middleware/CanUseTalkMiddleware.php
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: api 🛠️

#9526 Use the color-primary-element* variables
  src/components/ChatView.vue
  src/components/ConversationSettings/NotificationsSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/ContactSelectionBubble/ContactSelectionBubble.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/NewMessageForm/TemplatePreview.vue
  src/components/Quote.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser/SharedItemsBrowser.vue
  src/views/RoomSelector.vue
Labels: 3. to review, bug, design

#9430 Refactor `NewMessageForm` component
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/components/BreakoutRoomsEditor/SendMessageDialog.vue
  src/components/ChatView.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageAttachments.vue
  src/components/NewMessage/NewMessageAudioRecorder.vue
  src/components/NewMessage/NewMessageNewFileDialog.vue
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/NewMessage/NewMessageTemplatePreview.vue
  src/components/NewMessage/NewMessageTypingIndicator.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/components/NewMessageForm/SimplePollsEditor/PollOption.vue
  src/components/Quote.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
  src/services/filesSharingServices.js
Labels: 3. to review, enhancement, feature: frontend 🖌️

#9512 Translate chat messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
  src/services/messagesService.js
Labels: 3. to review, enhancement, feature: chat 💬, feature: frontend 🖌️

#9530 (follow-up) Minor javascript refactoring
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/EmptyCallView.vue
  src/components/ConversationSettings/DangerZone.vue
  src/components/ConversationSettings/ExpirationSettings.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/ConversationSettings/NotificationsSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.spec.js
  src/components/SetGuestUsername.vue
  src/utils/webrtc/analyzers/AverageStatValue.js
Labels: 3. to review, enhancement, feature: frontend 🖌️

#9531 Add main container id to the store for sidebars
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#9521 Release 17.0.0 beta.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, overview

#9533 chore(release): Bump version in info.xml
  appinfo/info.xml
Labels: 3. to review

#9547 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9546 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9545 [stable26] Fix replacement of special symbols by EmojiPicker
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#9549 Fix virtual background image being stretched instead of cropped
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.spec.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 📹

#9553 fix(deps): Bump @nextcloud/vue to 7.11.6
  package-lock.json
  package.json
Labels: 3. to review, bug, feature: frontend 🖌️

#9555 Release 17.0.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#9577 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9581 fix(CallView): fix no local video on empty call in not grid mode
  src/components/CallView/CallView.vue
Labels: 3. to review, backport-request, bug

#9599 Test command documentation only against 8.2
  .github/workflows/occ-command-documentation.yml
Labels: 3. to review, bug

#9605 fix(chat): Update own read marker before triggering events when posting
  lib/Chat/ChatManager.php
  lib/Controller/ChatController.php
  tests/integration/features/chat-2/unread-messages.feature
Labels: 3. to review, backport-request, feature: chat 💬, feature: api 🛠️

#9603 fix(chat): Don't send startTyping signaling message for each keystroke
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, backport-request, feature: chat 💬, feature: frontend 🖌️

#9609 fix(mediasettings): Fix broken aria-label
  src/components/MediaSettings/VideoBackgroundEditor.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#9591 chore(release): Add changelog for 14.0.11, 15.0.6, 16.0.4 and 17.0.0-rc.2
  CHANGELOG.md
Labels: 3. to review

#9592 Release 14.0.11
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9593 Release 15.0.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9594 Release 16.0.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9607 Fix Viewer with Fullscreen mode toggle
  src/composables/useViewer.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#9619 chore(release): Some changelog additions for 17.0.0-rc.2
  CHANGELOG.md
Labels: 3. to review

#9595 Release 17.0.0 rc.2
  .drone.jsonnet
  .drone.yml
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9621 fix(MediaSettings): Fix guests being prompted with login window when blurring background
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/store/fileUploadStore.js
Labels: 3. to review, backport-request, feature: chat 💬, feature: frontend 🖌️, feature: call 📹

#9623 chore(docs): Move scalability to admin documentation and improve readme
  README.md
  docs/scalability.md
  docs/user-requirements.md
  mkdocs.yml
Labels: 3. to review

#9625 fix(TypingIndicator): Actors are only unique by type+id
  src/components/NewMessage/NewMessageTypingIndicator.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️

#9628 fix(docs): Document end call for everyone parameter
  docs/call.md
Labels: 3. to review, feature: api 🛠️, feature: call 📹

#9654 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9655 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9659 feat(docs): Organize the docs overview
  README.md
  docs/index.md
  mkdocs.yml
Labels: 3. to review

#9629 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#9663 feat(docs): Add a script that allows reading the HPB log more easily
  docs/HPB-log-simplifier.sh
Labels: 3. to review, enhancement, feature: signaling 📶
