Repository nextcloud/spreed, pull requests merged in 2023-08, with the labels that each got.

#10081 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10082 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10088 fix(recording): Fix transcription opt-in
  lib/Service/RecordingService.php
  tests/integration/features/callapi/recording.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: recordings ⏺️

#10090 [stable27] feat(chat): Add a property to indicate whether markdown should be rendered
  docs/chat.md
  lib/Model/Message.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#10096 [stable27] chore(deps): Bump @nextcloud/axios from 2.3.0 to 2.4.0
  package-lock.json
  package.json
  src/__mocks__/axios.js
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/services/conversationsService.spec.js
  src/services/filesSharingServices.spec.js
  src/services/messagesService.spec.js
  src/views/RoomSelector.spec.js
Labels: dependencies, javascript

#10095 [stable27] feat(OpenConversationsList) - Make list of open conversations discoverable and usable
  src/collections.js
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue
  src/components/LeftSidebar/OpenConversationsList/OpenConversationsList.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/Forwarder.vue
  src/components/RoomSelector.spec.js
  src/components/RoomSelector.vue
  src/deck.js
  src/maps.js
Labels: 2. developing, feature: frontend 🖌️, feature: conversations 👥

#10079 feat(notification): 🔔 API for "Remind me later"
  appinfo/routes/routesChatController.php
  docs/capabilities.md
  docs/chat.md
  lib/BackgroundJob/ChatMessageReminder.php
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Controller/ChatController.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/recording.feature
  tests/integration/features/chat-2/reminder.feature
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#10086 feat(CallTime)- add one hour hint during the call
  src/components/TopBar/CallTime.vue
  src/store/messagesStore.js
Labels: enhancement, feature: frontend 🖌️, feature: call 📹

#10104 [stable27] feat(notification): 🔔 API for "Set reminder"
  appinfo/routes/routesChatController.php
  docs/capabilities.md
  docs/chat.md
  lib/BackgroundJob/ChatMessageReminder.php
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Controller/ChatController.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/recording.feature
  tests/integration/features/chat-2/reminder.feature
  tests/php/CapabilitiesTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#10100 [stable27] feat(store) replace Vuex `settingsStore` with equivalent Pinia store
  package-lock.json
  package.json
  src/components/NewMessage/NewMessage.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/main.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/mainRecording.js
  src/store/settingsStore.js
  src/store/storeConfig.js
  src/stores/__tests__/settings.spec.js
  src/stores/settings.js
Labels: enhancement, feature: frontend 🖌️, dependencies

#10106 fix(docs): Fix navigation nesting of the documentation
  docs/TURN.md
  docs/coturn.md
  docs/eturnal.md
  mkdocs.yml
Labels: 3. to review, pending documentation

#10078 fix: Stop using Symfony event dispatcher directly
  composer.lock
  lib/AppInfo/Application.php
  lib/Chat/SystemMessage/Listener.php
  lib/Share/Listener.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/Symfony_Component_EventDispatcher_GenericEvent.php
Labels: 3. to review, technical debt

#10107 Fix already shared event
  lib/Chat/SystemMessage/Listener.php
  lib/Events/AlreadySharedEvent.php
Labels: 3. to review, technical debt

#10130 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10131 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10134 fix(CI): Remove stable24 from dependabot
  .github/dependabot.yml
Labels: 3. to review

#10059 feat(ConversationSettings) - add frontend support for enabling bots / webhooks
  src/components/ConversationSettings/BotsSettings.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/constants.js
  src/services/botsService.js
  src/stores/bots.js
Labels: 3. to review, enhancement, feature: settings ⚙️, feature: frontend 🖌️

#9777 feat(MessageGroup) - group system messages
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
  src/components/MessagesList/MessagesList.spec.js
  src/components/MessagesList/MessagesList.vue
  src/composables/useCombinedSystemMessage.js
Labels: 2. developing, backport-request, enhancement, medium, feature: chat 💬, feature: frontend 🖌️

#10068 feat(Participant) - count total talking time within call for participants
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/components/TopBar/CallTime.vue
  src/store/participantsStore.js
  src/utils/formattedTime.js
  src/utils/webrtc/SpeakingStatusHandler.js
  src/utils/webrtc/index.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/webrtc.js
Labels: 2. developing, backport-request, enhancement, feature: frontend 🖌️, feature: call 📹

#10149 Fix "Unread mentions" button appearing
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request

#10146 feat(chat): Option to get and clear reminders
  appinfo/info.xml
  appinfo/routes/routesChatController.php
  docs/chat.md
  lib/BackgroundJob/ChatMessageReminder.php
  lib/BackgroundJob/Reminder.php
  lib/Chat/ChatManager.php
  lib/Controller/ChatController.php
  lib/Migration/Version18000Date20230504205823.php
  lib/Migration/Version18000Date20230808120823.php
  lib/Model/Reminder.php
  lib/Model/ReminderMapper.php
  lib/Notification/Notifier.php
  lib/Service/ReminderService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/reminder.feature
  tests/integration/spreedcheats/lib/Controller/ApiController.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Controller/ChatControllerTest.php
Labels: 2. developing, enhancement, feature: chat 💬, feature: api 🛠️

#10153 fix: Run the background job every minute
  appinfo/info.xml
  lib/BackgroundJob/Reminder.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️

#10105 feat(Message) - 🔔 add frontend support for message reminders
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesList.vue
  src/services/remindersService.js
Labels: 3. to review, backport-request, enhancement, feature: chat 💬, feature: frontend 🖌️

#10154 fix(ChatView) - adjust 'scrollToBottom' button position in call
  src/components/ChatView.vue
Labels: 3. to review, regression, feature: chat 💬, feature: frontend 🖌️, feature: call 📹

#10163 fix(bruteforce): Fix resetting the bruteforce protection
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, performance 🚀

#10151 feat: Document bots
  appinfo/routes/routesBotController.php
  docs/bot-list.md
  docs/bot-management.md
  docs/bots.md
  docs/botscreenshots/call-summary.png
  docs/capabilities.md
  docs/commands.md
  docs/constants.md
  lib/Controller/BotController.php
  mkdocs.yml
  src/components/AdminSettings/BotsSettings.vue
  src/components/AdminSettings/Commands.vue
  src/components/ConversationSettings/BotsSettings.vue
  src/constants.js
  src/services/botsService.js
  src/views/AdminSettings.vue
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: bots & commands 🤖

#10168 fix(release): Exclude .editorconfig from release package
  Makefile
Labels: 3. to review, backport-request, technical debt

#10162 Replace NcMultiselect with NcSelect
  src/components/ConversationSettings/ExpirationSettings.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/MediaDevicesSelector.vue
  src/views/FlowPostToConversation.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#10167 Changelog conversation update for 17.1
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, enhancement

#10169 chore(release): Add changelog for 17.1.0-rc.1
  CHANGELOG.md
Labels: 3. to review

#10170 [stable27] Release 17.1.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10164 Search improvement
  lib/Controller/PageController.php
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, accessibility, feature: conversations 👥

#10180 fix(desktop): fix disabling avatar menu for desktop
  src/components/MessagesList/MessagesGroup/AuthorAvatar.vue
Labels: backport-request, bug, client: 💻 desktop

#10181 Fix duplicate bot formatting
  lib/Controller/BotController.php
Labels: 3. to review, technical debt

#10177 fix(MessageButtonsBar) - adjust predefined reminders conditions
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#10199 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10200 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10201 Simplify tracking of total counted time
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/store/participantsStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#10216 fix(CI): Move oracle to GA
  .github/workflows/phpunit-oci.yml
Labels: backport-request

#10215 fix(bots): Update call_summary_bot behaviour and screenshot
  docs/botscreenshots/call-summary.png
  tests/integration/features/chat/bots.feature
Labels: 3. to review, backport-request, feature: api 🛠️, feature: bots & commands 🤖

#10217 align styles for h1-h4 tags
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, enhancement, feature: chat 💬, feature: frontend 🖌️

#10224 Make psalm more aggressive
  lib/Chat/ChatManager.php
  lib/Collaboration/Collaborators/RoomPlugin.php
  lib/Collaboration/Resources/ConversationProvider.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Federation/Notifications.php
  lib/Listener/CircleMembershipListener.php
  lib/Listener/GroupMembershipListener.php
  lib/Listener/RestrictStartingCalls.php
  lib/Model/AttendeeMapper.php
  lib/Service/AvatarService.php
  lib/Service/HostedSignalingServerService.php
  lib/Service/ParticipantService.php
  lib/Share/Helper/ShareAPIController.php
  psalm.xml
Labels: 3. to review, feature: api 🛠️, technical debt

#10222 fix(conversations): Allow accessing avatars of listable conversations
  lib/Controller/AvatarController.php
  lib/Middleware/Attribute/RequireParticipantOrLoggedInAndListedConversation.php
  lib/Middleware/InjectionMiddleware.php
  tests/integration/features/conversation/avatar.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#10189 fix(techdebt) - add unified `TransitionWrapper` component for transitions
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/assets/variables.scss
  src/components/AdminSettings/RecordingServers.vue
  src/components/AdminSettings/SignalingServers.vue
  src/components/AdminSettings/StunServers.vue
  src/components/AdminSettings/TurnServers.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/ReactionToaster.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/ChatView.vue
  src/components/ConversationSettings/EditableTextField.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/components/TransitionWrapper.vue
  src/views/MainView.vue
Labels: backport-request, enhancement, technical debt, feature: frontend 🖌️

#10218 feat(Message) - update styles for Quote and blockquote tags
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/Quote.vue
Labels: 3. to review, enhancement, feature: chat 💬, feature: frontend 🖌️

#10212 Fix recording buttons conditioned appearing
  src/components/TopBar/CallTime.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️, feature: recordings ⏺️

#10206 Fix local participant data not updated after forced reconnection
  src/components/CallView/CallView.vue
  src/utils/signaling.js
  src/utils/webrtc/SpeakingStatusHandler.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
Labels: 3. to review, backport-request, bug, feature: WebRTC 🚡, feature: signaling 📶, feature: frontend 🖌️

#10230 Fix checking if WebAssembly is supported for virtual background
  src/utils/media/pipeline/VirtualBackground.js
  src/utils/media/pipeline/VirtualBackground.spec.js
  src/utils/webrtc/models/LocalMediaModel.js
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️, feature: call 📹

#8427 Fix using signaling settings while being refetched
  src/utils/signaling.js
  src/utils/webrtc/index.js
Labels: 3. to review, backport-request, bug, feature: signaling 📶

#10260 feat(Message) - refactor components and store
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/NewMessage/NewMessage.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
  src/store/quoteReplyStore.js
  src/store/quoteReplyStore.spec.js
Labels: 3. to review, feature: chat 💬, technical debt, feature: frontend 🖌️

#10263 fix(LeftSidebar): create a conversation button is shown when forbidden
  src/components/LeftSidebar/LeftSidebar.vue
Labels: backport-request, bug, feature: conversations 👥

#10268 Fix call view shown if force reconnected when not in a call
  src/utils/signaling.js
Labels: 3. to review, backport-request, bug, regression, feature: signaling 📶, feature: frontend 🖌️

#10055 Migrate to ESBuild in Webpack
  package-lock.json
  package.json
  src/__mocks__/attachmediastream.js
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Screen.vue
  src/components/CallView/shared/VideoVue.vue
  src/mixins/devices.js
  src/utils/media/effects/virtual-background/index.js
  src/utils/media/pipeline/VirtualBackground.js
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/simplewebrtc/getscreenmedia.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/peer.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
  src/utils/webrtc/simplewebrtc/webrtc.js
  tsconfig.json
  webpack.common.config.js
  webpack.config.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#10269 fix(bots): Fix some system messages for bots
  lib/Chat/Parser/SystemMessage.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, bug, feature: api 🛠️, feature: bots 🤖

#10051 refactor(conversations): separate search results and conversations
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
Labels: 3. to review, backport-request

#10203 feat(conversationsStore) - cache conversations to BrowserStorage
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/services/talkBroadcastChannel.js
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
  src/store/participantsStore.js
  src/store/talkHashStore.js
  src/test-setup.js
  src/utils/requestTabLeadership.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, performance 🚀, feature: conversations 👥

#10281 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10284 follow-up(LeftSidebar) - caching optimization
  src/components/LeftSidebar/LeftSidebar.vue
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
Labels: 3. to review, feature: frontend 🖌️, feature: conversations 👥, refactoring

#10287 fix(participantsStore) - use attendeeId as a key to store speaking information
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
  src/utils/webrtc/SpeakingStatusHandler.js
Labels: 3. to review, backport-request, bug, feature: signaling 📶, feature: frontend 🖌️, feature: call 📹

#10292 Fix patch conversation performance
  src/store/conversationsStore.js
Labels: 3. to review, regression, performance 🚀, feature: conversations 👥

#10289 feat(bots): Add feature flags aka permissions to bots
  appinfo/info.xml
  docs/occ.md
  lib/Command/Bot/Install.php
  lib/Command/Bot/ListBots.php
  lib/Command/Bot/State.php
  lib/Controller/BotController.php
  lib/Migration/Version18000Date20230821112014.php
  lib/Model/Bot.php
  lib/Model/BotServer.php
  lib/Service/BotService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/bots.feature
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: bots 🤖

#10262 Virtual scrolling for conversations list
  package-lock.json
  package.json
  src/components/ConversationIcon.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsListVirtual.vue
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 4. to release, backport-request

#10297 [stable27] Virtual scrolling for conversations list
  package-lock.json
  package.json
  src/components/ConversationIcon.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsListVirtual.vue
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 4. to release

#10299 fix(messagesStore) - clean conversation history for participants in call
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#10306 fix(bots): Fix option name
  docs/occ.md
  lib/Command/Bot/Install.php
Labels: 3. to review, feature: api 🛠️, feature: bots 🤖

#10300 Allow to offboard only on private conversations
  docs/occ.md
  lib/Command/User/Remove.php
  lib/Manager.php
  tests/integration/features/command/user-remove.feature
Labels: 3. to review, feature: api 🛠️, feature: conversations 👥

#10301 fix(BrowserStorage) - clear BrowserStorage when different user logged in
  src/App.vue
Labels: 3. to review, regression, security, feature: frontend 🖌️

#10309 fix(dashboard): Adjust dashboard API response after server PR
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/integration/dashboard.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#10190 feat(security): Integration tests for bruteforce protection
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation/bruteforce-protection.feature
  tests/integration/spreedcheats/lib/Controller/ApiController.php
Labels: 3. to review, feature: api 🛠️, technical debt

#10319 fix(push): Improve push notification for better content if server cou…
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: reactions 👍

#10316 Add stub for command base class
  lib/Command/Developer/UpdateDocs.php
  lib/Command/Room/TRoomCommand.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/oc_core_command_base.php
Labels: feature: api 🛠️, technical debt

#10325 fix(SearchBox) - unify component handling
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: search 🔎

#10322 feat(Message) - copy formatted message (with markdown and mentions) to clipboard
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, backport-request, enhancement, feature: chat 💬, feature: frontend 🖌️

#10332 fix(chat): Fix responding with "X-Chat-Last-Common-Read" when request…
  lib/Controller/ChatController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/read-status.feature
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#10339 chore(release): Add changelog for 17.1.0-rc.2
  CHANGELOG.md
Labels: 3. to review, overview

#10342 Added active calls to the unread messages filter
  src/components/LeftSidebar/LeftSidebar.vue
Labels: backport-request, feature: frontend 🖌️, feature: call 📹, feature: conversations 👥

#10336 fix(MessagesGroup) move date separator to the parent component level
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
  src/components/MessagesList/MessagesList.spec.js
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, feature: chat 💬, technical debt, feature: frontend 🖌️

#10347 feat(deps): Update @nextcloud/vue to 7.12.3
  package-lock.json
  package.json
Labels: 3. to review

#10350 Release 17.1.0 rc.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10349 chore(deps): Update @nextcloud/vue to 7.12.3
  package-lock.json
  package.json
Labels: 3. to review

#10357 fix(LeftSidebar): adjust conversation padding and size
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsListVirtual.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️

#10360 fix(chat): Fix primary color selection on quotes
  src/components/Quote.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#10361 Fix(RoomSelector) - Align text vertically
  src/components/RoomSelector.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: conversations 👥

#10362 fix(changelog): Prevent duplicated changelog message by parallel requ…
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#10364 feat(capability): Add a capability for messages being markdown
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, backport-request, feature: chat 💬, feature: api 🛠️

#10368 feat(bot)!: Ensure bot uniqueness
  appinfo/info.xml
  docs/occ.md
  lib/AppInfo/Application.php
  lib/Command/Bot/Uninstall.php
  lib/Command/Developer/UpdateDocs.php
  lib/Events/BotUninstallEvent.php
  lib/Listener/BotListener.php
  lib/Migration/Version18000Date20230504205823.php
  lib/Migration/Version18000Date20230824123939.php
  lib/Model/BotServerMapper.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: bots 🤖

#10356 fix(LeftSidebar): wrong user status after scrolling
  src/components/ConversationIcon.vue
Labels: 3. to review, backport-request, bug, regression, feature: frontend 🖌️

#10370 [stable27] fix(deps): Bump @nextcloud/vue to 7.12.4
  package-lock.json
  package.json
Labels: 3. to review

#10372 chore(release): Changelog for 17.1.0-rc.3
  CHANGELOG.md
Labels: 3. to review

#10371 [stable27] feat(bot)!: Ensure bot uniqueness
  appinfo/info.xml
  docs/occ.md
  lib/AppInfo/Application.php
  lib/Command/Bot/Uninstall.php
  lib/Command/Developer/UpdateDocs.php
  lib/Events/BotUninstallEvent.php
  lib/Listener/BotListener.php
  lib/Migration/Version18000Date20230504205823.php
  lib/Migration/Version18000Date20230824123939.php
  lib/Model/BotServerMapper.php
Labels: 3. to review, bug, enhancement, feature: api 🛠️, feature: bots 🤖

#10374 🚀 Move integration tests to GitHub actions
  .drone.jsonnet
  .drone.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/integration-summary-when-unrelated.yml
  lib/Chat/Command/Executor.php
  lib/Service/CommandService.php
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
  tests/integration/config/behat.yml
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/FederationContext.php
  tests/integration/features/bootstrap/SharingContext.php
Labels: 2. developing, technical debt

#10389 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10390 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10392 fix(Deck) - show conversation name and highlight link in deck integration
  src/deck.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: integration 📦

#10393 techdebt(Jest) - introduce response helper, clear output, raise coverage
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/services/conversationsService.spec.js
  src/store/conversationsStore.spec.js
  src/store/messagesStore.spec.js
  src/store/participantsStore.spec.js
  src/stores/__tests__/bots.spec.js
  src/stores/__tests__/settings.spec.js
  src/test-helpers.js
  src/test-setup.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#10396 fix(CI): Enable APCu in integration tests
  .github/workflows/integration-pgsql.yml
  tests/integration/features/bootstrap/CommandLineTrait.php
Labels: 3. to review, feature: api 🛠️, technical debt, performance 🚀

#9177 Docker compose for recording server
  recording/docker-compose/Dockerfile
  recording/docker-compose/docker-compose.yml
  recording/docker-compose/wrap_chromium_binary
Labels: 3. to review, technical debt, feature: recordings ⏺️

#10403 feat(leftSidebar) - Persist the filter status after reload
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: conversations 👥

#10402 feat(bots): Add "concurrency convertor" as AppEcosystem sample
  .github/ISSUE_TEMPLATE/3_bot_list.yml
  docs/bot-list.md
  docs/botscreenshots/currency-convertor.png
Labels: 3. to review

#10417 fix(CI): Only reset BFP when we changed it
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/spreedcheats/lib/SpeechToText/LoremIpsumSpeechToTextProvider.php
Labels: 3. to review, feature: api 🛠️, technical debt, performance 🚀

#10399 deps(PHP): Try execution against PHP 8.3 beta
  .github/workflows/integration-pgsql.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review, feature: api 🛠️, technical debt

#10326 fix(arrowNavigation) - update way to listen for focus/blur events
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue
  src/composables/useArrowNavigation.js
Labels: backport-request, bug, regression, feature: frontend 🖌️, feature: conversations 👥

#10421 tests(bots): add negative tests for bots
  docs/occ.md
  lib/Chat/MessageParser.php
  lib/Command/Bot/Install.php
  lib/Command/Bot/Setup.php
  lib/Controller/BotController.php
  lib/Listener/BotListener.php
  lib/Service/BotService.php
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/bots.feature
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: bots 🤖

#10425 [stable27] tests(bots): add negative tests for bots
  .drone.jsonnet
  .drone.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/integration-summary-when-unrelated.yml
  docs/occ.md
  lib/Chat/Command/Executor.php
  lib/Chat/MessageParser.php
  lib/Command/Bot/Install.php
  lib/Command/Bot/Setup.php
  lib/Controller/BotController.php
  lib/Listener/BotListener.php
  lib/Service/BotService.php
  lib/Service/CommandService.php
  tests/drone-run-acceptance-tests.sh
  tests/drone-run-integration-tests.sh
  tests/drone-run-php-tests.sh
  tests/integration/config/behat.yml
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/FederationContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/chat/bots.feature
  tests/integration/spreedcheats/lib/SpeechToText/LoremIpsumSpeechToTextProvider.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: bots 🤖

#10427 fix(CI): Kill stray child proccesses now that the php server is spawning multiple childs
  tests/integration/config/behat.yml
  tests/integration/run.sh
Labels: 3. to review, backport-request, technical debt

#10432 fix(dev): Fix autoloader populating dev dependencies
  composer.json
  psalm.xml
Labels: 3. to review, feature: api 🛠️, technical debt

#10437 techdebt(NewMessage) - move "addTemporaryMessage" dispatch to the store
  src/components/NewMessage/NewMessage.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 4. to release, backport-request, feature: chat 💬, technical debt, feature: frontend 🖌️

#10406 store self as unique user in combined system message
  src/composables/useCombinedSystemMessage.js
Labels: backport-request, bug, regression, feature: chat 💬, feature: frontend 🖌️, feature: call 📹

#10422 fix(NewMessage, EditabeTextField) - don't parse NcRichContenteditable output before sending
  src/components/ConversationSettings/BasicInfo.vue
  src/components/ConversationSettings/EditableTextField.vue
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️, feature: conversations 👥

#10441 chore(release): Add changelog for 17.1.0-rc.4
  CHANGELOG.md
Labels: 3. to review

#10442 Release 17.1.0-rc.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
