Repository nextcloud/spreed, pull requests merged in 2023-04, with the labels that each got.

#9219 fix(CI): Auto approve and merge when it's NOT our interest
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review, technical debt

#9229 [stable25] Update nextcloud/ocp dependency
  composer.lock
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#9234 fix(CI): Disable rate limiting protection
  tests/integration/run.sh
Labels: 3. to review, bug, feature: api 🛠️

#9231 [stable26] Update nextcloud/ocp dependency
  composer.lock
  lib/Chat/ChatManager.php
  lib/Chat/ReactionManager.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/oc_comments_manager.php
  vendor-bin/csfixer/composer.lock
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies

#9240 Fix redirect url in session error handling for desktop
  src/mixins/sessionIssueHandler.js
Labels: 3. to review, backport-request, bug, client: 💻 desktop

#9217 String fixes
  .gitignore
  lib/Chat/Changelog/Manager.php
Labels: backport-request

#9244 fix(settings): Fix missing recording settings when upload limit is INF
  lib/Settings/Admin/AdminSettings.php
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: api 🛠️, feature: recordings ⏺️

#9246 fix(avatar): Fix missing avatars for user and group conversation sugg…
  src/components/ConversationIcon.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: conversations 👥

#9241 l10n: Correct word
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request

#9255 fix(avatar): Prevent 404 avatar request from dummy conversation object
  src/components/ConversationIcon.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: conversations 👥

#9072 Populate icon-url on call rich objects
  lib/Chat/Parser/UserMention.php
  lib/Controller/ChatController.php
  lib/Notification/Notifier.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/rich-object-share.feature
  tests/integration/features/conversation/avatar.feature
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request, feature: api 🛠️

#9068 Flatten left sidebar nested lists
  src/__mocks__/router.js
  src/components/ConversationsOptionsList.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/test-helpers.js
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#9259 Add note about using modifiedSince with includeStatus set to true
  docs/conversation.md
Labels: backport-request

#9261 fix(chat): Ignore whitespace for "emoji only" check
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#9263 Fix invalid current conversation after conversation remove
  src/components/LeftSidebar/LeftSidebar.vue
Labels: bug, regression

#9290 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9275 Fix squeezed user mentions in NcRichcontenteditable
  src/components/BreakoutRoomsEditor/SendMessageDialog.vue
  src/components/ChatView.vue
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#9289 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9303 fix(open-conversations): Add options for open conversations to be usa…
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: conversations 👥

#9070 feat(avatar): Add back avatar capability and use in other components
  docs/capabilities.md
  lib/Activity/Provider/Base.php
  lib/Capabilities.php
  lib/Collaboration/Reference/TalkReferenceProvider.php
  lib/Dashboard/TalkWidget.php
  lib/Search/ConversationSearch.php
  tests/integration/features/integration/dashboard.feature
  tests/php/Activity/Provider/BaseTest.php
  tests/php/CapabilitiesTest.php
Labels: 2. developing, feature: api 🛠️

#9058 [stable26] Show index page instead of hard redirect to 404 on chat delete after signaling error
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/utils/signaling.js
Labels: enhancement, feature: frontend 🖌️

#9308 fix(docs): Split avatar docs because it has a different base API version
  docs/avatar.md
  docs/conversation.md
  docs/index.md
  mkdocs.yml
Labels: 3. to review

#9262 [stable26] Flatten left sidebar nested lists
  src/__mocks__/router.js
  src/components/ConversationsOptionsList.vue
  src/components/LeftSidebar/ConversationsList/ConversationsList.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/test-helpers.js
Labels: enhancement, feature: frontend 🖌️

#9319 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#9296 Allow using images as background in virtual background
  src/App.vue
  src/components/AdminSettings/WebServerSetupChecks.vue
  src/constants.js
  src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js
  src/utils/media/effects/virtual-background/constants.js
  src/utils/media/pipeline/VirtualBackground.js
  src/utils/media/pipeline/VirtualBackground.spec.js
  src/utils/webrtc/index.js
  src/utils/webrtc/models/LocalMediaModel.js
  src/utils/webrtc/simplewebrtc/localmedia.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: call 📹

#9276 Video background image round one
  img/backgrounds/1.jpg
  img/backgrounds/2.jpg
  img/backgrounds/4.jpg
  img/backgrounds/5.jpg
  img/backgrounds/6.jpg
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareSidebar.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/DeviceChecker/DeviceChecker.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️

#9310 fix(recording): Don't create confusing system message about recording if actor ended the call
  lib/Activity/Listener.php
  lib/Chat/SystemMessage/Listener.php
  lib/Service/RecordingService.php
  psalm.xml
  tests/integration/features/callapi/recording.feature
  tests/php/Chat/SystemMessage/ListenerTest.php
Labels: 3. to review, backport-request, feature: chat 💬, feature: api 🛠️, feature: recordings ⏺️

#9329 feat(virtual-background): Add capabilities for predefined virtual bac…
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: call 📹

#9311 Add signaling messages for reactions in calls
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/simplewebrtc/simplewebrtc.js
Labels: 3. to review, enhancement, feature: call 📹

#9338 chore(deps): bump @nextcloud/vue from 7.9.0 to 7.10.0
  package-lock.json
  package.json
Labels: 3. to review, backport-request, dependencies

#9337 feat(call-reactions): Document the list of supported emojis as capabi…
  docs/capabilities.md
  lib/Capabilities.php
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: call 📹, feature: reactions 👍

#9340 [stable26] chore(deps): bump @nextcloud/vue from 7.8.5 to 7.10.0
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#9342 chore(release): Add changelog for 16.0.3
  CHANGELOG.md
Labels: 3. to review

#9343 chore(release): Bump version to 16.0.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9304 Reactions in video calls
  src/components/CallView/CallView.vue
  src/components/CallView/shared/ReactionToaster.vue
  src/components/TopBar/ReactionMenu.vue
  src/components/TopBar/TopBar.vue
Labels: 1. to develop, enhancement, feature: frontend 🖌️, feature: call 📹, feature: reactions 👍

#9363 Fix TypeError at `LeftSidebar`
  src/components/LeftSidebar/LeftSidebar.vue
Labels: backport-request, bug, regression, feature: frontend 🖌️

#9346 Allow to mark conversation as unread
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/services/conversationsService.js
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
Labels: enhancement, feature: frontend 🖌️, feature: conversations 👥

#9365 fix(notifications): Remove duplicate call to markProcessed() with rec…
  lib/Service/RecordingService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/callapi/recording.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: recordings ⏺️

#9332 fix(avatar): Use conversation avatar in mention suggestion
  src/components/NewMessageForm/NewMessageForm.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️, feature: conversations 👥

#9367 techdebt(controllers): Migrate controllers to Attributes
  lib/Controller/FilesIntegrationController.php
  lib/Controller/PageController.php
  lib/Controller/RecordingController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Middleware/InjectionMiddleware.php
Labels: 3. to review, feature: api 🛠️, technical debt

#9372 techdebt(controllers): Move talk annotations to attributes
  lib/Controller/AvatarController.php
  lib/Controller/BreakoutRoomController.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/GuestController.php
  lib/Controller/MatterbridgeController.php
  lib/Controller/PollController.php
  lib/Controller/ReactionController.php
  lib/Controller/RecordingController.php
  lib/Controller/RoomController.php
  lib/Middleware/Attribute/RequireCallEnabled.php
  lib/Middleware/Attribute/RequireLoggedInModeratorParticipant.php
  lib/Middleware/Attribute/RequireLoggedInParticipant.php
  lib/Middleware/Attribute/RequireModeratorOrNoLobby.php
  lib/Middleware/Attribute/RequireModeratorParticipant.php
  lib/Middleware/Attribute/RequireParticipant.php
  lib/Middleware/Attribute/RequirePermission.php
  lib/Middleware/Attribute/RequireReadWriteConversation.php
  lib/Middleware/Attribute/RequireRoom.php
  lib/Middleware/CanUseTalkMiddleware.php
  lib/Middleware/InjectionMiddleware.php
  tests/psalm-baseline.xml
Labels: 3. to review, feature: api 🛠️, technical debt

#9375 Fix command description
  docs/occ.md
  lib/Command/Monitor/Room.php
Labels: 3. to review, backport-request, feature: api 🛠️, php

#9376 Accessibility improvements for text fields and buttons
  src/components/LeftSidebar/NewGroupConversation/SetContacts/SetContacts.vue
  src/components/LeftSidebar/NewGroupConversation/SetConversationName/SetConversationName.vue
  src/components/LeftSidebar/SearchBox/SearchBox.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue
  src/components/NewMessageForm/SimplePollsEditor/PollOption.vue
  src/components/NewMessageForm/SimplePollsEditor/SimplePollsEditor.vue
  src/components/TopBar/TopBar.vue
  src/views/RoomSelector.vue
Labels: 3. to review, feature: frontend 🖌️, accessibility

#9377 feat(controllers): Migrate server annotations to attributes
  composer.lock
  lib/Controller/AvatarController.php
  lib/Controller/BreakoutRoomController.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/FederationController.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/GuestController.php
  lib/Controller/HostedSignalingServerController.php
  lib/Controller/MatterbridgeController.php
  lib/Controller/PageController.php
  lib/Controller/PollController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/ReactionController.php
  lib/Controller/RecordingController.php
  lib/Controller/RoomController.php
  lib/Controller/SettingsController.php
  lib/Controller/SignalingController.php
  lib/Controller/TempAvatarController.php
Labels: 3. to review, feature: api 🛠️, technical debt

#9253 Avoid out-of-memory errors when uploading a recording
  lib/Service/RecordingService.php
  recording/pyproject.toml
  recording/src/nextcloud/talk/recording/BackendNotifier.py
  tests/php/Service/RecordingServiceTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: recordings ⏺️

#9400 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
