Repository nextcloud/spreed, pull requests merged in 2023-11, with the labels that each got.

#10819 fix(events): Move chat message parsers and creation to typed events
  lib/AppInfo/Application.php
  lib/Chat/Parser/Changelog.php
  lib/Chat/Parser/Command.php
  lib/Chat/Parser/Listener.php
  lib/Chat/Parser/ReactionParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Chat/SystemMessage/Listener.php
  lib/Events/MessageParseEvent.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
Labels: 3. to review, feature: chat 💬, feature: api 🛠️, technical debt

#10823 Log error when starting a screen share fails
  src/utils/webrtc/simplewebrtc/localmedia.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#10824 Log internal signaling messages in debug mode
  src/utils/signaling.js
Labels: 3. to review, bug, feature: signaling 📶, feature: frontend 🖌️

#10766 Fix "Validation by remoteAttendeeId + accessToken might be ambiguous"
  lib/Controller/FederationController.php
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/FederationManager.php
  lib/Migration/Version13000Date20210625232111.php
  lib/Migration/Version18000Date20231024141626.php
  lib/Migration/Version18000Date20231024141627.php
  lib/Model/Invitation.php
  lib/Model/InvitationMapper.php
  lib/Notification/Notifier.php
  lib/ResponseDefinitions.php
  openapi.json
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/invite.feature
  tests/php/Federation/FederationTest.php
Labels: 3. to review, feature: api 🛠️, feature: federation 🌐

#10826 feat(attachments): Allow sending captions as silent messages
  docs/chat.md
  lib/Chat/ChatManager.php
  lib/Chat/SystemMessage/Listener.php
  tests/php/Chat/SystemMessage/ListenerTest.php
Labels: 3. to review, enhancement, feature: chat 💬, feature: api 🛠️, feature: upload & shares & voice 📤🎙️

#10831 fix(chat): Fix mentions at the beginning of captions
  lib/Chat/Parser/UserMention.php
  tests/integration/features/chat/file-share.feature
Labels: 3. to review, feature: chat 💬, feature: api 🛠️, feature: upload & shares & voice 📤🎙️

#10832 fix(reactions): Don't break mobile clients when the reactions list is…
  lib/Controller/ChatController.php
  lib/Controller/ReactionController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/rich-object-share.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: reactions 👍

#10817 Migrate to NcTextArea
  src/components/AdminSettings/SIPBridge.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
Labels: 3. to review, technical debt

#10839 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10818 fix(LeftSidebar): revert temp styles and fix conversation styling
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, regression, feature: conversations 👥

#10841 fix(event): Migrate to typed event AutoCompleteFilterEvent
  lib/AppInfo/Application.php
  lib/Collaboration/Collaborators/Listener.php
Labels: 3. to review, feature: api 🛠️, technical debt

#10840 Fix(MessageButtonsBar): Hide copy message button for files
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️

#10846 fix(events): Migrate signaling to typed events
  lib/AppInfo/Application.php
  lib/Service/RoomService.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Listener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/RecordingTrait.php
  tests/integration/features/callapi/recording.feature
  tests/integration/features/callapi/update-call-flags.feature
  tests/integration/features/chat/group-read-only.feature
  tests/integration/features/command/user-remove.feature
  tests/integration/features/conversation-2/promotion-demotion.feature
  tests/integration/features/conversation-2/public-private.feature
  tests/integration/features/conversation-2/remove-participant.feature
  tests/integration/features/conversation-2/rename-room.feature
  tests/integration/features/conversation-2/set-description.feature
  tests/integration/features/conversation-2/set-listable.feature
  tests/integration/features/conversation-2/set-password.feature
  tests/integration/features/conversation/add-participant.feature
  tests/integration/features/conversation/breakout-rooms.feature
  tests/integration/features/conversation/delete-room.feature
  tests/integration/features/conversation/join-leave.feature
  tests/integration/features/conversation/lobby.feature
  tests/php/Signaling/BackendNotifierTest.php
  tests/php/Signaling/ListenerTest.php
Labels: 3. to review, feature: api 🛠️, feature: signaling 📶, technical debt

#10843 Fix(ParticipantsList): Update list when needed
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/mixins/getParticipants.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 📹

#10812 Replace OC dialog with NcDialog
  src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/DangerZone.vue
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: technical debt, feature: frontend 🖌️

#10852 fix(deps): Update to stable versions of nextcloud JS libraries
  package-lock.json
  package.json
Labels: 3. to review

#10853 Release/18.0.0 beta.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#10871 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10870 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10869 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10874 fix(session): Don't attempt to set session state without a session
  lib/Controller/RoomController.php
  openapi.json
  tests/integration/features/chat/notifications.feature
Labels: 3. to review, feature: api 🛠️, feature: conversations 👥

#10881 fix(chat): Handle `at-all` in note to self
  lib/Chat/Parser/UserMention.php
  lib/Room.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/mentions.feature
Labels: 3. to review, bug, feature: chat 💬, feature: api 🛠️, deployed on testing

#10877 fix(DAVClient): wrap DAV client creation in a function
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/services/DavClient.js
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10876 fix(activeSession): don't set state for cases when token is undefined
  src/composables/useActiveSession.js
Labels: 3. to review, bug, feature: frontend 🖌️

#10891 [stable27] fix(DAVClient): wrap DAV client creation in a function
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/services/DavClient.js
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10896 fix(LeftSidebar): replace three-dot icon with chat-plus icon in
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: conversations 👥

#10897 fix(AvatarWrapper): fix size for icon-changelog in chat
  src/components/AvatarWrapper/AvatarWrapper.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#10884 fix(chat): Adjust "author" when creating "Note to self" and "changelo…
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/SystemMessage/Listener.php
  lib/Model/Attendee.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat/mentions.feature
  tests/integration/features/chat/note-to-self.feature
  tests/integration/spreedcheats/lib/AppInfo/Application.php
  tests/integration/spreedcheats/lib/PreferenceListener.php
Labels: 3. to review, feature: chat 💬, feature: api 🛠️

#10900 fix(LeftSidebar): reuse logic for unread mentions in pop-up button
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: conversations 👥

#10904 [stable27] fix(LeftSidebar): replace three-dot icon with chat-plus icon
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: conversations 👥

#10898 feat(shares): add drag-n-drop option in the modal
  src/components/NewMessage/NewMessageUploadEditor.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10905 [stable27] fix(LeftSidebar): reuse logic for unread mentions in pop-up button
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: conversations 👥

#10914 fix(sip-dialout): Fix the successful dialout case when error is null
  lib/Service/ParticipantService.php
Labels: 3. to review, bug, feature: api 🛠️, feature: SFU & SIP ☎️

#10912 fix: audio/video stream in Safari by coping `attachmediastream` to source in `ESM` format
  package-lock.json
  package.json
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/Screen.vue
  src/components/CallView/shared/VideoVue.vue
  src/mixins/devices.js
  src/utils/attachmediastream.js
  src/utils/webrtc/models/CallParticipantModel.js
Labels: 3. to review, bug, high, regression, feature: WebRTC 🚡, feature: call 📹, browser: Safari

#10913 Keep track of senders to allow unmutung with Safari
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, feature: WebRTC 🚡, feature: frontend 🖌️, feature: call 📹, browser: Safari

#10855 fix(deps): Readd fixed style import from nextcloud/dialogs
  src/deck.js
  src/init.js
  src/mainAdminSettings.js
  src/mainRecording.js
  src/maps.js
Labels: 3. to review, regression, feature: frontend 🖌️

#10879 fix(shares): fix issues with file upload
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10889 fix(notifications): Mark notifications about read chat messages as re…
  lib/Notification/Listener.php
  lib/Notification/Notifier.php
  lib/Service/BreakoutRoomService.php
  lib/Signaling/Listener.php
Labels: 3. to review, feature: chat 💬, feature: api 🛠️, deployed on testing

#10921 fix(search): Remove development log
  lib/Chat/CommentsManager.php
Labels: 4. to release, feature: api 🛠️, feature: search 🔎

#10924 fix(CI): Fix psalm missing chache() on the stub
  tests/stubs/oc_comments_manager.php
Labels: 3. to review, bug, feature: api 🛠️

#10923 Fix new message input appearance
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#10919 fix(search): Use OCP constants for filters
  composer.lock
  lib/Search/MessageSearch.php
Labels: 3. to review, feature: api 🛠️, technical debt, feature: search 🔎

#10857 fix(API): Add more specific int-types
  lib/Controller/BreakoutRoomController.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/FederationController.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/PollController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/ReactionController.php
  lib/Controller/RecordingController.php
  lib/Controller/RoomController.php
  lib/Controller/SettingsController.php
  lib/Controller/SignalingController.php
  lib/Controller/TempAvatarController.php
  lib/Service/BreakoutRoomService.php
  openapi.json
Labels: 3. to review, enhancement, feature: api 🛠️

#10920 fix(call): Handle DoesNotExistException when ringing an attendee
  docs/call.md
  lib/Controller/CallController.php
  lib/Service/ParticipantService.php
  openapi.json
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/notifications.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹

#10939 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10940 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10942 [stable26] feat(CI): Try to automatically merge OCP updates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review, feature: api 🛠️, technical debt

#10943 [stable27] feat(CI): Try to automatically merge OCP updates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review, feature: api 🛠️, technical debt

#10947 [stable27] fix(call): Handle DoesNotExistException when ringing an attendee
  docs/call.md
  lib/Controller/CallController.php
  lib/Service/ParticipantService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/notifications.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹

#10949 [stable27] fix(reactions): Don't break mobile clients when the reactions list is…
  lib/Controller/ChatController.php
  lib/Controller/ReactionController.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/rich-object-share.feature
Labels: 3. to review, bug, feature: reactions 👍

#10952 feat(LeftSidebar): Always show "create a new conversation" item
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: conversations 👥

#10954 Revert "Keep track of senders to allow unmutung with Safari"
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, bug, regression, feature: WebRTC 🚡, feature: frontend 🖌️, feature: call 📹, browser: Safari

#10960 fix(settings): Remove notification settings for guests
  src/components/ConversationSettings/ConversationSettingsDialog.vue
Labels: 3. to review, backport-request, bug, feature: settings ⚙️

#10961 fix(settings): Allow requesting hosted HPB without being in "Can use …
  lib/Middleware/CanUseTalkMiddleware.php
Labels: 3. to review

#10963 fix(messages): revert "sort messages within one group"
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#10962 fix(settings): Fix Hosted HPB settings UI
  src/components/AdminSettings/HostedSignalingServer.vue
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️

#10970 fix(hosted-hpb): Correctly handle API response when the account expir…
  lib/BackgroundJob/CheckHostedSignalingServer.php
  lib/Controller/HostedSignalingServerController.php
  lib/Notification/Notifier.php
  lib/Service/HostedSignalingServerService.php
  tests/stubs/GuzzleHttp_Exception_ServerException.php
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: signaling 📶

#10974 [stable27] fix(settings): Remove notification settings for guests
  src/components/ConversationSettings/ConversationSettingsDialog.vue
Labels: 3. to review, backport-request, bug

#10975 fix(API): Move away from own deprecated constants
  lib/Command/Room/TRoomCommand.php
  lib/Command/User/TransferOwnership.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Listener/AMembershipListener.php
  lib/Listener/CircleDeletedListener.php
  lib/Listener/GroupDeletedListener.php
  lib/Manager.php
  lib/MatterbridgeManager.php
  lib/Service/BreakoutRoomService.php
  lib/Service/ParticipantService.php
Labels: 3. to review, feature: api 🛠️, technical debt

#10971 fix(calls): Explicitly block calls in former one-to-one
  lib/Service/ParticipantService.php
  tests/integration/features/callapi/one-to-one.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: call 📹

#10980 fix(search): restore app search behaviour (wait for nextTick, use refs)
  src/App.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: search 🔎

#10979 fix(AdminSettings): fix style specificity
  src/components/AdminSettings/HostedSignalingServer.vue
  src/components/AdminSettings/RecordingServer.vue
  src/components/AdminSettings/RecordingServers.vue
  src/components/AdminSettings/SIPBridge.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/SignalingServers.vue
  src/components/AdminSettings/TurnServer.vue
Labels: backport-request, bug, regression, feature: settings ⚙️, feature: frontend 🖌️

#10945 feat(chat): Add changelog conversation entries for Talk 18
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, enhancement, feature: chat 💬

#10988 Release 16.0.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10989 Release 17.1.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10990 Release 18.0.0 rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10987 chore(release): Add changelog for 16.0.8, 17.1.3 and 18.0.0-rc.1
  CHANGELOG.md
Labels: 3. to review

#11008 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#10986 fix(uploads): allow to send empty uploads as normal messages
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#10973 fix(search): change conditions for showing trailing button
  src/components/LeftSidebar/SearchBox/SearchBox.vue
Labels: 2. developing, backport-request, bug, feature: frontend 🖌️, feature: search 🔎

#11011 fix(chat): use the default new message placeholder
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️

#11009 refactor: make browserCheck an util instead of mixin
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthRequestPasswordButton.vue
  src/PublicShareSidebar.vue
  src/components/TopBar/CallButton.vue
  src/mixins/browserCheck.js
  src/utils/browserCheck.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#11013 [stable28] fix(uploads): allow to send empty uploads as normal messages
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11014 fix(calls): Remove a query in a loop when ending call for everyone
  lib/Listener/RestrictStartingCalls.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: call 📹, performance 🚀

#11019 fix(API): Add ParameterOutOfRange middleware
  lib/AppInfo/Application.php
  lib/Middleware/ParameterOutOfRangeMiddleware.php
Labels: 3. to review, bug, feature: api 🛠️

#10916 fix(shares): handle shares with duplicate names and caption message
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
  src/utils/__tests__/fileUpload.spec.js
  src/utils/fileUpload.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#11026 Fix undefined $participant when calling a lobbied room
  lib/Notification/Notifier.php
  tests/integration/features/callapi/lobby.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: meetings 📅, feature: call 📹

#11030 fix(UI): Fix missing headlines after vue library changed from title t…
  src/components/MediaSettings/MediaSettings.vue
  src/components/NewMessage/NewMessage.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#11006 Fix lost audio track on safari
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, backport-request, feature: WebRTC 🚡, feature: call 📹, browser: Safari

#10850 feat(ViewerOverlayCallView): Add screensharing support
  src/components/CallView/CallView.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
Labels: 2. developing, 3. to review, backport-request, enhancement, feature: frontend 🖌️

#11034 fix(CallView): pass method reference instead of result to debounce function
  src/components/CallView/Grid/Grid.vue
Labels: bug, regression, feature: frontend 🖌️, feature: call 📹

#11035 I should "git add" before I "git commit"
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
Labels: backport-request

#11045 [stable27] fix(hosted-hpb): Correctly handle API response when the account expir…
  lib/BackgroundJob/CheckHostedSignalingServer.php
  lib/Controller/HostedSignalingServerController.php
  lib/Notification/Notifier.php
  lib/Service/HostedSignalingServerService.php
  tests/stubs/GuzzleHttp_Exception_ServerException.php
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: signaling 📶

#11051 fix(chat): patch stored message input
  src/store/quoteReplyStore.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#11054 fix(search): Hide "Messages in current conversation" when not on talk
  lib/Search/CurrentMessageSearch.php
  lib/Search/MessageSearch.php
Labels: 3. to review, backport-request, bug, feature: chat 💬

#10968 fix(AuthSidebar): Order popups
  src/PublicShareAuthSidebar.vue
  src/stores/guestName.js
Labels: backport-request, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️, feature: call 📹

#11057 Release 18.0.0 rc.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
