Repository nextcloud/spreed, pull requests merged in 2024-10, with the labels that each got.

#13397 fix(SelectableParticipant): fix keydown.enter event
  src/components/BreakoutRoomsEditor/SelectableParticipant.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️

#13428 fix(Participant): re-render component in VirtualScroller
  src/components/RightSidebar/Participants/Participant.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13425 fix(MessagesList): update date separator overnight
  src/components/MessagesList/MessagesList.vue
Labels: backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#13423 fix: replace v-tooltip with native title
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/WebServerSetupChecks.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/NewMessage/NewMessageAudioRecorder.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/ReactionMenu.vue
  src/components/TopBar/TopBar.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
  src/components/UIShared/EditableTextField.vue
Labels: 3. to review, feature: frontend 🖌️, accessibility

#13458 fix: do not show two promoted videos
  src/components/CallView/CallView.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#13456 feat(calls): Allow to enforce a maximum call length
  appinfo/info.xml
  docs/settings.md
  lib/BackgroundJob/MaximumCallDuration.php
  lib/Manager.php
  lib/Service/ParticipantService.php
Labels: 3. to review, enhancement, feature: settings ⚙️, feature: api 🛠️, feature: conversations 👥

#13464 fix(calls): End calls without falling back to a user when killing via…
  lib/Activity/Listener.php
  lib/Chat/Parser/SystemMessage.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, bug, feature: chat 💬, feature: call 📹

#13481 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13482 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13483 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13480 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13465 fix: migrate pollService to TS
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/PollViewer/PollViewer.vue
  src/services/pollService.js
  src/services/pollService.ts
  src/store/messagesStore.js
  src/stores/__tests__/polls.spec.js
  src/stores/polls.ts
  src/types/index.ts
Labels: 3. to review, technical debt, feature: frontend 🖌️, feature: polls 📊

#13492 fix: Check media direction in internal signaling messages
  lib/Controller/SignalingController.php
  tests/php/Controller/SignalingControllerTest.php
Labels: 3. to review, backport-request, bug, feature: signaling 📶, feature: call 📹

#13488 feat(calls): Add appconfig and user preference for default setting of…
  docs/capabilities.md
  docs/settings.md
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Config.php
  lib/Controller/RoomController.php
  lib/Controller/SettingsController.php
  lib/ResponseDefinitions.php
  lib/Settings/BeforePreferenceSetEventListener.php
  lib/Settings/UserPreference.php
  openapi-administration.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/__mocks__/capabilities.ts
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-backend-signaling.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-bots.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/php/CapabilitiesTest.php
Labels: 3. to review, backport-request, enhancement, feature: settings ⚙️, feature: api 🛠️, feature: call 📹

#13344 🤖 techdebt: Add PHP rector
  .github/dependabot.yml
  composer.json
  rector.php
  templates/index.php
  templates/recording.php
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
Labels: 3. to review, technical debt

#13500 fix: store form data as a single object
  src/components/NewMessage/NewMessagePollEditor.vue
  src/stores/__tests__/polls.spec.js
  src/stores/polls.ts
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13509 chore(release): Add changelog for 18.0.12, 19.0.10 and 20.0.1
  CHANGELOG.md
Labels: 3. to review

#13511 Release 20.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#13512 Release 19.0.10
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#13513 Release 18.0.12
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#13514 chore: bump @nextcloud/webpack-vue-config from 6.1.1 to 6.2.0
  package-lock.json
  package.json
Labels: 3. to review, backport-request, feature: frontend 🖌️, dependencies

#13484 feat(devices): add an option to always disable streams by default befo…
  src/components/CallView/CallView.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/services/settingsService.js
  src/stores/__tests__/settings.spec.js
  src/stores/settings.js
Labels: enhancement, feature: frontend 🖌️, feature: call 📹

#13536 [stable30] chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: 3. to review, feature: api 🛠️, dependencies

#13537 chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: 3. to review, feature: api 🛠️, dependencies

#13516 feat: align polls state management with API
  src/__mocks__/capabilities.ts
  src/constants.js
  src/services/pollService.ts
  src/stores/__tests__/polls.spec.js
  src/stores/polls.ts
  src/types/index.ts
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: polls 📊

#13541 ci(dependabot): fix missing schedule
  .github/dependabot.yml
Labels: 3. to review, dependencies

#13432 fix(callView): move store to Pinia 🍍
  src/App.vue
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.spec.js
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
  src/composables/useIsInCall.js
  src/composables/useViewer.js
  src/store/callViewStore.js
  src/store/callViewStore.spec.js
  src/store/messagesStore.js
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
  src/store/storeConfig.js
  src/stores/__tests__/callView.spec.js
  src/stores/callView.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#13542 [stable30] feat(calls): Allow to enforce a maximum call length
  appinfo/info.xml
  docs/capabilities.md
  docs/settings.md
  lib/Activity/Listener.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/MaximumCallDuration.php
  lib/Capabilities.php
  lib/Chat/Parser/SystemMessage.php
  lib/Manager.php
  lib/ResponseDefinitions.php
  lib/Service/ParticipantService.php
  lib/SetupCheck/Configuration.php
  openapi-administration.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/__mocks__/capabilities.ts
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-backend-signaling.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-bots.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/php/CapabilitiesTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, feature: api 🛠️, feature: call 📹

#13545 fix: omit 'with 0 guests' in system messages when call ends
  lib/Chat/Parser/SystemMessage.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: call 📹

#13519 feat(calls): Allow moderators to download a call participants list
  appinfo/routes/routesCallController.php
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/CallController.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/public.feature
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: call 📹

#13504 fix: respect mimetype aliases for file previews
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#13558 fix(readme): Correct link to developer setup
  README.md
Labels: 3. to review

#13564 fix(docs): Add federation occ to developer setup docs
  docs/developer-setup.md
Labels: 3. to review

#13557 feat(calls): Allow moderators to download a call participants list - frontend
  lib/Controller/CallController.php
  src/components/TopBar/TopBarMenu.vue
Labels: enhancement, feature: frontend 🖌️, feature: call 📹

#13576 fix(call): Fix support for PHP < 8.3
  lib/Controller/CallController.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#13510 [stable28] chore(deps): bump nextcloud/* lib family, audit dependencies
  package-lock.json
  package.json
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, feature: frontend 🖌️, dependencies

#13518 feat: draft polls management 📊
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/PollViewer/PollDraftHandler.vue
  src/components/PollViewer/PollViewer.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/stores/polls.ts
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: polls 📊

#13572 fix(chat): disable smooth scroll to bottom
  src/components/ChatView.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#13595 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13593 fix(activity): Fix parameter type of call activity
  lib/Activity/Provider/Base.php
  lib/Activity/Provider/Invitation.php
  tests/php/Activity/Provider/InvitationTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹

#13581 ci: Fix restoring the domain and skeleton of the main and real-fed se…
  tests/integration/run.sh
Labels: 3. to review, backport-request

#13507 fix: handle background blur in Talk if server doesn't support it
  src/components/CallView/CallView.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/utils/__tests__/satisfyVersion.spec.js
  src/utils/satisfyVersion.ts
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️, feature: call 📹

#13487 feat(polls): Import/Export pre-filled poll form to JSON 📊
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/PollViewer/PollViewer.vue
  src/utils/fileDownload.ts
  src/utils/validatePollForm.ts
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: polls 📊

#13600 ci: Always reset the skeleton directory
  tests/integration/run.sh
Labels: 3. to review

#13608 feat: replace audioRecorderStore with composable
  src/components/NewMessage/NewMessageAudioRecorder.vue
  src/composables/useAudioEncoder.ts
  src/store/audioRecorderStore.js
  src/store/storeConfig.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13611 fix: check for false positive hidden parent when scroll
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13607 fix: localURL previews
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessage/NewMessageAudioRecorder.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#13499 feat(email): Recognize guests invited via email
  css/icons.css
  docs/bots.md
  lib/Activity/Listener.php
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Chat/MessageParser.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Chat/SystemMessage/Listener.php
  lib/Collaboration/Reference/TalkReferenceProvider.php
  lib/Controller/BanController.php
  lib/Controller/ChatController.php
  lib/Controller/PageController.php
  lib/Controller/RoomController.php
  lib/GuestManager.php
  lib/Manager.php
  lib/Model/Message.php
  lib/Notification/Notifier.php
  lib/ResponseDefinitions.php
  lib/Search/MessageSearch.php
  lib/Service/BanService.php
  lib/Service/ParticipantService.php
  lib/Service/RoomFormatter.php
  lib/Signaling/BackendNotifier.php
  lib/TalkSession.php
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-3/invite-email.feature
  tests/integration/features/conversation-5/sip-dialin.feature
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: meetings 📅, feature: conversations 👥

#13619 fix: appearance of public conversation for guests
  src/App.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13625 fix: pass token to callView store via actions
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.spec.js
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/TopBar/TopBarMenu.vue
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
  src/stores/__tests__/callView.spec.js
  src/stores/callView.js
Labels: 3. to review, bug, feature: frontend 🖌️

#13618 feat(chat): add download link to attachments
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/utils/davUtils.ts
Labels: 3. to review, backport-request, enhancement

#13605 Share from Files wording fix (better consistency)
  src/components/NewMessage/NewMessageAttachments.vue
Labels: 3. to review, design, enhancement, feature: frontend 🖌️, feature: conversations 👥

#13629 fix(TopBarMenu): check capabilities for downloading participants in call
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️, feature: call 📹

#13632 fix(sharing): Align expected sharing behaviour after server change
  tests/integration/features/sharing-1/create.feature
Labels: 3. to review, feature: api 🛠️, feature: upload & shares & voice 📤🎙️

#13596 [main] Update nextcloud/ocp dependency
  composer.lock
  lib/Model/Attachment.php
  lib/Model/Attendee.php
  lib/Model/Ban.php
  lib/Model/BotConversation.php
  lib/Model/BotServer.php
  lib/Model/Consent.php
  lib/Model/Invitation.php
  lib/Model/Poll.php
  lib/Model/ProxyCacheMessage.php
  lib/Model/Reminder.php
  lib/Model/RetryNotification.php
  lib/Model/Session.php
  lib/Model/Vote.php
Labels: 3. to review, dependencies

#13628 fix: PublicShareSidebar for Nextcloud 31
  css/publicshare.css
  lib/PublicShare/TemplateLoader.php
  package-lock.json
  package.json
  src/PublicShareSidebar.vue
  src/PublicShareSidebarTrigger.vue
  src/mainPublicShareSidebar.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#13554 fix: use method of largest remainder to count poll votes
  src/components/PollViewer/PollViewer.vue
  src/utils/__tests__/calculateVotePercentage.spec.js
  src/utils/calculateVotePercentage.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: polls 📊

#13633 fix: e-mail guests - frontend 📧 (part 1)
  src/components/AvatarWrapper/AvatarWrapper.spec.js
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/constants.js
  src/services/participantsService.js
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#13660 fix: hide 'Browse drafts' button in Note to self and 1-1 rooms
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13503 feat: show conversation settings, if URL hash is specified
  src/App.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/MediaSettings/MediaSettings.vue
  src/views/MainView.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#13667 ci(integration): Bump behat/behat to support PHP 8.4
  tests/integration/composer.json
  tests/integration/composer.lock
Labels: 3. to review, backport-request, technical debt
