Repository nextcloud/spreed, pull requests merged in 2024-04, with the labels that each got.

#11990 fix(SystemMessage): Use link parameter for Circle URL in rich object parameters
  lib/Chat/Parser/SystemMessage.php
Labels: 3. to review, bug

#11978 fix(federation): Fix empty strings being null in Oracle
  lib/Chat/MessageParser.php
  lib/Model/ProxyCacheMessage.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/chat.feature
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: federation 🌐

#12002 Release 17.1.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12000 chore(release): Add changelog for 17.1.7 and 18.0.6
  CHANGELOG.md
Labels: backport-request

#12003 desktop: add screen sharing support
  src/components/TopBar/TopBarMediaControls.vue
  src/utils/webrtc/simplewebrtc/getscreenmedia.js
Labels: 3. to review, backport-request, client: 💻 desktop

#11993 chore: define explicit reactivity for webrtc models
  src/components/CallView/CallView.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/TopBar/TopBar.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
  src/utils/webrtc/SentVideoQualityThrottler.js
  src/utils/webrtc/SpeakingStatusHandler.js
  src/utils/webrtc/analyzers/CallAnalyzer.js
  src/utils/webrtc/models/CallParticipantCollection.js
  src/utils/webrtc/models/LocalCallParticipantModel.js
  src/utils/webrtc/models/LocalMediaModel.js
Labels: technical debt, feature: frontend 🖌️

#12005 chore(Vue3): v-bind checking
  src/assets/missingMaterialDesignIcons/PromotedView.vue
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/CallView/CallView.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/components/TopBar/TopBarMenu.vue
  src/components/UIShared/TransitionWrapper.vue
Labels: technical debt, feature: frontend 🖌️

#12023 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12022 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12024 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#11992 fix(MessagesSystemGroup): Follow-up correct collapsed property
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
Labels: regression, feature: chat 💬, feature: frontend 🖌️

#12028 fix(openapi): Make the operation-id unique
  appinfo/routes/routesRoomController.php
  openapi-backend-sipbridge.json
  openapi-full.json
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-full.ts
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#10250 perf(dashboard): implement widget item api v2
  lib/Dashboard/TalkWidget.php
  src/dashboard.js
  src/views/Dashboard.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/integration/dashboard.feature
  webpack.config.js
Labels: 2. developing, backport-request, feature: api 🛠️, feature: frontend 🖌️, feature: integration 📦, performance 🚀

#12037 deps(CI): Update to PHPUnit10
  composer.json
  tests/php/Service/ProxyCacheMessageServiceTest.php
  tests/php/Signaling/ListenerTest.php
  tests/php/phpunit.xml
  vendor-bin/csfixer/composer.json
  vendor-bin/mozart/composer.json
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
Labels: 3. to review, feature: api 🛠️, technical debt

#12038 chore(CI): Update Behat and PHPUnit10 in integration tests
  psalm.xml
  tests/integration/composer.json
  tests/integration/composer.lock
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  vendor-bin/psalm/composer.json
Labels: 3. to review, feature: api 🛠️, technical debt

#12021 fix: Set all rich object parameter values to string
  lib/Chat/Parser/SystemMessage.php
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/types/index.ts
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#10692 feat(federation): Register the OCM resource
  lib/AppInfo/Application.php
  lib/Federation/Proxy/TalkV1/Listener/ResourceTypeRegisterListener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/ocm.feature
  tests/integration/features/federation/poll.feature
  tests/integration/features/federation/reminder.feature
Labels: 4. to release, backport-request, enhancement, feature: api 🛠️, feature: federation 🌐

#11879 feat: handle callUser links in Talk without page reload
  src/store/conversationsStore.js
  src/views/WelcomeView.vue
Labels: 3. to review, feature: frontend 🖌️

#12049 fix(TopBarMenu): register File icon
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review, regression, feature: frontend 🖌️

#12041 refactor(OpenAPI): Use proper type inheritance for chat messages
  lib/Model/ProxyCacheMessage.php
  lib/ResponseDefinitions.php
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, backport-request, technical debt

#12053 Revert "[stable29] fix(frontpage): Don't bruteforce protect "undefined""
  lib/Controller/PageController.php
  tests/integration/features/conversation-1/bruteforce-protection.feature
Labels: 3. to review

#12054 Revert "fix(frontpage): Don't bruteforce protect "undefined""
  lib/Controller/PageController.php
  tests/integration/features/conversation-1/bruteforce-protection.feature
Labels: 3. to review

#12048 chore(deps): bump nextcloud/vue from 8.11.1 to 8.11.2
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#12058 fix(MessagesButtonsBar): exclude click on emoji picker from outside click event listener
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: backport-request, regression, feature: frontend 🖌️

#12063 feat(MessageBody): apply checkbox interactivity
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
Labels: backport-request, enhancement, feature: chat 💬

#12068 chore(release): Add changelog for 19.0.0-rc.3
  CHANGELOG.md
Labels: 3. to review, backport-request

#12072 fix(dashboard): Don't show read one-to-one when the last system messa…
  lib/Dashboard/TalkWidget.php
  tests/integration/features/integration/dashboard.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: conversations 👥

#12074 fix(tests): Clean up unit test code
  tests/php/Activity/Provider/BaseTest.php
  tests/php/Activity/Provider/InvitationTest.php
  tests/php/Activity/SettingTest.php
  tests/php/BackgroundJob/CheckHostedSignalingServerTest.php
  tests/php/BackgroundJob/RemoveEmptyRoomsTest.php
  tests/php/CapabilitiesTest.php
  tests/php/Chat/AutoComplete/SearchPluginTest.php
  tests/php/Chat/AutoComplete/SorterTest.php
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/Command/ExecutorTest.php
  tests/php/Chat/Command/ShellExecutorTest.php
  tests/php/Chat/NotifierTest.php
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Chat/SystemMessage/ListenerTest.php
  tests/php/Collaboration/Collaborators/RoomPluginTest.php
  tests/php/Collaboration/Reference/TalkReferenceProviderTest.php
  tests/php/Collaboration/Resources/ConversationProviderTest.php
  tests/php/Command/Signaling/AddTest.php
  tests/php/Command/Signaling/DeleteTest.php
  tests/php/Command/Signaling/ListCommandTest.php
  tests/php/Command/Stun/AddTest.php
  tests/php/Command/Stun/DeleteTest.php
  tests/php/Command/Stun/ListCommandTest.php
  tests/php/Command/Turn/AddTest.php
  tests/php/Command/Turn/DeleteTest.php
  tests/php/Command/Turn/ListCommandTest.php
  tests/php/ConfigTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/EventDocumentationTest.php
  tests/php/Federation/FederationTest.php
  tests/php/Listener/RestrictStartingCallsTest.php
  tests/php/Model/AttendeeMapperTest.php
  tests/php/Notification/NotifierTest.php
  tests/php/Recording/BackendNotifierTest.php
  tests/php/Service/AvatarServiceTest.php
  tests/php/Service/BreakoutRoomServiceTest.php
  tests/php/Service/CertificateServiceTest.php
  tests/php/Service/ParticipantServiceTest.php
  tests/php/Service/ProxyCacheMessageServiceTest.php
  tests/php/Service/RecordingServiceTest.php
  tests/php/Service/RoomServiceTest.php
  tests/php/Service/SIPDialOutServiceTest.php
  tests/php/Settings/Admin/AdminSettingsTest.php
  tests/php/Settings/Admin/SectionTest.php
  tests/php/Signaling/ListenerTest.php
  tests/php/TalkSessionTest.php
  tests/php/phpunit.xml
Labels: 3. to review

#12075 chore(commands): Notify again about the end of `/commands`
  CHANGELOG.md
Labels: backport-request

#12076 🌇 fix(chat): Remove commands
  appinfo/info.xml
  appinfo/routes.php
  appinfo/routes/routesCommandController.php
  docs/commands.md
  docs/events.md
  docs/index.md
  docs/occ.md
  lib/AppInfo/Application.php
  lib/Chat/ChatManager.php
  lib/Chat/Command/Executor.php
  lib/Chat/Command/Listener.php
  lib/Chat/Command/ShellExecutor.php
  lib/Chat/Parser/Command.php
  lib/Command/Command/Add.php
  lib/Command/Command/AddSamples.php
  lib/Command/Command/Delete.php
  lib/Command/Command/ListCommand.php
  lib/Command/Command/TRenderCommand.php
  lib/Command/Command/Update.php
  lib/Controller/CommandController.php
  lib/Events/CommandEvent.php
  lib/Flow/Operation.php
  lib/Migration/CreateHelpCommand.php
  lib/Model/Command.php
  lib/Model/CommandMapper.php
  lib/Service/CommandService.php
  lib/Settings/Admin/AdminSettings.php
  mkdocs.yml
  sample-commands/calc.sh
  sample-commands/hackernews.php
  sample-commands/wikipedia.php
  src/components/AdminSettings/Commands.vue
  src/components/MessagesList/MessagesList.vue
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
  src/views/AdminSettings.vue
  templates/settings/admin-settings.php
  tests/integration/features/chat-1/commands.feature
  tests/integration/features/chat-2/reply.feature
  tests/integration/features/command/command-list.feature
  tests/php/Chat/Command/ExecutorTest.php
  tests/php/Chat/Command/ShellExecutorTest.php
  tests/php/Chat/Command/echo-argument.sh
  tests/php/Chat/Command/echo-option.sh
  tests/php/Settings/Admin/AdminSettingsTest.php
  tests/psalm-baseline.xml
Labels: 3. to review, bug, feature: chat 💬, feature: settings ⚙️, feature: api 🛠️, feature: frontend 🖌️, feature: bots 🤖

#12078 fix(docs): Sync and update feature list in info.xml and readme
  README.md
  appinfo/info.xml
Labels: 3. to review, backport-request

#12081 chore(release): Add changelog for 17.1.8 and 18.0.7
  CHANGELOG.md
Labels: 3. to review, backport-request

#12082 Release 18.0.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12083 Release 17.1.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12106 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12105 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12110 chore(deps): Update openapi-extractor
  openapi-administration.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/index.ts
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request

#12104 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12112 fix(notifications): Update the notification handling
  lib/Notification/Notifier.php
Labels: 3. to review, bug

#12113 fix(chat): Rename circles to teams in system messages
  lib/Chat/Parser/SystemMessage.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#12107 style: update CSS specificity for fallback mention icons
  css/icons.css
Labels: backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#12109 fix(NewMessage): make silent chat button appearance more obvious
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, backport-request, feature: chat 💬, feature: frontend 🖌️

#12115 fix(tests): Make tests more reliable on PostgreSQL by also sorting on stop
  lib/Service/BreakoutRoomService.php
  lib/Signaling/Listener.php
Labels: 3. to review, backport-request, feature: api 🛠️

#12108 fix(media): rewrite media preferences functions
  src/services/__tests__/mediaDevicePreferences.spec.js
  src/services/mediaDevicePreferences.ts
  src/utils/webrtc/MediaDevicesManager.js
Labels: 2. developing, feature: frontend 🖌️, feature: call 📹

#12125 fix(VideoVue): fix bottom bar not clickable
  src/components/CallView/shared/VideoVue.vue
Labels: backport-request, regression

#12121 fix(conversations): Include rooms in "modified since" updates when at…
  appinfo/info.xml
  lib/Controller/RoomController.php
  lib/Migration/Version19000Date20240416104656.php
  lib/Model/Attendee.php
  lib/Model/AttendeeMapper.php
  lib/Model/SelectHelper.php
  lib/Service/ParticipantService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/unread-messages.feature
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: conversations 👥

#12032 enh(LobbySettings): add timezone and relative time
  src/components/ConversationSettings/LobbySettings.vue
  src/components/LobbyScreen.vue
  src/utils/__tests__/formattedTime.spec.js
  src/utils/formattedTime.ts
Labels: enhancement, feature: frontend 🖌️, feature: meetings 📅

#12133 fix(PublicShareSidebar): fix prop reactivity
  src/mainPublicShareSidebar.js
Labels: feature: talk-sidebar ⬅️

#12136 fix(chat): show iconSvgInline in attachments
  src/components/NewMessage/NewMessageAttachments.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬

#12140 fix(MessagesList): make sure to compare numeric values
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, regression, feature: chat 💬, feature: frontend 🖌️

#12137 fix: lobby timer translation
  src/utils/formattedTime.ts
Labels: regression

#12142 test: fix tests, cleanup jest output
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesList.spec.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12143 fix: correct translation
  src/components/ConversationSettings/LobbySettings.vue
Labels: backport-request, feature: frontend 🖌️

#12147 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12151 fix(media): Fix initial selection of devices
  src/utils/webrtc/MediaDevicesManager.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#12146 fix(media): improve the default selection before preferences
  src/components/MediaSettings/MediaSettings.vue
  src/utils/webrtc/MediaDevicesManager.js
Labels: enhancement, feature: frontend 🖌️

#12150 chore(release): Add changelog for 19.0.0-rc.5
  CHANGELOG.md
Labels: 3. to review, backport-request

#12158 fix(MessageBody): restrict checkbox editing in one-to-one conversation
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
Labels: backport-request, regression, feature: chat 💬, feature: frontend 🖌️

#12162 fix(dashboard): Dashboard does not show mentions from federated conversations
  lib/Dashboard/TalkWidget.php
  lib/Manager.php
  lib/Room.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/chat.feature
Labels: 3. to review, backport-request, feature: api 🛠️, feature: federation 🌐

#12156 fix(techdebt): Update exception handling in activity app
  lib/Activity/Listener.php
  lib/Activity/Provider/Base.php
  lib/Activity/Provider/Call.php
  lib/Activity/Provider/Invitation.php
  tests/php/Activity/Provider/BaseTest.php
  tests/php/Activity/Provider/InvitationTest.php
Labels: 3. to review, feature: api 🛠️, technical debt

#12175 fix(MessageBody): pass actorId and actorType as props to the component
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#12177 fix(NewMessage): clear debounce queue when posting a message
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#12178 fix(messagesStore): compare message ids as numeric values
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#12180 chore(release): Add changelog for 19.0.0-rc.6
  CHANGELOG.md
Labels: 3. to review, backport-request

#12186 fix(CI): Fix local cs:check by nailing symfony/finder to 5.4.x
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
Labels: 3. to review, bug, feature: api 🛠️

#11943 Follow-up: chat scrolling refactoring
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
  src/store/participantsStore.js
Labels: feature: chat 💬, technical debt, feature: frontend 🖌️

#12202 fix(a11y): provide aria-labels for screenshare buttons in every state
  src/components/TopBar/TopBarMediaControls.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, accessibility

#12201 fix(breakout-rooms): enforce rooms order, minor fixes
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/BreakoutRoomsEditor/BreakoutRoomsParticipantsEditor.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
  src/stores/breakoutRooms.ts
Labels: 3. to review, bug, feature: frontend 🖌️, feature: breakout rooms 🖖

#12205 fix(MessagesList): handle special case in scrolling
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
Labels: feature: chat 💬

#12237 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12198 fix(signaling): Make alluserids more reliable for testing
  lib/Signaling/BackendNotifier.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: signaling 📶

#12215 Updating all *.yml workflows from template
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies
