Repository nextcloud/spreed, pull requests merged in 2024-05, with the labels that each got.

#12247 fix(API): Avoid changing variable types
  lib/Share/Helper/ShareAPIController.php
Labels: 3. to review, feature: api 🛠️, technical debt

#12248 fix(editing): restore default behaviour of keyboard hotkeys `Ctrl+Up`
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️, accessibility

#12253 fix(spdx): Deduplicate license statements
  .github/no-response.yml
  .github/workflows/command-rebase.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/jest.yml
  .github/workflows/occ-command-documentation.yml
  .reuse/dep5
Labels: 3. to review

#12255 docs: Add REUSE badge to readme
  README.md
Labels: 3. to review

#12260 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#12257 fix(LeftSidebar): small glitch on sidebar scroll
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12243 feat(OpenConversationsList): expose description
  lib/Service/RoomFormatter.php
  src/App.vue
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
  src/components/LeftSidebar/ConversationsList/ConversationsSearchListVirtual.vue
  src/components/LeftSidebar/OpenConversationsList/OpenConversationsList.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
  src/composables/useConversationInfo.js
  tests/integration/features/conversation-2/find-listed.feature
Labels: 3. to review, enhancement, feature: conversations 👥

#12214 Refactor: Move common message related computed props into composable
  src/components/CallView/shared/EmptyCallView.vue
  src/components/ConversationIcon.vue
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/NewMessage/NewMessage.vue
  src/components/Quote.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
  src/components/TopBar/TopBar.vue
  src/composables/__tests__/useMessageInfo.spec.js
  src/composables/useConversationInfo.js
  src/composables/useGetParticipants.js
  src/composables/useMessageInfo.js
Labels: feature: chat 💬, technical debt, feature: frontend 🖌️

#12258 fix(MessagesList): clean up expired, removed messages from the chat
  src/components/MessagesList/MessagesList.spec.js
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#12288 fix(LobbySettings): convert to string before passing it to translation
  src/components/ConversationSettings/LobbySettings.vue
Labels: 3. to review, regression, feature: frontend 🖌️

#12280 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12289 fix(chat): focus submit on upload attachments without caption
  src/components/NewMessage/NewMessageUploadEditor.vue
Labels: 3. to review, feature: frontend 🖌️

#12298 chore(deps): Bump @nextcloud/vue from 8.11.2 to 8.11.3
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#12285 fix: replace emoji-mart-vue-fast lib usage with nextcloud/vue function
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, feature: frontend 🖌️, dependencies

#12259 ⛔ feat(ban): Contract for banning attendees and IP/ranges
  appinfo/routes.php
  appinfo/routes/routesBanController.php
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/BanController.php
  lib/Controller/RoomController.php
  lib/ResponseDefinitions.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/php/CapabilitiesTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#12302 fix(dashboard): Fix dashboard when the last message of a chat expired
  lib/Dashboard/TalkWidget.php
  tests/integration/features/integration/dashboard.feature
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#12312 fix: check for `note-to-self` capability on frontend
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#12311 feat(capabilities): Expose which capabilities should be considered lo…
  docs/capabilities.md
  lib/Capabilities.php
  lib/ResponseDefinitions.php
  openapi-administration.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-backend-signaling.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-bots.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/php/CapabilitiesTest.php
Labels: 3. to review, backport-request, bug

#12304 fix: Debugging failing integration tests
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, bug, feature: api 🛠️

#12303 fix(notifications): Preparse call notifications for improved performance
  lib/Notification/Listener.php
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹, performance 🚀

#12333 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12335 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12334 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12339 fix(conversations): bring back missing prop
  src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12341 fix(polls): Remove actor info from system message
  lib/Chat/Parser/SystemMessage.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/poll.feature
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: polls 📊

#12338 fix(settings): don't allow guests when breakout rooms are set
  src/components/ConversationSettings/LinkShareSettings.vue
  src/store/conversationsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: breakout rooms 🖖

#12346 feat(vue3): replace vue-outside-events with vueuse
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/main.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/mainRecording.js
Labels: technical debt

#12349 fix(prevent-unload): replace PreventUnload with native browser functionality
  package-lock.json
  package.json
  src/App.vue
  src/FilesSidebarCallViewApp.vue
  src/PublicShareSidebar.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12350 chore(lint): use strict checks on import/order rule
  .eslintrc.js
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12353 fix: hide Translate option for files without caption
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12356 refactor(plugins): add reusable requestRoomSelection util to run room selector
  src/collections.js
  src/deck.js
  src/maps.js
  src/search.js
  src/utils/requestRoomSelection.js
Labels: 3. to review, technical debt

#12357 fix(plugins): return null when room is not selected in plugin instead of throwing an exception
  src/utils/requestRoomSelection.js
Labels: 3. to review, bug, regression

#12358 fix(directive): unify tooltip registration
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/WebServerSetupChecks.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessage/NewMessageAudioRecorder.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/TopBar/ReactionMenu.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12319 fix(federation): Don't send notifications for most system messages in…
  lib/Federation/CloudFederationProviderTalk.php
  lib/Notification/FederationChatNotifier.php
  tests/integration/features/federation/chat.feature
  tests/php/Federation/FederationTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: federation 🌐

#12369 fix(tests): Sort attendees before using them when preparing the expec…
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#12374 fix(vue3): remove v-on.native modifier
  src/App.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review

#12283 fix: throw error when target has DND on
  lib/Controller/CallController.php
  lib/Service/ParticipantService.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/callapi/notifications.feature
  tests/php/Service/ParticipantServiceTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹, feedback-requested

#12384 fix(style): don't pass data-theme-dark
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12368 fix(vue3): use value from v-model (instead of event.target.value)
  src/components/NewConversationDialog/NewConversationSetupPage.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12393 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12381 chore(vue3): migrate async component registration and remove $children
  src/FilesSidebarCallViewApp.vue
  src/FilesSidebarTabApp.vue
  src/views/FilesSidebarCallView.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12383 feat(mobile): use button without text if on mobile
  src/components/TopBar/CallButton.vue
Labels: 3. to review, design, enhancement, browser: Mobile View

#12365 fix(recording): Stop broken recording backend
  lib/Controller/PageController.php
  lib/Controller/RecordingController.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: recordings ⏺️

#12386 fix(OpenAPI): Add missing reactionsSelf to ChatMessage
  lib/ResponseDefinitions.php
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, bug

#12332 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12308 fix(recording): Handle the problem gracefully when the recording can …
  lib/Controller/RecordingController.php
  lib/Service/RecordingService.php
  openapi-backend-recording.json
  openapi-full.json
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-full.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/recording.feature
  tests/php/Service/RecordingServiceTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: recordings ⏺️

#12408 Release 18.0.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12407 Release 17.1.9
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12431 fix(NewConversationDialog): speed up conversation creation flow
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/NewConversationDialog/NewConversationDialog.vue
  src/store/conversationsStore.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12337 [stable28] fix(Conversation): do not render NcDialog if was not called explicitly
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#11970 chore(browserCheck): unify ua-parser usage through the utils
  src/utils/browserCheck.js
  src/utils/media/pipeline/MediaDevicesSource.js
Labels: 2. developing, technical debt, feature: frontend 🖌️

#12435 chore: remove empty file after migration to TS
  src/services/breakoutRoomsService.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️
