Repository nextcloud/spreed, pull requests merged in 2024-11, with the labels that each got.

#13658 fix(chat): Edit last message hotkey on macOS
  package-lock.json
  package.json
  src/App.vue
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthRequestPasswordButton.vue
  src/PublicShareSidebar.vue
  src/components/NewMessage/NewMessage.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/components/TopBar/CallButton.vue
  src/utils/browserCheck.ts
  src/utils/media/pipeline/MediaDevicesSource.js
  src/utils/webrtc/index.js
  src/utils/webrtc/simplewebrtc/peer.js
Labels: 3. to review, backport-request, bug, feature: chat 💬

#13684 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13696 chore(deps): bump @nextcloud/dialogs library from 6.0.0 to 6.0.1
  package-lock.json
  package.json
Labels: 3. to review, backport-request, feature: frontend 🖌️, dependencies

#13699 feat: invite email guests when creating a conversation
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/NewConversationDialog/NewConversationContactsPage.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/services/CapabilitiesManager.ts
  src/services/__tests__/coreService.spec.js
  src/services/conversationsService.js
  src/services/coreService.ts
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#13706 style: move a hover effect to image container
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13672 fix: move useDocumentTitle logic to composable
  src/App.vue
  src/composables/useDocumentTitle.ts
  src/views/SessionConflictView.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13714 chore: add stable30.0 as target for Transifex backports
  .tx/backport
  REUSE.toml
Labels: 3. to review, technical debt

#13722 fix: non-moderators should not query participants from server
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13721 style: fix e-mail guests icons
  css/icons.css
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13728 chore(release): Add changelog for 18.0.13, 19.0.11 and 20.0.2
  CHANGELOG.md
Labels: 3. to review, backport-request

#13732 chore(release): Bump version to 18.0.13
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#13737 fix: make useIsInCall a shared composable
  src/composables/useIsInCall.js
Labels: 3. to review, backport-request, feature: frontend 🖌️, performance 🚀

#13740 fix: reduce amount of EventBus listeners on messages
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, regression, feature: frontend 🖌️

#13751 [stable30] style: fix public share layout
  css/publicshare.css
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13733 fix: faulty avatars for guests and deleted users
  src/components/AvatarWrapper/AvatarWrapper.spec.js
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsList.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/PollViewer/PollVotersDetails.vue
  src/components/Quote.vue
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/RightSidebar/Participants/Participant.vue
  src/composables/__tests__/useMessageInfo.spec.js
  src/composables/useMessageInfo.js
  src/utils/getDisplayName.ts
Labels: 3. to review, bug, feature: frontend 🖌️

#13755 chore(deps): bump @nextcloud/vue lib from 8.19.0 to 8.20.0
  package-lock.json
  package.json
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/NewConversationDialog/NewConversationSetupPage.vue
Labels: 3. to review, feature: frontend 🖌️, dependencies

#13758 fix: rename 'Private poll' to 'Anonymous poll'
  src/components/NewMessage/NewMessagePollEditor.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: polls 📊

#13763 chore: update authors
  appinfo/info.xml
Labels: 3. to review

#13770 fix: hide archive-conversations feature from 20.1.0rc1
  src/__mocks__/capabilities.ts
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/DangerZone.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/utils/conversation.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13736 fix: overwrite EventBus.off method to clear once events
  src/App.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/services/EventBus.ts
  src/services/__tests__/EventBus.spec.js
Labels: 3. to review, feature: frontend 🖌️, performance 🚀

#13773 chore(release): Add changelog for 20.1.0-rc.1
  CHANGELOG.md
Labels: 3. to review, overview

#13490 feat(call): add option to enable blur background by default for all c…
  docs/capabilities.md
  docs/settings.md
  lib/Capabilities.php
  lib/Config.php
  lib/Controller/RoomController.php
  lib/Federation/Proxy/TalkV1/ProxyRequest.php
  lib/ResponseDefinitions.php
  lib/Settings/BeforePreferenceSetEventListener.php
  lib/Settings/UserPreference.php
  openapi-administration.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/__mocks__/capabilities.ts
  src/components/MediaSettings/MediaSettings.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/SettingsDialog/MediaDevicesPreview.vue
  src/services/settingsService.js
  src/stores/__tests__/settings.spec.js
  src/stores/settings.js
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-backend-signaling.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-bots.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  src/utils/webrtc/models/LocalMediaModel.js
  tests/php/CapabilitiesTest.php
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: frontend 🖌️, feature: call 📹

#13778 fix: share autocomplete mentions for NewMessage
  src/components/NewMessage/NewMessage.vue
  src/composables/useChatMentions.ts
  src/services/mentionsService.js
  src/services/mentionsService.ts
  src/types/index.ts
Labels: 3. to review, bug, feature: frontend 🖌️

#13768 fix(matterbridge): fix Matterbridge setup
  lib/MatterbridgeManager.php
  src/components/ConversationSettings/Matterbridge/BridgePart.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/ConversationSettings/Matterbridge/matterbridgeTypes.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: integration 📦

#13797 fix: minor regression fixes
  src/composables/useChatMentions.ts
  src/composables/useDocumentTitle.ts
Labels: 3. to review, regression, feature: frontend 🖌️

#13804 fix(CallView): update isEmptyCallView correctly
  src/components/CallView/CallView.vue
Labels: backport-request, regression, feature: frontend 🖌️, feature: call 📹

#13801 fix: replace IconLink variant
  img/icon-conversation-public-bright.svg
  img/icon-conversation-public-dark.svg
  img/icon-public-white.svg
  src/components/CallView/shared/EmptyCallView.vue
  src/components/ConversationIcon.vue
Labels: 3. to review, backport-request, design, feature: frontend 🖌️

#13785 fix(calls): Add email to exported participant list and list everyone …
  lib/Controller/CallController.php
  lib/Service/ParticipantService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/public.feature
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: meetings 📅, feature: call 📹

#13750 [main] Update nextcloud/ocp dependency
  composer.lock
  lib/Controller/ChatController.php
  lib/Dashboard/TalkWidget.php
  lib/Model/AttachmentMapper.php
  lib/Model/AttendeeMapper.php
  lib/Model/BanMapper.php
  lib/Model/BotConversationMapper.php
  lib/Model/BotServerMapper.php
  lib/Model/ConsentMapper.php
  lib/Model/InvitationMapper.php
  lib/Model/PollMapper.php
  lib/Model/ProxyCacheMessageMapper.php
  lib/Model/ReminderMapper.php
  lib/Model/RetryNotificationMapper.php
  lib/Model/SessionMapper.php
  lib/Model/VoteMapper.php
Labels: 3. to review, dependencies

#13814 feat(archive): Finalize archived conversation behaviour
  .github/workflows/lint-php-cs.yml
  docs/capabilities.md
  docs/conversation.md
  lib/Capabilities.php
  lib/Chat/Notifier.php
  lib/Controller/RoomController.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, backport-request, feature: api 🛠️, feature: conversations 👥

#13812 fix: e-mail guests parsing in chat messages
  lib/Chat/AutoComplete/SearchPlugin.php
  lib/Controller/ChatController.php
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/composables/useChatMentions.ts
  src/constants.js
  src/utils/textParse.ts
Labels: 3. to review, bug, feature: chat 💬

#13807 feat(AI-call-summary): Automatically summarize call transcript
  docs/settings.md
  lib/AppInfo/Application.php
  lib/Controller/RecordingController.php
  lib/Notification/Notifier.php
  lib/Recording/Listener.php
  lib/Service/RecordingService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/callapi/recording.feature
  tests/php/Service/RecordingServiceTest.php
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: call 📹, feature: recordings ⏺️

#13806 fix: improve silent message visibility
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/NewMessage/NewMessage.vue
Labels: backport-request, bug, enhancement, feature: chat 💬, feature: frontend 🖌️

#13823 fix(chat): Fix summarizing chats if there are blocks with only invisible messages
  lib/Controller/ChatController.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#13825 fix(call): Add warning to AI summary and transcript
  lib/Service/RecordingService.php
  tests/php/Service/RecordingServiceTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹

#13829 fix(calls): Fix call notifications in archived conversations
  lib/Service/ParticipantService.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹

#13835 fix: adjust archive filtering behaviour - frontend
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/utils/conversation.js
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#13827 Update Minimum Android Version for Nextcloud Talk
  docs/user-requirements.md
Labels: 3. to review

#13840 chore(deps): bump @nextcloud/vue lib from 8.20.0 to 8.21.0
  package-lock.json
  package.json
Labels: backport-request, feature: frontend 🖌️, dependencies

#13842 Bugfix/noid/emoji font for reaction
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
Labels: 3. to review, backport-request, bug, feature: reactions 👍

#13839 fix(call): prevent call time jumping
  src/components/TopBar/CallTime.vue
Labels: 3. to review, backport-request, bug, feature: call 📹

#13830 fix(openapi): Improve empty array cases
  lib/Capabilities.php
  lib/Controller/BanController.php
  lib/Controller/BotController.php
  lib/Controller/BreakoutRoomController.php
  lib/Controller/CallController.php
  lib/Controller/FederationController.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/GuestController.php
  lib/Controller/HostedSignalingServerController.php
  lib/Controller/RecordingController.php
  lib/Controller/SettingsController.php
  lib/Controller/SignalingController.php
  lib/Controller/TempAvatarController.php
  lib/Federation/Proxy/TalkV1/Controller/CallController.php
  lib/Federation/Proxy/TalkV1/Controller/ReactionController.php
  lib/Federation/Proxy/TalkV1/ProxyRequest.php
  lib/Model/BanMapper.php
  lib/ResponseDefinitions.php
  lib/Service/BanService.php
  lib/Service/PollService.php
  lib/Service/RoomFormatter.php
  lib/Service/RoomService.php
  openapi-administration.json
  openapi-backend-recording.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, bug, feature: api 🛠️

#13779 feat(rooms): add option to automatically lock public and group rooms
  appinfo/info.xml
  docs/settings.md
  lib/BackgroundJob/LockInactiveRooms.php
  lib/Config.php
  lib/Manager.php
  lib/Service/RoomService.php
  tests/php/BackgroundJob/LockInactiveRoomsTest.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: conversations 👥

#13834 fix(MessagesList): fix fetching messages completion when there is no …
  src/components/MessagesList/MessagesList.vue
  src/constants.js
  src/store/messagesStore.js
Labels: bug, feature: chat 💬, feature: frontend 🖌️

#13803 feat: add 'Generate summary' integration: frontend ✨
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageAbsenceInfo.vue
  src/components/NewMessage/NewMessageChatSummary.vue
  src/constants.js
  src/services/coreService.ts
  src/services/messagesService.ts
  src/stores/chatExtras.js
  src/types/index.ts
Labels: 2. developing, feature: frontend 🖌️, feature: integration 📦

#13859 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13862 fix: introduce submenu logic in Conversation component
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: conversations 👥

#13813 fix: delegate message posting from NewMessage to parent components
  src/components/BreakoutRoomsEditor/SendMessageDialog.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#13869 fix: minor regressions
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/composables/useChatMentions.ts
Labels: 3. to review, regression, feature: frontend 🖌️

#13880 fix(chat): No "Generate summary" in federated conversations
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request

#13874 build: Remove updated composer patch for firebase/php-jwt
  .patches/.gitkeep
  .patches/firebase-php-jwt-572.diff
  .patches/firebase-php-jwt-572.diff.license
  LICENSES/BSD-3-Clause.txt
  composer.patches.json
Labels: 3. to review, bug, feature: api 🛠️

#13871 feat(invitations): Allow importing CSV email lists
  appinfo/routes/routesRoomController.php
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/RoomController.php
  lib/Exceptions/GuestImportException.php
  lib/GuestManager.php
  lib/Service/ParticipantService.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: meetings 📅, feature: conversations 👥

#13767 feat(conversations): add option to force passwords
  docs/capabilities.md
  docs/conversation.md
  docs/settings.md
  lib/Capabilities.php
  lib/Config.php
  lib/Controller/RoomController.php
  lib/Manager.php
  lib/ResponseDefinitions.php
  lib/Service/RoomService.php
  openapi-administration.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/__mocks__/capabilities.ts
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-backend-signaling.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-bots.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/php/CapabilitiesTest.php
  tests/php/Service/RoomServiceTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#13885 ci(openapi): Add a command to regenerate OpenAPI assets
  .github/workflows/command-openapi.yml
  .github/workflows/openapi.yml
Labels: 3. to review

#13863 fix: handle password policy validation
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/NewConversationDialog/NewConversationDialog.vue
  src/components/NewConversationDialog/NewConversationSetupPage.vue
  src/store/conversationsStore.js
Labels: 2. developing, bug, feature: frontend 🖌️

#13892 fix: respect user changes of devices state when toggling it
  src/components/CallView/CallView.vue
  src/components/MediaSettings/MediaSettings.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 📹

#13894 chore(release): Add changelog for 20.1.0-rc.3
  CHANGELOG.md
Labels: 3. to review

#13875 feat(invitations): Import e-mail participants from CSV 🗒️
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Exceptions/GuestImportException.php
  lib/GuestManager.php
  openapi-full.json
  openapi.json
  src/__mocks__/capabilities.ts
  src/components/ConversationSettings/LobbySettings.vue
  src/components/ImportEmailsDialog.vue
  src/components/RightSidebar/LobbyStatus.vue
  src/services/participantsService.js
  src/types/index.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/php/GuestManagerTest.php
  tests/php/data/import-valid-email-and-name.csv
  tests/php/data/import-valid-email-and-name.csv.license
  tests/php/data/import-valid-filter-duplicates-by-email.csv
  tests/php/data/import-valid-filter-duplicates-by-email.csv.license
  tests/php/data/import-valid-only-email.csv
  tests/php/data/import-valid-only-email.csv.license
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: meetings 📅

#13891 fix(openapi): Remove lastMessage from TalkRoom object when empty
  lib/ResponseDefinitions.php
  lib/Service/RoomFormatter.php
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/composables/useConversationInfo.js
  src/store/conversationsStore.js
  src/store/messagesStore.js
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  src/utils/getMessageIcon.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-3/lobby.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#13898 feat(release): Promote Desktop, AI Summaries, Meetings and Archiving
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, overview
