Repository nextcloud/spreed, pull requests merged in 2024-08, with the labels that each got.

#12870 style: adjust line-height usage after change from px value to unitless
  css/talk-admin-settings.css
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, design, feature: frontend 🖌️

#12853 fix(PublicShareAuthSidebar): fix and refactor styles for video verification sidebar
  css/publicshareauth.css
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/ConversationIcon.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: talk-sidebar ⬅️

#12873 fix(FilesSidebarChaView): hide duplicated CallButton, when in call
  src/views/FilesSidebarChatView.vue
Labels: 3. to review, design, feature: frontend 🖌️

#12856 Fix silent call notifications in federated calls
  docs/events.md
  lib/Activity/Listener.php
  lib/AppInfo/Application.php
  lib/Controller/CallController.php
  lib/Events/ACallEndedEvent.php
  lib/Events/ACallEndedForEveryoneEvent.php
  lib/Events/ACallStartedEvent.php
  lib/Events/ActiveSinceModifiedEvent.php
  lib/Events/BeforeCallEndedEvent.php
  lib/Events/BeforeCallStartedEvent.php
  lib/Events/CallEndedEvent.php
  lib/Events/CallEndedForEveryoneEvent.php
  lib/Events/CallStartedEvent.php
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/Proxy/TalkV1/Controller/CallController.php
  lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
  lib/Notification/Listener.php
  lib/Recording/Listener.php
  lib/Room.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  lib/Signaling/Listener.php
  tests/integration/features/federation/call.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: call 📹, feature: federation 🌐

#12863 Fix avatars in federated calls
  lib/Controller/SignalingController.php
  lib/ResponseDefinitions.php
  lib/Signaling/BackendNotifier.php
  openapi-full.json
  openapi.json
  src/components/CallView/shared/VideoVue.vue
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  src/utils/webrtc/models/CallParticipantModel.js
  src/utils/webrtc/webrtc.js
  tests/integration/features/callapi/update-call-flags.feature
  tests/integration/features/conversation-4/promotion-demotion.feature
Labels: 3. to review, bug, feature: call 📹, feature: federation 🌐

#12877 fix(ChatView): mark when used in sidebar, simplify templates
  src/PublicShareAuthSidebar.vue
  src/PublicShareSidebar.vue
  src/components/ChatView.vue
  src/components/RightSidebar/RightSidebar.vue
  src/views/FilesSidebarChatView.vue
  src/views/MainView.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12876 Release 20.0.0 beta.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12879 fix(federation): disable call buton if talk proxy hash is dirty
  src/components/TopBar/CallButton.vue
  src/services/CapabilitiesManager.ts
  src/stores/talkHash.js
Labels: 3. to review, bug, feature: frontend 🖌️, feature: federation 🌐

#12889 fix(ConversationSettings): hide ban section in note to self
  src/components/ConversationSettings/ConversationSettingsDialog.vue
Labels: bug, feature: frontend 🖌️

#12891 fix(ConversationIcon): show avatar thumbnail for former 1-1 conversations
  src/components/ConversationIcon.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: conversations 👥

#12899 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12823 fix(MessageList): rewrite CSS layout of chat
  src/assets/variables.scss
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageTypingIndicator.vue
Labels: 3. to review, design, feature: chat 💬, feature: frontend 🖌️

#12855 fix(MessagesList): position loading spinner to not affect scrolling
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️

#12854 fix(Reactions): integrate reactions into grid CSS layout
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12900 chore(deps): bump nextcloud/vue lib from 8.15.1 to 8.16.0
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#12819 fix(Participant): migrate to NcListItem
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12906 fix(RightSidebar): discard unread messages toast on conversation change
  src/components/RightSidebar/RightSidebar.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12907 fix(ContactSelectionBubble): migrate to NcChip and script setup
  src/components/NewConversationDialog/NewConversationContactsPage.vue
  src/components/UIShared/ContactSelectionBubble.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12869 Fix conversations layout
  src/components/ConversationIcon.vue
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/constants.js
Labels: 2. developing, bug, design, feature: frontend 🖌️

#12875 fix(TopBar): align lines
  src/components/CallView/CallView.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, design, feature: frontend 🖌️

#12909 release: v20.0.0-beta.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#12911 fix(participants): adjust placeholder
  src/components/UIShared/LoadingPlaceholder.vue
Labels: feature: frontend 🖌️

#12915 fix(Conversation): adjust design of icons
  src/components/LeftSidebar/ConversationsList/Conversation.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12918 fix(MediaSettings): provide accessible heading
  src/components/MediaSettings/MediaSettings.vue
  src/composables/useId.ts
Labels: 3. to review, feature: frontend 🖌️, accessibility

#12926 fix(TopBar): hand raised button animation
  src/components/MediaSettings/MediaSettingsTabs.vue
  src/components/MediaSettings/TransitionExpand.vue
  src/components/MediaSettings/TransitionExpandDown.vue
  src/components/TopBar/TopBarMenu.vue
Labels: 3. to review, design, feature: frontend 🖌️

#12937 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12927 fix(CallButton): replace video icon with phone
  src/components/TopBar/CallButton.vue
Labels: 3. to review, design, feature: frontend 🖌️

#12939 fix(LeftSidebar): Fix conversation click when filter and search are on
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/UIShared/SearchBox.vue
Labels: regression, feature: frontend 🖌️, feature: conversations 👥

#12938 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12943 fix(ban): Don't allow banning in one-to-one conversations and fix banning IP ranges
  lib/Controller/BanController.php
  lib/Service/BanService.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-1/ban.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#12893 fix: Cannot enable bots in former 1:1 rooms
  lib/Controller/BotController.php
  tests/integration/features/chat-1/bots.feature
Labels: 3. to review, feature: api 🛠️, feature: bots 🤖, feature: conversations 👥

#12821 fix: When banning a user they are also removed from the room
  lib/Service/BanService.php
  tests/integration/features/conversation-1/ban.feature
Labels: 2. developing, bug, feature: api 🛠️, feature: conversations 👥

#12947 chore: Removed ban checks for federated users
  lib/Service/BanService.php
Labels: 3. to review, feature: api 🛠️

#12925 feat: Added tests for recording consent of federated conversations
  tests/integration/features/federation/call.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: call 📹, feature: recordings ⏺️

#12924 fix(Participant): remove unneeded separator
  src/components/RightSidebar/Participants/Participant.vue
Labels: bug, feature: frontend 🖌️

#12944 fix(signaling): Add the displayname to the signaling ticket for feder…
  lib/Config.php
  lib/Controller/SignalingController.php
Labels: 3. to review, feature: api 🛠️, feature: call 📹, feature: federation 🌐

#12951 fix(OpenAPI): Fix expired parent messages
  lib/ResponseDefinitions.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, bug, feature: api 🛠️

#12916 fix: make more obvious that you can add Federated Cloud ID accounts
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/UIShared/SearchBox.vue
Labels: 3. to review, bug, design, feature: frontend 🖌️, feature: federation 🌐, feature: conversations 👥

#12954 fix(federation): Fix invited cloudID and save the responded displayname
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Service/ParticipantService.php
  tests/integration/features/federation/invite.feature
  tests/php/Federation/FederationTest.php
Labels: 3. to review, feature: api 🛠️, feature: federation 🌐

#12960 chore(deps): bump nextcloud/auth library from 2.3.0 to 2.4.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#12958 tests: Disable flaky test-step
  tests/integration/features/federation/chat.feature
Labels: 3. to review, bug, feature: chat 💬, feature: api 🛠️, feature: federation 🌐

#12913 Refactor: clean call view styles and use CSS variables.
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/VideoVue.spec.js
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, feature: frontend 🖌️, feature: call 📹

#12967 chore: update PR template
  .github/pull_request_template.md
Labels: 3. to review

#12971 fix: provide accessible heading for components
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/GuestWelcomeWindow.vue
  src/components/PermissionsEditor/PermissionsEditor.vue
  src/components/PollViewer/PollViewer.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️

#12964 fix(Participant): hide ban option for federated users
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/RightSidebar/Participants/Participant.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#12961 Fix using signaling session ID instead of Nextcloud session ID
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/ReactionToaster.vue
  src/components/CallView/shared/Screen.vue
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#12902 feat(TopBar): add next meeting date
  src/components/TopBar/TopBar.vue
  src/services/conversationsService.js
  src/stores/chatExtras.js
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️, feature: conversations 👥

#12968 fix(federation): No notification for call summary and other system me…
  lib/Notification/FederationChatNotifier.php
  tests/integration/features/federation/call.feature
Labels: 3. to review, backport-request

#12962 Get call peers by federated users
  docs/call.md
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Federation/Proxy/TalkV1/Controller/CallController.php
  src/components/CallView/shared/VideoVue.vue
  tests/integration/features/federation/call.feature
  tests/integration/features/federation/join-leave.feature
Labels: 3. to review, backport-request, bug, feature: federation 🌐

#12941 feat: add login button to guest welcome window
  src/components/GuestWelcomeWindow.vue
  src/components/LobbyScreen.vue
  src/components/SetGuestUsername.vue
Labels: backport-request, enhancement, feature: frontend 🖌️, feature: conversations 👥

#12986 ci: Also install sqlite and pdo_sqlite for now
  .github/workflows/integration-mariadb.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
Labels: 3. to review, bug

#12970 fix: migrate NcModal to NcDialog
  src/components/BreakoutRoomsEditor/SendMessageDialog.vue
  src/components/ConversationSettings/BanSettings/BanSettings.vue
  src/components/LeftSidebar/InvitationHandler.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsList.vue
  src/components/NewMessage/NewMessagePollEditor.vue
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#12963 chore(CI): Adjust testing matrix for Nextcloud 30 on stable30
  .github/workflows/integration-mariadb.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  .github/workflows/occ-command-documentation.yml
  composer.json
  composer.lock
Labels: 3. to review

#12966 fix(Participant): design follow-ups
  src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#12861 fix(capabilities): store remote capabilities based on remoteServer
  src/__mocks__/capabilities.ts
  src/components/LeftSidebar/InvitationHandler.vue
  src/services/CapabilitiesManager.ts
  src/services/__tests__/CapabilitiesManager.spec.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#12992 fix(capabilities): minor adjustments for federation
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/services/CapabilitiesManager.ts
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#12956 fix(avatar): decrease avatar size from 44px to 36px
  src/components/AvatarWrapper/AvatarWrapper.spec.js
  src/components/ConversationIcon.vue
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
  src/components/LeftSidebar/InvitationHandler.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
  src/components/TopBar/TopBar.vue
  src/components/UIShared/LoadingPlaceholder.vue
  src/constants.js
Labels: 3. to review, backport-request, design, feature: frontend 🖌️

#12994 fix: remove extra spinner
  src/components/AvatarWrapper/AvatarWrapper.vue
Labels: backport-request, bug, feature: call 📹

#12998 fix: warning from `false` SearchBox's aria-describedby value
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13001 chore(release): Changelog for 20.0.0-rc.1
  CHANGELOG.md
Labels: 3. to review

#12969 fix(call): Fix race condition of "End call for everyone" and a parall…
  lib/Controller/CallController.php
  lib/Service/RoomService.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: call 📹

#13002 chore(eslint): ignore openapi generated files
  .eslintignore
  src/services/conversationsService.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13005 Release 20.0.0 rc.1
  CHANGELOG.md
Labels: 3. to review

#12999 feat: Add "New in Talk 20" messages
  lib/Chat/Changelog/Manager.php
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️

#13010 fix(avatar): increase avatar size to 40px
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
  src/components/LeftSidebar/InvitationHandler.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
  src/components/TopBar/TopBar.vue
  src/components/UIShared/LoadingPlaceholder.vue
  src/constants.js
Labels: 3. to review, design, feature: frontend 🖌️

#13016 Release 20.0.0 rc.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12997 fix(a11y): migrate NcModal to NcDialog p2
  src/components/BreakoutRoomsEditor/BreakoutRoomsEditor.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/LeftSidebar/CallPhoneDialog/CallPhoneDialog.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageForwarder.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageTranslateDialog.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewConversationDialog/NewConversationContactsPage.vue
  src/components/NewConversationDialog/NewConversationDialog.vue
  src/components/NewMessage/NewMessageNewFileDialog.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsActions.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser.vue
  src/components/RoomSelector.spec.js
  src/components/RoomSelector.vue
  src/components/SelectPhoneNumber.vue
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13028 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#13037 fix: Fix some minor things found by stan
  lib/Chat/MessageParser.php
  lib/Controller/RoomController.php
  lib/Service/BotService.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  tests/psalm-baseline.xml
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#13042 style(FilePreview): adjust row layout design
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#13041 fix(ConversationSettingsDialog): hide unused settings sections in 1-1
  src/components/ConversationSettings/ConversationSettingsDialog.vue
Labels: 3. to review, backport-request, feature: settings ⚙️, feature: frontend 🖌️

#13017 fix(SelectableParticipant): restyle component
  src/components/BreakoutRoomsEditor/SelectableParticipant.vue
Labels: 3. to review, design, feature: frontend 🖌️

#13036 Enable debug mode in helper script for integration tests
  tests/integration/run.sh
Labels: 3. to review, bug

#13049 fix(federation): Fix system message when a fed user is removed by mod…
  lib/Chat/Parser/SystemMessage.php
Labels: 3. to review, backport-request, bug

#13050 fix(guest): migrate localStorage nick to nextcloud/auth implementation
  src/PublicShareAuthSidebar.vue
  src/components/CallView/Grid/Grid.vue
  src/components/SetGuestUsername.vue
  src/stores/__tests__/guestName.spec.js
  src/stores/guestName.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13009 feat: Added blurhash to image metadata
  lib/Chat/Parser/SystemMessage.php
  lib/ResponseDefinitions.php
  lib/Share/Helper/FilesMetadataCache.php
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, feature: api 🛠️

#13030 fix: correct userGroups intersection check for federation access
  lib/Config.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#13057 fix(RightSidebar): hide sidebar button in lobby
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13068 chore(deps): bump nextcloud/vue from 8.16.0 to 8.17.0
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#13066 feat(FilePreview): add blurhash support
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#13064 chore(deps): Update openapi-extractor to v1.0.0
  openapi-administration.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/index.ts
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-bots.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request, dependencies

#13027 Fix adding and removing permissions
  lib/Model/AttendeeMapper.php
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-5/set-permissions.feature
Labels: 3. to review, backport-request, bug

#13035 feat: NoteToSelf messages are editable forever
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/ChatController.php
  tests/integration/features/chat-1/note-to-self.feature
Labels: 2. developing, backport-request, feature: chat 💬, feature: api 🛠️

#13087 fix(recording): distinguish global consent and room-level consent in constants
  src/components/AdminSettings/RecordingServers.vue
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/RecordingConsentSettings.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/TopBar/CallButton.vue
  src/constants.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#12698 chore(deps): replace vue-shortkey with vueuse directive
  package-lock.json
  package.json
  src/App.vue
  src/PublicShareAuthRequestPasswordButton.vue
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
  src/components/ConversationSettings/LinkShareSettings.vue
  src/components/NewMessage/NewMessage.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/TopBar/TopBarMenu.vue
  src/main.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/mainRecording.js
Labels: 3. to review, technical debt, feature: frontend 🖌️, dependencies

#13084 feat(NoteToSelf): allow to edit old messages on frontend
  src/__mocks__/capabilities.ts
  src/composables/__tests__/useMessageInfo.spec.js
  src/composables/useMessageInfo.js
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#13078 fix(signaling): check only required features on Frontend
  src/utils/signaling.js
Labels: 2. developing, backport-request, bug, feature: frontend 🖌️, client: 💻 desktop

#13093 fix(avatar): decrease size of loading spinner
  src/components/AvatarWrapper/AvatarWrapper.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️

#13074 fix(NcListItem): force three-dot-menu (+ minor follow-ups)
  src/components/AdminSettings/RecordingServers.vue
  src/components/AdminSettings/SIPBridge.vue
  src/components/AdminSettings/SignalingServers.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/WebServerSetupChecks.vue
  src/components/ConversationSettings/ConversationPermissionsSettings.vue
  src/components/ConversationSettings/DangerZone.vue
  src/components/ConversationSettings/LobbySettings.vue
  src/components/ConversationSettings/LockingSettings.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/NewMessage/NewMessage.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/RightSidebar.vue
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#13097 [stable30] chore(deps): bump libraries to align with main
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#12611 [stable28] chore(deps): bump @nextcloud/vue from 8.11.3 to ^8.14.0
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#13072 fix(federation): Sync room properties on join
  docs/events.md
  lib/AppInfo/Application.php
  lib/Controller/RoomController.php
  lib/Events/ARoomModifiedEvent.php
  lib/Events/ARoomSyncedEvent.php
  lib/Events/BeforeRoomSyncedEvent.php
  lib/Events/RoomSyncedEvent.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/Proxy/TalkV1/Controller/RoomController.php
  lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
  lib/Recording/Listener.php
  lib/Service/RoomService.php
  lib/Signaling/Listener.php
  openapi-federation.json
  openapi-full.json
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  tests/php/Service/RoomServiceTest.php
  tests/php/Signaling/ListenerTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#13086 fix(conversations): Remove call-permissions
  .github/workflows/integration-mariadb.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  docs/conversation.md
  docs/participant.md
  lib/Controller/CallController.php
  lib/Controller/RoomController.php
  lib/Events/ARoomModifiedEvent.php
  lib/Participant.php
  lib/Room.php
  lib/Service/RoomFormatter.php
  lib/Service/RoomService.php
  lib/Signaling/Listener.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-2/bots.feature
  tests/integration/features/chat-2/mentions.feature
  tests/integration/features/chat-3/poll.feature
  tests/integration/features/chat-3/public-read-only.feature
  tests/integration/features/chat-3/public.feature
  tests/integration/features/chat-3/reaction.feature
  tests/integration/features/chat-3/read-status.feature
  tests/integration/features/chat-3/reference-id.feature
  tests/integration/features/chat-3/reminder.feature
  tests/integration/features/chat-4/reply.feature
  tests/integration/features/chat-4/rich-messages.feature
  tests/integration/features/chat-4/rich-object-share.feature
  tests/integration/features/chat-4/search.feature
  tests/integration/features/chat-4/system-messages.feature
  tests/integration/features/chat-4/typing-privacy.feature
  tests/integration/features/chat-4/unread-messages.feature
  tests/integration/features/conversation-5/bruteforce-protection.feature
  tests/integration/features/conversation-5/delete-room.feature
  tests/integration/features/conversation-5/delete-user.feature
  tests/integration/features/conversation-5/set-permissions.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: conversations 👥

#13092 fix(federation): Propagate permission changes to federated servers
  lib/AppInfo/Application.php
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/FederationManager.php
  lib/Federation/Proxy/TalkV1/Notifier/ParticipantModifiedListener.php
  lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/permissions.feature
  tests/php/Federation/FederationTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#13103 Release 18.0.11
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#13104 Release 19.0.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#13108 Release 20.0.0 rc.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#13112 fix(TopBar): show "now" instead of start time when it is in the past
  src/components/TopBar/TopBar.vue
Labels: backport-request, bug, feature: frontend 🖌️, feature: conversations 👥

#13109 fix(FilePreview): set fixed size to image container
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#13116 fix(Reactions): show all names if they are at most 4 reactions
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Reactions.vue
Labels: enhancement, feature: chat 💬, feature: frontend 🖌️, feature: reactions 👍

#13135 docs: Fix values for used recording consent options
  docs/constants.md
  docs/conversation.md
Labels: 3. to review, backport-request, bug

#13138 fix(GuestWelcomeWindow): fix padding and text clipping
  src/components/GuestWelcomeWindow.vue
Labels: 3. to review, feature: frontend 🖌️, feature: conversations 👥

#13142 fix(federation): Expire sessions of federated users
  lib/Controller/RoomController.php
  lib/Service/SessionService.php
  tests/php/Service/SessionServiceTest.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#13140 feat(calls): Support "Send call notification" for and with federated …
  docs/call.md
  lib/Controller/CallController.php
  lib/Events/AParticipantModifiedEvent.php
  lib/Events/CallNotificationSendEvent.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/Proxy/TalkV1/Controller/CallController.php
  lib/Federation/Proxy/TalkV1/Notifier/ParticipantModifiedListener.php
  lib/Notification/Listener.php
  lib/Notification/Notifier.php
  lib/Service/ParticipantService.php
  src/components/RightSidebar/Participants/Participant.vue
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/call.feature
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: call 📹, feature: federation 🌐

#13149 fix(federation): ensure federation invites appear in store
  src/App.vue
  src/services/federationService.ts
  src/stores/__tests__/federation.spec.js
  src/stores/federation.ts
  src/types/index.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: federation 🌐

#13150 fix(federation): Correctly handle decline in system messages
  lib/Chat/Parser/SystemMessage.php
  tests/integration/features/federation/chat.feature
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: federation 🌐

#13122 feat(NoteToSelf): add tasks counter
  src/components/MessagesList/MessagesList.spec.js
  src/components/MessagesList/MessagesList.vue
  src/components/TopBar/TasksCounter.vue
  src/components/TopBar/TopBar.vue
  src/stores/chatExtras.js
Labels: 3. to review, feature: frontend 🖌️, feature: conversations 👥

#12890 feat(Call): show presenter overlay for local screenshare
  src/components/CallView/CallView.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/PresenterOverlay.vue
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: call 📹

#13154 fix(appconfig): Ensure configs are within ranges
  lib/Config.php
Labels: 3. to review, backport-request, technical debt

#13133 feat(error_message): Display proper message on error on join call
  src/components/CallView/shared/EmptyCallView.vue
  src/store/participantsStore.js
  src/utils/signaling.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#13168 fix(TopBar): disable buttons if user has no media permissions
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
  src/components/TopBar/TopBarMediaControls.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: call 📹

#13166 fix: remove rebase bug
  src/components/CallView/shared/LocalVideo.vue
Labels: bug

#13167 fix(api): Properly typed room-property updates - Part 1
  lib/Command/Room/TRoomCommand.php
  lib/Controller/RoomController.php
  lib/Exceptions/RoomProperty/DefaultPermissionsException.php
  lib/Exceptions/RoomProperty/LobbyException.php
  lib/Exceptions/RoomProperty/NameException.php
  lib/Exceptions/RoomProperty/RecordingConsentException.php
  lib/Exceptions/RoomProperty/SipConfigurationException.php
  lib/Service/RoomService.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, feature: api 🛠️

#13159 fix(CallView): remove shadow of avatars
  src/components/CallView/CallView.vue
Labels: bug, feature: frontend 🖌️, feature: call 📹

#13147 fix(FilePreview): use original size for uploaded image files
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#13177 fix(TasksCounter): fix translations
  src/components/TopBar/TasksCounter.vue
Labels: backport-request, regression, feature: frontend 🖌️

#13180 fix(FilePreview): limit preview size to 384px at upload
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#13145 fix(tests): Always use absolute path in run-docker.sh
  tests/integration/run-docker.sh
Labels: 3. to review, feature: api 🛠️, technical debt

#13187 fix: use provide/inject to pass values of devMode to CallView children
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#13182 docs: update screenshots in appstore to match Nc30 styles
  docs/call-in-action.jpg
  docs/call-in-action.png
  docs/chat.png
  docs/file-darg-and-drop.png
  docs/screensharing.png
  docs/video-verfication.png
Labels: 3. to review, pending documentation
