Repository nextcloud/spreed, pull requests merged in 2024-07, with the labels that each got.

#12627 Only check path for being accessible when the storage is a object home
  lib/Share/RoomShareProvider.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: upload & shares & voice 📤🎙️

#12510 feat: show out of office replacement
  src/components/NewMessage/NewMessageAbsenceInfo.vue
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: conversations 👥

#12361 feat(CallView): introduce dynamic order
  src/components/CallView/Grid/Grid.vue
  src/store/participantsStore.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: call 📹

#12632 fix(chat): promptly update messages list in sidebar, store and chat
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#12557 fix(conversation): adjust broadcasted data between tabs
  src/components/LeftSidebar/LeftSidebar.vue
  src/store/conversationsStore.js
  src/store/participantsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️

#12635 fix(deps): Use less 3rdparty dependencies by comparing `IDBConnection::PLATFORM_*`
  lib/Migration/Version2001Date20170707115443.php
  lib/Migration/Version2001Date20171026134605.php
  lib/Migration/Version2001Date20180103144447.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review

#12640 fix(MessagesSystemGroup): separate messages with different actors
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
Labels: backport-request, bug, feature: chat 💬

#12643 chore(deps): bump nextcloud/vue from 8.13.0 to 8.14.0
  package-lock.json
  package.json
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
Labels: 3. to review, feature: frontend 🖌️, dependencies

#12648 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12652 fix(license): Change reuse to toml file
  .github/workflows/reuse.yml
  .reuse/dep5
  REUSE.toml
Labels: 3. to review

#12644 Fix(GroupSystemMessages): add tests and adjust conditions for combined messages
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
Labels: 3. to review, feature: chat 💬, feature: frontend 🖌️

#12651 fix(chat): wrap Quote in RouterLink to handle in-app navigation
  src/components/Quote.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#12641 fix(MessagesList): show date separator when div is not scrollable
  src/components/MessagesList/MessagesList.vue
Labels: bug, feature: chat 💬

#12661 fix(federation): Fix federation with Nextcloud 29.0.4 or later
  appinfo/info.xml
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Migration/Version19000Date20240709183937.php
  tests/php/Federation/FederationTest.php
Labels: 3. to review, backport-request, bug, regression, feature: api 🛠️, feature: federation 🌐

#12664 fix(chat): Fix missing reference information for federated message links
  lib/Chat/ChatManager.php
  lib/Collaboration/Reference/TalkReferenceProvider.php
  lib/Exceptions/InvalidRoomException.php
  lib/Model/ProxyCacheMessageMapper.php
  lib/Notification/Notifier.php
  tests/php/Collaboration/Reference/TalkReferenceProviderTest.php
  tests/php/Service/ProxyCacheMessageServiceTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: federation 🌐

#12659 fix(MessageList): Workaround rendering issue on safari when unread marker is removed
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, feature: chat 💬, feature: api 🛠️, browser: Safari

#12657 feat(filepicker): add button to show smart picker
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageAttachments.vue
  src/components/Quote.vue
Labels: enhancement, feature: chat 💬, feature: frontend 🖌️

#12558 feat: Added database migration for banning users
  appinfo/info.xml
  appinfo/routes/routesBanController.php
  lib/Controller/BanController.php
  lib/Migration/Version20000Date20240621150333.php
  lib/Model/Ban.php
  lib/Model/BanMapper.php
  lib/Service/BanService.php
  openapi-full.json
  openapi.json
  src/services/banService.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-1/ban.feature
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#12655 fix(directive): replace v-observe-visibility with vIntersectionObserver
  package-lock.json
  package.json
  src/components/MessagesList/MessagesGroup/Message/Message.spec.js
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue
  src/components/NewConversationDialog/NewConversationContactsPage.vue
  src/main.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/mainRecording.js
Labels: 3. to review, feature: frontend 🖌️, dependencies

#12633 fix(settings): drop local setting for background blur filter, use provided by server
  lib/TInitialState.php
  src/components/CallView/CallView.vue
  src/components/SettingsDialog/SettingsDialog.vue
Labels: 3. to review, backport-request, feature: api 🛠️, technical debt, feature: frontend 🖌️

#12672 fix(dashboard): Fix missing dashboard icon
  lib/Dashboard/TalkWidget.php
Labels: 3. to review, backport-request, bug, design, feature: frontend 🖌️

#12550 fix(chat): show spinner for temporary / edited messages
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#12554 [stable29] perf(sharing): Use getFirstNodeById() which is more performant
  lib/Chat/Parser/SystemMessage.php
  tests/php/Chat/Parser/SystemMessageTest.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: upload & shares & voice 📤🎙️, deployed on testing, performance 🚀

#12675 chore(release): Changelog for 18.0.10 and 19.0.5
  CHANGELOG.md
Labels: 3. to review

#12680 Release 19.0.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12685 fix(federation): Also fix room::remote_server and pcm::remote_server_url
  appinfo/info.xml
  lib/Migration/Version19000Date20240709183938.php
Labels: 3. to review, backport-request, feature: chat 💬, feature: api 🛠️, feature: federation 🌐

#12686 fix(federation): Allow setting the session state in federated convers…
  lib/Controller/RoomController.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Notification/FederationChatNotifier.php
  lib/Service/ParticipantService.php
  tests/integration/features/federation/chat.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#12695 chore(release): Release 19.0.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12696 chore(deps): bump @nextcloud/upload library from 1.4.1 to 1.4.2
  package-lock.json
  package.json
Labels: 3. to review, bug, dependencies

#12713 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12714 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12712 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12697 fix(chat): keep message parents in the store after update
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, backport-request, regression, feature: chat 💬, feature: frontend 🖌️

#12710 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 3. to review, dependencies, automated

#12671 fix: Moderators no longer able to ban themselves or other moderators
  lib/Service/BanService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-1/ban.feature
Labels: 3. to review, bug, feature: api 🛠️

#12715 fix(federation): Fix message parameters after adjusting https handling
  lib/Federation/Proxy/TalkV1/UserConverter.php
  lib/Model/SelectHelper.php
  lib/Model/SessionMapper.php
  lib/Notification/FederationChatNotifier.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, deployed on testing, feature: federation 🌐

#12723 fix(ban): Limit query for participants when they actually can be a moderator
  lib/Controller/BanController.php
  lib/Model/Ban.php
  lib/Service/BanService.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/conversation-1/ban.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: conversations 👥

#12725 debug: add time measurement for chat requests
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
  src/utils/debugTimer.ts
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#12733 chore(release): Add changelog for 19.0.7
  CHANGELOG.md
Labels: 3. to review

#12734 Release 19.0.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12730 fix(CI): Fix mariadb and mysql options in integration test
  .github/workflows/integration-mariadb.yml
  .github/workflows/integration-mysql.yml
Labels: 3. to review

#12639 fix(CallView): freeze promoted video on hover
  src/components/CallView/CallView.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/VideoVue.vue
Labels: feature: call 📹

#12718 fix: add edited and server hints to author name in quotes
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/Quote.vue
  src/composables/__tests__/useMessageInfo.spec.js
  src/composables/useMessageInfo.js
Labels: backport-request, feature: chat 💬, feature: frontend 🖌️

#12658 fix: refactor messages list update in watchers
  src/components/ChatView.vue
  src/components/MessagesList/MessagesList.vue
Labels: feature: chat 💬, feature: frontend 🖌️

#12739 fix(bans): minor corrections
  src/components/ConversationSettings/BanSettings/BannedItem.vue
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/RightSidebar/Participants/Participant.vue
  src/store/participantsStore.js
  src/views/ForbiddenView.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: conversations 👥

#12662 style: adjust variables and styles for Nc30
  src/PublicShareSidebar.vue
  src/PublicShareSidebarTrigger.vue
  src/assets/missingMaterialDesignIcons/MenuPeople.vue
  src/components/AdminSettings/AllowedGroups.vue
  src/components/AdminSettings/RecordingServer.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/TurnServer.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBackground.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/ConversationSettings/BotsSettings.vue
  src/components/ConversationSettings/Matterbridge/BridgePart.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageAbsenceInfo.vue
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/SettingsDialog/SettingsDialog.vue
  src/components/TopBar/TopBar.vue
  src/components/UIShared/EditableTextField.vue
  src/components/UIShared/Hint.vue
  src/components/UIShared/SearchBox.vue
  src/views/FilesSidebarChatView.vue
Labels: 3. to review, design, feature: frontend 🖌️

#12741 fix(federation): Ignore outdated sessions when checking for active se…
  lib/Service/ParticipantService.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: federation 🌐

#12743 fix: Fix generating session id again if duplicated
  lib/Service/SessionService.php
  tests/php/Service/SessionServiceTest.php
Labels: 3. to review, backport-request, bug

#12740 feat: Added (user,state) index for talk_invitations
  appinfo/info.xml
  lib/Migration/Version18000Date20231024141627.php
  lib/Migration/Version20000Date20240716190335.php
Labels: 3. to review, bug, feature: api 🛠️, feature: federation 🌐, performance 🚀

#12559 fix: chat jumping when reference widgets are rendered
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/MessagesList/MessagesList.vue
Labels: feature: chat 💬

#12752 fix(sharing): Don't repopulate query builder object
  lib/Share/RoomShareProvider.php
Labels: 3. to review, feature: api 🛠️, feature: upload & shares & voice 📤🎙️

#12754 [stable29] chore: update workflow templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, technical debt

#12753 fix(Quote): simplify styles for ellipsized text
  src/components/Quote.vue
Labels: 3. to review, bug, feature: chat 💬, feature: frontend 🖌️

#12758 fix(ci): Use apcu in all integration tests
  .github/workflows/integration-mariadb.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-sqlite.yml
Labels: 3. to review

#12261 fix(LeftSidebar): get rid of server styles for settings button
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, feature: frontend 🖌️

#12769 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12770 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12746 fix(ban): Validate actor types on banning
  lib/Controller/BanController.php
  lib/Service/BanService.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, bug, feature: api 🛠️

#12756 fix(federation): Make sure the returned unread message count is alway…
  lib/Model/Attendee.php
  tests/php/Controller/ChatControllerTest.php
Labels: 3. to review, bug, feature: api 🛠️, feature: federation 🌐

#12774 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12691 Ban guests by ip
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Middleware/InjectionMiddleware.php
  lib/Model/BanMapper.php
  lib/Service/BanService.php
  lib/TalkSession.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-1/ban.feature
  tests/php/Controller/SignalingControllerTest.php
Labels: 3. to review, bug, feature: api 🛠️

#12749 fix: Removed redundant database indices
  appinfo/info.xml
  lib/Migration/Version10000Date20201015134000.php
  lib/Migration/Version18000Date20230504205823.php
  lib/Migration/Version20000Date20240717180417.php
Labels: bug, feature: api 🛠️

#12776 Fix mapping of token to identifier for federated rooms
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/chat.feature
  tests/integration/features/federation/invite.feature
  tests/integration/features/federation/poll.feature
  tests/integration/features/federation/reminder.feature
Labels: 3. to review, backport-request, bug

#12767 style: design adjustments for Nc30
  package-lock.json
  package.json
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesGroup/Message/Message.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewConversationDialog/NewConversationSetupPage.vue
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, design, feature: frontend 🖌️

#12618 feat(mentions): prevent mention `@all` for non moderators
  appinfo/info.xml
  appinfo/routes/routesRoomController.php
  docs/capabilities.md
  docs/constants.md
  docs/conversation.md
  lib/Capabilities.php
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Chat/Parser/UserMention.php
  lib/Controller/RoomController.php
  lib/Events/ARoomModifiedEvent.php
  lib/Manager.php
  lib/Migration/Version20000Date20240623123938.php
  lib/Model/Message.php
  lib/Model/SelectHelper.php
  lib/ResponseDefinitions.php
  lib/Room.php
  lib/Service/RoomFormatter.php
  lib/Service/RoomService.php
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/ConversationSettings/MentionsSettings.vue
  src/constants.js
  src/services/conversationsService.js
  src/store/conversationsStore.js
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-1/mentions.feature
  tests/integration/features/chat-1/notifications.feature
  tests/php/Chat/ChatManagerTest.php
  tests/php/Chat/NotifierTest.php
  tests/php/Chat/Parser/UserMentionTest.php
  tests/php/Service/RoomServiceTest.php
Labels: 2. developing, feature: chat 💬, feature: api 🛠️, feature: frontend 🖌️, feedback-requested

#12780 fix(openapi): Update openapi extractor to latest
  openapi-administration.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-bots.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/services/banService.ts
  src/types/index.ts
  src/types/openapi/openapi-administration.ts
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-bots.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review

#12782 feat(chat): Outline the participant count when trying to mention ever…
  docs/chat.md
  lib/Chat/ChatManager.php
  lib/ResponseDefinitions.php
  openapi-full.json
  openapi.json
  src/components/NewMessage/NewMessage.vue
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-1/mentions.feature
  tests/php/Chat/ChatManagerTest.php
Labels: 3. to review, enhancement, feature: chat 💬

#12784 fix(chat): Fix OpenAPI optional attributes on mentions
  lib/Controller/ChatController.php
  lib/ResponseDefinitions.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, backport-request, feature: chat 💬, feature: api 🛠️

#12785 Add real federated server for integration tests
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/federation/chat.feature
  tests/integration/features/federation/poll.feature
  tests/integration/run.sh
Labels: 3. to review, feature: federation 🌐

#12777 fix: Do not try to post messages when federated room visibility changes
  lib/Chat/SystemMessage/Listener.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#12787 fix(tests): Ignore all integration server logs
  .gitignore
Labels: 3. to review

#12786 Propagate lobby state to federated servers
  lib/AppInfo/Application.php
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
  tests/integration/features/federation/lobby.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#12791 [stable29] fix(chat): Fix OpenAPI optional attributes
  lib/Controller/ChatController.php
  lib/ResponseDefinitions.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#12604 Add support for external signaling federation
  appinfo/info.xml
  appinfo/routes/routesRoomController.php
  docs/capabilities.md
  lib/Capabilities.php
  lib/Config.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Federation/Proxy/TalkV1/Controller/RoomController.php
  lib/Federation/Proxy/TalkV1/Controller/SignalingController.php
  lib/Migration/Version20000Date20240718031959.php
  lib/Model/AttendeeMapper.php
  lib/ResponseDefinitions.php
  lib/Service/ParticipantService.php
  lib/Service/SessionService.php
  lib/Signaling/BackendNotifier.php
  lib/Signaling/Manager.php
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/components/RightSidebar/Participants/Participant.vue
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  src/utils/signaling.js
  src/utils/webrtc/index.js
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/chat.feature
  tests/integration/features/federation/join-leave.feature
  tests/integration/features/federation/reminder.feature
  tests/integration/mocks/FakeSignalingServer.php
  tests/php/ConfigTest.php
  tests/php/Controller/SignalingControllerTest.php
  tests/php/Recording/BackendNotifierTest.php
  tests/php/Service/SessionServiceTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: frontend 🖌️, client: 🤖🍏 mobile, feature: call 📹, feature: federation 🌐

#12812 fix(AdminSettings): hide secrets in password fields
  src/components/AdminSettings/RecordingServers.vue
  src/components/AdminSettings/SIPBridge.vue
  src/components/AdminSettings/SignalingServers.vue
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, feature: settings ⚙️, feature: frontend 🖌️

#12816 tests: Fix "using server" step definition
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, bug

#12668 Add support for federated calls
  appinfo/routes/routesCallController.php
  docs/events.md
  lib/Activity/Listener.php
  lib/AppInfo/Application.php
  lib/Controller/CallController.php
  lib/Events/AActiveSinceModifiedEvent.php
  lib/Events/ARoomModifiedEvent.php
  lib/Events/ActiveSinceModifiedEvent.php
  lib/Events/BeforeActiveSinceModifiedEvent.php
  lib/Federation/BackendNotifier.php
  lib/Federation/CloudFederationProviderTalk.php
  lib/Federation/Proxy/TalkV1/Controller/CallController.php
  lib/Federation/Proxy/TalkV1/Notifier/RoomModifiedListener.php
  lib/Manager.php
  lib/Middleware/Attribute/RequireFederatedParticipant.php
  lib/Middleware/InjectionMiddleware.php
  lib/Model/SelectHelper.php
  lib/Room.php
  lib/Service/RoomFormatter.php
  lib/Service/RoomService.php
  lib/Signaling/BackendNotifier.php
  openapi-full.json
  openapi.json
  src/components/ConversationSettings/ConversationSettingsDialog.vue
  src/components/TopBar/CallButton.vue
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/federation/call.feature
  tests/php/Service/RoomServiceTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: frontend 🖌️, client: 🤖🍏 mobile, feature: call 📹, feature: federation 🌐

#12771 fix(AdminSettings): Require HPB for recording server configuration
  src/components/AdminSettings/HostedSignalingServer.vue
  src/components/AdminSettings/RecordingServers.vue
  src/components/AdminSettings/SIPBridge.vue
  src/components/AdminSettings/SignalingServers.vue
Labels: 3. to review, feature: settings ⚙️, feature: frontend 🖌️, feature: recordings ⏺️

#12822 Release 20.0.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#12825 fix(public share): make trigger button color contrast to background
  src/PublicShareSidebarTrigger.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#12834 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12836 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12838 fix(MediaSettings): remove PiP and increase mirror toggle margin
  src/components/MediaSettings/MediaSettings.vue
Labels: 3. to review, bug, design, feature: frontend 🖌️

#12814 fix(AdminSettings): server buttons visual interactivity
  src/components/AdminSettings/RecordingServer.vue
  src/components/AdminSettings/SignalingServer.vue
  src/components/AdminSettings/StunServer.vue
  src/components/AdminSettings/TurnServer.vue
Labels: 3. to review, design, feature: settings ⚙️, feature: frontend 🖌️

#12824 fix(Quote): prevent button click event from propagation
  src/components/Quote.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#12839 fix(AdminSettings): remove PHP template
  css/talk-admin-settings.css
  lib/Settings/Admin/AdminSettings.php
  templates/settings/admin-settings.php
Labels: 3. to review, bug, feature: settings ⚙️, feature: frontend 🖌️

#12833 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#12810 fix(design): adjustments for Nextcloud 30 - v3
  package-lock.json
  package.json
  src/components/ConversationIcon.vue
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MediaSettings/MediaDevicesSelector.vue
  src/components/MediaSettings/MediaDevicesSpeakerTest.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessagePollEditor.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomItem.vue
  src/constants.js
Labels: 3. to review, design, feature: frontend 🖌️

#12835 [stable27] Update nextcloud/ocp dependency
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  composer.lock
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, dependencies

#12859 fix(cs): Use single quotes for simple strings
  lib/Command/Developer/UpdateDocs.php
  lib/Controller/RecordingController.php
  lib/Controller/SignalingController.php
  lib/MatterbridgeManager.php
  tests/integration/features/bootstrap/CommandLineTrait.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/php/Service/CertificateServiceTest.php
Labels: 3. to review

#12858 fix(tests): Limit notification testing to `app='spreed'`
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, feature: api 🛠️

#12860 fix(openapi): add remote* fields to Room definition
  lib/ResponseDefinitions.php
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, feature: api 🛠️

#12845 feat(calls): Add notifications for federated calls
  lib/AppInfo/Application.php
  lib/Controller/CallController.php
  lib/Events/ActiveSinceModifiedEvent.php
  lib/Notification/Listener.php
  lib/Notification/Notifier.php
  lib/Service/RoomService.php
  tests/integration/features/federation/call.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: call 📹, feature: federation 🌐
