Repository nextcloud/spreed, pull requests merged in 2025-09, with the labels that each got.

#15767 fix(CalendarEventsDialog): don't let popovers overlap
  src/components/CalendarEventsDialog.vue
  src/components/ExtendOneToOneDialog.vue
Labels: regression, feature: frontend 🖌️, feature: conversations 👥

#15769 fix(vue3): adjust to Vue 3, fix regressions
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/RoomSelector.vue
  src/components/UIShared/StaticDateTime.vue
  src/utils/davUtils.ts
  src/utils/requestRoomSelection.js
Labels: 3. to review, bug, regression, feature: frontend 🖌️

#15770 fix: Use normal subtitles icon instead of outline when enabled
  src/components/CallView/BottomBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: call 📹

#15774 fix(MessagesList): scroll to bottom when joining the call
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#15771 fix(Dashboard): wrap buttons and break words
  src/components/Dashboard/DashboardSection.vue
  src/components/Dashboard/TalkDashboard.vue
Labels: regression, feature: frontend 🖌️, feature: dashboard 🏠

#15781 fix(threads): Hide unsubscribed threads from "Followed threads"
  lib/Service/ThreadService.php
Labels: 3. to review, bug, feature: api 🛠️, feature: threads 🧵

#15782 fix(thread): Fix thread info for the root message
  lib/Controller/ChatController.php
Labels: 3. to review, bug, feature: api 🛠️, feature: threads 🧵

#15787 fix(LeftSidebar): show loading state in sidebar
  src/components/LeftSidebar/LeftSidebar.vue
  src/stores/chatExtras.ts
Labels: 3. to review, bug, feature: frontend 🖌️

#15788 fix(PollViewer): fix mispositioned icons
  src/components/PollViewer/PollVotersDetails.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#15790 fix(threads): prevent submitting a thread without a title
  src/components/NewMessage/NewMessage.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: threads 🧵

#15793 fix: fix skewed position of user status
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
Labels: feature: frontend 🖌️

#15789 fix: don't reset automatically threads list
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, feature: frontend 🖌️, feature: conversations 👥

#15819 style(ThreadItem): adjust color scheme
  src/components/RightSidebar/Threads/ThreadItem.vue
  src/components/TopBar/TopBar.vue
Labels: backport-request

#15829 style(BottomBar): increase selector specificity for tertiary buttons
  src/components/CallView/BottomBar.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15832 style(BottomBar): increase selector specificity for control buttons
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15836 fix(messagesStore): harden check for lastMessage
  src/store/messagesStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15839 fix: remove old migrations
  src/init.js
Labels: backport-request, technical debt, feature: frontend 🖌️

#15850 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15851 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_core.ts
  src/types/openapi/core/openapi_files_sharing.ts
Labels: 3. to review, dependencies

#15835 fix(RecycleScroller): reuse items for better performance
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationSearchResult.vue
  src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15838 fix(call): apply selected device state after closing dialog in call
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
  src/components/MediaSettings/MediaSettings.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: call 📹

#15871 fix(chat): do not highlight messages, if they're not focused
  src/components/MessagesList/MessagesList.vue
  src/components/Quote.vue
  src/components/RightSidebar/SearchMessages/SearchMessageItem.vue
  src/composables/useGetMessages.ts
  src/services/EventBus.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15878 fix(CallView): align UI elements
  src/components/CallView/BottomBar.vue
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/VideoVue.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: call 📹

#15881 chore: update transifex link
  .github/contributing.md
Labels: 3. to review

#15916 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15834 fix: removed deprecated relics from the early, experimental days of WebRTC
  src/components/TopBar/TopBarMediaControls.vue
  src/utils/webrtc/simplewebrtc/getscreenmedia.js
Labels: backport-request, feature: WebRTC 🚡, technical debt

#15902 fix(threads): remove unsubscribed threads from the list
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RightSidebar/Threads/ThreadItem.vue
  src/stores/chatExtras.ts
  src/utils/prepareTemporaryMessage.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15937 fix(threads): upload files in the opened thread
  src/components/ChatView.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: threads 🧵

#15939 chore(deps): bump @nextcloud/dialogs 7.0.0-rc.3
  package-lock.json
  package.json
Labels: dependencies

#15935 feat: add thread controls in sidebar / in-call chat
  src/components/ChatView.vue
  src/components/MessagesList/MessagesList.vue
  src/components/RightSidebar/Threads/ThreadHeader.vue
  src/components/RightSidebar/Threads/ThreadItem.vue
  src/components/RightSidebar/Threads/threadsConstants.ts
  src/components/TopBar/TopBar.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, feature: talk-sidebar ⬅️, feature: call 📹

#15942 fix(tests): Reduce the error spam from missing default contact
  tests/integration/run.sh
Labels: 3. to review, backport-request, feature: api 🛠️

#15943 fix(threads): Count shared files as thread replies and last message
  lib/Chat/SystemMessage/Listener.php
  lib/Service/ThreadService.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/integration/features/chat-4/threads.feature
Labels: 3. to review, backport-request, bug, feature: upload & shares & voice 📤🎙️, feature: threads 🧵

#15880 fix(threads): add threadId to objectId for notifications
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Chat/SystemMessage/Listener.php
  lib/Notification/Notifier.php
  lib/Search/MessageSearch.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/chat-4/threads.feature
Labels: 2. developing, bug, feature: api 🛠️, feature: threads 🧵

#15960 style(TopBar): set fixed width for digit characters
  src/components/TopBar/CallTime.vue
  src/components/TopBar/TopBar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#15959 fix(LeftSidebar): allow to search for strings with diacritics
  src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15955 chore(release): Add changelog for 20.1.10 and 21.1.5
  CHANGELOG.md
Labels: 3. to review

#15967 Release 21.1.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#15949 fix(devices): fix reactive update of the devices list
  src/components/CallView/shared/LocalAudioControlButton.vue
  src/components/CallView/shared/LocalVideoControlButton.vue
  src/components/MediaSettings/MediaSettings.vue
  src/composables/useDevices.js
  src/utils/webrtc/MediaDevicesManager.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15974 chore: prepare changelog for v22.0.0-rc.3
  CHANGELOG.md
Labels: 3. to review

#15985 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15986 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15984 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#16000 fix(threads): Allow posting polls into threads (frontend)
  src/components/PollViewer/PollEditor.vue
  src/services/messagesService.ts
  src/services/pollService.ts
  src/stores/polls.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: polls 📊, feature: threads 🧵

#15999 fix(chat): attach actual parent message to file uploads
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/store/fileUploadStore.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#15995 fix(sounds): do not pause playing audio on speaker change
  src/composables/useDevices.js
  src/stores/sounds.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#16012 fix(threads): show main chat after activity in a thread view on a fresh reload
  src/composables/useGetMessages.ts
  src/stores/chat.ts
Labels: 3. to review, backport-request, regression, feature: frontend 🖌️, feature: threads 🧵

#16015 chore(dependencies): bump @nextcloud/vue to stable v9.0.0
  package-lock.json
  package.json
  src/components/CalendarEventsDialog.vue
  src/components/MediaSettings/MediaSettings.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️, dependencies

#16028 chore: prepare v22.0.0-rc.4 release
  CHANGELOG.md
Labels: 3. to review

#16031 fix(LeftSidebar): change wording to 'Threads'
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️

#16013 fix(threads): show thread icon in LeftSidebar
  src/utils/getMessageIcon.ts
Labels: 3. to review, enhancement, feature: frontend 🖌️

#16030 fix(chat): improve check for last message context
  src/composables/useGetMessages.ts
  src/stores/chat.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#16048 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#16049 chore(lint): enable 'vue/multi-word-component-names' rule
  eslint.config.mjs
  src/RecordingApp.vue
  src/components/AdminSettings/FederationSettings.vue
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/VideosGrid.vue
  src/components/CallView/shared/ScreenShare.vue
  src/components/CallView/shared/VideoBottomBar.spec.js
  src/components/CallView/shared/VideoVue.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/LeftSidebar/ConversationsList/Conversation.spec.js
  src/components/LeftSidebar/ConversationsList/ConversationItem.vue
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
  src/components/LeftSidebar/InvitationHandler.vue
  src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
  src/components/MessageQuote.vue
  src/components/MessagesList/MessagesGroup/Message/MessageItem.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessageItem.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/ContactCard.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/LocationCard.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MentionChip.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/PollCard.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsWrapper.spec.js
  src/components/MessagesList/MessagesGroup/Message/MessagePart/ReactionsWrapper.vue
  src/components/MessagesList/MessagesGroup/MessagesGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesGroup.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.spec.js
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
  src/components/NewMessage/NewMessage.vue
  src/components/PollViewer/PollDraftHandler.vue
  src/components/RightSidebar/BreakoutRooms/BreakoutRoomsTab.vue
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/RightSidebar/Participants/ParticipantItem.vue
  src/components/RightSidebar/Participants/ParticipantsList.vue
  src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
  src/components/RightSidebar/Participants/ParticipantsSearchResults.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/SelectPhoneNumber.vue
  src/components/UIShared/NavigationHint.vue
  src/mainRecording.js
  src/services/messagesService.ts
  src/services/pollService.ts
  src/views/AdminSettings.vue
Labels: 3. to review, technical debt, feature: frontend 🖌️
