Repository nextcloud/spreed, pull requests merged in 2025-02, with the labels that each got.

#14278 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14279 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14255 fix(Screen): change double-click behaviour for screenshare panzoom
  src/components/CallView/shared/Screen.vue
Labels: 3. to review, feature: frontend 🖌️, feature: call 📹

#14289 Empty iceServers.urls handling fix (reloaded)
  lib/Controller/SignalingController.php
  tests/php/Controller/SignalingControllerTest.php
Labels: 3. to review, backport-request, bug, feature: settings ⚙️, feature: signaling 📶

#14297 fix(dashboard): Hide archived conversations from dashboard unless mentioned
  lib/Dashboard/TalkWidget.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-1/archive.feature
  tests/integration/features/integration/dashboard.feature
Labels: 3. to review, backport-request, bug, feature: talk-sidebar ⬅️, feature: conversations 👥

#14286 ci: Update psalm to v6
  .github/workflows/psalm.yml
  composer.json
  lib/Controller/RecordingController.php
  lib/Controller/SignalingController.php
  psalm.xml
  tests/psalm-baseline.xml
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, feature: api 🛠️, technical debt

#14304 fix(absence): Don't break when you are the absence or it's recursion
  src/components/NewMessage/NewMessageAbsenceInfo.vue
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: frontend 🖌️

#14303 feat(bots): Let bots know the parent message when it was a reply
  lib/Events/BotInvokeEvent.php
  lib/Service/ActivityPubHelper.php
  lib/Service/BotService.php
  tests/psalm-baseline.xml
Labels: 3. to review, backport-request, enhancement, feature: api 🛠️, feature: bots 🤖

#14270 feat(chat): Add the mention id to parameters for easier editing
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Federation/Proxy/TalkV1/UserConverter.php
  tests/integration/features/callapi/notifications.feature
  tests/integration/features/chat-1/delete.feature
  tests/integration/features/chat-1/edit-message.feature
  tests/integration/features/chat-1/file-share.feature
  tests/integration/features/chat-1/note-to-self.feature
  tests/integration/features/chat-3/poll.feature
  tests/integration/features/chat-3/reaction.feature
  tests/integration/features/chat-4/rich-messages.feature
  tests/integration/features/chat-4/rich-object-share.feature
  tests/integration/features/chat-4/unread-messages.feature
  tests/integration/features/command/user-remove.feature
  tests/integration/features/conversation-1/avatar.feature
  tests/integration/features/federation/chat.feature
  tests/integration/features/federation/invite.feature
  tests/integration/features/federation/poll.feature
  tests/integration/features/sharing-1/delete.feature
  tests/php/Chat/Parser/SystemMessageTest.php
  tests/php/Chat/Parser/UserMentionTest.php
Labels: 3. to review, backport-request, enhancement, feature: chat 💬, feature: api 🛠️

#14314 chore(release): Add changelog 21.0.0-rc.3
  CHANGELOG.md
Labels: 3. to review

#14322 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14323 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14329 fix(PresenterOverlay): fix RTL check
  src/App.vue
  src/components/CallView/shared/PresenterOverlay.vue
  src/components/MessagesList/MessagesList.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#14324 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14335 feat(bots): Allow bots to get invoked for reactions
  docs/events.md
  lib/AppInfo/Application.php
  lib/Chat/ReactionManager.php
  lib/Controller/BotController.php
  lib/Controller/ReactionController.php
  lib/Events/AReactionEvent.php
  lib/Events/BeforeReactionAddedEvent.php
  lib/Events/BeforeReactionRemovedEvent.php
  lib/Events/BotInvokeEvent.php
  lib/Events/ReactionAddedEvent.php
  lib/Events/ReactionRemovedEvent.php
  lib/Listener/BotListener.php
  lib/Model/Bot.php
  lib/Service/BotService.php
  lib/Service/SampleConversationsService.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: bots 🤖

#14334 fix(ConversationIcon): get rid of grey hairline, provide a fallback icon
  src/components/ConversationIcon.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#14338 docs(bots): Update documentation for bots
  docs/bots.md
  docs/constants.md
  docs/occ.md
  lib/Command/Bot/Install.php
  lib/Command/Bot/State.php
  lib/Events/BotInvokeEvent.php
Labels: 3. to review, backport-request, feature: api 🛠️, feature: bots 🤖

#14345 fix(teams): Filter out already added teams from invite suggestions
  lib/Collaboration/Collaborators/Listener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-1/add-participant.feature
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: conversations 👥

#14344 fix(chat): Allow to edit messages of bots in one-to-one conversations
  lib/Controller/ChatController.php
  src/composables/useMessageInfo.js
  src/constants.ts
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: bots 🤖

#14354 fix(teams): Track team name updates
  lib/AppInfo/Application.php
  lib/Listener/CircleEditedListener.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-5/team-participants.feature
  tests/psalm-baseline.xml
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: conversations 👥

#14361 fix(chat): Correctly limit editing to bots IN 1-1
  src/composables/useMessageInfo.js
Labels: 3. to review, backport-request, bug, feature: chat 💬

#14362 [stable29] style: make type icon in LeftSidebar blend with background
  src/components/LeftSidebar/ConversationsList/Conversation.vue
  src/components/LeftSidebar/ConversationsList/ConversationsListVirtual.vue
  src/components/NewConversationDialog/NewConversationSetupPage.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#14360 [stable29] fix(chat): Allow to edit messages of bots in one-to-one conversations
  lib/Controller/ChatController.php
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
  src/constants.js
Labels: 3. to review, bug, feature: chat 💬

#14369 fix(PresenterOverlay): do not move component to negative values
  src/components/CallView/shared/PresenterOverlay.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#14376 Release 20.1.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#14355 fix(CalDavClient): handle XHR errors internally on Desktop client
  src/services/CalDavClient.ts
Labels: 3. to review, bug, feature: frontend 🖌️, client: 💻 desktop

#14381 chore(release): Add changelog for 21.0.0-rc.4
  CHANGELOG.md
Labels: 3. to review, backport-request

#14069 fix(chat): preserve selection (caret) on new message input
  src/components/NewMessage/NewMessage.vue
  src/utils/selectionRange.ts
Labels: 3. to review, backport-request, bug, feature: chat 💬

#14333 fix(callView): reset promoted view once switched to Grid mode
  src/App.vue
  src/components/CallView/CallView.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/LocalVideo.vue
  src/components/CallView/shared/VideoBottomBar.spec.js
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/VideoVue.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBarMenu.vue
  src/composables/useIsInCall.js
  src/composables/useViewer.js
  src/store/messagesStore.js
  src/store/participantsStore.js
  src/stores/__tests__/callView.spec.js
  src/stores/callView.ts
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: call 📹

#14385 chore(deps): bump nextcloud/vue from 8.22.0 to 8.23.1
  package-lock.json
  package.json
Labels: 3. to review, feature: frontend 🖌️, dependencies

#14328 fix(capabilities): make a deep comparison
  src/components/TopBar/CallButton.vue
  src/services/CapabilitiesManager.ts
  src/services/__tests__/CapabilitiesManager.spec.js
  src/stores/__tests__/federation.spec.js
  src/stores/federation.ts
  src/stores/talkHash.js
  src/test-setup.js
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#14435 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14438 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14436 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14437 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14433 fix: replace moment.unix()
  src/components/AdminSettings/TurnServer.vue
  src/components/CalendarEventsDialog.vue
  src/components/ConversationSettings/LobbySettings.vue
  src/components/LobbyScreen.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessageAbsenceInfo.vue
  src/store/conversationsStore.js
  src/store/messagesStore.js
  src/store/participantsStore.js
  src/utils/__tests__/formattedTime.spec.js
  src/utils/formattedTime.ts
  src/utils/signaling.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#14419 Fix distributing staged stats when not updated three times in a row
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.js
  src/utils/webrtc/analyzers/PeerConnectionAnalyzer.spec.js
Labels: 3. to review, backport-request, bug

#14444 tests: Make federation tests do real federation
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/call.feature
  tests/integration/features/federation/chat.feature
  tests/integration/features/federation/invite.feature
  tests/integration/features/federation/join-leave.feature
  tests/integration/features/federation/lobby.feature
  tests/integration/features/federation/permissions.feature
  tests/integration/features/federation/poll.feature
  tests/integration/features/federation/reminder.feature
  tests/integration/features/federation/user-statuses.feature
  tests/integration/run.sh
Labels: 2. developing, feature: federation 🌐

#14447 fix(actorStore): fetch teams with membership
  src/App.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Mention.vue
  src/services/teamsService.ts
  src/store/actorStore.js
  src/types/index.ts
Labels: 3. to review, backport-request, enhancement, feature: frontend 🖌️

#14456 ci: Adjust to changed guests app branching
  .github/workflows/integration-federation.yml
Labels: 3. to review

#14366 fix: add script to generate core types (from shipped apps)
  .github/workflows/update-nextcloud-openapi.yml
  package.json
  src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
  src/services/coreService.ts
  src/services/settingsService.ts
  src/types/generate-core-types.sh
  src/types/index.ts
  src/types/openapi/core/index.ts
  src/types/openapi/core/openapi_core.ts
  src/types/openapi/core/openapi_dav.ts
  src/types/openapi/core/openapi_provisioning_api.ts
Labels: 2. developing, technical debt, feature: frontend 🖌️

#14391 fix: vue-lib follow-ups
  src/components/CalendarEventsDialog.vue
  src/components/NewConversationDialog/NewConversationContactsPage.vue
  src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
  src/components/RoomSelector.vue
  src/components/UIShared/SearchBox.vue
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#14464 chore(release): Add changelog for 21.0.0-rc.5
  CHANGELOG.md
Labels: 3. to review

#14460 fix(call): Show "Missed call" in one-to-one also when "End for everyo…
  lib/Activity/Listener.php
Labels: 3. to review, bug, feature: api 🛠️, feature: call 📹

#14271 fix(textParse): use mention id to parse message parameters
  src/stores/__tests__/chatExtras.spec.js
  src/types/index.ts
  src/utils/__tests__/textParse.spec.js
  src/utils/textParse.ts
Labels: 3. to review, technical debt, feature: frontend 🖌️

#14441 fix: replace moment objects comparison
  src/components/CalendarEventsDialog.vue
  src/components/ConversationSettings/LobbySettings.vue
  src/components/LobbyScreen.vue
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesList.vue
  src/components/NewMessage/NewMessage.vue
  src/composables/useMessageInfo.js
  src/utils/formattedTime.ts
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#14484 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14485 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14486 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14487 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14393 fix(MessagesList): rename method to pollNewMessages
  src/FilesSidebarTabApp.vue
  src/components/MessagesList/MessagesList.vue
  src/constants.ts
  src/services/__tests__/messagesService.spec.js
  src/services/messagesService.ts
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, backport-request, feature: chat 💬, technical debt, feature: frontend 🖌️

#14461 fix(call): Simplify wording for one-to-one calls
  lib/Chat/Parser/SystemMessage.php
  tests/integration/features/command/user-remove.feature
  tests/integration/features/command/user-transfer-ownership.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: call 📹

#14443 feat(conversation): add federated typing indicator
  lib/Controller/RoomController.php
  lib/Federation/Proxy/TalkV1/ProxyRequest.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/federation/chat.feature
Labels: 2. developing, enhancement, feature: chat 💬, feature: api 🛠️, feature: signaling 📶, feature: federation 🌐

#14502 fix(LeftSidebar): do not expand empty search bar when focused
  src/components/LeftSidebar/LeftSidebar.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#14489 [l10n]: Change apostrophe
  docs/sample-conversations.md
  docs/samples/en/lets-get-started.md
  lib/Service/SampleConversationsService.php
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#14327 fix(MessagesList): fix resizeObserver and scrolledToBottom state update
  src/components/MessagesList/MessagesList.vue
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
Labels: 3. to review, bug, feature: frontend 🖌️

#14515 fix(LeftSidebar): fetch room if user was in the lobby
  lib/Service/RoomFormatter.php
  tests/integration/features/conversation-3/lobby.feature
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️, feature: meetings 📅
