Repository nextcloud/spreed, pull requests merged in 2025-03, with the labels that each got.

#14539 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14540 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14541 feat(App): add escape shortcut to go to root
  src/App.vue
Labels: backport-request, enhancement, feature: frontend 🖌️

#14542 fix(update/openapi): make PR from spreed Git repo
  .github/workflows/update-nextcloud-openapi.yml
Labels: 3. to review, technical debt, feature: frontend 🖌️

#14544 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_files_sharing.ts
Labels: 3. to review, dependencies

#14548 fix(search): Include captions in message search
  lib/Chat/ChatManager.php
  lib/Chat/CommentsManager.php
  lib/Search/MessageSearch.php
  tests/integration/features/chat-4/search.feature
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️, feature: search 🔎

#14549 fix(OpenAPI): Fix docs to be parsable with phpdoc-parser v2
  lib/Controller/ChatController.php
  lib/Controller/RoomController.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, technical debt

#14561 chore(openapi): Update openapi-extractor to allow deprecations and co…
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request, feature: api 🛠️, technical debt

#14494 fix(Participant): unexpected change of participant to be removed and users can ban themself
  src/components/RightSidebar/Participants/Participant.spec.js
  src/components/RightSidebar/Participants/Participant.vue
  src/components/RightSidebar/Participants/ParticipantsListVirtual.vue
  src/components/RightSidebar/Participants/ParticipantsTab.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#14522 fix(Views): migrate to ts
  src/App.vue
  src/composables/useDocumentTitle.ts
  src/env.d.ts
  src/main.js
  src/mainRecording.js
  src/router/router.ts
  src/views/ForbiddenView.vue
  src/views/MainView.vue
  src/views/NotFoundView.vue
  src/views/SessionConflictView.vue
  src/views/WelcomeView.vue
Labels: technical debt, feature: frontend 🖌️

#14497 feat(conversation): Add new API endpoint that allows to provide all s…
  docs/capabilities.md
  lib/Capabilities.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/PublicShareAuthController.php
  lib/Controller/RoomController.php
  lib/Exceptions/RoomProperty/CreationException.php
  lib/Manager.php
  lib/Model/InvitationList.php
  lib/ResponseDefinitions.php
  lib/Room.php
  lib/Service/AvatarService.php
  lib/Service/EmojiService.php
  lib/Service/InvitationService.php
  lib/Service/NoteToSelfService.php
  lib/Service/ParticipantService.php
  lib/Service/RoomService.php
  openapi-full.json
  openapi.json
  psalm.xml
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/conversation-1/breakout-rooms.feature
  tests/integration/features/conversation-1/create.feature
  tests/php/Service/AvatarServiceTest.php
  tests/php/Service/EmojiServiceTest.php
  tests/php/Service/RoomServiceTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#14575 fix(openapi): move from full-json to separate files
  src/types/index.ts
Labels: 3. to review, technical debt, feature: frontend 🖌️

#14585 fix(openapi): add types from files/openapi.json
  src/types/generate-core-types.sh
  src/types/openapi/core/openapi_files.ts
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#14601 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14602 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14604 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14605 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_dav.ts
Labels: 3. to review, dependencies

#14606 [stable31] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_dav.ts
  src/types/openapi/core/openapi_files_sharing.ts
Labels: 3. to review, dependencies

#14607 [stable30] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_core.ts
  src/types/openapi/core/openapi_dav.ts
  src/types/openapi/core/openapi_files_sharing.ts
Labels: 3. to review, dependencies

#14579 fix(conversationsService): migrate to ts
  src/components/LeftSidebar/CallPhoneDialog/CallPhoneDialog.vue
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/RoomSelector.spec.js
  src/components/RoomSelector.vue
  src/services/conversationsService.js
  src/services/conversationsService.ts
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
  src/store/participantsStore.spec.js
  src/types/index.ts
Labels: 3. to review, technical debt, feature: frontend 🖌️

#14572 fix(openapi): Fix deprecation syntax after openapi-extractor change
  lib/Controller/RoomController.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, feature: api 🛠️

#14583 fix(lobby): Hide lobbied conversations from dashboard
  lib/Dashboard/TalkWidget.php
  tests/integration/features/integration/dashboard.feature
Labels: 3. to review, backport-request, bug, feature: meetings 📅

#14608 Update quick-install.md (fix TURN secret example)
  docs/quick-install.md
Labels: 3. to review, feature: api 🛠️

#14603 [stable29] Update nextcloud/ocp dependency
  .github/workflows/integration-mariadb.yml
  .github/workflows/integration-mysql.yml
  .github/workflows/integration-oci.yml
  .github/workflows/integration-pgsql.yml
  .github/workflows/integration-sqlite.yml
  composer.lock
Labels: 3. to review, dependencies

#14613 chore(openapi): Update openapi-extractor to 1.5.1 to fix openapi-full.json
  openapi-full.json
  src/types/openapi/openapi-full.ts
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request, feature: api 🛠️

#14614 fix(reminder): Log when generating the reminder didn't work
  lib/Notification/Notifier.php
  lib/Service/ReminderService.php
  tests/php/Notification/NotifierTest.php
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: api 🛠️

#14586 fix: migrate fileSharingServices to TS
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageNewFileDialog.vue
  src/constants.ts
  src/services/coreService.ts
  src/services/filesSharingServices.js
  src/services/filesSharingServices.spec.js
  src/services/filesSharingServices.ts
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
  src/types/index.ts
  src/types/openapi/core/index.ts
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️

#14624 fix(Message): show loading spinner when request chat summary
  src/components/MessagesList/MessagesGroup/Message/Message.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#14620 fix: expose 'createConversation' method
  src/__mocks__/capabilities.ts
  src/components/ConversationSettings/ConversationAvatarEditor.vue
  src/components/NewConversationDialog/NewConversationDialog.vue
  src/services/conversationsService.ts
  src/store/conversationsStore.js
  src/store/conversationsStore.spec.js
Labels: 3. to review, backport-request, technical debt, feature: frontend 🖌️, performance 🚀

#14634 Release 19.0.14
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#14636 Release 21.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#14629 fix(calls): Fix displayname when exporting call participants
  lib/Controller/CallController.php
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  tests/integration/features/callapi/public.feature
Labels: 3. to review, bug, feature: api 🛠️, feature: meetings 📅, feature: call 📹

#14621 fix(l10n): Fix translation source strings
  src/components/AdminSettings/MatterbridgeIntegration.vue
  src/components/NewMessage/NewMessageAbsenceInfo.vue
  src/components/NewMessage/NewMessageChatSummary.vue
Labels: 3. to review, backport-request, bug

#14638 feat: add notify_push setup check
  lib/AppInfo/Application.php
  lib/SetupCheck/NotifyPush.php
Labels: 3. to review, feature: settings ⚙️, feature: api 🛠️

#14646 fix(call): do not show warning for the same conversation
  src/App.vue
  src/components/Quote.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#14665 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14499 feat(conversations): handle event conversation rooms
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Listener/CalDavEventListener.php
  lib/Room.php
  lib/Service/RoomService.php
  psalm.xml
  tests/php/Listener/CalDavEventListenerTest.php
  tests/psalm-baseline.xml
  tests/stubs/oca_dav_caldav_timezoneservice.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#14649 fix: migrate from deprecated OC.dialogs.confirmDestructive
  src/App.vue
  src/components/UIShared/ConfirmDialog.vue
  src/store/participantsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️

#14637 fix(Grid): fix cropped videos in the last row
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/Grid/gridPlaceholders.ts
Labels: 3. to review, bug, technical debt, feature: call 📹

#14690 fix(AdminSettings): respect initial state of E2EE setting
  src/components/AdminSettings/GeneralSettings.vue
Labels: 3. to review, backport-request, regression, feature: settings ⚙️, feature: frontend 🖌️

#14687 fix(messages): fix missing instant reactions for own message
  src/store/messagesStore.js
Labels: backport-request, bug, feature: frontend 🖌️, feature: reactions 👍

#14697 [stable29] fix: show tooltips in sidebar (from Vue directive)
  src/components/AdminSettings/TurnServer.vue
  src/components/AdminSettings/WebServerSetupChecks.vue
  src/components/CallView/Grid/Grid.vue
  src/components/CallView/shared/VideoBottomBar.vue
  src/components/CallView/shared/ViewerOverlayCallView.vue
  src/components/ConversationSettings/Matterbridge/MatterbridgeSettings.vue
  src/components/MediaSettings/MediaSettings.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/Contact.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/DeckCard.vue
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/NewMessage/NewMessageAudioRecorder.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/TopBar/CallButton.vue
  src/components/TopBar/TopBar.vue
  src/components/TopBar/TopBarMediaControls.vue
  src/components/UIShared/EditableTextField.vue
  src/main.js
  src/mainAdminSettings.js
  src/mainFilesSidebar.js
  src/mainPublicShareAuthSidebar.js
  src/mainPublicShareSidebar.js
  src/mainRecording.js
Labels: 3. to review, bug, regression, feature: frontend 🖌️

#14707 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14708 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14709 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14711 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_files.ts
Labels: 3. to review, dependencies

#14710 [stable31] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_files.ts
Labels: 3. to review, dependencies

#14700 fix(PollViewer): hide intermediate results from anonymous polls
  src/components/PollViewer/PollViewer.vue
Labels: 3. to review, backport-request, bug, feature: frontend 🖌️

#14717 feat(conversation): Send switch-to signaling message when creating fr…
  docs/constants.md
  docs/events.md
  lib/AppInfo/Application.php
  lib/Controller/RoomController.php
  lib/Events/RoomExtendedEvent.php
  lib/Room.php
  lib/Service/RoomService.php
  lib/Signaling/Listener.php
  tests/php/Signaling/ListenerTest.php
Labels: 3. to review, enhancement, feature: api 🛠️, feature: conversations 👥

#14721 [stable30] style: drop redundant overrides for public shares
  css/publicshare.css
Labels: 3. to review, bug, feature: frontend 🖌️

#14718 fix(call): prevent screen from turning off during call
  src/components/CallView/CallView.vue
  src/components/CallView/useWakeLock.ts
Labels: 3. to review, bug, feature: call 📹

#14669 feat: reduce items rendering in left sidebar search results
  src/components/LeftSidebar/LeftSidebar.spec.js
  src/components/LeftSidebar/LeftSidebar.vue
  src/components/LeftSidebar/SearchConversationsResults/SearchConversationsResults.vue
  src/components/UIShared/SearchBox.vue
  src/types/vendor/vue-virtual-scroller.d.ts
Labels: enhancement, technical debt, feature: frontend 🖌️, feature: conversations 👥

#14732 fix: Do not reset previous users after a resume
  src/utils/signaling.js
Labels: 3. to review, backport-request, bug, feature: signaling 📶, feature: frontend 🖌️

#14756 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14755 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14754 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#14759 [stable31] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_provisioning_api.ts
Labels: 3. to review, dependencies

#14757 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_provisioning_api.ts
Labels: 3. to review, dependencies

#14758 [stable30] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_provisioning_api.ts
Labels: 3. to review, dependencies

#14739 fix(calls): Fix system message for unanswered call
  lib/Chat/Parser/SystemMessage.php
  tests/integration/features/command/user-remove.feature
Labels: 3. to review, backport-request, bug, feature: chat 💬, feature: call 📹

#14720 [stable29] fix: public share style and guest actions fixes
  src/PublicShareSidebarTrigger.vue
  src/components/SetGuestUsername.vue
Labels: 3. to review, feature: frontend 🖌️

#14664 fix: do not add organizer as attendee and set status
  lib/Controller/RoomController.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: meetings 📅
