Repository nextcloud/spreed, pull requests merged in 2025-06, with the labels that each got.

#15272 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15273 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15274 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15275 [stable31] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_files.ts
Labels: 3. to review, dependencies

#15280 fix(meeting): allow to toggle lobby state for instant meetings
  lib/Service/RoomService.php
  src/components/ConversationSettings/LobbySettings.vue
  src/components/RightSidebar/LobbyStatus.vue
  src/store/conversationsStore.js
Labels: 3. to review, backport-request, feature: api 🛠️, feature: frontend 🖌️, feature: meetings 📅

#15294 fix(notification): Fix 'Undefined array key "user"' in case of a sens…
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#15302 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15172 feat(request-headers): Document request headers
  lib/Controller/AEnvironmentAwareOCSController.php
  lib/Controller/AvatarController.php
  lib/Controller/BotController.php
  lib/Controller/CallController.php
  lib/Controller/ChatController.php
  lib/Controller/FederationController.php
  lib/Controller/PollController.php
  lib/Controller/ReactionController.php
  lib/Controller/RecordingController.php
  lib/Controller/RoomController.php
  lib/Controller/SignalingController.php
  lib/Federation/Authenticator.php
  openapi-backend-sipbridge.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
Labels: 3. to review, enhancement, feature: api 🛠️, technical debt

#15305 ci(openapi): Bump nextcloud/openapi-extractor to 1.8
  composer.json
  openapi-backend-recording.json
  openapi-backend-signaling.json
  openapi-backend-sipbridge.json
  openapi-federation.json
  openapi-full.json
  openapi.json
  src/types/openapi/openapi-backend-recording.ts
  src/types/openapi/openapi-backend-signaling.ts
  src/types/openapi/openapi-backend-sipbridge.ts
  src/types/openapi/openapi-federation.ts
  src/types/openapi/openapi-full.ts
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review

#15319 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_core.ts
  src/types/openapi/core/openapi_files.ts
  src/types/openapi/core/openapi_files_sharing.ts
  src/types/openapi/core/openapi_provisioning_api.ts
Labels: 3. to review, dependencies

#15325 fix(ParticipantService): fix sending a federation invite from room with no owner
  lib/Service/ParticipantService.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: federation 🌐

#15351 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_core.ts
  src/types/openapi/core/openapi_files_sharing.ts
Labels: 3. to review, dependencies

#15332 Verify signaling token keys
  appinfo/info.xml
  docs/occ.md
  lib/Command/Signaling/VerifyKeys.php
  lib/Config.php
  lib/SetupCheck/HighPerformanceBackend.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️, feature: signaling 📶

#15329 techdebt: migrate calls service to typescript
  src/components/CallView/CallView.vue
  src/components/LeftSidebar/CallPhoneDialog/CallPhoneDialog.vue
  src/components/RightSidebar/Participants/Participant.vue
  src/components/TopBar/CallButton.vue
  src/services/callsService.ts
  src/store/participantsStore.js
  src/store/participantsStore.spec.js
  src/types/index.ts
Labels: technical debt, feature: frontend 🖌️

#15363 feat(web): always render code blocks LTR
  src/components/MessagesList/MessagesGroup/Message/MessagePart/MessageBody.vue
Labels: 3. to review, bug, feature: frontend 🖌️, feature: RTL ⬅️

#15334 fix: migrate file integration services to TS
  src/FilesSidebarTabApp.vue
  src/PublicShareAuthRequestPasswordButton.vue
  src/PublicShareSidebar.vue
  src/components/MediaSettings/VideoBackgroundEditor.vue
  src/components/NewMessage/NewMessage.vue
  src/components/NewMessage/NewMessageUploadEditor.vue
  src/services/DavClient.ts
  src/services/__tests__/filesSharingServices.spec.js
  src/services/__tests__/messagesService.spec.js
  src/services/banService.ts
  src/services/conversationsService.ts
  src/services/coreService.ts
  src/services/federationService.ts
  src/services/filesIntegrationServices.js
  src/services/filesIntegrationServices.ts
  src/services/groupwareService.ts
  src/services/messagesService.ts
  src/services/publicShareAuthService.js
  src/services/reactionsService.ts
  src/services/translationService.js
  src/store/fileUploadStore.js
  src/store/fileUploadStore.spec.js
  src/store/messagesStore.js
  src/store/messagesStore.spec.js
  src/types/index.ts
  src/utils/__tests__/prepareTemporaryMessage.spec.js
  src/utils/prepareTemporaryMessage.ts
Labels: 3. to review, technical debt, feature: frontend 🖌️

#15381 chore: Update coding standards to 1.4
  .git-blame-ignore-revs
  lib/BackgroundJob/CheckHostedSignalingServer.php
  lib/Chat/ChatManager.php
  lib/Chat/Notifier.php
  lib/Chat/Parser/Command.php
  lib/Chat/Parser/SystemMessage.php
  lib/Chat/Parser/UserMention.php
  lib/Chat/SystemMessage/Listener.php
  lib/Command/Developer/UpdateDocs.php
  lib/Command/Turn/Add.php
  lib/Controller/ChatController.php
  lib/Controller/FilesIntegrationController.php
  lib/Controller/RoomController.php
  lib/Controller/TempAvatarController.php
  lib/Dashboard/Event.php
  lib/Middleware/CanUseTalkMiddleware.php
  lib/Middleware/InjectionMiddleware.php
  lib/Model/Attendee.php
  lib/Model/Message.php
  lib/Notification/Notifier.php
  lib/PublicShare/TemplateLoader.php
  lib/Search/ConversationSearch.php
  lib/Search/MessageSearch.php
  lib/Service/AvatarService.php
  lib/Service/RoomFormatter.php
  lib/Service/RoomService.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/SharingContext.php
  tests/php/Chat/NotifierTest.php
  tests/php/Command/Stun/AddTest.php
  tests/php/Command/Turn/AddTest.php
  tests/php/Controller/ChatControllerTest.php
  tests/php/Controller/SignalingControllerTest.php
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
Labels: 3. to review

#15376 perf(frontend): lazy load `libphonenumber-js`
  src/components/SelectPhoneNumber.vue
  src/composables/useAsyncInit.ts
  src/composables/useLibphonenumber.ts
Labels: 3. to review, feature: frontend 🖌️, performance 🚀

#15380 chore(eslint): use complete config on lint
  eslint.config.mjs
  package.json
  webpack.common.config.js
  webpack.config.js
Labels: 3. to review, technical debt, feature: frontend 🖌️

#15395 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#15398 ci: Update workflows
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#15396 [main] Update Nextcloud OpenAPI types
  src/types/openapi/core/openapi_provisioning_api.ts
Labels: 3. to review, dependencies

#15399 fix(ts): address typescript issues
  src/components/CalendarEventsDialog.vue
  src/components/Dashboard/EventCard.vue
  src/components/ExtendOneToOneDialog.vue
  src/components/PollViewer/PollEditor.vue
  src/components/RightSidebar/SearchMessages/SearchMessageItem.vue
  src/components/RightSidebar/SearchMessages/SearchMessagesTab.vue
  src/components/UIShared/ConfirmDialog.vue
  src/composables/useDocumentTitle.ts
  src/composables/useSessionIssueHandler.ts
  src/composables/useTemporaryMessage.ts
  src/services/EventBus.ts
  src/types/vendor/vuex.d.ts
  tsconfig.json
Labels: technical debt, feature: frontend 🖌️

#15414 fix: allow encrypted calls in Talk integrations
  lib/Controller/PageController.php
  lib/Listener/CSPListener.php
Labels: 3. to review, backport-request, bug, feature: api 🛠️

#15421 fix(messages): fix toggle for combined message
  src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue
  src/components/MessagesList/MessagesGroup/MessagesSystemGroup.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#15419 fix: expand ts migration and fix infinite loading bug of shared items tab in 1-1 conversation
  src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue
  src/components/RightSidebar/RightSidebar.vue
  src/components/RightSidebar/SharedItems/SharedItems.vue
  src/components/RightSidebar/SharedItems/SharedItemsBrowser.vue
  src/components/RightSidebar/SharedItems/SharedItemsTab.vue
  src/components/RightSidebar/SharedItems/sharedItemsConstants.ts
  src/services/sharedItemsService.ts
  src/store/conversationsStore.js
  src/store/messagesStore.js
  src/stores/__tests__/sharedItems.spec.js
  src/stores/sharedItems.ts
  src/types/index.ts
Labels: bug, feature: frontend 🖌️, feature: upload & shares & voice 📤🎙️

#15409 fix(vue3): fullscreen mode in Vue 3 container
  src/App.vue
Labels: 3. to review, bug, feature: frontend 🖌️

#15424 fix: adjust logic of 'conversation-received' event emitting
  src/App.vue
  src/components/LeftSidebar/LeftSidebar.vue
  src/services/EventBus.ts
  src/store/conversationsStore.js
Labels: 3. to review, bug, feature: frontend 🖌️

#15429 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
